### PR TITLE
🐛 Register `LINKER_CREATED` on ampdoc instead of attribute

### LINKED ISSUE #28220: 🚨 Error: ShadowRoot is not defined
Details
---
**Error report:** [link](http://go/ampe/CNz4-OG0lYDW_wE)
**First seen:** Apr 30, 2020
**Frequency:** ~ 248/day

Stacktrace
---
```
Error: ShadowRoot is not defined
    at ShadowRoot (https://raw.githubusercontent.com/ampproject/amphtml/2005020055000/extensions/amp-analytics/0.1/linker-manager.js:237:26)
    at isLegacyOptIn_ (https://raw.githubusercontent.com/ampproject/amphtml/2005020055000/extensions/amp-analytics/0.1/linker-manager.js:161:15)
    at processConfig_ (https://raw.githubusercontent.com/ampproject/amphtml/2005020055000/extensions/amp-analytics/0.1/linker-manager.js:93:19)
    at init (https://raw.githubusercontent.com/ampproject/amphtml/2005020055000/extensions/amp-analytics/0.1/amp-analytics.js:584:6)
    at linkerTask (https://raw.githubusercontent.com/ampproject/amphtml/2005020055000/extensions/amp-analytics/0.1/amp-analytics.js:589:6)
```

Notes
---
`@lannka` modified `extensions/amp-analytics/0.1/linker-manager.js:161-161` in #18029 (Sep 13, 2018)
`@rsimha` modified `extensions/amp-analytics/0.1/linker-manager.js:93-95` in #21212 (May 16, 2019)
`@zhouyx` modified `extensions/amp-analytics/0.1/amp-analytics.js:583-585` in #27605 (Apr 20, 2020)
`@zhouyx` modified `extensions/amp-analytics/0.1/amp-analytics.js:587-590` in #27605 (Apr 20, 2020)

**Seen in:**
- 05-02 Nightly (0055)
- 05-05 Nightly (0322)

**Possible assignees:** `@zhouyx`, `@lannka`

/cc @ampproject/release-on-duty

### PR DESCRIPTION
**Pull request by zhouyx**
To fix #28220. 

TBH I still don't know what's causing the error. But the purpose of the check is to only initiate the linker manager once for each ampdoc. No need to check for `ShadowRoot`, the attribute can be applied to the document.body.

### CODE REVIEW

**Comment by jridgewell** [comment]
`ShadowRoot` isn't defined in old Chrome, so trying to reference it throws a `ReferenceError`.

But we shouldn't be using attributes as markers. It seems we have a need to mark arbitrary data on the ampdoc instance ([`registerTrackingIframe`](https://github.com/ampproject/amphtml/blob/master/src/service/ampdoc-impl.js#L756-L767)). Maybe we should generalize that into object properties.

**Comment by zhouyx** [comment]
>ShadowRoot isn't defined in old Chrome, so trying to reference it throws a ReferenceError.

Thanks! That's good to know. However based on #28220, the error appears very recently despite that the code was merged back in Feb. 

> But we shouldn't be using attributes as markers. It seems we have a need to mark arbitrary data on the ampdoc instance (registerTrackingIframe). Maybe we should generalize that into object properties.

I like the idea! Will generalize the solution.

**Comment by jridgewell** [comment]
This is an async error being caught by a promise. If there's no `catch` handler in the promise chain, then usually we'd get a `unhandledrejection` error event. But, because not everything uses `crossorigin=anonymous`, `unhandledrejection` errors get dropped! We'd never receive the error report.

Now, https://github.com/ampproject/amphtml/blame/c985e344b25effca5e8f2a604a3cef11eff6c0d3/extensions/amp-analytics/0.1/amp-analytics.js#L587 breaks the initialization out of the promise chain. It's now happening in chunked event loop. We have wrappers around these event loops that can catch the error and report it properly, even when the error comes from a non-anonymous script.

So, I think the bug was always there, we just never received the reports.

**Comment by mdmower** [comment]
Oh, I remember this (#26683). Sorry, `headNode instanceof ShadowRoot` isn't the most compatible solution. To give some context, attribute `i-amphtml-linker-created` is added to `<meta name="amp-google-client-id-api" content="googleanalytics">` when `LinkerManager` inits. Since this meta tag is not scoped to AmpDocShadow instances, I opted to attach the the attribute to `<body>`.

I like that you plan to abandon use of this attribute as a marker. If you need a quick fix in the meantime...
```
--- a/extensions/amp-analytics/0.1/linker-manager.js
+++ b/extensions/amp-analytics/0.1/linker-manager.js
@@ -234,7 +234,7 @@ export class LinkerManager {
 
     const headNode = this.ampdoc_.getHeadNode();
     const linkerCreatedEl =
-      headNode instanceof ShadowRoot
+      headNode.toString() === '[object ShadowRoot]'
         ? this.ampdoc_.getBody()
         : headNode.querySelector(
             'meta[name="amp-google-client-id-api"][content="googleanalytics"]'

```

**Comment by zhouyx** [comment]
Thank you @jridgewell That makes a lot of sense! 
I believe the error reported #28264 was surface recently for the same reason.

**Comment by zhouyx** [comment]
Thank all for the suggestion. I've introduced a more generic solution as Justin suggested.

File: src/service/ampdoc-impl.js [hunk 1]
```diff
@@ -754,16 +754,22 @@ export class AmpDoc {
   }
 
   /**
-   * Allow one tracking iframe for each amp doc. Caller need to handle user
-   * error when registeration returns false
+   * Attempt to register a service that is allowed/required one for each ampdoc.
+   * Caller need to handle user error when registration returns false.
+   *
+   * Please list your service name below:
```
Comment (zhouyx) [inline src/service/ampdoc-impl.js:760]: I don't want to add extra bytes to the runtime by keeping an enum list. But I do want to keep such a list somewhere for reference so that we don't end up with identical service name. Let me know if there's better way to address : )

File: extensions/amp-analytics/0.1/linker-manager.js [hunk 2]
```diff
@@ -232,19 +232,10 @@ export class LinkerManager {
...
-    const headNode = this.ampdoc_.getHeadNode();
-    const linkerCreatedEl =
-      headNode instanceof ShadowRoot
-        ? this.ampdoc_.getBody()
-        : headNode.querySelector(
-            'meta[name="amp-google-client-id-api"][content="googleanalytics"]'
-          );
-
-    if (linkerCreatedEl.hasAttribute(LINKER_CREATED)) {
+    if (!this.ampdoc_.registerService(LINKER_CREATED)) {
```
Comment (jridgewell) [inline extensions/amp-analytics/0.1/linker-manager.js:235]: Nit: Just `return this.ampdoc_.registerService(LINKER_CREATED)`?

File: src/service/ampdoc-impl.js (hunk 1 above)
Comment (jridgewell) [reply src/service/ampdoc-impl.js:760]: Enums get eliminated if unused, and the `Enum.FOO` reference will be rewritten with whatever the value is if it's used. Enums are basically 0 cost. 😉

File: src/service/ampdoc-impl.js [hunk 3]
```diff
@@ -754,16 +754,22 @@ export class AmpDoc {
...
+   * 'tracking_iframe',
+   * 'linker-created',
+   *
+   * @param {string} name
    * @return {boolean}
    */
-  registerTrackingIframe() {
-    if (this.hasTrackingIframe_) {
-      return false;
+  registerService(name) {
```
Comment (jridgewell) [inline src/service/ampdoc-impl.js:767]: Nit: I wouldn't call this `service`, to avoid confusion with ampdoc/window services. Maybe "singleton"?

File: extensions/amp-analytics/0.1/linker-manager.js (hunk 2 above)
Comment (zhouyx) [reply extensions/amp-analytics/0.1/linker-manager.js]: 👍 Good point

File: src/service/ampdoc-impl.js (hunk 3 above)
Comment (zhouyx) [reply src/service/ampdoc-impl.js]: Sounds good. Changed to `registerSingleton()`

File: src/service/ampdoc-impl.js (hunk 1 above)
Comment (zhouyx) [reply src/service/ampdoc-impl.js]: That's cool! Switched to enum

File: extensions/amp-iframe/0.1/amp-iframe.js [hunk 4]
```diff
@@ -14,6 +14,7 @@
  * limitations under the License.
  */
 
+import {AMPDOC_SINGLETON_NAME} from '../../../src/service/ampdoc-impl';
```
Comment (jridgewell) [inline extensions/amp-iframe/0.1/amp-iframe.js:17]: Maybe we should move this elsewhere, with only this in the file? That way there are no transitive imports, and we don't need the presubmit whitelist?

Comment (zhouyx) [reply extensions/amp-iframe/0.1/amp-iframe.js:17]: I agreed! Any idea where to move it to. I wish there's a src/const.js file.

Comment (jridgewell) [reply extensions/amp-iframe/0.1/amp-iframe.js:17]: That sounds fine to me. Or `src/enums.js`

File: src/enums.js [hunk 5]
```diff
@@ -0,0 +1,24 @@
...
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+/**
+ * Registred singleton on AMP doc.
+ * @enum {number}
+ */
+export const AMPDOC_SINGLETON_NAME = {
```
Comment (mdmower) [inline src/enums.js:21]: How about just `AMPDOC_SINGLETON`?

File: src/enums.js [hunk 6]
```diff
@@ -0,0 +1,24 @@
...
+ *
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS-IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+/**
+ * Registred singleton on AMP doc.
```
Comment (mdmower) [inline src/enums.js:18]: **Registered** singleton on **AmpDoc**.
