### PR TITLE
Fix service.js "...orNull" functions to instantiate services if needed #8616

### LINKED ISSUE #8616: Registered/expected services should never resolve `null` from any of the methods
This appears to affect the following methods in service.js:
- `getServicePromiseOrNullInternal`
- `getExistingServiceForWindowOrNull`
- `getLocalExistingServiceForEmbedWinOrNull`
- might be more

And, of course, all methods that call them.

The bottom line: there's only one distinction: whether the service is registered/expected-to-be-registered or not. Initialization state should not matter.

Related to #7839.

### PR DESCRIPTION
**Pull request by kmh287**
Fixes #8616 

/to @dvoytenko

### CODE REVIEW

File: src/service.js [hunk 1]
```diff
@@ -87,7 +87,11 @@ export function getExistingServiceForWindow(win, id) {
  */
 export function getExistingServiceForWindowOrNull(win, id) {
   win = getTopWindow(win);
-  return win.services && win.services[id] && win.services[id].obj;
+  if (win.services && win.services[id]) {
+    return getService(win, id);
```
Comment (dvoytenko) [inline src/service.js]: Should we just call `getServiceInternal(win, win, id)` for symmetry?

File: src/service.js [hunk 2]
```diff
@@ -586,9 +588,9 @@ function getServicePromiseOrNullInternal(holder, id) {
       return s.promise;
     } else if (s.obj) {
       return s.promise = Promise.resolve(s.obj);
-    } else {
-      dev().assert((s.build),
-          'Expected object, promise, or builder to be present');
+    } else if (s.build) {
+      s.obj = s.build();
```
Comment (dvoytenko) [inline src/service.js]: Let's leave `} else {` and `dev.assert()`. It's still better to assert this in dev since we expect either `promise` or `obj` or `build` to exist.

File: src/service.js [hunk 3]
```diff
@@ -173,13 +177,11 @@ function getLocalExistingServiceForEmbedWinOrNull(embedWin, id) {
...
   const topWin = getTopWindow(embedWin);
-  if (embedWin != topWin &&
-          embedWin.services &&
-          embedWin.services[id] &&
-          embedWin.services[id].obj) {
-    return embedWin.services[id].obj;
+  if (embedWin != topWin && embedWin.services && embedWin.services[id]) {
+    return getServiceInternal(embedWin, embedWin, id);
+  } else {
+    return null;
```
Comment (dvoytenko) [inline src/service.js]: It looks like `getExistingServiceForDoc` is also affected. Please fix.

File: src/service.js (hunk 1 above)
Comment (kmh287) [inline src/service.js]: done

File: src/service.js (hunk 3 above)
Comment (kmh287) [inline src/service.js]: done

File: src/service.js (hunk 2 above)
Comment (kmh287) [inline src/service.js]: done
