### PR TITLE
✨Request Bank: Fixed AMP CORs and Multipart form data

### LINKED ISSUE #20868: Request Bank: Send back AMP CORS Headers
Was writing request bank test for #20541 , and found that there are not AMP CORS headers sent back by the request bank.

screen shot 2019-02-14 at 11 53 45 am

### LINKED ISSUE #20869: Request Bank: Send back POST Form Data in the body
Currently, request bank isn't handling form data from POST requests, and moving it into the body, similar to: https://github.com/ampproject/amphtml/blob/master/build-system/recaptcha-router.js#L49

This should be done for easy POST tests using amp-form 😄

### PR DESCRIPTION
**Pull request by torch2424**
closes #20868 
closes #20869 
relates to #20541 

This adds [multipart form data parsing into the request body](https://stackoverflow.com/questions/37630419/how-to-handle-formdata-from-express-4), which AMP Form uses, to the RequestBank Express Middleware, as well as, enables AMP Cors on request bank (which included some refactoring in other places).

# Example Requests

**These examples are made from just switching around the endpoint of the POST request on the recaptcha example**

## Submitting to a standard endpoint on the dev server

screen shot 2019-02-14 at 5 46 00 pm
screen shot 2019-02-14 at 5 46 19 pm

## Depositing to request bank

screen shot 2019-02-14 at 6 11 26 pm
screen shot 2019-02-14 at 6 11 46 pm

## Withdrawing from request bank

screen shot 2019-02-14 at 6 11 16 pm

### CODE REVIEW

File: build-system/amp-cors.js [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+  res.setHeader('Access-Control-Expose-Headers',
+    ['AMP-Access-Control-Allow-Source-Origin']
+    .concat(opt_exposeHeaders || []).join(', '));
+  if (req.query.__amp_source_origin) {
+    res.setHeader('AMP-Access-Control-Allow-Source-Origin',
+      req.query.__amp_source_origin);
+  }
+}
+
+module.exports = {
```
Comment (lannka) [inline build-system/amp-cors.js]: you can do:
```
module.exports = enableCors;
```

and to import
```
const enableCors = require('./amp-cors');
```

File: build-system/amp4test.js [hunk 2]
```diff
@@ -101,26 +106,31 @@ const bank = {};
...
-  if (typeof bank[req.params.bid][key] === 'function') {
-    bank[req.params.bid][key](req);
-  } else {
-    bank[req.params.bid][key] = req;
-  }
-  res.end();
-});
+app.use(
+    '/request-bank/:bid/deposit/:id/',
+    upload.array(),
```
Comment (lannka) [inline build-system/amp4test.js]: i suppose this is a no-op for non-form POST?

Comment (torch2424) [reply build-system/amp4test.js]: Yup 😄 

screen shot 2019-02-20 at 1 00 51 pm
