### PR TITLE
🏗✨ Enhance AMP tooling so developers can run tests on local changes only

### LINKED ISSUE #15369: Add support for developers to quickly test their changes locally before pushing them to GitHub
## What's the issue?

Travis is getting congested with builds containing linting errors. This is making it more difficult to get changes published.

Idea: Add an optional (disabled by default) `pre-push` hook that lints only the files change in a commit. If there is a failure, the push doesn't continue until the linting errors are resolved. This would allow frequent contributors to be more confident their changes will not fail during linting on Travis.

### PR DESCRIPTION
**Pull request by rsimha**
This PR does a few things:
1. Adds a `--local-changes` mode to `gulp test`, which runs only unit tests from files changed in the local branch. (Works with `--nobuild` and `--headless`.)
2. Adds the file `build-system/git.js` to consolidate all the `git` commands run in various places in `build-system/`.
3. Updates `gulp lint --local-changes` so it runs on any files changed in the local branch. They no longer need to be committed to show up in the list.
4. Does a minor clean up / refactor of `build-system/config.js`
5. Updates AMP dev docs to reflect the new testing flags

Note that we can only run unit tests with `--local-changes`, since they are self contained, don't require the entire AMP runtime to be built, and can start up in very little time. Any changes to integration tests will require the runtime to be built, so these tests are better off being run on Travis.

Once this is in place, it will become feasible to add an opt-in pre-push hook that will be run before a local branch is pushed to GitHub. Commands like `gulp lint --local-changes` and `gulp test --local-changes` should only take a few seconds to run. 

Fixes #15369

### CODE REVIEW

**Comment by rsimha** [comment]
/to @kristoferbaxter @choumx since we discussed this
/cc @erwinmombay @jridgewell in case you have comments to add

File: build-system/tasks/runtime-test.js [hunk 1]
```diff
@@ -442,5 +473,6 @@ gulp.task('test', 'Runs tests', preTestTasks, function() {
     'config': '  Sets the runtime\'s AMP config to one of "prod" or "canary"',
     'coverage': '  Run tests in code coverage mode',
     'headless': '  Run tests in a headless Chrome window',
+    'local-changes': '  Run unit tests from files commited to the local branch',
```
Comment (kristoferbaxter) [inline build-system/tasks/runtime-test.js]: Curious what you think of inverting the logic here.

By default only run unit tests from files changed, use a flag to run against all.

File: build-system/git.js [hunk 2]
```diff
@@ -0,0 +1,75 @@
+/**
```
Comment (kristoferbaxter) [inline build-system/git.js]: Good idea to consolidate this logic here.

File: build-system/tasks/runtime-test.js (hunk 1 above)
Comment (rsimha) [reply build-system/tasks/runtime-test.js]: I think the default `gulp test` behavior should be to run all unit / integration tests (based on whether you use `--unit` or `--integration`), since that's the only way to make sure that changes to the core runtime didn't break anything. Note that `--local-changes` only works when you change a test file, and not when you change runtime code, since there's no way to reliably map each runtime files to a set of test files that it affects.

Comment (kristoferbaxter) [reply build-system/tasks/runtime-test.js]: Thanks. Makes sense!

**Comment by bradfrizzell** [comment]
Just noticed the new --local-changes
Thank you!!! I'd wanted that feature for so long, this is a great addition.
