### PR TITLE
🏗 Pre-build JS files and extensions loaded by core runtime during `gulp` startup

### LINKED ISSUE #24226: Make `build-system/app.js` compatible with `gulp --lazy_build`
`gulp --lazy_build` was recently introduced to speed up the local development experience. See #24141 for more details.

In this mode, the path modifications in `build-system/app.js` can break the lazy-building / serving of some unminified JS files. For example, requests for these files fail because the modifications to the requst urls done by `app.js` are invisible to the lazy builder.

```
/dist/ww.js (actually at /dist/ww.max.js)
/ww.js.map (actually at /dist/ww.max.js.map)
/dist/rtv/1908262352450/v0/amp-auto-lightbox-0.1.js (actually at /dist/v0/amp-auto-lightbox-0.1.max.js)
/dist/v0/amp-sticky-ad-0.1.max.js (aliased from /dist/v0/amp-sticky-ad-1.0.max.js)
```

This issue is meant to track and fix problems of this sort as they crop up.

### LINKED ISSUE #25024: Lazy gulp doesn't build ww.js when amp-bind.js detected
## What's the issue?

When `gulp` is used to start a localhost server with lazy-loaded AMP components, AMP pages that depend on `amp-bind` do not work correctly. The web worker `ww.js` is never built, so bind initialization and attempts to set states all fail.

## How do we reproduce the issue?

1. `gulp clean`
2. `gulp`
3. Open [http://localhost:8000/examples/bind/basic.amp.html](http://localhost:8000/examples/bind/basic.amp.html)
4. Tap the "Click me" button at the bottom of the page -- nothing happens.

You can confirm `ww.js` is the culprit by putting a breakpoint in `initialize_(root)` in `extensions/amp-bind/0.1/bind-impl.js` before `this.ww_()` as well as inside the subsequent `.then()`.

## What browsers are affected?

Chrome 78 on Ubuntu 19.04

## Which AMP version is affected?

Confirmed on `master` branch at commit `a9b947b4cb740d9805ca916bc3a9b1ad5f0e1231`.

### PR DESCRIPTION
**Pull request by rsimha**
**Background:**

The default `gulp` task pre-builds the core runtime, and lazy builds all other JS files and extensions. This results in 404 errors for files that are sometimes loaded by the core runtime without a separate server request (#25024, #24226).

**PR highlights:**

- Pre-builds `ww.js` during default `gulp` startup
- Pre-builds `amp-loader` and `amp-auto-lightbox` during default `gulp` startup
- Waits for pre-build tasks to complete before ending default `gulp` task
- Fixes logging to indicate which extensions are being pre-built
- Server startup still happens before pre-build tasks are executed

Fixes #25024
Fixes #24226

### CODE REVIEW

File: build-system/tasks/serve.js [hunk 1]
```diff
@@ -150,7 +148,7 @@ async function serve() {
   logServeMode();
   watch(serverFiles, restartServer);
   await startServer();
```
Comment (cramforce) [inline build-system/tasks/serve.js]: Could you `await Promise.all([startServer(), performPreBuildSteps()])`?

Comment (rsimha) [reply build-system/tasks/serve.js]: Tried that initially. Server startup takes ~1 second, so I separated the steps in order to prevent the logs from getting interspersed.
