### PR TITLE
🐛 Fix LargestContentfulPaintVisible and remove FirstInputDelayVisible

### LINKED ISSUE #29015: LCP and FID variable values differ greatly from chrome extension values
## What's the issue?
The substitute variables for LCP and FID in my `amp-analytics` script don't appear to be accurate. They are both long ints that look like `1593003422844`, and don't match any of the numbers output by my web vitals chrome extension (not simply a matter of moving a decimal point)

## How do we reproduce the issue?
My code looks like this: 
```
...
<amp-analytics type="googleanalytics" id="googleanalytics1">
<script type="application/json">
{
   "vars":{
      "account":"UA-XXXXXXX-1"
   },
   "extraUrlParams":{
      "cd53":"Outlook;History"
   },
   "triggers":{
      "webVitals": {
      	"on":"visible",
         "request":"event",
         "extraUrlParams":{
            "lcp":"${largestContentfulPaint}",
            "fid":"${firstInputDelay}",
            "cls":"${cumulativeLayoutShift}"
         }
      }
   }
}
</script>
</amp-analytics>
```

CLS is working beautifully, but when I look at the network call for lcp & fid, they look more like ids than the true vital values. I can't get a jsbin to fire any of the events so I don't have a sandbox for you, but hoping you can still help

image
image
image

## What browsers are affected?
At least chrome

## Which AMP version is affected?
Version 2006112352001

### PR DESCRIPTION
**Pull request by zhouyx**
Closes #29015

LargestContentfulPaintVisible:
Calculate the end_time by adding `this.timeOrigin_ + entry.renderTime`
Also fix the issue where delta 0 is treated as `undefined`. 

FirstInputDelay:
The first input should always happen after the document is visible, and the measuring start time is not `this.timeOrigin_`. Removed `FirstInputDelayVisible` since it doesn't tell anything.

### CODE REVIEW

File: src/utils/signals.js [hunk 1]
```diff
@@ -101,7 +101,7 @@ export class Signals {
       // Do not duplicate signals.
       return;
     }
-    const time = opt_time || Date.now();
+    const time = opt_time == undefined ? Date.now() : opt_time;
```
Comment (cramforce) [inline src/utils/signals.js:104]: Please add a test

Comment (zhouyx) [reply src/utils/signals.js:104]: good point. done
