### PR TITLE
Call fake scroll API on iOS to unstuck the clicks

### LINKED ISSUE #30838: browser back can cause clicks to not working in AMP Cache
## What's the issue?

browser back can cause clicks to not working in AMP.
However, origin AMP is fine.

## How do we reproduce the issue?

1. Open Google AMP Cache
2. Make transitions within the site
3. Browser Back to AMP Cache (AMP Viewer)  <- (Click not working here)

## What browsers are affected?

I think it will happen at least if you use safari or chrome on iPhone with OS version 13 or higher.

My Device
- iOS 13.5.1  iphoneSE NG
- iOS 14.1    iphoneSE NG

VM Device(browserstack.com)

- iOS 11 iphoneX  OK
- iOS 12 iphoneXS OK
- iOS 13 iphone8  NG
- iOS 14 iphone11 NG

## Which AMP version is affected?

Version 2010132225002 

## Screen Capture and AMP Cache URL

-
 - https://www.google.com/amp/s/www.ikyu.com/sd/theme/a320701c2/amp/

- 
 - https://www.google.com/amp/s/akiba-pc.watch.impress.co.jp/docs/sp/1160/581/amp.index.html

- 
 - https://www.google.com/amp/s/www3.nhk.or.jp/nhkworld/en/news/20201023_14/amp.html

### PR DESCRIPTION
**Pull request by dvoytenko**
Closes #30838.

### CODE REVIEW

File: src/service/viewport/viewport-impl.js [hunk 1]
```diff
@@ -204,6 +204,14 @@ export class ViewportImpl {
         // Ignore errors.
       }
     }
+
+    // BF-cache navigation sometimes breaks clicks in an iframe on iOS. See
+    // https://github.com/ampproject/amphtml/issues/30838 for more details.
+    // The solution is to make a "fake" scrolling API call.
+    const isIframedIos = Services.platformFor(win).isIos() && isIframed(win);
```
Comment (ericfs) [inline src/service/viewport/viewport-impl.js:211]: Does this run when loading from bf-cache? LGTM assuming it does.

**Review by ericfs — APPROVED** [review]

File: src/service/viewport/viewport-impl.js (hunk 1 above)
Comment (dvoytenko) [reply src/service/viewport/viewport-impl.js:211]: Yes. Definitely.

**Review by samouri — APPROVED** [review]
