### PR TITLE
Fix mechanism to detect the files in a PR

### LINKED ISSUE #9778: Update pr-check.js with a mechanism to detect outdated branches
Often times, a PR will fail on Travis because a branch is out of date. This will manifest as an error related to the mixing of flag-config and non-flag-config files in a PR, while in reality, this is simply due to a stale branch that has a huge list of diffs from master.

It would be useful to add a detection mechanism to pr-check.js, with clear instructions on how to sync and push the branch.

For more background, see #9012 and #9014

### PR DESCRIPTION
**Pull request by rsimha-amp**
This PR updates the mechanism to detect the files contained in a PR. This is necessary because pushing a PR from a branch that wasn't recently synced to master could sometimes result in Travis counting *all* the files committed to master since the creation of that branch as being within the PR. This has resulted in all sorts of confusion stemming from errors in unrelated files.

Fixes #9778

### CODE REVIEW

**Comment by erwinmombay** [comment]
something like this maybe:

```
const firstParent = execSync(`diff -u <(git rev-list --first-parent ${process.env.TRAVIS_PULL_REQUEST_SHA}) <(git rev-list --first-parent master) | sed -ne 's/^ //p' | head -1`)
const travisCommitRange  =`${firstParent}...${process.env.TRAVIS_PULL_REQUEST_SHA}`
```

**Comment by rsimha-amp** [comment]
@erwinmombay, this is now ready for review. Note that I didn't use `--all` with `git merge-base`, since I want only the best common ancestor of `master` and the branch being pushed. See description in https://www.kernel.org/pub/software/scm/git/docs/git-merge-base.html.

File: build-system/pr-check.js [hunk 1]
```diff
@@ -93,12 +93,15 @@ function timedExecOrDie(cmd) {
...
- * yields the list of files.
- * @param {string} travisCommitRange
+ * Returns a list of files in the commit range within this pull request (PR)
+ * after filtering out commits to master from other PRs.
  * @return {!Array<string>}
  */
-function filesInPr(travisCommitRange) {
+function filesInPr() {
+  const branches = `master ${process.env.TRAVIS_PULL_REQUEST_SHA}`;
+  const commonAncestors = getStdout(`git merge-base ${branches}`);
```
Comment (jridgewell) [inline build-system/pr-check.js]: Why not use `--fork-point`?

File: build-system/pr-check.js [hunk 2]
```diff
@@ -93,13 +102,23 @@ function timedExecOrDie(cmd) {
...
- * yields the list of files.
- * @param {string} travisCommitRange
+ * Returns a list of files in the commit range within this pull request (PR)
+ * after filtering out commits to master from other PRs.
  * @return {!Array<string>}
  */
-function filesInPr(travisCommitRange) {
-  return getStdout(`git diff --name-only ${travisCommitRange}`);
+function filesInPr() {
+  const branches = `master ${process.env.TRAVIS_PULL_REQUEST_SHA}`;
```
Comment (jridgewell) [inline build-system/pr-check.js]: Remove the second part, all you need is `master`

File: build-system/pr-check.js [hunk 3]
```diff
@@ -93,13 +102,23 @@ function timedExecOrDie(cmd) {
...
+  const commonAncestor =
+      getStdout(`git merge-base --fork-point ${branches}`).trim();
+  const travisCommitRange  =
+      `${commonAncestor}...${process.env.TRAVIS_PULL_REQUEST_SHA}`;
```
Comment (jridgewell) [inline build-system/pr-check.js]: We can drop `...${process.env.TRAVIS_PULL_REQUEST_SHA}`

File: build-system/pr-check.js (hunk 2 above)
Comment (rsimha-amp) [inline build-system/pr-check.js]: Done.

File: build-system/pr-check.js (hunk 3 above)
Comment (rsimha-amp) [inline build-system/pr-check.js]: Done.

**Comment by rsimha-amp** [comment]
@erwinmombay, @jridgewell: On further reading https://www.kernel.org/pub/software/scm/git/docs/git-diff.html, we were on the right track. I've eliminated the use of `TRAVIS_PULL_REQUEST_SHA` in favor of `master` and `HEAD`, or more simply, just `master`. I'm going to run this a few times after pushing, rebasing, etc. to make sure that everything is good before merging it.

**Comment by jridgewell** [comment]
That's not what we want, we need to compare from `HEAD` to `FORK_POINT`. Imagine:

1. User forks to `branch`
2. User edits and commits `a.html`
3. We edit `b.html` on `master`
4. User submits PR

`b.html` will show up in the users diff, even though they never touched it.

**Comment by rsimha-amp** [comment]
Tried what you said, and the existing syntax does work.

- `git diff HEAD...master` will show you all commits on `master` since the common ancestor commit.
- `git diff master...HEAD` will show you all commits on `HEAD` since the common ancestor commit.

We're using the second version, you were probably using the first. (I don't see a.html *and* b.html in either version).

The other changes in this PR should alleviate the confusion better than before. I'll watch Travis to see if the issue recurs in future.
