### PR TITLE
🐛inabox: workaround to keep compiler from removing cross-domain check

### LINKED ISSUE #19653: Broken cross-domain check on Inabox
In #18794 we upgraded the closure compiler, which caused our compiled output to change from:

```
h.getMeasureableFrame = function(a) {
        if (!a) return null;
        for (var b, c = 0, d = a; 10 > c && d != d.top && !ra(d); c++, b = d, d = d.parent);
        if (b) {
            c = b.parent.document.querySelectorAll("iframe");
            d = 0;
            for (var e = c[d]; d < c.length; d++, e = c[d])
                if (e.contentWindow == b) return e
        }
        return a.frameElement
    };
```

to:

```
 h.getMeasureableFrame = function(a) {
        if (!a) return null;
        var b;
        if (b)
            for (var c = b.parent.document.querySelectorAll("iframe"), d = 0, e = c[d]; d < c.length; d++, e = c[d])
                if (e.contentWindow == b) return e;
        return a.frameElement
    };
```

The loop is checking `canInspectWindow_()` (`ra`, compiled)on a series of parent frames, looking for a cross domain frame, and the compiler has decided that this function will always return `true`.

That function does:

```
function canInspectWindow_(win) {
  try {
    const unused = !!win.location.href && win['test']; // eslint-disable-line no-unused-vars
    return true;
  } catch (unusedErr) { // eslint-disable-line no-unused-vars
    return false;
  }
}
```

Because the compiler assumes property reads can never throw, it deduces that `canInspectWindow_()` always returns `true`.

### PR DESCRIPTION
**Pull request by jeffkaufman**
The compiler assumes that property reads are side-effect free, and so is removing our check for whether a window is cross domain.  As a workaround, rewrite the function to confuse the compiler into keeping our code.  This could easily get broken again, though, if the compiler got smarter.

Fixes #19653

### CODE REVIEW

**Comment by jeffkaufman** [comment]
Sorry, this is slightly wrong, as @nbeloglazov and @zombifier point out; will fix

File: ads/inabox/inabox-messaging-host.js [hunk 1]
```diff
@@ -359,9 +359,12 @@ export class InaboxMessagingHost {
...
  */
 function canInspectWindow_(win) {
+  // TODO: this is not reliable.  The compiler assumes that property reads are
+  // side-effect free.  The recommended fix is to use goog.reflect.sinkValue
+  // but since we're not using the closure library I'm not sure how to do this.
+  // See https://github.com/google/closure-compiler/issues/3156
   try {
-    const unused = !!win.location.href && win['test']; // eslint-disable-line no-unused-vars
-    return true;
+    return !!win.location.href && win['test'];
```
Comment (jridgewell) [inline ads/inabox/inabox-messaging-host.js]: I wonder: `win.Object() !== win.Object()`.

Comment (jeffkaufman) [reply ads/inabox/inabox-messaging-host.js]: that could work; @nbeloglazov proposed `(win['test'] || true)` which should also work; I did that in ddad8f6

**Comment by jeffkaufman** [comment]
This compiles to:

```
function ra(a) {
  try{
    return !!a.location.href && (a.test || !0)
  } catch(b) {
    return !1
  }
}
```

which looks good to me.

(Verified with `gulp dist --noextensions --with-inabox` and then looking at `dist/amp4ads-host-v0.js`)

**Comment by jeffkaufman** [comment]
@jridgewell ready for re-review.

The travis failures look unrelated to me

**Comment by choumx** [comment]
Visual diffs were in amp-story (unrelated), approved.
