### PR TITLE
Using Array#includes instead Array#indexOf when needed

### LINKED ISSUE #8450: Cleanup uses of Array#indexOf to use Array#includes
### First Timers Only
We know figuring out the process for contributing to an open source project can be intimidating, so we created this issue as a way for you to learn the ropes.  (If you feel comfortable contributing to open source projects, please leave this issue for someone else.)

### What you will need to know
- Javascript

### Background

Recently, we introduced an [`Array#includes`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) polyfill to our codebase, so now everything in the core AMP code can use it. But, a lot of old code was written before this, so we have things like:

```js
// This is just Array#includes
if (array.indexOf(x) > -1) {
}
if (array.indexOf(x) >= 0) {
}
if (!(array.indexOf(x) == -1)) {
}

// Or this is array doesn't include
if (array.indexOf(x) == -1) {
}
if (array.indexOf(x) < 0) {
}
```

### Motivation

It'd be good to convert these over to just use `Array#includes` (or the not version).

### Step by step
- [ ] Claim this issue by adding a comment below.  Please only claim this bug if you plan on starting work in the next day or so.
- [ ] If you aren't too familiar with Git/GitHub, see the [Getting Started End-to-End Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md) for [an intro to Git & GitHub,](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#intro-to-git-and-github) and [how to get a copy of the code](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#get-a-copy-of-the-amphtml-code).  You can also refer to the [Quick Start Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md) for the necessary setup steps with less explanation than the End-to-End guide.
- [ ] Follow the instructions for [building AMP](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#building-amp-and-starting-a-local-server).
- [ ] [Create a Git branch](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#create-a-git-branch) for making your changes.
- [ ] Replace uses of `#indexOf`
  - Grep search for `"\.indexOf\("`
  - If the caller is definitely an Array instance, let's convert it over to `#includes`
  - The one exception is when the return index is actually needed (like a splice or something). Basically, only convert if we just need a boolean check
- [ ] [Commit your changes](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#edit-files-and-commit-them) frequently.
- [ ] [Push your changes to GitHub](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#push-your-changes-to-your-github-fork).
- [ ] [Create a Pull Request](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#send-a-pull-request-ie-request-a-code-review).  Mention `closes Issue <this issue number>` in the description.
  - CC Me (@jridgewell) and Kevin (@kmh287)
- [ ] [Respond to your reviewer's comments](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#respond-to-pull-request-comments) (if any).

Once approved, your changes will be merged.  **⚡⚡⚡Congrats on making your first contribution to the AMP Project!⚡⚡⚡**  You'll be able to see it [live across the web soon](https://github.com/ampproject/amphtml/blob/master/README.md#releases)!

Thanks, and we hope to see more contributions from you soon.

### Questions?

If you have questions ask in this issue or on your Pull Request (if you've created one) or see the [How to get help](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#how-to-get-help) section of the Getting Started guide.  Or ping @jridgewell.

### PR DESCRIPTION
**Pull request by nandosangenetto**
- Changed `.indexOf(var) > -1` to `.includes(var) === true`
- Changed `.indexOf(var) >= 0` to `.includes(var) === true`
- Changed `(!(array.indexOf(var) == -1)` to `.includes(var) === true`
- Changed `.indexOf(var) == -1` to `.includes(var) === false`
- Changed `.indexOf(var) === -1` to `.includes(var) === false`
- Changed `.indexOf(var) < 0` to `.includes(var) === false`

Closes #8450

### CODE REVIEW

**Comment by nandosangenetto** [comment]
I signed it!

File: 3p/3p.js [hunk 1]
```diff
@@ -154,7 +154,7 @@ export function validateSrcPrefix(prefix, src) {
  * @param {string} src
  */
 export function validateSrcContains(string, src) {
-  if (src.indexOf(string) === -1) {
+  if (src.includes(string) === false) {
```
Comment (choumx) [inline 3p/3p.js]: Instead of `if (condition === false)`, please use `if (!condition)`. Likewise for the `true` case. It's more concise and easier to read!

File: yarn.lock [hunk 2]
```diff
@@ -345,7 +345,7 @@ asynckit@^0.4.0:
   version "0.4.0"
   resolved "https://registry.yarnpkg.com/asynckit/-/asynckit-0.4.0.tgz#c79ed97f7f34cb8f2ba1bc9790bcc366474b4b79"
 
-autoprefixer@6.7.0:
+autoprefixer@6.7.0, autoprefixer@^6.0.3:
```
Comment (choumx) [inline yarn.lock]: Please revert this file to keep the PR strictly relevant to the attached issue.

**Comment by nandosangenetto** [comment]
Done @choumx and @jridgewell

File: ads/holder.js [hunk 3]
```diff
@@ -25,7 +25,7 @@ export function holder(global, data) {
   const wcl = global.context.location;
   const n = navigator.userAgent;
   let l = '&r' + Math.round((Math.random() * 10000000)) + '&h' + wcl.href;
-  if (!(n.indexOf('Safari') != -1 && n.indexOf('Chrome') == -1)) {
+  if (!(n.includes('Safari') && !n.includes('Chrome'))) {
```
Comment (kmh287) [inline ads/holder.js]: This may be more readable as 
```js
if (!n.includes('Safari') || n.includes('Chrome')) { ... }
```

File: 3p/3p.js [hunk 4]
```diff
@@ -154,7 +154,7 @@ export function validateSrcPrefix(prefix, src) {
  * @param {string} src
```
Comment (jridgewell) [inline 3p/3p.js]: So everything in this file cannot be updated, because the 3p directory is run in foreign iframes. This means they will not have the `Array#includes` polyfill installed in them.

File: ads/alp/handler.js [hunk 5]
```diff
@@ -73,7 +73,7 @@ export function handleClick(e, opt_viewerNavigate) {
   const fragment = 'click=' + encodeURIComponent(
       addParamToUrl(link.a.href, 'amp', '1', /* opt_addToFront */ true));
   let destination = link.eventualUrl;
-  if (link.eventualUrl.indexOf('#') == -1) {
+  if (!link.eventualUrl.includes('#')) {
```
Comment (jridgewell) [inline ads/alp/handler.js]: `String#includes` is not supported in IE.

File: ads/alp/handler.js [hunk 6]
```diff
@@ -224,7 +224,7 @@ export function getA2AAncestor(win) {
   // Not a security property. We just check whether the
   // viewer might support A2A. More domains can be added to whitelist
   // as needed.
-  if (top.indexOf('.google.') == -1) {
+  if (!top.includes('.google.')) {
```
Comment (jridgewell) [inline ads/alp/handler.js]: `String#includes` is not supported in IE.

File: ads/holder.js (hunk 3 above)
Comment (jridgewell) [inline ads/holder.js]: `String#includes` is not supported in IE.

File: ads/medianet.js [hunk 7]
```diff
@@ -132,7 +132,7 @@ function loadHBTag(global, data, publisherUrl, referrerUrl) {
     let currentParam = '';
     for (let i = 0; i < allParams.length; i++) {
       currentParam = allParams[i];
-      if (dfpParams.indexOf(currentParam) === -1 && data[currentParam]) {
+      if (!dfpParams.includes(currentParam) && data[currentParam]) {
```
Comment (jridgewell) [inline ads/medianet.js]: So everything in this file cannot be updated, because the ads directory is run in foreign iframes. This means they will not have the Array#includes polyfill installed in them.

File: ads/taboola.js [hunk 8]
```diff
@@ -38,7 +38,7 @@ export function taboola(global, data) {
 
   // copy none blacklisted attribute to the 'params' map
   Object.keys(data).forEach(k => {
-    if (blackList.indexOf(k) === -1) {
+    if (!blackList.includes(k)) {
```
Comment (jridgewell) [inline ads/taboola.js]: So everything in this file cannot be updated, because the ads directory is run in foreign iframes. This means they will not have the Array#includes polyfill installed in them.

File: extensions/amp-access/0.1/login-dialog.js [hunk 9]
```diff
@@ -307,6 +307,6 @@ function buildLoginUrl(url, returnUrl) {
     return url.replace(RETURN_URL_REGEX, encodeURIComponent(returnUrl));
   }
   return url +
-      (url.indexOf('?') == -1 ? '?' : '&') +
+      (!url.includes('?') ? '?' : '&') +
```
Comment (jridgewell) [inline extensions/amp-access/0.1/login-dialog.js]: `String#includes` is not supported in IE.

File: extensions/amp-ad-network-cloudflare-impl/0.1/amp-ad-network-cloudflare-impl.js [hunk 10]
```diff
@@ -110,7 +110,7 @@ export class AmpAdNetworkCloudflareImpl extends AmpA4A {
     url = encodeURI(this.replacements(url, values));
 
     // include other data attributes as query parameters
-    let pre = url.indexOf('?') < 0 ? '?' : '&';
+    let pre = !url.includes('?') ? '?' : '&';
```
Comment (jridgewell) [inline extensions/amp-ad-network-cloudflare-impl/0.1/amp-ad-network-cloudflare-impl.js]: `String#includes` is not supported in IE.

File: extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js [hunk 11]
```diff
@@ -269,7 +269,7 @@ export class AmpAdXOriginIframeHandler {
       // unlayout already called
       return;
     }
-    this.freeXOriginIframe(this.iframe.name.indexOf('_master') >= 0);
+    this.freeXOriginIframe(this.iframe.name.includes('_master'));
```
Comment (jridgewell) [inline extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js]: `String#includes` is not supported in IE.

File: extensions/amp-analytics/0.1/amp-analytics.js [hunk 12]
```diff
@@ -595,7 +595,7 @@ export class AmpAnalytics extends AMP.BaseElement {
     }
 
     const paramString = s.join('&');
-    if (request.indexOf('${extraUrlParams}') >= 0) {
+    if (request.includes('${extraUrlParams}')) {
```
Comment (jridgewell) [inline extensions/amp-analytics/0.1/amp-analytics.js]: `String#includes` is not supported in IE.

File: ads/holder.js (hunk 3 above)
Comment (nandosangenetto) [inline ads/holder.js]: Yep, I agree. I'll commit this change.

File: src/3p-frame.js [hunk 13]
```diff
@@ -264,7 +264,7 @@ function getCustomBootstrapBaseUrl(parentWindow, opt_strictForUnitTest) {
     return null;
   }
   const url = assertHttpsUrl(meta.getAttribute('content'), meta);
-  user().assert(url.indexOf('?') == -1,
+  user().assert(!url.includes('?'),
```
Comment (jridgewell) [inline src/3p-frame.js]: `String#includes` is not supported in IE.

File: src/runtime.js [hunk 14]
```diff
@@ -802,7 +802,7 @@ class MultidocManager {
             } else {
               // Non-src version of script.
               const type = n.getAttribute('type') || 'application/javascript';
-              if (type.indexOf('javascript') == -1) {
+              if (!type.includes('javascript')) {
```
Comment (jridgewell) [inline src/runtime.js]: `String#includes` is not supported in IE.

File: src/service-worker/core.js [hunk 15]
```diff
@@ -233,7 +233,7 @@ export function isBlacklisted(version) {
    * @type {AmpVersion}
    */
   const ampVersion = version.substr(2);
-  return BLACKLIST.indexOf(ampVersion) > -1;
+  return BLACKLIST.includes(ampVersion);
```
Comment (jridgewell) [inline src/service-worker/core.js]: This is another special file that can't be updated just yet.

File: src/service/extension-location.js [hunk 16]
```diff
@@ -76,7 +76,7 @@ export function calculateEntryPointScriptUrl(location, entryPoint, isLocalDev,
  */
 function isMax(location) {
   const path = location.pathname;
-  return path.indexOf('.max') >= 0 || path.indexOf('/max/') >= 0;
+  return path.includes('.max') || path.includes('/max/');
```
Comment (jridgewell) [inline src/service/extension-location.js]: `String#includes` is not supported in IE.

File: src/service/extension-location.js [hunk 17]
```diff
@@ -86,5 +86,5 @@ function isMax(location) {
  */
 function isMin(location) {
   const path = location.pathname;
-  return path.indexOf('.min') >= 0 || path.substr(0, 5) == '/min/';
+  return path.includes('.min') || path.substr(0, 5) == '/min/';
```
Comment (jridgewell) [inline src/service/extension-location.js]: `String#includes` is not supported in IE.

File: src/service/variable-source.js [hunk 18]
```diff
@@ -160,7 +160,7 @@ export class VariableSource {
    * @return {!VariableSource}
    */
   set(varName, syncResolver) {
-    dev().assert(varName.indexOf('RETURN') == -1);
+    dev().assert(!varName.includes('RETURN'));
```
Comment (jridgewell) [inline src/service/variable-source.js]: `String#includes` is not supported in IE.

File: src/service/variable-source.js [hunk 19]
```diff
@@ -179,7 +179,7 @@ export class VariableSource {
    * @return {!VariableSource}
    */
   setAsync(varName, asyncResolver) {
-    dev().assert(varName.indexOf('RETURN') == -1);
+    dev().assert(!varName.includes('RETURN'));
```
Comment (jridgewell) [inline src/service/variable-source.js]: `String#includes` is not supported in IE.

File: src/url.js [hunk 20]
```diff
@@ -371,7 +371,7 @@ export function getSourceUrl(url) {
       ? 'https://' + decodeURIComponent(path[3])
       : 'http://' + decodeURIComponent(domainOrHttpsSignal);
   // Sanity test that what we found looks like a domain.
-  user().assert(origin.indexOf('.') > 0, 'Expected a . in origin %s', origin);
+  user().assert(origin.includes('.'), 'Expected a . in origin %s', origin);
```
Comment (jridgewell) [inline src/url.js]: `String#includes` is not supported in IE.

File: third_party/mustache/mustache.js [hunk 21]
```diff
@@ -386,7 +386,7 @@
       var context = this, names, index, lookupHit = false;
 
       while (context) {
-        if (name.indexOf('.') > 0) {
+        if (name.includes('.')) {
```
Comment (jridgewell) [inline third_party/mustache/mustache.js]: `String#includes` is not supported in IE.

File: third_party/webcomponentsjs/ShadowCSS.js [hunk 22]
```diff
@@ -236,7 +236,7 @@ export const ShadowCSS = {
       scoped = parts.map(function(p) {
         // remove :host since it should be unnecessary
         var t = p.trim().replace(polyfillHostRe, '');
-        if (t && (splits.indexOf(t) < 0) && (t.indexOf(attrName) < 0)) {
+        if (t && (!splits.includes(t)) && (!t.includes(attrName))) {
```
Comment (jridgewell) [inline third_party/webcomponentsjs/ShadowCSS.js]: The `t.includes` is `String#includes`. `String#includes` is not supported in IE.

File: validator/engine/validator.js [hunk 23]
```diff
@@ -837,7 +837,7 @@ class ChildTagMatcher {
     this.numChildTagsSeen_++;  // Increment this first to allow early exit.
     if (childTags.childTagNameOneof.length > 0) {
       const names = childTags.childTagNameOneof;
-      if (names.indexOf(tagName) === -1) {
+      if (!names.includes(tagName)) {
```
Comment (jridgewell) [inline validator/engine/validator.js]: Another special file that can't be updated.

File: 3p/3p.js (hunk 4 above)
Comment (nandosangenetto) [inline 3p/3p.js]: I see. Ok, I'll revert this file.

File: ads/taboola.js [hunk 24]
```diff
@@ -28,7 +28,7 @@ export function taboola(global, data) {
   // ensure we have vlid publisher, placement and mode
   // and exactly one page-type
   validateData(data, ['publisher', 'placement', 'mode',
-    ['article', 'video', 'photo', 'search', 'category', 'homepage', 'others']]);
+    ['article', 'video', 'photo', 'search', 'category', 'homepage', 'other']]);
```
Comment (jridgewell) [inline ads/taboola.js]: Can't change this.

**Comment by nandosangenetto** [comment]
Done @jridgewell, everything should be ok now :)

File: extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js [hunk 25]
```diff
@@ -184,7 +184,7 @@ describes.sandboxed('amp-ad-network-adsense-impl', {}, () => {
         ampStickyAd.appendChild(element);
         fixture.doc.body.appendChild(ampStickyAd);
         return impl.getAdUrl().then(adUrl => {
-          expect(adUrl.indexOf('act=sa') >= 0).to.be.true;
+          expect(adUrl.includes('act=sa')).to.be.true;
```
Comment (jridgewell) [inline extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js]: I missed this one.

Comment (nandosangenetto) [inline extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js]: Done.

File: ads/taboola.js (hunk 24 above)
Comment (nandosangenetto) [inline ads/taboola.js]: Reverted manually.

File: build-system/app.js [hunk 26]
```diff
@@ -729,7 +730,7 @@ app.get('/dist/rtv/9[89]*/*.js', function(req, res, next) {
 
   setTimeout(() => {
     // Cause a delay, to show the "stale-while-revalidate"
-    if (req.path.indexOf('v0.js') > -1) {
+    if (req.path.includes('v0.js')) {
```
Comment (kmh287) [inline build-system/app.js]: @jridgewell Can we use `includes` here in app.js?
