### PR TITLE
Make inabox host correctly get position of a nested iframe

### LINKED ISSUE #14010: inabox visible trigger broken for nested friendly iframe
in case that frame windows are nested in the following way:

host window -> friendly child iframe -> friendly ad iframe

PR #12541 changed host script to observe the position of `friendly ad iframe` instead of `friendly child iframe`. 

It caused a bug in [this code](https://github.com/ampproject/amphtml/blob/master/ads/inabox/position-observer.js#L91) when we trying to measure the position of the iframe. The coordinate system is no longer the host document as we expected.

The fix will be to traverse all way to the host window and add the offsets.

### PR DESCRIPTION
**Pull request by zombifier**
Fixes #14010.

### CODE REVIEW

**Comment by lannka** [comment]
thanks @zombifier for the quick fix! will take a look later today.

Meantime, have you checked the local example mentioned in #14010 with your fix?

**Comment by zombifier** [comment]
I had, and it works.

**Comment by lannka** [comment]
awesome. is it easy to add an integration test ?

**Comment by zombifier** [comment]
I can try; the main issue is that the main test iframe is scrollable and by default much smaller than the browser window, so even if the creative is not visible it could technically still be within the size of the viewport and trigger viewability. I can try to see if resizing the test iframe to full height can help.

Visibility detection in general does not work properly if any of the nested iframes can be scrolled so its content enter the viewport rectangle while remaining invisible (and it's more or less impossible to fix without native IntersectionObserver), but that's not the case we ever need to bother about outside of testing.

**Comment by zombifier** [comment]
I should probably add some unit tests though.

**Comment by lannka** [comment]
> I should probably add some unit tests though.

Might be hard for unit test to simulate the nested iframe situation though.

File: ads/inabox/position-observer.js [hunk 1]
```diff
@@ -142,3 +144,27 @@ function getScrollingElement(win) {
 function isWebKit(ua) {
   return /WebKit/i.test(ua) && !/Edge/i.test(ua);
 }
+
+/**
+ * Get the element's layout rect relative to the viewport.
+ * If parentWin is provided, then attempt to walk up the DOM and add the
```
Comment (lannka) [inline ads/inabox/position-observer.js]: shall we just always walk up to the host window?

File: ads/inabox/position-observer.js [hunk 2]
```diff
@@ -142,3 +144,27 @@ function getScrollingElement(win) {
...
+ * friendly and can be inspected (because the element itself can be inspected
+ * as well).
+ * @param {!Element} element
+ * @param {?Window} parentWin The window that contains the element
+ * @return {!LayoutRectDef}
+ */
+export function getTargetRect(element, parentWin) {
+  let targetRect = layoutRectFromDomRect(element./*OK*/getBoundingClientRect());
+  if (parentWin) {
+    for (let j = 0, tempWin = parentWin;
```
Comment (lannka) [inline ads/inabox/position-observer.js]: nit: `while` loop might fit better here?

File: ads/inabox/position-observer.js [hunk 3]
```diff
@@ -142,3 +144,27 @@ function getScrollingElement(win) {
...
+      j < 10 && tempWin != tempWin.top; j++, tempWin = tempWin.parent) {
```
Comment (lannka) [inline ads/inabox/position-observer.js]: so the assumption is `tempWin.top` is the host window? I feel it's not that reliable. Any better way?

Comment (zombifier) [reply ads/inabox/position-observer.js]: I agree. The host window is the window that has the position observer installed, so I moved the function into the class and have the DOM climb stop at that window. The top condition remains just in case.

File: ads/inabox/position-observer.js (hunk 1 above)
Comment (zombifier) [reply ads/inabox/position-observer.js]: the parentWin parameter has to be provided, since this is a general-purpose position observer and there's no way to get the immediate window/iframe that contains the observed element.

I can change it so that if parentWin is not provided then automatically assume the host window to be its immediate parent. What do you think?

**Comment by rsimha** [comment]
Removing myself, since the latest commit doesn't seem to increase the bundle size. Feel free to re-add me if that's not the case.

**Comment by zombifier** [comment]
Since the amp-inabox integration tests are in nested iframe mode, if they're successfully reenabled on Safari I think that's a good enough integration test for this PR. I'm not pushing the commit until Sauce is reenabled on master, but manual local Sauce testing seems to confirm that it works.

File: ads/inabox/position-observer.js (hunk 1 above)
Comment (lannka) [reply ads/inabox/position-observer.js]: Does `targetElement.ownerDocument.defaultView` not work?

Comment (zombifier) [reply ads/inabox/position-observer.js]: TIL. I will try that. If it works then the parameter wouldn't be needed.

**Comment by lannka** [comment]
> Since the amp-inabox integration tests are in nested iframe mode, if they're successfully reenabled on Safari I think that's a good enough integration test for this PR. I'm not pushing the commit until Sauce is reenabled on master, but manual local Sauce testing seems to confirm that it works.

that sounds good. thanks for checking

File: ads/inabox/position-observer.js (hunk 3 above)
Comment (lannka) [reply ads/inabox/position-observer.js]: sorry, I still didn't quite get it. where is the code to stop the DOM climb at host window?

Comment (lannka) [reply ads/inabox/position-observer.js]: ah, sorry, was looking at outdated file.

**Comment by zombifier** [comment]
@lannka Is this ready? I resolved all the flaky tests by merging with upstream.

**Comment by lannka** [comment]
Merged, good work!
