### PR TITLE
🏗 Run E2E test job in PRs only when you have a build artifact

### LINKED ISSUE #21880: Don't run E2E tests unless runtime changes are included in a PR
For validator-only changes, there is no runtime build. Therefore, the E2E test job fails.

Let's skip E2E tests unless there are runtime changes and a build was generated.

https://travis-ci.org/ampproject/amphtml/jobs/518871123#L322

```
e2e-tests.js: Downloading build output from gs://amp-travis-builds/amp_build_56929.zip...
Activated service account credentials for: [sa-travis@amp-travis-build-storage.iam.gserviceaccount.com]
Updated property [core/account].
Updated property [core/pass_credentials_to_gsutil].
[core]
account = sa-travis@amp-travis-build-storage.iam.gserviceaccount.com
disable_usage_reporting = True
pass_credentials_to_gsutil = true
project = travis-ci-prod-2
Your active configuration is: [default]
CommandException: No URLs matched: gs://amp-travis-builds/amp_build_56929.zip
The command "node build-system/pr-check/e2e-tests.js" exited with 1.
```

### PR DESCRIPTION
**Pull request by estherkim**
Uses the same logic that creates a build artifact in the build job when running the e2e test job.

Fixes #21880

### CODE REVIEW

File: build-system/pr-check/e2e-tests.js [hunk 1]
```diff
@@ -21,31 +21,49 @@
...
-    downloadBuildOutput(FILENAME);
-  }
-  timedExecOrDie('gulp update-packages');
-  timedExecOrDie('gulp e2e --nobuild --headless');
+    if (buildTargets.has('RUNTIME') ||
+        buildTargets.has('UNIT_TEST') ||
+        buildTargets.has('INTEGRATION_TEST') ||
+        buildTargets.has('BUILD_SYSTEM') ||
+        buildTargets.has('FLAG_CONFIG') ||
+        buildTargets.has('VISUAL_DIFF')) {
```
Comment (danielrozenberg) [inline build-system/pr-check/e2e-tests.js]: Why are these relevant to visual diffs?

Comment (estherkim) [reply build-system/pr-check/e2e-tests.js]: Not exactly relevant, but I'd like to run this job whenever possible, which means whenever a build artifact is created. By doing so we'd catch errors more quickly if something external changed, like browser versions.
