### PR TITLE
🏗 Use a mock instead of a stub to catch console errors during tests

### LINKED ISSUE #7381: Change tests to fail on logged errors unless they are expected
A recent change no longer async throws these errors, but relying on that to fail the test was always brittle.

It would be great if we could add a device to expect error logs and fail tests if they don't do so.

### PR DESCRIPTION
**Pull request by rsimha**
In #14336, a stub was added for `console.error` that would throw an exception when called from within a test.

This PR implements the same check more elegantly by using a mock for `console.error`. It also adds a helper function called `allowConsoleError` that tests can use when they want execute code that may generate an error.

For now, given the sheer number of AMP tests that generate console errors, we print a warning after each test (local dev) / after all tests (on Travis) with instructions for how to fix these errors. Once all of them are fixed (or wrapped in an `allowConsoleError` block), we can start failing tests when an error is encountered.

**Examples:**

This test will print a warning...
```
it('test with unexpected console errors', () => {
  doAThing();  // No console error
  doAnotherThing(); // Contains a console error
  doYetAnotherThing(); // Contains a console error
});
```
... and so will this test...
```
it('test with some unexpected console errors', () => {
  doAThing();  // No console error
  allowConsoleError(() => {
    doAnotherThing(); // Contains a console error
  });
  doYetAnotherThing(); // Contains a console error
});
```
... but this test will pass...
```
it('test with all expected console errors', () => {
  doAThing();  // No console error
  allowConsoleError(() => {
    doAnotherThing(); // Contains a console error
    doYetAnotherThing(); // Contains a console error
  });
});
```

Fixes #7381
Follow up to #14336
Related to #14406

### CODE REVIEW

**Comment by rsimha** [comment]
This is incomplete as is, and needs an override for the chai assertion `expect().to.throw`.

**Comment by rsimha** [comment]
@choumx After further debugging, it appears that using a mock will break existing usage of `expect().to.throw` in our tests. 

I suspect we're going to have to abandon this PR and go back to what @danielrozenberg was doing with the stub. 

Will discuss in person to see if there's a way around this with mocks.

File: test/_init_tests.js [hunk 1]
```diff
@@ -265,13 +265,33 @@ sinon.sandbox.create = function(config) {
...
+    this.consoleMock.verify();
+  } catch (e) {
+    const helpMessage =
+        'Your test resulted in an unexpected call to console.error.\n' +
+        '⤷ If the error is real, fix the code that generated it.\n' +
+        '⤷ If the error is expected:\n' +
+        '  ⤷ Call "this.consoleMock.expects(\'error\').withArgs' +
+            '(\'<message>\')" before the code containing the error.\n' +
+        '  ⤷ Call "this.consoleMock.expects(\'error\').never()" ' +
+            'after the code containing the error.\n';
```
Comment (danielrozenberg) [inline test/_init_tests.js]: 1) I'm not sure if you have add the expectation before the offending call to `console.error(…)`, since mocks are only verified in the `afterEach` hook. You can remove the "before the code containing the error" part, replace it with "inside your test". Test writers should be able to decide where they want to write the expectations :)

2) Does this `.never()` resetting work as expected? Again, since `.verify()` happens at the end, I think you're telling test writers to reset the expectation that they just wrote, before the mock gets verified. I think if you want the test to be very explicit it should be something like:
```javascript
…
this.consoleMock.expects('error').withArgs('foo', 'bar');
doStuff(); // calls console.error('foo', 'bar');
this.consoleMock.verify();
this.consoleMock.expects('error').never();
…
```
But this seems a bit _too_ explicit. Maybe instead we can suggest this:
```javascript
this.consoleMock.expects('error').once().withArgs('foo', 'bar');
```
(this way, the `.verify()` call at the end verifies the `.once()` constraint)

3) `<message>` is vague. I suggest adding a link to http://sinonjs.org/releases/v4.5.0/matchers/ (nit: can we dynamically replace the version number to always point to the Sinon version we're using?)

**Comment by rsimha** [comment]
Responding to top level comment re: mocks vs stubs first.

There are 541 instances of `to.throw()` in our tests, and a sizeable number of them look for an error message.

https://gist.github.com/rsimha/0e2b456f5d41d953692840380f65fbe1

**Comment by danielrozenberg** [comment]
A cursory glance over a few of these seems to show that these errors are thrown using `user().assert()` or `dev().assert()`. Shouldn't that still work then?

**Comment by rsimha** [comment]
I believe `user.assert()` and `dev().assert` internally call `console.log()`. There is likely some logic that causes them to do things differently in non-local-dev or non-test mode, but I'm not sure what it is.

File: test/_init_tests.js (hunk 1 above)
Comment (rsimha) [reply test/_init_tests.js]: Based on offline discussions and debugging with @danielrozenberg, I retract my comment above re: abandoning the approach that uses mocks. Updated commits coming up. The above comments are moot.

File: build-system/tasks/karma.conf.js [hunk 2]
```diff
@@ -197,7 +197,7 @@ module.exports = {
       // Longer timeout on Travis; fail quickly at local.
       timeout: process.env.TRAVIS ? 10000 : 2000,
     },
-    captureConsole: false,
+    captureConsole: true, // DEBUGGING
```
Comment (danielrozenberg) [inline build-system/tasks/karma.conf.js]: I'm assuming this is supposed to be gone before merging?

File: test/_init_tests.js [hunk 3]
```diff
@@ -265,13 +266,40 @@ sinon.sandbox.create = function(config) {
...
+    mockConsoleError();
+  };
+}
+
+function restoreConsoleError() {
+  try {
+    consoleMock.verify();
+  } catch (e) {
+    const helpMessage =
+        'Your test resulted in an unexpected call to console.error.\n' +
```
Comment (danielrozenberg) [inline test/_init_tests.js]: nit: :%s/unexpected call/uncaught call/g (since you're continuing later to say "if this was expected/not expected, it seems odd to announce from beforehand that the call was unexpected)

File: test/_init_tests.js [hunk 4]
```diff
@@ -265,13 +266,40 @@ sinon.sandbox.create = function(config) {
   return sandbox;
 };
 
+function mockConsoleError() {
```
Comment (danielrozenberg) [inline test/_init_tests.js]: nit: the naming of mockConsoleError and forbidConsoleError bother me, since the "forbidding" part is happening inside the function called "mock". Not sure how I would rename them tho...
