### PR TITLE
🏗🐛 Clean up iframes between tests on Safari

### LINKED ISSUE #29930: Integration tests on Safari run in parallel instead of in series
This is a bug because every test's iframe is created in a single Karma window. It affects common assertions like element position, and fails to ensure silo'ed environments per test.

Note that this is seen in Safari only, and not Firefox or Chrome.

Thanks @zhouyx for the find!

### PR DESCRIPTION
**Pull request by rsimha**
Implements the plan in https://github.com/ampproject/amphtml/issues/29930#issuecomment-682988055 by cleaning up iframes between tests on Safari. With this, tests that rely on absolute position should no longer fail due to the presence of multiple iframes.

I can see that `test/integration/test-amp-ad-3p.js` passes locally when run with other tests. Will confirm with a full run on GH actions.

Fixes #29930

### CODE REVIEW

**Comment by rsimha** [comment]
Review link that hides whitespace-only changes: https://github.com/ampproject/amphtml/pull/30029/files?w=1

File: test/integration/test-amp-ad-3p.js [hunk 1]
```diff
@@ -23,261 +23,254 @@ function createFixture() {
...
+        fixture.win.scrollTo(0, 1125);
+        fixture.win.dispatchEvent(new Event('scroll'));
+        await poll(
+          'wait for new IO entry when intersectionRatio changes',
+          () => {
             return (
               lastIO != null &&
-              lastIO.boundingClientRect.top == (platform.isIos() ? 1 : 0) &&
-              lastIO.intersectionRatio == 1
+              lastIO.intersectionRatio > 0 &&
```
Comment (estherkim) [inline test/integration/test-amp-ad-3p.js:232]: Intentional change?

Comment (zhouyx) [reply test/integration/test-amp-ad-3p.js:232]: I think this is a mismatch between the two versions. This compares to previous line 239 : )

Comment (rsimha) [reply test/integration/test-amp-ad-3p.js:232]: Can confirm this line wasn't changed, it was merely re-indented. I verified that the code is the same by hiding whitespaces: https://github.com/ampproject/amphtml/pull/30029/files?w=1
