### PR TITLE
Fixture setup timeout should be same as Mocha's

### LINKED ISSUE #9906: Flaky integration test: test-extensions-loading & test-errors
https://travis-ci.org/ampproject/amphtml/jobs/242641942

```
Chrome 45.0.2454 (Linux 0.0.0) test extensions loading in multiple orders two extensions, one of extension scripts and v0 in header FAILED
	Error: Timeout waiting for elements to start loading.
	    at /home/travis/build/ampproject/amphtml/testing/iframe.js:152:15 <- /tmp/1cdfdf8c28006aa7b83f2c72cb85513d.browserify:55167:16

### PR DESCRIPTION
**Pull request by choumx**
Fixes #9906 (hopefully).

### CODE REVIEW

File: testing/iframe.js [hunk 1]
```diff
@@ -152,7 +152,7 @@ export function createFixtureIframe(fixture, initialIframeHeight, opt_beforeLoad
       };
       let timeout = setTimeout(function() {
         reject(new Error('Timeout waiting for elements to start loading.'));
-      }, 2000);
+      }, process.env.TEST_TIMEOUT);
```
Comment (jridgewell) [inline testing/iframe.js]: I don't know if `process` is propagated to the browser by Karma. We do a few things like this elsewhere, but I can't find it on my phone.

Comment (choumx) [inline testing/iframe.js]: It worked for me locally but I don't see precedence for this. Changed it to use `ampTestRuntimeConfig` instead.
