### PR TITLE
IntersectionObserver: Translate element coords into viewport coords

### LINKED ISSUE #5090: observeIntersection sends incorrect rootBounds and boundingClientRect
Please walk through the following steps for reporting an issue about AMP:

## Short description of your issue:

```Top``` and ```bottom``` of ```rootBounds``` change incorrectly as the amp-ad moves within the page.  We would expect ```rootBounds``` to remain constant.  ```Top``` and ```bottom``` of ```boundingClientRect``` do not change, which would expect to change as the amp-ad moves within the page.

For example, this hack fixes the top and bottom of boundingClientRect to be the same as in non-amp pages:
```javascript
latestIntersection['boundingClientRect']['top'] = latestIntersection['boundingClientRect']['top'] - latestIntersection['rootBounds']['top'];
latestIntersection['boundingClientRect']['bottom'] = latestIntersection['boundingClientRect']['bottom'] - latestIntersection['rootBounds']['bottom'];
```

## How do we reproduce the issue?

Please post a public URL and ideally post a reduced test case. E.g. on jsbin.com that exhibits only your issue and nothing else.

See:
http://test.yieldmo.com.s3.amazonaws.com/basak/index-amp_1ad.html
(first ad labeled "You may like")

Internally, this uses the event data from observeIntersection to get its position.  We would expect the behavior to match this:
http://test.yieldmo.com/test/hyperscroller.html

Since this JS needs to be run in the context of an amp ad, making a reduced test case is a little tricky — but let me know if I can help reproduce the issue.

## What browsers are affected?

iOS and Android, all browsers

## Which AMP version is affected?

Reproducible using amp v. 1474060428356.  The behavior seems to have changed recently

### PR DESCRIPTION
**Pull request by jridgewell**
I made a mistake in Fixes a mistake in #4826. The “viewport” we report
moves with the scroll position, while a real IntersectionObserver does
not. And, our elements didn’t move with the scroll position, while the
real one did.

So, this translates elements into their position relative to scroll,
and removes the scroll relative position from viewport.

Fixes #5090.
/cc @jasti

### CODE REVIEW

**Comment by sriramkrish85** [comment]
could you add unit tests with and without owner on the function.

File: src/intersection-observer.js [hunk 1]
```diff
@@ -81,20 +81,29 @@ export function getIntersectionChangeEntry(element, owner, viewport) {
       'Negative dimensions in element.');
   // Building an IntersectionObserverEntry.
 
-  let intersectionRect = element;
+  // The element is relative to (0, 0), while the viewport moves. So, we must
+  // adjust.
+  const boundingClientRect = moveLayoutRect(element, -viewport.left,
```
Comment (dvoytenko) [inline src/intersection-observer.js]: Can we do this for `position:fixed` elements?

File: src/intersection-observer.js [hunk 2]
```diff
@@ -81,20 +81,29 @@ export function getIntersectionChangeEntry(element, owner, viewport) {
...
-    intersectionRect = rectIntersection(owner, intersectionRect) ||
+    const ownerRect = moveLayoutRect(owner, -viewport.left, -viewport.top);
+    intersectionRect = rectIntersection(ownerRect, boundingClientRect) ||
         // No intersection.
         layoutRectLtwh(0, 0, 0, 0);
   }
-  intersectionRect = rectIntersection(viewport, intersectionRect) ||
+
+  // Now, a normal IntersectionObserver reports the viewport as (x,y) (0, 0).
+  const rootBounds = moveLayoutRect(viewport, -viewport.left, -viewport.top);
```
Comment (dvoytenko) [inline src/intersection-observer.js]: That's simply the viewport rect with `0/0` for top/left. Right?

File: src/intersection-observer.js [hunk 3]
```diff
@@ -81,20 +81,29 @@ export function getIntersectionChangeEntry(element, owner, viewport) {
...
+  intersectionRect = rectIntersection(rootBounds, intersectionRect) ||
       // No intersection.
       layoutRectLtwh(0, 0, 0, 0);
 
   return /** @type {!IntersectionObserverEntry} */ ({
     time: Date.now(),
-    rootBounds: DomRectFromLayoutRect(viewport),
-    boundingClientRect: DomRectFromLayoutRect(element),
+    rootBounds: DomRectFromLayoutRect(rootBounds),
```
Comment (dvoytenko) [inline src/intersection-observer.js]: I, sort of, can see both interpretation is being ok - since they look to be using the same coord system in both cases: one is adjusted to 0 and one is not. But the new system adds more calculations and object-creation. How does the spec define `rootBounds`? Obviously, I'd expect `boundingClientRect` to be viewport based...

File: src/intersection-observer.js (hunk 1 above)
Comment (jridgewell) [inline src/intersection-observer.js]: I'm still fighting with this problem. It fixes the normal case (non-fixed), but breaks fixed.

I think I'm going to have to change how we calculate the position of fixed elements. We currently add the viewport to their bounding box, where we shouldn't -- most of the time. I was really hoping to avoid Layers.

File: src/intersection-observer.js (hunk 2 above)
Comment (jridgewell) [inline src/intersection-observer.js]: Yup.

File: src/intersection-observer.js (hunk 3 above)
Comment (jridgewell) [inline src/intersection-observer.js]: > How does the spec define rootBounds? 

`root.getBoundingClientRect()`. Or, if there's no root (the viewport is the implicit root), it's a `{ top: 0, left: 0, width, height }` of the viewport.

> Obviously, I'd expect boundingClientRect to be viewport based...

Yup.

File: src/intersection-observer.js (hunk 1 above)
Comment (sriramkrish85) [inline src/intersection-observer.js]: would it be easy to expose methods from fixedlayer to get the right intersection for position:fixed elements?

File: src/intersection-observer.js (hunk 3 above)
Comment (dvoytenko) [inline src/intersection-observer.js]: Got it.

File: src/intersection-observer.js (hunk 1 above)
Comment (dvoytenko) [inline src/intersection-observer.js]: Yes, `FixedLayer` can be used here. `Viewport` currently has `isDeclaredFixed` method that responds with "this element could be fixed". But I think we can dig a bit deeper and expose "this element is currently fixed" result.

Overall, is this fix critical? Would it wait for layers in any form?

Comment (jridgewell) [inline src/intersection-observer.js]: We [need](https://github.com/ampproject/amphtml/issues/5090) this PR now (I screwed up `IntersectionObserver` by not translating the coords). The fixed position stuff is [blocking](https://github.com/ampproject/amphtml/issues/3812) `<amp-fx-flying-carpet>`.

Comment (dvoytenko) [inline src/intersection-observer.js]: Do you mean that you will address `position:fixed` issue in a follow up? If so, please add `TODO(#issue)`.

**Comment by dvoytenko** [comment]
LGTM
