### PR TITLE
Fix flaky tests in test-custom-element.js

### LINKED ISSUE #19752: Fix two flaky tests in `test-custom-element.js`
This test became flaky on Chrome 71, disabled in PR #19750 

Tests are:
* 'should apply media condition'
* 'should apply sizes condition'

### PR DESCRIPTION
**Pull request by alabiaga**
Fixes #19752. Mock window.matchMedia as is not behaving consistently when the test is ran in headless mode. I think this is fine as we are not testing browser window functionality. Added a TODO to revisit this again but in the in the meantime unskip tests so that we test that media attribute values are applied.

### CODE REVIEW

File: test/functional/test-custom-element.js [hunk 1]
```diff
@@ -1012,88 +1011,110 @@ describes.realWin('CustomElement', {amp: true}, env => {
       }).to.throw(/Must never be called in template/); });
     });
 
+    // TODO(alabiaga): Fixes #19752. The window.matchMedia call in the code
+    // path of element.applySizesAndMediaQuery is not behaving consistently
+    // in headless mode, thus we mock the calls here. This is fine as we are
+    // not testing window behavior.
```
Comment (choumx) [inline test/functional/test-custom-element.js]: Why a TODO? Also we should move the explanation to where we stub `matchMedia`.

File: test/functional/test-custom-element.js [hunk 2]
```diff
@@ -1012,88 +1011,110 @@ describes.realWin('CustomElement', {amp: true}, env => {
...
-      element1.setAttribute('layout', 'responsive');
-      element1.setAttribute('width', '200px');
-      element1.setAttribute('height', '200px');
-      element1.setAttribute('heights', '(min-width: 1px) 99%, 1%');
-      container.appendChild(element1);
-      element1.applySizesAndMediaQuery();
-      expect(element1.sizerElement.style.paddingTop).to.equal('99%');
+        matchMedia =
+           sandbox.stub(element2.ownerDocument.defaultView, 'matchMedia');
+        matchMedia.withArgs('(min-width: 1111111px)').returns({matches: false});
```
Comment (choumx) [inline test/functional/test-custom-element.js]: Instead of restoring and stubbing again, use `withArgs()` to reuse the same stub but return different values for different args.

```js
    var callback = sinon.stub();
    callback.withArgs(42).returns(1);
    callback.withArgs(1).throws("name");
```

https://sinonjs.org/releases/latest/stubs/

File: test/functional/test-custom-element.js (hunk 1 above)
Comment (alabiaga) [reply test/functional/test-custom-element.js]: I wanted to follow up on why this why happening but a comment should suffice.

File: test/functional/test-custom-element.js (hunk 2 above)
Comment (alabiaga) [reply test/functional/test-custom-element.js]: done. Thanks!

**Comment by alabiaga** [comment]
@choumx Also, I too was confused as to where the height and width was coming from and found that it was just part of the spec. https://www.w3.org/TR/CSS2/visudet.html#inline-replaced-width

I also tried setting it explicitly but the result was the same flakiness.

**Comment by alabiaga** [comment]
thanks Will!!
