### PR TITLE
Use content height for "near bottom" resize logic

### LINKED ISSUE #14790: Resize fails when content height < viewport height
`amp-list` resize fails for the last element on the page when the page contents completely fit in the viewport (content height < scroll height).

Concerns case "6" in our resize algorithm:

https://github.com/ampproject/amphtml/blob/eb5666e96c313ef01625cd4a819e59a9009e4239/src/service/resources-impl.js#L1316-L1320

We should probably use `min(contentHeight, scrollHeight)` when calculating `docBottomOffset`:

https://github.com/ampproject/amphtml/blob/eb5666e96c313ef01625cd4a819e59a9009e4239/src/service/resources-impl.js#L1221-L1222

Repro page:
```
<!doctype html>
<html ⚡>
<head>
  <meta charset="utf-8">
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <script async custom-element="amp-list" src="https://cdn.ampproject.org/v0/amp-list-0.1.js"></script>
  <script async custom-template="amp-mustache" src="https://cdn.ampproject.org/v0/amp-mustache-0.1.js"></script>
  <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
</head>
<body>
  <div>There are 10 items in this list:<br><br></div>
  <amp-list layout="fixed-height" height="400" src="https://jsonplaceholder.typicode.com/users" items=".">
    <template type="amp-mustache">
      <b>{{name}}</b>
      <div><br>spacer<br><br></div>
    </template>
  </amp-list>
</body>
</html>
```

/cc @jridgewell @zhouyx @dvoytenko

### PR DESCRIPTION
**Pull request by choumx**
Fixes #14790.

- Use `getContentHeight()` instead of `getScrollHeight()` for calculating distance of an element from bottom of document
- Use closure to only compute `getContentHeight()` if necessary

/to @jridgewell @alabiaga

### CODE REVIEW

File: src/service/resources-impl.js [hunk 1]
```diff
@@ -1216,11 +1215,19 @@ export class Resources {
...
     const viewportRect = this.viewport_.getRect();
-    const scrollHeight = this.viewport_.getScrollHeight();
     const topOffset = viewportRect.height / 10;
     const bottomOffset = viewportRect.height / 10;
-    const maxDocBottomOffset = scrollHeight - DOC_BOTTOM_OFFSET_LIMIT_;
-    const docBottomOffset = Math.max(scrollHeight * 0.85, maxDocBottomOffset);
+    /**
+     * @param {!../layout-rect.LayoutRectDef} layoutBox
+     * @param {!../layout-rect.LayoutRectDef} initialLayoutBox
+     * @returns True if element is within 15% and 1000px of document bottom.
```
Comment (jridgewell) [inline src/service/resources-impl.js]: `@return {boolean}`

File: src/service/resources-impl.js [hunk 2]
```diff
@@ -1216,11 +1215,19 @@ export class Resources {
...
+     */
+    const elementNearBottom = (layoutBox, initialLayoutBox) => {
```
Comment (jridgewell) [inline src/service/resources-impl.js]: Pass in `viewport` and we can hoist this out of the method.

Comment (choumx) [reply src/service/resources-impl.js]: Kept `this.viewport_` reference and hoisted anyways.

File: src/service/resources-impl.js [hunk 3]
```diff
@@ -1335,8 +1331,7 @@ export class Resources {
             this.requestsChangeSize_.push(request);
           }
           continue;
-        } else if (iniBox.bottom >= docBottomOffset ||
-                      box.bottom >= docBottomOffset) {
+        } else if (this.elementNearBottom_(box, iniBox)) {
```
Comment (jridgewell) [inline src/service/resources-impl.js]: Nit: `iniBox` is only needed in this case. We could defer creating that struct until we call this method.

Comment (choumx) [reply src/service/resources-impl.js]: Good idea.
