### PR TITLE
🐛 Fix BeOp's style issue with flex

### LINKED ISSUE #24672: <amp-beopinion>does not work in <amp-story-page-attachment>
## What's the issue?
`<amp-beopinion>` does not work in `<amp-story-page-attachment> ` 

## How do we reproduce the issue?
```
<amp-story-page id="page1">
<amp-story-page-attachment layout="nodisplay">
                <h1>Vote Now</h1>
                <amp-beopinion width=375 height=472
                               layout="responsive"
                               data-account="5d85e66f46e0fb00019f4e68"
                               data-content="5d85e77f46e0fb00019f5837"
                               data-name="content-slot">
                </amp-beopinion>
            </amp-story-page-attachment>
        </amp-story-page>

```
Upload this code in a story

## Solution
@BeOpinion Needs to change the style of the iframe to `display:block` from `display:flex`

**Working in this image 1**
image

**Not working in the existing setting**
image

### PR DESCRIPTION
**Pull request by bloodyowl**
Closes #24672

### CODE REVIEW

**Comment by bloodyowl** [comment]
@googlebot I signed it!

**Comment by gmajoulet** [comment]
cc @ampproject/wg-ui-and-a11y

**Comment by sparhami** [comment]
This change looks fine to me, but I'm not sure why it was display flex to begin with, and what situations it made a difference. It is also unclear what the layout issue was.

It looks like the beopinion code now sets the display to `block` it a setTimeout loop continuously. which is definitely not good. This seems to be the workaround referenced in the issue.

Stuff seems to be centered, though that may be due to additional code changes on their side to replace the original flex on the container element.

File: 3p/beopinion.js [hunk 1]
```diff
@@ -74,9 +74,7 @@ function createContainer(global, data) {
 
   setStyles(container, {
     width: '100%',
```
Comment (sparhami) [inline 3p/beopinion.js]: Can remove the `width: '100%'`, it is redundant with `display: block`.

Comment (bloodyowl) [reply 3p/beopinion.js]: it might be better to keep it in cases it's contained in a flex element. the iframe we inject inside uses a `width: 1px; min-width: 100%` trick due to a iOS bug. 

Screenshot 2019-09-26 at 11 39 50
Screenshot 2019-09-26 at 11 40 01
