### PR TITLE
🐛 amp-ima-video: Fix duration label on livestreams

### LINKED ISSUE #34831: `amp-ima-video` shows `Infinity:NaN` as duration for livestreams
### Description

When `amp-ima-video` is used with a livestream the control bar shows `Infinity:NaN` for the duration.

amp-ima-video-bug

### Reproduction Steps

The issue can be seen on this [demo page (https://playground.amp.dev)](https://playground.amp.dev/?format=websites&mode=iPhone+X%2FXs#share=PCEtLQogICMjIEludHJvZHVjdGlvbgoKICBbYGFtcC1pbWEtdmlkZW9gXShodHRwczovL2dpdGh1Yi5jb20vYW1wcHJvamVjdC9hbXBodG1sL2Jsb2IvbWFpbi9leHRlbnNpb25zL2FtcC1pbWEtdmlkZW8vYW1wLWltYS12aWRlby5tZCkgZW1iZWRzIGEgdmlkZW8gcGxheWVyIGZvciBpbnN0cmVhbSB2aWRlbyBhZHMgdGhhdCBhcmUgaW50ZWdyYXRlZCB3aXRoIHRoZSBbSU1BIFNES10oaHR0cHM6Ly9kZXZlbG9wZXJzLmdvb2dsZS5jb20vaW50ZXJhY3RpdmUtbWVkaWEtYWRzL2RvY3Mvc2Rrcy9odG1sNS8pLgoKICBUaGUgcGx1Z2luIHByb3ZpZGVzIGEgdmlkZW8gcGxheWVyIHdpdGggY29udHJvbHMgZm9yIHlvdXIgY29udGVudCwgYW5kIHJlcXVlc3RzIGFuZCBkaXNwbGF5cyBhZHMgZnJvbSBhIFZBU1QtY29tcGxpYW50IGFkIHNlcnZlciBvZiB5b3VyIGNob2ljZSB1c2luZyB0aGUgSU1BIFNESy4KLS0+CjwhLS0gLS0+CjwhRE9DVFlQRSBodG1sPgo8aHRtbCDimqEgbGFuZz0iZW4iPgogIDxoZWFkPgogICAgPG1ldGEgY2hhcnNldD0idXRmLTgiIC8+CiAgICA8dGl0bGU+YW1wLWltYS12aWRlbzwvdGl0bGU+CiAgICA8bGluawogICAgICByZWw9ImNhbm9uaWNhbCIKICAgICAgaHJlZj0iaHR0cHM6Ly9hbXAuZGV2L2RvY3VtZW50YXRpb24vZXhhbXBsZXMvY29tcG9uZW50cy9hbXAtaW1hLXZpZGVvL2luZGV4Lmh0bWwiCiAgICAvPgogICAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCIgLz4KICAgIDxzY3JpcHQgYXN5bmMgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC5qcyI+PC9zY3JpcHQ+CiAgICA8IS0tICMjIFNldHVwIC0tPgogICAgPCEtLSBJbXBvcnQgdGhlIGFtcC1pbWEtdmlkZW8gY29tcG9uZW50LiAgLS0+CiAgICA8c2NyaXB0CiAgICAgIGFzeW5jCiAgICAgIGN1c3RvbS1lbGVtZW50PSJhbXAtaW1hLXZpZGVvIgogICAgICBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwL2FtcC1pbWEtdmlkZW8tMC4xLmpzIgogICAgPjwvc2NyaXB0PgogICAgPHN0eWxlIGFtcC1ib2lsZXJwbGF0ZT4KICAgICAgYm9keSB7CiAgICAgICAgLXdlYmtpdC1hbmltYXRpb246IC1hbXAtc3RhcnQgOHMgc3RlcHMoMSwgZW5kKSAwcyAxIG5vcm1hbCBib3RoOwogICAgICAgIC1tb3otYW5pbWF0aW9uOiAtYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsIGVuZCkgMHMgMSBub3JtYWwgYm90aDsKICAgICAgICAtbXMtYW5pbWF0aW9uOiAtYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsIGVuZCkgMHMgMSBub3JtYWwgYm90aDsKICAgICAgICBhbmltYXRpb246IC1hbXAtc3RhcnQgOHMgc3RlcHMoMSwgZW5kKSAwcyAxIG5vcm1hbCBib3RoOwogICAgICB9CgogICAgICBALXdlYmtpdC1rZXlmcmFtZXMgLWFtcC1zdGFydCB7CiAgICAgICAgZnJvbSB7CiAgICAgICAgICB2aXNpYmlsaXR5OiBoaWRkZW47CiAgICAgICAgfQoKICAgICAgICB0byB7CiAgICAgICAgICB2aXNpYmlsaXR5OiB2aXNpYmxlOwogICAgICAgIH0KICAgICAgfQogICAgICBALW1vei1rZXlmcmFtZXMgLWFtcC1zdGFydCB7CiAgICAgICAgZnJvbSB7CiAgICAgICAgICB2aXNpYmlsaXR5OiBoaWRkZW47CiAgICAgICAgfQoKICAgICAgICB0byB7CiAgICAgICAgICB2aXNpYmlsaXR5OiB2aXNpYmxlOwogICAgICAgIH0KICAgICAgfQogICAgICBALW1zLWtleWZyYW1lcyAtYW1wLXN0YXJ0IHsKICAgICAgICBmcm9tIHsKICAgICAgICAgIHZpc2liaWxpdHk6IGhpZGRlbjsKICAgICAgICB9CgogICAgICAgIHRvIHsKICAgICAgICAgIHZpc2liaWxpdHk6IHZpc2libGU7CiAgICAgICAgfQogICAgICB9CiAgICAgIEAtby1rZXlmcmFtZXMgLWFtcC1zdGFydCB7CiAgICAgICAgZnJvbSB7CiAgICAgICAgICB2aXNpYmlsaXR5OiBoaWRkZW47CiAgICAgICAgfQoKICAgICAgICB0byB7CiAgICAgICAgICB2aXNpYmlsaXR5OiB2aXNpYmxlOwogICAgICAgIH0KICAgICAgfQogICAgICBAa2V5ZnJhbWVzIC1hbXAtc3RhcnQgewogICAgICAgIGZyb20gewogICAgICAgICAgdmlzaWJpbGl0eTogaGlkZGVuOwogICAgICAgIH0KCiAgICAgICAgdG8gewogICAgICAgICAgdmlzaWJpbGl0eTogdmlzaWJsZTsKICAgICAgICB9CiAgICAgIH0KICAgIDwvc3R5bGU+CiAgICA8bm9zY3JpcHQKICAgICAgPjxzdHlsZSBhbXAtYm9pbGVycGxhdGU+CiAgICAgICAgYm9keSB7CiAgICAgICAgICAtd2Via2l0LWFuaW1hdGlvbjogbm9uZTsKICAgICAgICAgIC1tb3otYW5pbWF0aW9uOiBub25lOwogICAgICAgICAgLW1zLWFuaW1hdGlvbjogbm9uZTsKICAgICAgICAgIGFuaW1hdGlvbjogbm9uZTsKICAgICAgICB9CiAgICAgIDwvc3R5bGU+CiAgICA8L25vc2NyaXB0PgogIDwvaGVhZD4KICA8Ym9keT4KICAgIDxhbXAtaW1hLXZpZGVvCiAgICAgIGlkPSJ0ZXN0LXZpZGVvIgogICAgICB3aWR0aD0iMTYiCiAgICAgIGhlaWdodD0iOSIKICAgICAgbGF5b3V0PSJyZXNwb25zaXZlIgogICAgICBkYXRhLXRhZz0iaHR0cHM6Ly93d3cuZ29vZ2xlLmNvbSIKICAgID4KICAgICAgPHNvdXJjZQogICAgICAgIHNyYz0iaHR0cHM6Ly9jcGgtcDJwLW1zbC5ha2FtYWl6ZWQubmV0L2hscy9saXZlLzIwMDAzNDEvdGVzdC9tYXN0ZXIubTN1OCIKICAgICAgICB0eXBlPSJhcHBsaWNhdGlvbi94LW1wZWdVUkwiCiAgICAgIC8+CiAgICA8L2FtcC1pbWEtdmlkZW8+CiAgPC9ib2R5Pgo8L2h0bWw+Cg==)

### Relevant Logs

_No response_

### Browser(s) Affected

Safari

### OS(s) Affected

iOS

### Device(s) Affected

iPhone 11

### AMP Version Affected

_No response_

### PR DESCRIPTION
**Pull request by alanorozco**
Fixes #34831

In addition, hides progress slider on livestreams since it's not usable.

### CODE REVIEW

File: ads/google/ima/ima-video.js [hunk 1]
```diff
@@ -949,14 +946,35 @@ function playerDataTick() {
...
+
+  // https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/duration
+  const isLivestream = duration === Infinity;
+
+  // Progress bar should not be displayed on livestreams.
+  // TODO(alanorozco): This is likely handled by native controls, so we wouldn't
+  // need this clause if we switch. https://go.amp.dev/issue/8841
+  if (progress.hasAttribute('hidden') !== isLivestream) {
+    toggle(progress, !isLivestream);
+    progress.setAttribute('aria-hidden', isLivestream ? 'true' : 'false');
```
Comment (caroqliu) [inline ads/google/ima/ima-video.js:963]:
```suggestion
    progress.setAttribute('aria-hidden', String(isLivestream));
```

**Review by caroqliu — APPROVED** [review]

**Review by micajuine-ho — APPROVED** [review]
Thanks for this change Alan!
