### PR TITLE
Partially fix existing lint errors in `build-system/`

### LINKED ISSUE #11273: Add lint rules for `build-system/`
I just took the existing linter that we use for the AMP runtime and ran it against `build-system/` (minus `build-system/node-modules/`), and encountered numerous errors.

https://gist.github.com/rsimha-amp/c9e5e1caa4829bd65ea94c373068993a

Several errors are due to the fact that we use ES5 style for the build system while the lint rules are for ES6. However, there are a significant number of genuine errors that should gradually be found and fixed.

### PR DESCRIPTION
**Pull request by rsimha-amp**
This PR contains all possible automatic lint fixes for `build-system` by running:

```
gulp lint --build_system --fix
```

There are still a bunch of errors that must be dealt with via manual fixes, or eslint rule changes.

Partial fix for #11273

### CODE REVIEW

**Comment by rsimha-amp** [comment]
/to @erwinmombay @choumx 

This PR reduces the number of lint errors in `build-system` from ~800 to ~400. The ones that remain are in https://travis-ci.org/ampproject/amphtml/jobs/277423411, and we must decide which of them we forgive via rule overrides in `build-system/.eslintrc`, and which ones we must manually fix.

File: build-system/tasks/changelog.js [hunk 1]
```diff
@@ -437,11 +437,11 @@ function getClosedPullRequests(opt_page) {
   options.qs = {
     state: 'closed',
     page: opt_page,
-    access_token: GITHUB_ACCESS_TOKEN,
```
Comment (cramforce) [inline build-system/tasks/changelog.js]: Could we change the policy to align with our non-build code?

Comment (rsimha-amp) [reply build-system/tasks/changelog.js]: We currently use the rules in `eslint-config-es5` because the build system code is written in ES5 JS, while the runtime is in ES 6. That's where the non-conforming comma rules are coming from.

I'm working on a parallel thread on upgrading to using node 6 on Travis, at which point we can safely use ES6 code in `build-system`, and then use the same linter as the rest of the runtime. Will update this PR once I have that part figured out.

**Comment by cramforce** [comment]
You should be able to opt into trailing comma. Totally valid ES5.

**Comment by rsimha-amp** [comment]
Right, what I meant to say was that with the impending move to node 6 on Travis, we no longer need to restrict build system code to ES5, and therefore, no longer need separate sets of lint rules.

For context on why we're doing so, see the discussion starting at https://github.com/ampproject/amphtml/issues/11278#issuecomment-330571821

File: build-system/tasks/changelog.js (hunk 1 above)
Comment (rsimha-amp) [reply build-system/tasks/changelog.js]: We now use the same ES6 rules as the rest of the AMP runtime, and trailing commas are back. PTAL.

**Comment by rsimha-amp** [comment]
The latest commit in this PR uses ES6 rules, and after an automatic `--fix` run, we are down to fewer than 100 remaining lint errors in `build-system` that need to be manually fixed.

@cramforce PTAL.

File: .eslintrc [hunk 2]
```diff
@@ -33,7 +33,10 @@
     "sandbox": true,
     "context": false,
     "global": false,
-    "describes": true
+    "describes": true,
+    "require": false,
```
Comment (jridgewell) [inline .eslintrc]: Please move these into a sub folder's `.eslintrc`. They're dangerous in the `src` folder.

Comment (rsimha-amp) [reply .eslintrc]: Good point. I was about to ask. Done.
