### PR TITLE
Wait for viewer visible before sending cid request

### LINKED ISSUE #11888: Error: Request cid failed: document is not visible
https://pantheon.corp.google.com/errors/13023421735792682607?service=default-cdn-1p-canary&time=P1D&filter&project=amp-error-reporting

```
Error: Request cid failed: document is not visible
at Error (https://raw.githubusercontent.com/ampproject/amphtml/1507083985898/extensions/amp-viewer-integration/0.1/messaging/messaging.js:310)
at (https://raw.githubusercontent.com/ampproject/amphtml/1507083985898/extensions/amp-viewer-integration/0.1/messaging/messaging.js:90)
```

This appears to have 1M+ error volume.

Feel free to lower priority if found non-critical.

(All related PRs: #11631 #11969 #12035)

### PR DESCRIPTION
**Pull request by zhouyx**
Attempt to fix #11888 and #11628 

This is my best guess...

### CODE REVIEW

File: src/service/cid-impl.js [hunk 1]
```diff
@@ -405,19 +406,20 @@ export function viewerBaseCid(ampdoc, opt_data) {
...
-          if (data && !tryParseJson(data)) {
-            // TODO(dvoytenko, #9019): use this for reporting: dev().error('cid', 'invalid cid format');
-            return JSON.stringify(dict({
-              'time': Date.now(), // CID returned from old API is always fresh
-              'cid': data,
-            }));
-          }
-          return data;
-        });
+    return viewer.whenNextVisible().then(() => {
```
Comment (dvoytenko) [inline src/service/cid-impl.js]: II recommend to unnest.

Comment (zhouyx) [reply src/service/cid-impl.js]: unnested, if this is what you mean : )

File: test/functional/test-cid.js [hunk 2]
```diff
@@ -736,17 +736,29 @@ describes.realWin('cid', {amp: true}, env => {
...
     stubServiceForDoc(sandbox, ampdoc, 'viewer', 'hasCapability')
         .withArgs('cid').returns(true);
     sandbox.stub(url, 'isProxyOrigin').returns(true);
-    return expect(cid.get({scope: 'foo'}, hasConsent))
-        .to.eventually.equal('cid-from-viewer');
+    let viewerVisibleResolver;
+    const viewerNextVisiblePromise = new Promise(resolve => {
+      viewerVisibleResolver = resolve;
+    });
+    stubServiceForDoc(sandbox, ampdoc, 'viewer', 'whenNextVisible')
```
Comment (zhouyx) [inline test/functional/test-cid.js]: modified the old test to include coverage for viewer visible instead.
