### PR TITLE
 ✨Autofocus on `show()`

### LINKED ISSUE #19949: input.focus is not working on iOS on a default `hidden` element
Good Day there, I have created a [demo](https://aemsite.github.io/ampdemo/amp-ios-input.html) , please play around with iOS device, by clicking on the button, it will do the following 2 actions

1. show the element which wraps the `input`
2. set `focus` on the `input`

As you can see, on the first click attempt on the button, the focus is not working as expected while it will only work on the second attempt.

### PR DESCRIPTION
**Pull request by alanorozco**
## Breakdown

- Autofocuses element annotated as `[autofocus]` inside the displayed tree via `show`/`toggle`.
- Forces synchronous display-focus chain on iOS so that programmatic focus is actually honored.

## Usage

```html
  <button on="tap: wrapper.show">
    Show
  </button>
  <div id="wrapper" hidden>
    <input type="text" autofocus>
  </div>
```

## etc.

Demo: <https://amp-autofocus.glitch.me/>

Closes #19949.

### CODE REVIEW

File: src/service/standard-actions-impl.js [hunk 1]
```diff
@@ -311,17 +323,36 @@ export class StandardActions {
...
-      if (target.classList.contains('i-amphtml-element')) {
-        target./*OK*/expand();
-      } else {
-        toggle(target, true);
-      }
-    });
+    const autofocusElOrNull = getAutofocusElementForShowAction(target);
+
+    // Safari only honors focus in sync operations.
+    if (autofocusElOrNull && Services.platformFor(ownerWindow).isSafari()) {
```
Comment (aghassemi) [inline src/service/standard-actions-impl.js]: Check for iOS instead, it is an iOS thing (I don't think isSafari catches Chrome on iOS for example)

Comment (alanorozco) [reply src/service/standard-actions-impl.js]: Gotcha, fixed. PTAL.
