### PR TITLE
🐛🏗 Split gitBranchPoint to two function

### LINKED ISSUE #19604: Extra files being included in the Travis pr-check.js
As stated in the team chat, some PRs are failing in travis due to incorrect files being added to their `pr-check.js`.

For example, see the following PRs and their Travis failures:

#19556 (Best Example)
#19334

### PR DESCRIPTION
**Pull request by danielrozenberg**
This PR splits the `gitBranchPoint` to two functions - one to be used by processes expecting the pre-#19558 behaviour, and one for those expecting the post-#19558 behaviour

Fixed #19604

### CODE REVIEW

**Comment by danielrozenberg** [comment]
#famouslastwords

File: build-system/git.js [hunk 1]
```diff
@@ -25,11 +25,20 @@ const {getStdout} = require('./exec');
  * Returns the branch point of the current branch off of master.
  * @return {string}
  */
-exports.gitBranchPoint = function() {
+exports.gitBranchPointFromMaster = function() {
+  return getStdout('git merge-base master HEAD^').trim();
```
Comment (rsimha) [inline build-system/git.js]: There's a nasty bug here. The branch point must be calculated based on `HEAD`, not `HEAD^`, or else the local changes logic breaks, and changes from other commits are included in the list of files changed on a given branch. I'm trying to dig into why this was changed to `HEAD^`.

Comment (rsimha) [reply build-system/git.js]: Found the culprit: #18940.

Comment (danielrozenberg) [reply build-system/git.js]: Hmm... I can revert that PR, but I wonder if that's just gonna break a new thing. Git is confusing. Let's talk about this offline?

Comment (rsimha) [reply build-system/git.js]: Fixed with #19933.
