### PR TITLE
Automatic Comments 

### LINKED ISSUE #11383: `gulp process-github-issues --dryrun` is broken
This is a leftover item from https://github.com/ampproject/amphtml/pull/11126#issuecomment-329250566

1. We should return `promise` and not `issues` in line 202 of `build-system/tasks/process-github-issues.js`.
2. The `util.log(util.inspect())` in line 195 doesn't actually print out the particulars of the change. A possible solution is to print the particulars of the request inside `createGithubRequest` if `isDryrun === true`.

```
~/src/amphtml$ gulp process-github-issues --dryrun
[19:17:13] Using gulpfile ~/src/amphtml/gulpfile.js
[19:17:13] Starting 'process-github-issues'...
[19:17:14] automation applied
[19:17:14] Finished 'process-github-issues' after 1.22 s
[19:17:14] Update 11382
[19:17:14] Performing a dry run. These are the updates that would have been applied:
(node:103148) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: util.inspect is not a function
```

### PR DESCRIPTION
**Pull request by adelinamart**
Adding automatic comments to issues for missing updates or category as per design at go/ampgithubautomation
Already run the linter.
Some tuning also for the code. 
Fixes #11383

### CODE REVIEW

File: build-system/tasks/process-github-issues.js [hunk 1]
```diff
@@ -108,6 +108,11 @@ function updateGitHubIssues() {
     getIssues(3),
```
Comment (rsimha-amp) [inline build-system/tasks/process-github-issues.js]: I think you can get as many issues as you want in one go by changing `per_page`. See https://developer.github.com/v3/guides/traversing-with-pagination/#changing-the-number-of-items-received

If that doesn't work, create a `const` called `NUM_PAGES` at the top of this file, and use it here instead of hard-coding each page fetch .

File: build-system/tasks/process-github-issues.js [hunk 2]
```diff
@@ -119,67 +124,118 @@ function updateGitHubIssues() {
...
+          let biweeklyUpdate = true;
+          let quartelyUpdate = true;
+          if (getLastUpdate(issueLastUpdate) > 89) {
+            quartelyUpdate = false;
+            biweeklyUpdate = false;
+          }
+          else if (getLastUpdate(issueLastUpdate) > 14) {
+            biweeklyUpdate = false;
+          }
+      // Get the assignee
```
Comment (rsimha-amp) [inline build-system/tasks/process-github-issues.js]: All the comments in this file are badly indented. This is because the linter has no way of knowing if they belong to the block before it or the block after it, and therefore, cannot fix them. You're going to have to manually fix them.

File: build-system/tasks/process-github-issues.js [hunk 3]
```diff
@@ -119,67 +124,118 @@ function updateGitHubIssues() {
...
+          const assignee = issue['assignee'];
+          let assigneeName = '';
+          const issueLastUpdate = issue.updated_at;
+          let biweeklyUpdate = true;
+          let quartelyUpdate = true;
+          if (getLastUpdate(issueLastUpdate) > 89) {
+            quartelyUpdate = false;
+            biweeklyUpdate = false;
+          }
+          else if (getLastUpdate(issueLastUpdate) > 14) {
```
Comment (rsimha-amp) [inline build-system/tasks/process-github-issues.js]: Move `else if` to the end of the line above.

File: build-system/tasks/process-github-issues.js [hunk 4]
```diff
@@ -119,67 +124,118 @@ function updateGitHubIssues() {
...
+          let hasCategory = false;
           let issueNewMilestone = MILESTONE_PENDING_TRIAGE;
-
-          // Get the title and state of the milestone
+          const assignee = issue['assignee'];
+          let assigneeName = '';
+          const issueLastUpdate = issue.updated_at;
+          let biweeklyUpdate = true;
+          let quartelyUpdate = true;
+          if (getLastUpdate(issueLastUpdate) > 89) {
```
Comment (rsimha-amp) [inline build-system/tasks/process-github-issues.js]: Use `const`s at the top of this file instead of hard-coding numbers like `89`.

File: build-system/tasks/process-github-issues.js (hunk 3 above)
Comment (rsimha-amp) [inline build-system/tasks/process-github-issues.js]: Same comment as above. Use `const`s at the top of this file instead of hardcoding numbers like `14`.

File: build-system/tasks/process-github-issues.js [hunk 5]
```diff
@@ -119,67 +124,118 @@ function updateGitHubIssues() {
...
+            labels.forEach(function(label) {
+              if (label) {
+            // Check if the issues has type
+                if (label.name.startsWith('Type') ||
+               label.name.startsWith('Related')) {
+                  issueType = label.name;
+                }
+            // Check if the issues has Priority
+                if (label.name.startsWith('P0') || label.name.startsWith('P1')
+               || label.name.startsWith('P2') || label.name.startsWith('P3')) {
```
Comment (rsimha-amp) [inline build-system/tasks/process-github-issues.js]: The indentation here is all messed up. Restore the one-per-line as it was before.

File: build-system/tasks/process-github-issues.js [hunk 6]
```diff
@@ -119,67 +124,118 @@ function updateGitHubIssues() {
...
+            assigneeName = '@' + assignee['login'];
+          }
+      // Get the title and state of the milestone
           if (milestone) {
-            milestoneTitle = milestone.title;
-            milestoneState = milestone.state;
+            milestoneTitle = milestone['title'];
+            milestoneState = milestone['state'];
           }
-          // Get the labels we want to check
```
Comment (rsimha-amp) [inline build-system/tasks/process-github-issues.js]: Why was the formatting in this block changed? Did you sync to master before editing this file? Please undo all the unnecessary changes in this file.

File: build-system/tasks/process-github-issues.js (hunk 1 above)
Comment (adelinamart) [reply build-system/tasks/process-github-issues.js]: it's number of pages actually, its batches. I need to request them selectively as specified and cannot make it a constant, but added a comment. let me know if it makes sense.

File: build-system/tasks/process-github-issues.js (hunk 3 above)
Comment (adelinamart) [reply build-system/tasks/process-github-issues.js]: done

Comment (adelinamart) [reply build-system/tasks/process-github-issues.js]: done

File: build-system/tasks/process-github-issues.js (hunk 2 above)
Comment (adelinamart) [reply build-system/tasks/process-github-issues.js]: done

File: build-system/tasks/process-github-issues.js (hunk 6 above)
Comment (adelinamart) [reply build-system/tasks/process-github-issues.js]: done

File: build-system/tasks/process-github-issues.js (hunk 5 above)
Comment (adelinamart) [reply build-system/tasks/process-github-issues.js]: done

**Comment by adelinamart** [comment]
@rsimha-amp so it seems I had some issues with syncing the files, but I think it should be good now. Please let me know what you think. Thank you

File: build-system/tasks/process-github-issues.js (hunk 1 above)
Comment (rsimha-amp) [reply build-system/tasks/process-github-issues.js]: What I meant was that you should be able specify how many issues are downloaded in a batch via `per_page`. So instead of fetching `X` issues `Y` times, you'd simply do a single fetch for `X * Y` items by changing the batch size. See the link above.

If that's not possible, or if the upper limit of the batch size doesn't meet your requirements, we should generate all the `getIssues` promises below from inside a single loop, by first constructing an array where you push `getissues(i)` a total of 10 times to the array, with `i` == 1 through `NUM_PAGES`, where `NUM_PAGES` is a constant equal to `10`. That's better than hard-coding ten consecutive promises.

File: build-system/tasks/process-github-issues.js [hunk 7]
```diff
@@ -119,44 +135,91 @@ function updateGitHubIssues() {
...
-          });
+          // promise starts
           promise = promise.then(function() {
             util.log('Update ' + issue.number);
             const updates = [];
-            // Milestone task: move issue from closed milestone
+            // Get the labels we want to check
+            labels.forEach(function(label) {
+              if (label) {
+              // Check if the issues has type
```
Comment (rsimha-amp) [inline build-system/tasks/process-github-issues.js]: nit: Fix indentation.

File: build-system/tasks/process-github-issues.js [hunk 8]
```diff
@@ -14,6 +14,7 @@
  * limitations under the License.
  */
 'use strict';
+/* eslint google-camelcase/google-camelcase: 0 */
```
Comment (rsimha-amp) [inline build-system/tasks/process-github-issues.js]: Remove this.

File: build-system/tasks/process-github-issues.js [hunk 9]
```diff
@@ -55,8 +55,18 @@ const MILESTONE_BACKLOG_BUGS = 4;
...
 // 23 is the number for Milestone 'New FRs'
 const MILESTONE_NEW_FRS = 23;
+// 22 is the number for Milestone 'Prioritized FRs'
+const MILESTONE_PRIORITIZED_FRS = 22;
 // 12 is the number for Milestone 'Docs Updates'
 const MILESTONE_DOCS_UPDATES = 12;
+// 25 is the number for Milestone 'Great First Issues (GFI)'
+const MILESTONE_GREAT_ISSUES = 25;
+// 11 is the number for Milestone '3P Implementation'
+const MILESTONE_3P_IMPLEMENTATION = 11;
```
Comment (rsimha-amp) [inline build-system/tasks/process-github-issues.js]: For maintainability, maybe sort these milestone numbers in increasing order?

File: build-system/tasks/process-github-issues.js [hunk 10]
```diff
@@ -119,44 +135,91 @@ function updateGitHubIssues() {
...
+                  issueType = label.name;
+                }
+                // Check if the issues has Priority
+                if (label.name.startsWith('P0') ||
+                    label.name.startsWith('P1') ||
+                    label.name.startsWith('P2') ||
+                    label.name.startsWith('P3')) {
+                  hasPriority = true;
+                  if (label.name.startsWith('P0')
+                      || label.name.startsWith('P1')) {
```
Comment (rsimha-amp) [inline build-system/tasks/process-github-issues.js]: nit: For consistency, move `||` to previous line, similar to the above `if` block.

File: build-system/tasks/process-github-issues.js [hunk 11]
```diff
@@ -119,44 +135,91 @@ function updateGitHubIssues() {
...
+                  } else if (label.name.startsWith('P2') &&
+                      quartelyUpdate == false) {
+                    quartelyUpdate = true;
+                    updates.push(applyComment(issue, 'This issue hasn\'t been '
+                        + ' updated in awhile.' +
+                    assigneeName + ' Do you have any updates?'));
+                  }
+                }
+                if (label.name.startsWith('Category')
+                    || label.name.startsWith('Related to')
```
Comment (rsimha-amp) [inline build-system/tasks/process-github-issues.js]: nit:  Same comment. Move `||` to previous lines.

File: build-system/tasks/process-github-issues.js [hunk 12]
```diff
@@ -119,44 +135,91 @@ function updateGitHubIssues() {
...
+            if (issueNewMilestone === MILESTONE_PENDING_TRIAGE) {
+              if (quartelyUpdate == false) {
+                quartelyUpdate = true;
+                updates.push(applyComment(issue, 'This issue seems to be in ' +
+                    ' Pending Triage for awhile.' +
+                    assigneeName + ' Please triage this to ' +
+                    'an appropriate milestone.'));
+              }
+            }
+            //if issueType is not null, add correct milestones
```
Comment (rsimha-amp) [inline build-system/tasks/process-github-issues.js]: nit: space after `//`

File: build-system/tasks/process-github-issues.js [hunk 13]
```diff
@@ -175,31 +238,42 @@ function updateGitHubIssues() {
...
-              util.log('Performing a dry run. ' +
-                  'These are the updates that would have been applied:');
-              updates.forEach(function(update) {
-                util.log(util.inspect(update, {depth: null}));
-              });
-              return Promise.resolve();
+            // Add comment with missing Category
+            if (hasCategory == false) {
+              if (issueNewMilestone === MILESTONE_PENDING_TRIAGE
+                  || issueNewMilestone === MILESTONE_DOCS_UPDATES
```
Comment (rsimha-amp) [inline build-system/tasks/process-github-issues.js]: Same comment re: `||`.

File: build-system/tasks/process-github-issues.js [hunk 14]
```diff
@@ -235,21 +307,59 @@ function applyMilestone(issue, milestoneNumber) {
...
+ */
+function applyComment(issue, comment) {
+  const options = extend({}, issuesOptions);
+  options.qs = {
+    'state': 'open',
+    'per_page': 100,
+    'access_token': GITHUB_ACCESS_TOKEN,
+  };
+  // delay the comment request so we don't reach github rate limits requests
+  const promise = new Promise(resolve => setTimeout(resolve,120000));
```
Comment (rsimha-amp) [inline build-system/tasks/process-github-issues.js]: nit: space after `,`.

File: build-system/tasks/process-github-issues.js [hunk 15]
```diff
@@ -235,21 +307,59 @@ function applyMilestone(issue, milestoneNumber) {
...
+ * @return {!Promise<*>}
+ */
+function applyComment(issue, comment) {
+  const options = extend({}, issuesOptions);
+  options.qs = {
+    'state': 'open',
+    'per_page': 100,
+    'access_token': GITHUB_ACCESS_TOKEN,
+  };
+  // delay the comment request so we don't reach github rate limits requests
```
Comment (rsimha-amp) [inline build-system/tasks/process-github-issues.js]: Does this mean that your gulp task will lie idle for 2 minutes? Perhaps print a message indicating the reason for the idle time?

File: build-system/tasks/process-github-issues.js [hunk 16]
```diff
@@ -235,21 +307,59 @@ function applyMilestone(issue, milestoneNumber) {
...
+  const promise = new Promise(resolve => setTimeout(resolve,120000));
+  return promise.then(function() {
+    if (isDryrun) {
```
Comment (rsimha-amp) [inline build-system/tasks/process-github-issues.js]: Yay! Thanks for making this fix! Does `gulp process-github-issues --dryrun` work now?

File: build-system/tasks/process-github-issues.js [hunk 17]
```diff
@@ -119,44 +127,91 @@ function updateGitHubIssues() {
           let milestoneTitle;
           let milestoneState;
           let hasPriority = false;
+          let hasCategory = false;
           let issueNewMilestone = MILESTONE_PENDING_TRIAGE;
-
+          const assignee = issue['assignee'];
```
Comment (rsimha-amp) [inline build-system/tasks/process-github-issues.js]: `issue.issignee`, not `issue['assignee']`

File: build-system/tasks/process-github-issues.js [hunk 18]
```diff
@@ -119,44 +127,91 @@ function updateGitHubIssues() {
...
+            biweeklyUpdate = false;
+          }
+          // Get the assignee
+          if (assignee) {
+            assigneeName = '@' + assignee['login'];
+          }
           // Get the title and state of the milestone
           if (milestone) {
-            milestoneTitle = milestone.title;
-            milestoneState = milestone.state;
```
Comment (rsimha-amp) [inline build-system/tasks/process-github-issues.js]: Why were these two lines changed? Revert.

File: build-system/tasks/process-github-issues.js [hunk 19]
```diff
@@ -119,44 +127,91 @@ function updateGitHubIssues() {
...
+            milestoneTitle = milestone['title'];
+            milestoneState = milestone['state'];
+            issueNewMilestone = milestone['number'];
```
Comment (rsimha-amp) [inline build-system/tasks/process-github-issues.js]: Use dot access here and elsewhere in the file.

File: build-system/tasks/process-github-issues.js [hunk 20]
```diff
@@ -119,44 +127,91 @@ function updateGitHubIssues() {
...
           promise = promise.then(function() {
             util.log('Update ' + issue.number);
             const updates = [];
-            // Milestone task: move issue from closed milestone
+            // Get the labels we want to check
+            labels.forEach(function(label) {
+              if (label) {
+                // Check if the issues has type
+                if (label.name.startsWith('Type') ||
+               label.name.startsWith('Related')) {
```
Comment (rsimha-amp) [inline build-system/tasks/process-github-issues.js]: Fix indentation.

File: build-system/tasks/process-github-issues.js [hunk 21]
```diff
@@ -119,44 +127,91 @@ function updateGitHubIssues() {
...
+                    label.name.startsWith('P2') ||
+                    label.name.startsWith('P3')) {
+                  hasPriority = true;
+                  if (label.name.startsWith('P0') ||
+                      label.name.startsWith('P1')) {
+                    if (biweeklyUpdate == false) {
+                      biweeklyUpdate = true;
+                      updates.push(applyComment(issue, 'This is a high priority'
+                      + ' issue but it hasn\'t been updated in awhile.' +
+                      assigneeName + ' Do you have any updates?'));
```
Comment (rsimha-amp) [inline build-system/tasks/process-github-issues.js]: Fix indentation of 2 lines above. Continuation += 4 spaces.

File: build-system/tasks/process-github-issues.js (hunk 15 above)
Comment (rsimha-amp) [reply build-system/tasks/process-github-issues.js]: This wasn't addressed.

File: build-system/tasks/process-github-issues.js [hunk 22]
```diff
@@ -278,7 +381,9 @@ function createGithubRequest(path, opt_method, opt_data, typeRequest) {
   if (opt_data) {
     options.json = true;
     if (typeRequest === 'milestone') {
-      options.body.milestone = opt_data;
```
Comment (rsimha-amp) [inline build-system/tasks/process-github-issues.js]: Why was this changed?

File: build-system/tasks/process-github-issues.js [hunk 23]
```diff
@@ -102,13 +111,12 @@ function getIssues(opt_page) {
...
-  return BBPromise.all([
-    getIssues(1),
-    getIssues(2),
-    getIssues(3),
-    getIssues(4),
-    getIssues(5),
-  ])
+  const arrayPromises = [];
+  // we need to pull issues in batches
+  for (let batch = 1; batch < 11; batch++) {
```
Comment (rsimha-amp) [inline build-system/tasks/process-github-issues.js]: You're still hard coding the number of batches. Move it to a const `NUM_BATCHES` at the top of the file.

File: build-system/tasks/process-github-issues.js [hunk 24]
```diff
@@ -279,6 +382,8 @@ function createGithubRequest(path, opt_method, opt_data, typeRequest) {
     options.json = true;
     if (typeRequest === 'milestone') {
       options.body.milestone = opt_data;
+    } else if (typeRequest === 'comment') {
+      options.body['body'] = opt_data;
```
Comment (rsimha-amp) [inline build-system/tasks/process-github-issues.js]: Use dot access.

File: build-system/tasks/process-github-issues.js [hunk 25]
```diff
@@ -119,44 +127,91 @@ function updateGitHubIssues() {
...
+          let quartelyUpdate = true;
+          if (getLastUpdate(issueLastUpdate) > QUARTERLY_DAYS) {
+            quartelyUpdate = false;
+            biweeklyUpdate = false;
+          } else if (getLastUpdate(issueLastUpdate) > BIWEEKLY_DAYS) {
+            biweeklyUpdate = false;
+          }
+          // Get the assignee
+          if (assignee) {
+            assigneeName = '@' + assignee['login'];
```
Comment (rsimha-amp) [inline build-system/tasks/process-github-issues.js]: Use dot access.

**Comment by hocalvin799** [comment]
Trust me Wei Ling,i meet you to lunch,pls?

File: build-system/tasks/process-github-issues.js (hunk 23 above)
Comment (rsimha-amp) [reply build-system/tasks/process-github-issues.js]: This is not what I meant. You can simply make`NUM_BATCHES` a constant equal to 11 and use it in the loop you'd written earlier.

Comment (adelinamart) [reply build-system/tasks/process-github-issues.js]: oh, ok. Now I know what you mean. Done. Thank you.

File: build-system/tasks/process-github-issues.js [hunk 26]
```diff
@@ -51,12 +50,23 @@ const milestoneOptions = {
...
 const MILESTONE_NEW_FRS = 23;
-// 12 is the number for Milestone 'Docs Updates'
-const MILESTONE_DOCS_UPDATES = 12;
+// 25 is the number for Milestone 'Great First Issues (GFI)'
+const MILESTONE_GREAT_ISSUES = 25;
+// days for biweekly updates
+const BIWEEKLY_DAYS = 14;
+// days for quarterly updates
+const QUARTERLY_DAYS = 89;
+const NUM_BATCHES = 11;
```
Comment (rsimha-amp) [inline build-system/tasks/process-github-issues.js]: Add a comment above this, mentioning the current default batch size and the total number of issues that will be fetched.

Comment (adelinamart) [reply build-system/tasks/process-github-issues.js]: done :)

**Comment by rsimha-amp** [comment]
Yay! I'm going to merge this now.
