### PR TITLE
Calculate correct documentHeight for short AMP docs

### LINKED ISSUE #12172: Short AMP docs sending wrong documentHeight
Hey, running into an issue with short AMP docs (smaller than the height of the viewport) and documentHeight messages. documentHeight is calculated using scrollHeight instead of the height of the content, so in this case you get a height value which is taller than the actual height of the content.

I can see that this case was originally handled when documentHeight events were implemented (https://github.com/ampproject/amphtml/commit/ac741f6d448305570659d0eae3c11c9049ae0fef), but this change was reverted before the PR was merged. Is there a reason for this? Would it be possible to add this behaviour back in?

### PR DESCRIPTION
**Pull request by peterjosling**
Handles the edge case of AMP documents which are shorter than their
containing viewport, which causes documentHeight to be scrollHeight,
which is the height of the viewport. Should be a no-op for docs which
are already taller than the viewport.

Re-implements changes made in https://github.com/ampproject/amphtml/commit/ac741f6d448305570659d0eae3c11c9049ae0fef, which were reverted before merging.

Fixes #12172

### CODE REVIEW

File: src/service/viewport/viewport-binding-ios-embed-wrapper.js [hunk 1]
```diff
@@ -216,6 +216,15 @@ export class ViewportBindingIosEmbedWrapper_ {
     return this.wrapper_./*OK*/scrollHeight;
   }
 
+  /** @override */
+  getContentHeight() {
+    // The reparented body inside wrapper will have the correct content height.
+    // Body is overflow: hidden so that the scrollHeight include the margins of
+    // body's first and last child.
+    const rect = this.win.document.body./*OK*/getBoundingClientRect();
+    return rect.height + rect.top + this.getScrollTop();
```
Comment (jridgewell) [inline src/service/viewport/viewport-binding-ios-embed-wrapper.js]: Can you confirm what this does? Why would scroll top be needed here?

Comment (peterjosling) [reply src/service/viewport/viewport-binding-ios-embed-wrapper.js]: Updated the comment to clarify.

I couldn't think of a better way to get the scrollTop back out of the DOM - offsetTop for the body is zero, and reading paddingTop out of the html element's style is messy. Alternatively could store paddingTop when setPaddingTop() is called and add it on here? This method is more generic though - would work with e.g. marginTop on body instead of paddingTop on html.
