### PR TITLE
Fix internal/local navigation links scrolling

### LINKED ISSUE #5334: Fragment link navigation is broken on iOS10
## How do we reproduce the issue?

1. Go to https://www.google.com/amp/dl.dropboxusercontent.com/u/530650439/abc.html#amph=1 on iOS 10 Safari and Chrome
2. Click the internal fragment link.

The first time it is broken. Subsequent clicks works.

## What browsers are affected?

iOS 10, all

## Which AMP version is affected?

Current

### PR DESCRIPTION
**Pull request by mkhatib**
Fixes #5334

Updating tests. @dvoytenko let me know if this looks good.

[Demo here](https://amp-mk-1.herokuapp.com/examples/viewer.html) try it on iOS simulator - second tab, open sidebar and click section 1 and 2 links to see it in effect, close the side bar notice everything works as expected.

### CODE REVIEW

**Comment by mkhatib** [comment]
[Demo here](https://amp-mk-1.herokuapp.com/examples/viewer.html) try it on iOS simulator - second tab, open sidebar and click section 1 and 2 links to see it in effect, close the side bar notice everything works as expected.

File: src/document-click.js [hunk 1]
```diff
@@ -248,12 +243,29 @@ export function onDocumentElementClick_(
...
+  // call to scroll to it.
+  // Without doing this, the viewport will not catch the updated scroll
+  // position on iOS Safari and hence calculate the wrong scrollTop for
+  // the scrollbar jumping the user back to the top for failing to calculate
+  // the new jumped offset.
+  // See https://github.com/ampproject/amphtml/issues/5334 for more details.
+  let oldAttribute = {};
   if (hash) {
     elem = ampdoc.getRootNode().getElementById(hash);
     if (!elem) {
```
Comment (jridgewell) [inline src/document-click.js]: Please swap this conditional.

File: src/document-click.js [hunk 2]
```diff
@@ -262,17 +274,25 @@ export function onDocumentElementClick_(
   // The choice of `location.replace` vs `history.replaceState` is important.
   // Due to bugs, not every browser triggers `:target` pseudo-class when
   // `replaceState` is called. See http://www.zachleat.com/web/moving-target/
-  // for more details.
-  win.location.replace(`#${hash}`);
+  // for more details. Do this only if fragment has changed.
+  if (tgtLoc.hash != curLoc.hash) {
+    win.location.replace(`#${hash}`);
```
Comment (jridgewell) [inline src/document-click.js]: Do we want to preserve the share tracking hash?

File: src/document-click.js [hunk 3]
```diff
@@ -248,12 +243,29 @@ export function onDocumentElementClick_(
...
       // Fallback to anchor[name] if element with id is not found.
       // Linking to an anchor element with name is obsolete in html5.
       elem = ampdoc.getRootNode().querySelector(`a[name=${hash}]`);
+      if (elem) {
+        oldAttribute = {key: 'name', value: elem.name};
+        elem.removeAttribute('name');
+      }
+    } else {
+      oldAttribute = {key: 'id', value: elem.id};
+      elem.removeAttribute('id');
```
Comment (jridgewell) [inline src/document-click.js]: We need to ensure there's not a `[name=${hash}]` element, too. And there could be multiple of both.

File: src/document-click.js [hunk 4]
```diff
@@ -262,17 +274,25 @@ export function onDocumentElementClick_(
...
   if (elem) {
     viewport./*OK*/scrollIntoView(elem);
+    elem.setAttribute(oldAttribute.key, oldAttribute.value);
   } else {
     dev().warn('documentElement',
         `failed to find element with id=${hash} or a[name=${hash}]`);
   }
 
+  // Has fragment really changed?
+  if (tgtLoc.hash != curLoc.hash) {
```
Comment (mkhatib) [inline src/document-click.js]: This is `==` (caught by a test). Fixing.

File: src/document-click.js [hunk 5]
```diff
@@ -248,12 +243,29 @@ export function onDocumentElementClick_(
...
     elem = ampdoc.getRootNode().getElementById(hash);
     if (!elem) {
       // Fallback to anchor[name] if element with id is not found.
       // Linking to an anchor element with name is obsolete in html5.
       elem = ampdoc.getRootNode().querySelector(`a[name=${hash}]`);
+      if (elem) {
+        oldAttribute = {key: 'name', value: elem.name};
+        elem.removeAttribute('name');
+      }
+    } else {
```
Comment (dvoytenko) [inline src/document-click.js]: Could you please revert `if/else` here to remove double negative?

File: src/document-click.js (hunk 4 above)
Comment (dvoytenko) [inline src/document-click.js]: It should be `==` here I believe. Also, please remove `return` and wrap the `history.push` inside the `if`.

Comment (mkhatib) [inline src/document-click.js]: Yes, caught by a test. Will fix

File: src/document-click.js (hunk 3 above)
Comment (mkhatib) [inline src/document-click.js]: Good points. Will fix.

File: src/document-click.js (hunk 2 above)
Comment (mkhatib) [inline src/document-click.js]: Not sure. @dvoytenko do you know how do we handle this here?

File: src/document-click.js (hunk 1 above)
Comment (mkhatib) [inline src/document-click.js]: Dropped. Using `||` instead.

File: src/document-click.js (hunk 3 above)
Comment (mkhatib) [inline src/document-click.js]: Done

File: src/document-click.js (hunk 4 above)
Comment (mkhatib) [inline src/document-click.js]: Fixed

File: src/document-click.js (hunk 5 above)
Comment (mkhatib) [inline src/document-click.js]: Dropped.

File: src/document-click.js (hunk 4 above)
Comment (mkhatib) [inline src/document-click.js]: Fixed.

**Comment by mkhatib** [comment]
PTAL 👀

File: src/document-click.js [hunk 6]
```diff
@@ -358,3 +347,52 @@ export function expandTargetHref_(e, target, urlReplacements) {
...
+ *   *[id=hash] and a[name=hash].
+ * @param {!./service/ampdoc-impl.AmpDoc} ampdoc
+ * @param {string} hash
+ * @return {!Array<!RestoreElementAttributesDef>}}
+ * @private
+ */
+function removeAttrsWithMatchingHash_(ampdoc, hash) {
+  const restoreElementsAttrs = [];
+  const targetElements = ampdoc.getRootNode().querySelectorAll(
+      `#${hash},a[name=${hash}]`) || [];
```
Comment (jridgewell) [inline src/document-click.js]: The hash should be escaped and quoted for the `name` part.

File: src/document-click.js [hunk 7]
```diff
@@ -358,3 +347,52 @@ export function expandTargetHref_(e, target, urlReplacements) {
...
+  for (let i = 0; i < targetElements.length; i++) {
+    const element = targetElements[i];
+    const attributes = {};
```
Comment (jridgewell) [inline src/document-click.js]: We can simplify to:

```js
attributes = {
  name: element.name === hash,
  id: element.id === name,
};

Comment (mkhatib) [inline src/document-click.js]: Then I'd have to check the value when looping over attrs. I also still need the if else to remove attributes when matching.

Comment (jridgewell) [inline src/document-click.js]: Ohh, I see the loop now.

File: src/document-click.js (hunk 6 above)
Comment (mkhatib) [inline src/document-click.js]: By the hash you mean the literal `#` sign or the variable `${hash}`?  If the earlier, why do we need to escape it?

If the latter, what values do we expect to break this? And what does escape means here?

Comment (jridgewell) [inline src/document-click.js]: hash = `something]` will break this. @dvoytenko recently did something with CSS escaping.

Comment (mkhatib) [inline src/document-click.js]: Used `dom.escapeCssSelectorIdent` to escape it. @dvoytenko is this accurate? Or if we should just use the `css-escape.cssEscape` instead?

**Comment by mkhatib** [comment]
PTAL 👀

File: src/document-click.js (hunk 2 above)
Comment (muxin) [inline src/document-click.js]: I don't think it's a good idea to have both document tag and share-tracking hash together in the url hash. Maybe we could only have document tag in this case. So I think this is good for now.

Comment (dvoytenko) [inline src/document-click.js]: Yeah, don't preserve. It's up to the publisher on whether they use hash-based links.

File: src/document-click.js (hunk 6 above)
Comment (dvoytenko) [inline src/document-click.js]: Yes, `dom.escapeCssSelectorIdent` would do the trick.

File: src/document-click.js (hunk 7 above)
Comment (dvoytenko) [inline src/document-click.js]: I think doing loop here is a bit too much: we should just focus on a most likely case here and leave edge-cases out. The fidelity requirement is somewhat lower here.

Comment (mkhatib) [inline src/document-click.js]: So just go back to only managing attributes on the found `elem`?

Comment (jridgewell) [inline src/document-click.js]: I think he's saying the `for attr in attrs` [loop](https://github.com/ampproject/amphtml/pull/5381/files#diff-db0430e49cbdcc5a4a002c5bbd3567b9R399) is too much. We only care about `name` and `id`, nothing else.

Comment (mkhatib) [inline src/document-click.js]: @dvoytenko can you clarify?

Comment (dvoytenko) [inline src/document-click.js]: Both:

1. It's enough to just have `RestoreElementAttributesDef` be `{element, attrName, attrValue}` and thus you can just take care of everything with a single loop.
2. We could even simplify this and only look for a single first element that matches either id search or name search. It seems to me that if there are several competing elements - we could live with that. But, obviously, a more foolproof solution is good as well :)

**Comment by mkhatib** [comment]
So @dvoytenko found few problems with this solution,

* Breaking CSS styling (because of removing of ID attr)
* Causing relayout with ID changes

I am exploring other solutions, one being calling `scrollIntoView` twice, once normally and once in a 0-timeout callback - the first is basically to override the browsers scroll right away and the timed out call to actually do the actual scroll into view.

```Javascript
viewport.scrollIntoView(elem);
setTimeout(() => viewport.scrollIntoView(elem), 0);
```

**Comment by muxin** [comment]
Why can't we use `replaceState` again? I saw a [post](http://stackoverflow.com/questions/1489624/modifying-document-location-hash-without-page-scrolling/14560718#14560718) about disabling default page scrolling by using `replaceState`

File: src/document-click.js [hunk 8]
```diff
@@ -14,11 +14,14 @@
  * limitations under the License.
  */
 
-import {closestByTag} from './dom';
+import {
+    closestByTag,
```
Comment (mkhatib) [inline src/document-click.js]: Fixed

File: src/document-click.js [hunk 9]
```diff
@@ -248,35 +246,42 @@ export function onDocumentElementClick_(
...
+    // scrolling behavior. The second call insides setTimeout allows us to
+    // scroll to that element properly.
+    // Without doing this, the viewport will not catch the updated scroll
+    // position on iOS Safari and hence calculate the wrong scrollTop for
+    // the scrollbar jumping the user back to the top for failing to calculate
+    // the new jumped offset.
+    // Without the first call there will be a visual jump due to browser scroll.
+    // See https://github.com/ampproject/amphtml/issues/5334 for more details.
     viewport./*OK*/scrollIntoView(elem);
+    setTimeout(() => viewport./*OK*/scrollIntoView(elem), 0);
```
Comment (mkhatib) [inline src/document-click.js]: @dvoytenko here's the updated approach.

File: src/document-click.js [hunk 10]
```diff
@@ -248,35 +246,42 @@ export function onDocumentElementClick_(
...
   } else {
     dev().warn('documentElement',
         `failed to find element with id=${hash} or a[name=${hash}]`);
   }
-
-  // Push/pop history.
-  history.push(() => {
-    win.location.replace(`${curLoc.hash || '#'}`);
```
Comment (mkhatib) [inline src/document-click.js]: @dvoytenko dropping this to fix #4184 See discussion there. Let me know what do you think about this?

**Comment by mkhatib** [comment]
@dvoytenko PTAL 👀 

Please ignore tests - outdated.

**Comment by dvoytenko** [comment]
@muxin When in iframe, `replaceState` may break parent history stack and definitely breaks `:target` selector.

File: src/document-click.js (hunk 10 above)
Comment (dvoytenko) [inline src/document-click.js]: Don't yet understand why this is being dropped. Can you re-sum this up in either thread? This exists so that users can click on back button and get to normal state, especially given the `:target` support.

File: src/document-click.js (hunk 9 above)
Comment (jridgewell) [inline src/document-click.js]: Can we use `timer.delay` here (which uses a micro task for `0` delays)?

File: src/document-click.js (hunk 10 above)
Comment (mkhatib) [inline src/document-click.js]: OK, as I replied to that bug, I want to just focus on fixing this bug now. So I'll bring this line back and stick with the timer fix. And will address the other issue in a followup PR.

**Comment by mkhatib** [comment]
Ok Updated PR now only addresses #5309 bug. Not the sidebar bug.

**Comment by mkhatib** [comment]
Please PTAL 👀

File: src/document-click.js [hunk 11]
```diff
@@ -248,35 +247,49 @@ export function onDocumentElementClick_(
...
-    if (!elem) {
-      // Fallback to anchor[name] if element with id is not found.
-      // Linking to an anchor element with name is obsolete in html5.
-      elem = ampdoc.getRootNode().querySelector(`a[name=${hash}]`);
-    }
+    const escapedHash = escapeCssSelectorIdent(ampdoc.win, hash);
+    elem = (ampdoc.getRootNode().getElementById(hash) ||
+        // Fallback to anchor[name] if element with id is not found.
+        // Linking to an anchor element with name is obsolete in html5.
+        ampdoc.getRootNode().querySelector(`a[name=${escapedHash}]`));
```
Comment (dvoytenko) [inline src/document-click.js]: This CSS selector here also needs `"` I believe. Please add a test for search of an element with name with a space or such.

Comment (mkhatib) [inline src/document-click.js]: Fixed

**Comment by mkhatib** [comment]
Done 👀  PTAL

**Comment by dvoytenko** [comment]
LGTM on my side.
