### PR TITLE
🐛 Patch web-animations-js polyfill to avoid writing to readonly property

### LINKED ISSUE #19783: TypeError: Action execution failed: AMP-ANIMATION start: Attempted to assign to readonly property.
```
cancel — web-animations.install.js:975
cancel — web-animations.install.js:2101
(anonymous function) — web-animations.install.js:2143
(anonymous function) — web-animations.install.js:2153
installWebAnimations — web-animations.install.js:2154
installWebAnimationsIfNecessary — web-animations-polyfill.js:29
createRunner_ — amp-animation.js:468
createRunnerIfNeeded_ — amp-animation.js:420
startOrResume_ — amp-animation.js:405
startAction_
executionAction_ — custom-element.js:1387
enqueAction — custom-element.js:1355
invoke_ — action-impl.js:566
(anonymous function) — action-impl.js:486
forEach
action_ — action-impl.js:487
trigger — amp.js:21701
trigger_ — amp-video-docking-0.1.max.js:1053
setCurrentlyDocked_ — amp-video-docking.js:1232
dock_ — amp-video-docking-0.1.max.js:1034
dockInTwoSteps_ — amp-video-docking.js:854
dockOnPositionChange_ — amp-video-docking-0.1.max.js:978
updateOnPositionChange_ — amp-video-docking.js:649
trigger_ — position-observer-worker.js:103
(anonymous function) — position-observer-worker.js:134
promiseReactionJob
```

Fixed on web-animations-js [`e2782a`](https://github.com/web-animations/web-animations-js/commit/e2782af1a3715fed5b96c5366f89f9b204f8b9a0#diff-2314e4f2e74b0a130fa863211c157653), but not released yet.

/cc @dvoytenko @aghassemi

### PR DESCRIPTION
**Pull request by alanorozco**
Fixes #19783

### CODE REVIEW

File: build-system/tasks/update-packages.js [hunk 1]
```diff
@@ -79,6 +79,12 @@ function patchWebAnimations() {
   // See https://github.com/ampproject/amphtml/issues/18612 and
   // https://github.com/web-animations/web-animations-js/issues/46
   file = file.replace(/b.true=a/g, 'b?b.true=a:true');
+
+  // Fix web-animations-js code that attempts to write a read-only property.
+  // https://github.com/ampproject/amphtml/issues/19783 and
+  // https://github.com/web-animations/web-animations-js/issues/160
+  file = file.replace(/this\._isFinished\s*=\s*!0,/g, '');
```
Comment (dvoytenko) [inline build-system/tasks/update-packages.js]: Doesn't `!` also need an escape?

Also, for safety, there's only one such instance. Should we remove `/g`?

Comment (alanorozco) [reply build-system/tasks/update-packages.js]: done, ptal.

**Comment by rsimha** [comment]
Merging so this can go into today's `canary` cut. Lone integration test failure is known flake that's being dealt with separately.
