### PR TITLE
Ensure that all extensions are processed

### LINKED ISSUE #2630: Access request not being sent, causing blank pages
Sometimes, when loading the AMP carousel and swiping a few times, the access requests stop being sent. When this happens, neither the article content nor the barrier are shown. I am signed in to the FT, and when the access request *does* happen, the service is returning `access: true`, and the content is correctly shown.

screenshot 2016-03-18 09 34 34

This is the article rendered at https://amp.ft.com/content/dbf0ae98-ec63-11e5-bb79-2303682345c8.

I'm also seeing some errors in the console; I'm unclear if these are related:

```
Uncaught Error: Service activity was requested to be provided through amp-analytics, but amp-analytics is not loaded in the current page. To fix this problem load the JavaScript file for amp-analytics in this page.​​​
Uncaught Error: Service cid was requested to be provided through amp-analytics, but amp-analytics is not loaded in the current page. To fix this problem load the JavaScript file for amp-analytics in this page.​​​
```

We're seeing this with an emulated Nexus 5 as well as a real iPhone 5s and Galaxy S4, in AMP version 1457721872758.

### PR DESCRIPTION
**Pull request by dvoytenko**
Fixes #2630.

### CODE REVIEW

**Comment by dvoytenko** [comment]
Ready for review: /cc @erwinmombay @jridgewell @mkhatib @sriramkrish85

File: src/render-delaying-extensions.js [hunk 1]
```diff
@@ -64,6 +65,7 @@ export function waitForExtensions(win) {
  */
 export function includedExtensions(win) {
   const document = win.document;
+  dev.assert(document.body);
```
Comment (sriramkrish85) [inline src/render-delaying-extensions.js]: is this needed?

File: src/custom-element.js [hunk 2]
```diff
@@ -1251,8 +1258,21 @@ export function getElementServiceIfAvailable(win, id, providedByElement) {
...
-  }
-  return getElementService(win, id, providedByElement);
+  // Microtask is necessary to ensure that window.ampExtendedElements has been
+  // initialized.
+  return Promise.resolve().then(() => {
+    if (isElementScheduled(win, providedByElement)) {
+      return getServicePromise(win, id);
+    }
+    // Wait for HEAD to fully form before denying access to the service.
+    if (!win.document.body) {
```
Comment (cramforce) [inline src/custom-element.js]: There could be a raise condition here: Body is now available, but element discovery has not run again.
Better to just always do this?

File: src/dom.js [hunk 3]
```diff
@@ -16,6 +16,60 @@
...
+      }
+    });
+    observer.observe(parent, {childList: true});
+  } else {
+    const interval = win.setInterval(() => {
+      if (checkFunc()) {
+        win.clearInterval(interval);
+        callback();
+      }
+    });
```
Comment (cramforce) [inline src/dom.js]: Something like 5 is better I believe. I think that is what we typically use for "almost busy wait"

File: src/render-delaying-extensions.js (hunk 1 above)
Comment (cramforce) [inline src/render-delaying-extensions.js]: Seems very useful. The good thing about `dev.assert` is that one can have many of them without guilt.

**Comment by cramforce** [comment]
LGTM with some comments.

File: src/dom.js [hunk 4]
```diff
@@ -16,6 +16,60 @@
...
 
 /**
+ * Waits until the child element is constructed. Once the child is found, the
+ * callback is executed.
+ * @param {!Element} parent
+ * @param {function():boolean} checkFunc
+ * @param {function()} callback
+ */
+export function waitForChild(parent, checkFunc, callback) {
+  if (checkFunc()) {
```
Comment (erwinmombay) [inline src/dom.js]: pass in parent to `checkFunc` to follow all other `predicate` type signatures. not useful in this case since you have a ref to `parent` but could see it being useful in other scenarios. (might also be useful to pass it into callback)

**Comment by erwinmombay** [comment]
LGTM per @cramforce requests

File: src/render-delaying-extensions.js (hunk 1 above)
Comment (dvoytenko) [inline src/render-delaying-extensions.js]: Needed for now.

File: src/custom-element.js (hunk 2 above)
Comment (dvoytenko) [inline src/custom-element.js]: Good point. Will always run it. Will separately provide a design doc for the right solution.

File: src/dom.js (hunk 3 above)
Comment (dvoytenko) [inline src/dom.js]: Done

File: src/dom.js (hunk 4 above)
Comment (dvoytenko) [inline src/dom.js]: Done

**Comment by cramforce** [comment]
Downintegrate into canary?

**Comment by dvoytenko** [comment]
In canary now.

**Comment by quarterto** [comment]
Is this fix live? We believe we've seen #2630 again today.

**Comment by dvoytenko** [comment]
@quarterto  Yes, it's live. And our monitoring shows no errors of this kind again. If you do think it's happening - let me know and I'll do more research in case there might be something else.
