### PR TITLE
🐛  [amp-story-player] Adds intermediate element and removes default size

### LINKED ISSUE #30423: [amp-story-player AMP version] Width & Height attributes not working with layout responsive
When using the AMP version of the `amp-story-player` with `layout="responsive"`, the `width` and `height` attributes are not respected. 

The amp-story-player CSS seems to force a width of 360px and height of 600px for the component.

For example, if we use `<amp-story-player width="410" height="684" layout="responsive">...`, the width and height stay at 360/600.

It seems to be caused by this CSS that gets applied:

https://github.com/ampproject/amphtml/blob/8fb1a06a49088fb87de9b24646dee2058d910a87/css/amp-story-player.css#L17-L22

But when I delete these default styles, the result is a player with a computed height of `0px`. Here is a [demo](https://amp-story-player-responsive.web.app/examples/amp-story/player-amp.html).

@ampproject/wg-ui-and-a11y, is there anything I have to do on the [amp-story-player](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story-player/0.1/amp-story-player.js) extension to fix this? Is it because I need to propagate the attributes correctly? Or is it caused by the fact we are embedding a shadow DOM with iframes?

@ampproject/wg-stories

### PR DESCRIPTION
**Pull request by Enriqe**
Closes #30423

I tested different layouts in AMP (responsive, fixed...) and they seemed to work fine.

Also tested without shadow DOM in case it's not supported.

Note that since there's no way of calling `this.applyFillContent(element)` from the `amp-story-player-impl.js` class directly (since it does not inherit from base element), I had to apply the CSS class `i-amphtml-fill-content` manually.

### CODE REVIEW

**Review by gmajoulet — APPROVED** [review]

**Comment by Enriqe** [comment]
Visual diff tests were failing because in non-AMP test version (no shadow DOM) the intermediary had the default height `auto`, making its children have height 0px.

**Comment by Enriqe** [comment]
@gmajoulet just making sure you saw the latest changes. re-requesting review.

File: src/amp-story-player/amp-story-player-impl.js [hunk 1]
```diff
@@ -389,10 +389,20 @@ export class AmpStoryPlayer {
     this.rootEl_ = this.doc_.createElement('div');
     this.rootEl_.classList.add('i-amphtml-story-player-main-container');
 
+    const shadowContainer = this.doc_.createElement('div');
+
+    // For AMP version.
+    shadowContainer.classList.add(
+      'i-amphtml-fill-content',
+      'i-amphtml-story-player-shadow-dom-intermediary'
```
Comment (gmajoulet) [inline src/amp-story-player/amp-story-player-impl.js:397]: Nit: shadow-root?

**Review by gmajoulet — APPROVED** [review]
