### PR TITLE
Run through all actions for each distFlavor in `amp release` before the next

### LINKED ISSUE #34542: `amp release` with no flags fails to build
### Description

Running `amp release` with no flags fails to build. Running it with `amp release --flavor base` works. I haven't tested specific experiments yet.

### Reproduction Steps

On a clean repository, run `amp release`

### Relevant Logs

```shell
[16:01:30] [Error: ENOENT: no such file or directory, open '/usr/local/google/home/rodaniel/dsfca/amphtml/release/org-cdn/rtv/002105251902000/alp.js'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/rodaniel/amphtml/release/org-cdn/rtv/002105251902000/alp.js'
}
```

### Browser(s) Affected

Chrome, Firefox, Safari, Edge, UC Browser

### OS(s) Affected

n/a

### Device(s) Affected

n/a

### AMP Version Affected

latest?

### PR DESCRIPTION
**Pull request by danielrozenberg**
Fixes #34542

Root cause of the issue is that the `compileDistFlavors_` function called `amp clean` between different flavors (base, experimentA, ...) which caused a followup function in the process (`populateOrgCdn_`) to fail, as it was expecting files that were cleaner by `amp clean`

The PR fixes this by looping through all the `distFlavors` and calling all the functions use each individual `distFlavor`, instead of calling those functions with `distFlavors` (plural) and looping through it inside those functions.

This PR also makes the typedefs more explicit and fixes some weird Promise-related type issues.

### CODE REVIEW

File: build-system/tasks/release/index.js [hunk 1]
```diff
@@ -15,7 +15,37 @@
...
+ * @typedef {{
+ *  experimentA: ExperimentConfigDef,
+ *  experimentB: ExperimentConfigDef,
+ *  experimentC: ExperimentConfigDef,
+ * }}
+ */
+ let ExperimentsConfigDef;
+
+ /**
+  * @typedef {ExperimentConfigDef & {
```
Comment (rsimha) [inline build-system/tasks/release/index.js:39]: Copy-paste typo?
```suggestion
  * @typedef {{
```

File: build-system/tasks/release/index.js [hunk 2]
```diff
@@ -176,78 +195,72 @@ function discoverDistFlavors_() {
...
-    await Promise.all(
-      DIST_DIRS.map((distDir) =>
-        fs.move(distDir, path.join(flavorTempDistDir, distDir))
+async function compileDistFlavors_(flavorType, command, tempDir) {
+  // TODO(danielrozenberg): remove undefined case when the release automation platform explicitly handles it.
+  if (argv.esm === undefined) {
+    command = `${command} --esm && ${command}`;
+  } else if (argv.esm) {
+    command += ' --esm';
+  }
```
Comment (rsimha) [inline build-system/tasks/release/index.js:208]: From my reading of release automation, `ESM_FLAG` is one of `('--esm', '--no-esm')` and the command run is:
```py
cd "${GIT_REPO_DIR}"
amp release --output_dir "${EXTERNAL_CONTENT_DIR}" --flavor "${FLAVOR}" "${ESM_FLAG}"
```
Does this mean the `argv.esm === undefined` case can be removed from here?

**Review by rileyajones — APPROVED** [review]

File: build-system/tasks/release/index.js [hunk 3]
```diff
@@ -15,7 +15,37 @@
  */
 'use strict';
 
+/**
```
Comment (rsimha) [inline build-system/tasks/release/index.js:18]: I just realized why this file wasn't already auto-formatted: We have an entry called `release` on line 22 of `.gitignore`, `.eslintignore`, and `.prettierignore`. Since this task file and its output directory share the same name, the two need to be differentiated.

(IIRC, you had done this correctly in #28344, but the slash was inadvertently removed when I reorganized these files in #33838.)

File: build-system/tasks/release/index.js (hunk 2 above)
Comment (rsimha) [inline build-system/tasks/release/index.js:208]: From my reading of release automation code, `ESM_FLAG` is set to one of `('--esm', '--no-esm')` , and this task is invoked as:
```py
amp release --output_dir "${EXTERNAL_CONTENT_DIR}" --flavor "${FLAVOR}" "${ESM_FLAG}"
```

Does this mean the `argv.esm === undefined` case here can be removed?

**Review by rsimha — APPROVED** [review]
LGTM with three comments.

File: build-system/tasks/release/index.js (hunk 2 above)
Comment (danielrozenberg) [reply build-system/tasks/release/index.js:208]: Eventually yes, but I'd rather do that in a separate PR after making sure the release automation calls it correctly for every case

File: build-system/tasks/release/index.js (hunk 1 above)
Comment (danielrozenberg) [reply build-system/tasks/release/index.js:39]: Yep, this is how you extend a type :)

File: build-system/tasks/release/index.js (hunk 3 above)
Comment (danielrozenberg) [reply build-system/tasks/release/index.js:18]: Restored the slash.

File: .eslintignore [hunk 4]
```diff
@@ -19,7 +19,7 @@ dist.tools
 export
 examples/storybook
 extensions/**/dist
-release
+/release
```
Comment (rsimha) [inline .eslintignore:22]: nit: Can we use a trailing slash here if it works? (Then the entry in `clean.js` can be synced with this.)

File: build-system/tasks/clean.js [hunk 5]
```diff
@@ -28,7 +28,7 @@ const ROOT_DIR = path.resolve(__dirname, '../../');
  * node_modules package directories.
```
Comment (rsimha) [inline build-system/tasks/clean.js:28]: nit: Update JSDoc.
```suggestion
 * node_modules package directories, or excludes some directories from deletion.
```

File: build-system/tasks/clean.js [hunk 6]
```diff
@@ -61,6 +61,10 @@ async function clean() {
   if (argv.include_subpackages) {
     pathsToDelete.push('**/node_modules', '!node_modules');
   }
+  if (argv.exclude) {
+    const excludes = argv.exclude.split(',');
+    pathsToDelete = pathsToDelete.filter((path) => !excludes.includes(path));
```
Comment (rsimha) [inline build-system/tasks/clean.js:66]: Instead of doing an exact match and risking a mismatch due to a stray slash, might be safer to explicitly negate these paths.
```suggestion
    for (const exclude of excludes) {
      pathsToDelete.push(`!${exclude}`);
    }
```

**Review by rsimha — APPROVED** [review]
Still LGTM, with a suggestion and a couple nits.

File: .eslintignore (hunk 4 above)
Comment (danielrozenberg) [reply .eslintignore:22]: In addition to the preceding slash? (this works) or instead of it? (this doesn't work)

Comment (rsimha) [reply .eslintignore:22]: I meant trailing only, but realized that wouldn't work because the JS file is not `release.js`, but `release/index.js`. Thanks for humoring me, and carry on!

**Comment by danielrozenberg** [comment]
Tested `amp release`, `amp release --no-esm`, and `amp-release --flavor base --esm` locally - looks like all reasonable scenarios are viable now. Enabling auto-merge
