### PR TITLE
Narrow down script matching to avoid incorrect prefix matches

### LINKED ISSUE #25436: Extension reload breaks waitForExtension
When an extension depends on another extension for a service it ends up in `waitForExtension` if the provider hasn't yet loaded.   We've been seeing timeouts from `waitForExtension` that shouldn't be happening.

This problem is that if v0.js detects a version mismatch (v0.js version differs from an extension version) it automatically loaded the correct version of the extension to match v0 9`getExtensionScript_`).  When it does this it creates a new extension holder which leaves `waitForExtension` waiting on a load that will never happen.

This only happens on publisher sites due to the AMP cache automatically syncing versions and it only happens if the extension in cache mismatches v0.js.

See deletion of the extension holder https://github.com/ampproject/amphtml/blame/40fa29d8daacd92fbbcfda825f4b7f89dab25a34/src/service/extensions-impl.js#L255

### PR DESCRIPTION
**Pull request by dvoytenko**
Fixes #25436.

Additionally fixes a race condition on the wait->reload sequence. Rare, but manifests itself exactly the same way as described in the #25436.

### CODE REVIEW

File: src/service/extensions-impl.js [hunk 1]
```diff
@@ -270,12 +270,22 @@ export class Extensions {
...
+    // We have to match against "src" because a few extensions, such as
+    // "amp-viewer-integration", do not have "custom-element" attribute.
     const modifier =
       ':not([i-amphtml-loaded-new-version])' +
       (includeInserted ? '' : ':not([i-amphtml-inserted])');
-    return this.win.document.head./*OK*/ querySelector(
+    const matches = this.win.document.head./*OK*/ querySelectorAll(
       `script[src*="/${extensionId}-"]` + modifier
     );
+    const matcher = new RegExp(`${extensionId}-[0-9]`);
```
Comment (jridgewell) [inline src/service/extensions-impl.js]: Nit: `\d`

Comment (dvoytenko) [reply src/service/extensions-impl.js]: Done

File: src/service/extensions-impl.js [hunk 2]
```diff
@@ -248,12 +248,10 @@ export class Extensions {
       /* includeInserted */ false
     );
     devAssert(el, 'Cannot find script for extension: %s', extensionId);
-    // "Disconnect" the old script element and extension record.
+    // The previously awaited extension loader must not have finished or
+    // failed.
     const holder = this.extensions_[extensionId];
-    if (holder) {
-      devAssert(!holder.loaded && !holder.error);
-      delete this.extensions_[extensionId];
```
Comment (jridgewell) [inline src/service/extensions-impl.js]: We were deleting this so that `isExtensionScriptRequired_` would return true. If we don't delete the holder, we must set `scriptPresent` to `false`

Comment (dvoytenko) [reply src/service/extensions-impl.js]: I see. I'll review the tests again. Someone should have failed.

Comment (dvoytenko) [reply src/service/extensions-impl.js]: Fixed
