### PR TITLE
🐛 Fix percentage-played when loadedmetadata fires before listener is added

### LINKED ISSUE #22701: video-percentage-played doesn't trigger
The `video-percentage-played` only triggers at 100% regardless of the `percentages` settings. 

Can be reproduced with `test/manual/amp-video.amp.html`.

### PR DESCRIPTION
**Pull request by cvializ**
Fixes #22701

@alanorozco do you think this will work or are there any concerns with this approach?

### CODE REVIEW

File: src/service/video-manager-impl.js [hunk 1]
```diff
@@ -1337,6 +1337,12 @@ export class AnalyticsPercentageTracker {
 
     this.unlisteners_ = this.unlisteners_ || [];
 
+    // If the video has already emitted LOADEDMETADATA, the event below
+    // will never fire, so we check if it's already available here.
+    if (this.hasDuration_()) {
+      this.calculate_(this.triggerId_);
```
Comment (alanorozco) [inline src/service/video-manager-impl.js]: Maybe we don't need to listen for `LOADEDMETADATA` in this case?

Comment (cvializ) [reply src/service/video-manager-impl.js]: oh good point, I'll try that
