### PR TITLE
🐛Fixes ima-video race condition and percentage played 

### LINKED ISSUE #23356: amp-ima-video: browser freezes after pre-roll ad plays
## What's the issue?

`amp-ima-video` with pre-roll ads will freeze browser tab when network conditions are poor. The tab freezes right about when the regular video starts to play after the pre-roll. You can see the moment right after the pre-roll ad that the CPU climbs up to 100%:
Screen Shot 2019-07-16 at 1 41 15 PM

We tried to also replicate this issue using the regular `amp-video` component and could not. This appears to only occur with `amp-ima-video`.

## How do we reproduce the issue?

https://jsbin.com/makubutuca/1/edit?html,output

1) Go to JS Bin link above
2) Turn off "Auto-run JS"
3) Control case - Press "Run with JS" - should see sample preroll & then video play.  
  Everything at this point is interactive and working as expected.
4) Go to network and set throttle (Slow 3g or slower)
5) Press 'Run with JS' again
6) Wait for the video to load & after pre roll plays (In most of our testing, it would take up to minute and a half to get to this point). Not able to interact with footer (or browser at all)

You can try the above steps on a regular `amp-video` component in the JS Bin link below to verify that it works as expected using `amp-video`:
https://jsbin.com/jefikolugo/edit?html,output

## What browsers are affected?

Tested on Mac:
Chrome, Safari, Firefox, Edge

## Which AMP version is affected?

1907091704050

### PR DESCRIPTION
**Pull request by micajuine-ho**
Fixes the race condition that causes the ima-video player to freeze with slow network connection. Also added event trigger to calculate percentage played.
Closes #23356

### CODE REVIEW

File: ads/google/ima-player-data.js [hunk 1]
```diff
@@ -23,7 +23,7 @@ export class ImaPlayerData {
     this.currentTime = 0;
 
     /* {!Number} */
-    this.duration = 1;
+    this.duration = NaN;
```
Comment (alanorozco) [inline ads/google/ima-player-data.js]: Since other players just return `1` to mean unsupported, let's revert this to `1` and change the condition on the percentage tracker to exclude `<= 1` as discussed offline.

File: extensions/amp-ima-video/0.1/amp-ima-video.js [hunk 2]
```diff
@@ -286,6 +286,7 @@ class AmpImaVideo extends AMP.BaseElement {
     }
     if (videoEvent == ImaPlayerData.IMA_PLAYER_DATA) {
       this.playerData_ = /** @type {!ImaPlayerData} */ (eventData['data']);
+      this.element.dispatchCustomEvent(VideoEvents.LOADEDMETADATA);
```
Comment (alanorozco) [inline extensions/amp-ima-video/0.1/amp-ima-video.js]: > when two lines end mayhem. 💪

File: src/service/video-manager-impl.js [hunk 3]
```diff
@@ -1434,7 +1434,7 @@ export class AnalyticsPercentageTracker {
     const duration = video.getDuration();
 
     // Livestreams or videos with no duration information available.
-    if (!duration || isNaN(duration) || duration <= 0) {
+    if (!duration || isNaN(duration) || duration <= 1) {
```
Comment (zhouyx) [inline src/service/video-manager-impl.js]: might worth adding comment on 1 is the default value to mean unsupported.

**Comment by zhouyx** [comment]
@micajuine-ho could you please take a look at the tests. Thanks. 

Also any idea on preventing this type of race condition in the future.

**Comment by micajuine-ho** [comment]
> Also any idea on preventing this type of race condition in the future.

I talked with @alanorozco yesterday and we said that guarding against NaN values in `delay()` could be good. 
Maybe something like: 
```
frequencyMs = isNaN(frequencyMs) ?  PERCENTAGE_FREQUENCY_MIN_MS : frequencyMs;
timer.delay(calculateAgain, frequencyMs);
```

**Comment by zhouyx** [comment]
@alanorozco should we add you to owner of src/service/video-manager-impl.js file? Or should we ask @dvoytenko for review : )

**Comment by alanorozco** [comment]
@zhouyx done, captain.

waiting for CI in order to merge.
