### PR TITLE
Fixes `update_tests` flag on `gulp validator`

### LINKED ISSUE #26964: Found invalid flags for gulp validator: --update_tests
## What's the issue?

Running `gulp validator --update_tests` fails with error

```
[14:06:54] ERROR: Found invalid flags for gulp validator: --update_tests
[14:06:54] For detailed usage information, run gulp help.
```
/cc @honeybadgerdontcare

### PR DESCRIPTION
**Pull request by wassgha**
Fixes #26964

/cc @honeybadgerdontcare

### CODE REVIEW

File: build-system/tasks/validator.js [hunk 1]
```diff
@@ -43,4 +43,12 @@ module.exports = {
 };
 
 validator.description = 'Builds and tests the AMP validator.';
+validator.flags = {
+  'update_tests': 'Updates validation test output files',
```
Comment (rsimha) [inline build-system/tasks/validator.js]: Add two spaces between `'` and `Updates` to make the output of `gulp help` more readable.

File: build-system/tasks/validator.js [hunk 2]
```diff
@@ -43,4 +43,12 @@ module.exports = {
...
+};
+
 validatorWebui.description = 'Builds and tests the AMP validator web UI.';
+validatorWebui.flags = {
+  'update_tests': 'Updates validation test output files',
```
Comment (rsimha) [inline build-system/tasks/validator.js]: Same here.

**Comment by rsimha** [comment]
> Just ran into this issue as well

Sorry about the friction caused by this check. I added it to keep ourselves honest about the flags that are actually supported by the build system, and to prevent inadvertent incorrect usage. Hopefully, this should resolve itself soon.
