### PR TITLE
🐛 Maintain ad-rolling state, use to init dock controls

### LINKED ISSUE #26980: amp-video-docking + preroll issue
amp-video-docking extension uses AD_START event to update controls, however it fails to do so on prerolls:

- Clicking play starts video play, preroll is started and AD_START is dispatched.
- User scrolls and player gets into the dock mode -- video-docking extension sets listeners at this time.
- Because AD_START was dispatched before, controls won't be updated.

Basically, dock extension won't update controls on ad started before player entered the dock mode at least once.

### PR DESCRIPTION
**Pull request by alanorozco**
Fixes #26980.

- Keeps `isRollingAd` state.
- Consolidates `getEntry(ForVideo|ForElement)_`.
- Rather than keep the manager as an intermediary for `VideoEntry` state, this exposes all state at once and proposes restructuring/moving public methods instead. Exposing all state at once prevents running a linear search thrice when showing controls.

### CODE REVIEW

File: src/service/video-manager-impl.js [hunk 1]
```diff
@@ -281,42 +281,48 @@ export class VideoManager {
...
-        return this.entries_[i];
+      const entry = this.entries_[i];
+      if (
+        entry.video === videoOrElement ||
+        entry.video.element === videoOrElement
+      ) {
+        return entry;
       }
     }
-    dev().error(TAG, 'video is not registered to this video manager');
```
Comment (alanorozco) [inline src/service/video-manager-impl.js]: Erroring and then returning null was weird before, and it's weird now.

This should just assert instead, but I'll explore refactoring this method later anyway. Unsure why the previous conditional check has not been failing before.

File: src/service/video-manager-impl.js [hunk 2]
```diff
@@ -498,6 +511,27 @@ class VideoEntry {
       this.logCustomAnalytics_(eventType, data['vars']);
     });
 
+    // TODO(alanorozco): Listeners below could be symmetrical (ie. just one)
+    // if consolidating VideoEvents with VideoAnalyticsEvents,
+    // e.g. `video-` prefix. This also applies to most other handlers that
+    // trigger an analyticsEvent.
+    // (Ensure symmetry between types via unit test.)
```
Comment (wassgha) [inline src/service/video-manager-impl.js]: Can we make an issue for this?

File: src/service/video-manager-impl.js [hunk 3]
```diff
@@ -942,6 +967,11 @@ class VideoEntry {
     return PlayingStates.PLAYING_MANUAL;
   }
 
+  /** @return {boolean} */
+  isRollingAd() {
+    return this.isRollingAd_;
+  }
```
Comment (wassgha) [inline src/service/video-manager-impl.js]: getter?

Comment (alanorozco) [reply src/service/video-manager-impl.js]: Will do later, keeping as-is for consistency with current getters.

File: extensions/amp-video-docking/0.1/controls.js [hunk 4]
```diff
@@ -427,20 +415,27 @@ export class Controls {
 
   /** @private */
   showOnNextAnimationFrame_() {
```
[the remark this answers is not in the document]
Comment (alanorozco) [reply extensions/amp-video-docking/0.1/controls.js]: 1. `mousemove` listener is removed when controls hide. is this a problem?
2. Verify what particularly? I'd like to display with new state each time rather than mutate. It's simpler and I don't think it's particularly more expensive.

**Comment by alanorozco** [comment]
@wassgha Actually, that comment still applies. We only care about **`register()`**, not for internal methods:

```
Its `register` method should only allow `VideoInterface` as a guarding measure.
```

`getEntry` should probably be `BaseElement|Element`, but it doesn't matter for now since it's private.

File: src/service/video-manager-impl.js (hunk 2 above)
Comment (alanorozco) [reply src/service/video-manager-impl.js]: Just realized this doesn't actually matter, `VideoAnalyticsEvents` is small. I feel like there are other opportunities to simplify analytics but unfortunately this isn't it.
