### PR TITLE
🏗 Replace `gulp-closure-compiler` with `google-closure-compiler`

### LINKED ISSUE #21839: gulp dist fails on Windows
## What's the issue?

**gulp dist fails on Windows because it fails to create sub directories**

The issue is that 'gulp-closure-compiler' uses 'graceful-fs' which is not capable of recursively create subdirectories in Windows
I was able to workaround the issue by manually editing **node_modules/gulp-closure-compiler.js**. 

**Code sample**
File: node_modules/gulp-closure-compiler.js
`    // Create directory for output file if it doesn't exist.
    if (opt.fileName && !fs.existsSync(path.dirname(opt.fileName))) {
      fs.mkdirSync(path.dirname(opt.fileName));
    }`

I modified the code to use mkdirp directly:
`    // Create directory for output file if it doesn't exist.
    if (opt.fileName && !fs.existsSync(path.dirname(opt.fileName))) {
      mkdirp(path.dirname(opt.fileName));
    }`

**Error message**
fs.js:1**14
    throw err;
    ^

Error: ENOENT: no such file or directory, mkdir 'build/cc/ads\inabox'
    at Object.mkdirSync (fs.js:752:3)
    at Stream.endStream (c:\src\amphtml\node_modules\gulp-closure-compiler\index.js:110:10)
    at _end (c:\src\amphtml\node_modules\through\index.js:65:9)
    at Stream.stream.end (c:\src\amphtml\node_modules\through\index.js:74:5)
    at DestroyableTransform.onend (c:\src\amphtml\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:523:10)
    at Object.onceWrapper (events.js:277:13)
    at DestroyableTransform.emit (events.js:194:15)
    at c:\src\amphtml\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:965:16
    at process._tickCallback (internal/process/next_tick.js:61:11)**

## How do we reproduce the issue?

1 - Setup a Windows machine following: https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md
2 - Build: gulp dist

## What browsers are affected?
N/A

## Which AMP version is affected?
master

##

### PR DESCRIPTION
**Pull request by rsimha**
This PR replaces `gulp-closure-compiler` (which has not received an update in 3 years) with the native `gulp` plugin that is part of `google-closure-compiler`. With this, we can do custom text replacements on `gulp.src` and pass them directly to closure compiler without having to copy the intermediate output to a temp directory.

Addresses https://github.com/ampproject/amphtml/issues/21828#issuecomment-483487677.
Partial fix for #21828
Follow up to #21830
Follow up to #16799
Fixes #21839

### CODE REVIEW

**Comment by jridgewell** [comment]
Got sourcemaps to work with the following changes. Unfortunately, it only works with multi-pass and not single-pass, because the replacements need to happen before the closure-compile to retain the appropriate input file names:

<details>

<summary>sourcemap diff</summary>

```diff
diff --git a/build-system/tasks/compile.js b/build-system/tasks/compile.js
index 9ce0aa146..21330d55b 100644
--- a/build-system/tasks/compile.js
+++ b/build-system/tasks/compile.js
@@ -27,6 +27,7 @@ const rename = require('gulp-rename');
 const replace = require('gulp-regexp-sourcemaps');
 const rimraf = require('rimraf');
 const shortenLicense = require('../shorten-license');
+const sourcemaps = require('gulp-sourcemaps');
 const {highlight} = require('cli-highlight');
 const {singlePassCompile} = require('../single-pass');
 
@@ -188,7 +189,6 @@ function compile(entryModuleFilenames, outputDir, outputFilename, options) {
     if (options.wrapper) {
       wrapper = options.wrapper.replace('<%= contents %>', '%output%');
     }
-    wrapper += '\n//# sourceMappingURL=' + outputFilename + '.map\n';
     if (fs.existsSync(intermediateFilename)) {
       fs.unlinkSync(intermediateFilename);
     }
@@ -383,7 +383,6 @@ function compile(entryModuleFilenames, outputDir, outputFilename, options) {
       // required.
       only_closure_dependencies: true,
       output_wrapper: wrapper,
-      create_source_map: intermediateFilename + '.map',
       source_map_location_mapping: '|' + sourceMapBase,
       warning_level: options.verboseLogging ? 'VERBOSE' : 'DEFAULT',
       jscomp_error: [],
@@ -425,6 +424,9 @@ function compile(entryModuleFilenames, outputDir, outputFilename, options) {
     });
 
     let stream = gulp.src(srcs, {base: '.'})
+        .pipe(sourcemaps.init({loadMaps: true}))
+        .pipe(replace(/\$internalRuntimeVersion\$/g, internalRuntimeVersion, 'runtime-version'))
+        .pipe(shortenLicense())
         .pipe(gulpClosureCompiler(compilerOptions, platformOptions))
         .on('error', function(err) {
           const {message} = err;
@@ -436,19 +438,13 @@ function compile(entryModuleFilenames, outputDir, outputFilename, options) {
     if (!argv.typecheck_only && !options.typeCheckOnly) {
       stream = stream
           .pipe(rename(outputFilename))
-          .pipe(replace(/\$internalRuntimeVersion\$/g, internalRuntimeVersion, 'runtime-version'))
-          .pipe(shortenLicense())
+          .pipe(sourcemaps.write('.'))
           .pipe(gulp.dest(outputDir))
-          .on('end', function() {
-            gulp.src(intermediateFilename + '.map')
-                .pipe(rename(outputFilename + '.map'))
-                .pipe(gulp.dest(outputDir))
-                .on('end', resolve);
-          });
+          .on('end', resolve);
     } else {
       stream = stream
-          .on('end', resolve)
-          .pipe(gulp.dest(outputDir));
+          .pipe(gulp.dest(outputDir))
+          .on('end', resolve);
     }
     return stream;
   });
```

</details>

**Comment by rsimha** [comment]
@jridgewell Nice! I've incorporated your patch and done a bunch of clean up. We no longer generate any output in `build/` or `dist/` during `gulp check-types`. Also, since sourcemaps are now directly written to `dist/`, we no longer need to write intermediate files to `build/cc/`.

File: build-system/tasks/compile.js [hunk 1]
```diff
@@ -351,100 +344,104 @@ function compile(entryModuleFilenames, outputDir, outputFilename, options) {
     }
     externs.push('build-system/amp.multipass.extern.js');
 
+    const platformOptions = {
```
Comment (jridgewell) [inline build-system/tasks/compile.js]: Nit: Add a comment

Comment (rsimha) [reply build-system/tasks/compile.js]: Done in c14604d325f1c22fdea99bcf41028b2d8a76bd84

File: build-system/single-pass.js [hunk 2]
```diff
@@ -608,6 +605,9 @@ function formatSinglePassClosureCompilerError(message) {
 }
 
 function compile(flagsArray) {
+  // Override to local closure compiler JAR
+  ClosureCompiler.JAR_PATH = require.resolve('./runner/dist/runner.jar');
```
Comment (erwinmombay) [inline build-system/single-pass.js]: what was the reason to move?

Comment (rsimha) [reply build-system/single-pass.js]: Single pass was setting the jar at the global level. I moved it to local so it doesn't leak across `gulp` tasks.

**Comment by aghassemi** [comment]
@rsimha `gulp dist` keep getting stuck on Travis after this PR. I have rerun Canary build (https://travis-ci.org/ampproject/amphtml/jobs/521047235) a few times and it does not seem budge. Same with Master.

**Comment by aghassemi** [comment]
`gulp --fortesting` also fails locally with `Compilation failed for ampcontext-v0.js:` for me.

**Comment by rsimha** [comment]
@aghassemi Thanks for the heads up. Investigating...

**Comment by rsimha** [comment]
I'm able to successfully run all `gulp dist` commands on Linux and Mac OS with this change.

**Linux (with this upgrade):** [~13 mins](https://gist.github.com/rsimha/fe3cbad85afcd0397eece957c62627fa)
**Linux (without this upgrade:** [~6 mins](https://gist.github.com/rsimha/b6d2e8514a3d50e9c2932249c91266d9)

However, as can be seen from the above logs, the upgrade has made `gulp dist` significantly slower. Let's revert to unblock `master`. I'll try to speed it up in a separate PR.

/cc @jridgewell @erwinmombay

**Comment by rsimha** [comment]
Here are some running times of `gulp dist --fortesting --noextensions` for comparison:
- With `gulp-closure-compiler` (sourcemaps and minification in one fell swoop): 1.63 min
- With `google-closure-compiler` and `gulp-sourcemaps`: 3.52 min
- With `google-closure-compiler`, but no `gulp-sourcemaps`: 2.3 min

These times become _much_ worse when all extensions are built, and _much much_ worse when run on Travis.

I'm going to try and speed things up. Failing that, we might have to abandon this PR, which makes me sad.

/cc @jridgewell @erwinmombay @dvoytenko

**Comment by ssantosms** [comment]
Agree with @rsimha 
It's unfortunate having to revert this, not only because it reverts the fix that makes it build on Windows properly, but because it removes dependency on a package that hasn't been maintained and update in a long time

File: build-system/tasks/compile.js [hunk 3]
```diff
@@ -353,98 +346,103 @@ function compile(entryModuleFilenames, outputDir, outputFilename, options) {
...
+          .pipe(gulpClosureCompiler(compilerOptions, platformOptions))
+          .on('error', handleCompilerError)
+          .pipe(nop())
+          .on('end', resolve);
+    } else {
+      return gulp.src(srcs, {base: '.'})
+          .pipe(sourcemaps.init({loadMaps: true}))
+          .pipe(replace(
+              /\$internalRuntimeVersion\$/g, internalRuntimeVersion,
+              'runtime-version'))
```
Comment (rsimha) [inline build-system/tasks/compile.js]: Bug 2: The calls to `replace` and `shortenLicense` must come _after_ closure compiler has run. The way we're doing things now, the text replacement is being done `O(N^2)` times on every input file, instead of `O(N)` times on every output file.

Comment (jridgewell) [reply build-system/tasks/compile.js]: This will break sourcemaps.

Comment (rsimha) [reply build-system/tasks/compile.js]: @jridgewell Running `replace` and `shortenLicense` before closure compiler increases compile time by 60%. Can you talk about how sourcemaps breaks? Maybe there's a way to have our cake and eat it too?

Comment (rsimha) [reply build-system/tasks/compile.js]: Figured it out offline. We can avoid the 60% slowdown by doing what I say in the top comment in this thread, and avoid the sourcemaps breakage by merging #21832.

**Comment by rsimha** [comment]
New version of this PR with fixes is available at #21900
