### PR TITLE
truncate up to new line to not cause server stack parsing to break

### LINKED ISSUE #9178: Pantheon lost error stacks
For instance, see p/2126860046192464866

Both "Parsed" and "Raw" stacks are not available. However, when I expand the first error report, I clearly see the stack in the "Report location" field:
```
u (.../r?...&s=%24b%40https%3A%2F%2Fcdn.ampproject.org%2Frtv%2F001493923946479%2Fv0.js%3A52%3A297%0AH%40https%3A%2F%2Fcdn.ampproject.org%2Frtv%2F001493923946479%2Fv0.js%3A51%3A506%0Abd%40
```

So, either Pantheon fails for some reason, or we are not feeding error stacks in correctly.

Please investigate ASAP. This is blocking PROD monitoring.

See [error.js](https://github.com/ampproject/amphtml/blob/6b68abe1f7853d2c0aac893c6045886fde0e619b/src/error.js#L366) for more details.

### PR DESCRIPTION
**Pull request by erwinmombay**
Fixes #9178

### CODE REVIEW

File: tools/errortracker/errortracker.go [hunk 1]
```diff
@@ -174,9 +175,15 @@ func handle(w http.ResponseWriter, r *http.Request) {
 		return
 	}
 
+	exception := r.URL.Query().Get("s")
+	// If format does not end with :\d+ truncate up to the last newline.
+	if !regexp.MustCompile(`:\d+\n?$`).MatchString(exception) {
+		exception = string(regexp.MustCompile(`\n.*$`).ReplaceAllString(exception, ""))
```
Comment (dvoytenko) [inline tools/errortracker/errortracker.go]: Just a sanity check, are you sure this will match the very last `\n`? I keep stumbling on those greedy/not-greedy expressions.

Comment (erwinmombay) [inline tools/errortracker/errortracker.go]: you are right, this is non greedy.. will fix

Comment (erwinmombay) [inline tools/errortracker/errortracker.go]: actually i stand corrected, retested it again and it seems to work fine.

Comment (erwinmombay) [inline tools/errortracker/errortracker.go]: screen shot 2017-05-09 at 5 02 01 pm

@dvoytenko  can you sanity check for me?

File: tools/errortracker/errortracker.go [hunk 2]
```diff
@@ -174,9 +175,15 @@ func handle(w http.ResponseWriter, r *http.Request) {
 		return
 	}
 
+	exception := r.URL.Query().Get("s")
+	// If format does not end with :\d+ truncate up to the last newline.
+	if !regexp.MustCompile(`:\d+\n?$`).MatchString(exception) {
```
Comment (jridgewell) [inline tools/errortracker/errortracker.go]: Can't have a newline.

Comment (erwinmombay) [inline tools/errortracker/errortracker.go]: got it. i was testing in node earlier and the output had newline for whatever reason

Comment (erwinmombay) [inline tools/errortracker/errortracker.go]: done.

File: tools/errortracker/errortracker.go (hunk 1 above)
Comment (dvoytenko) [inline tools/errortracker/errortracker.go]: @erwinmombay looks good
