### PR TITLE
Check that :scope selector behaves correctly.

### LINKED ISSUE #12151: amp-list inside amp-form inside amp-shadow does not work on Firefox
Using amp-list inside AMP form on Firefox does not show any data.
You can reproduce the problem by looking at:
[Favorite Button sample](https://ampbyexample.com/advanced/favorite_button/)

If you open the sample on Chrome, you should see an heart shape on which you can click to favorite content.
If you open the sample on Firefox, the heart is not visible.

@sebastianbenz FYI

### PR DESCRIPTION
**Pull request by cvializ**
Fixes #12151

Firefox does not throw when the `:scope` pseudoclass is used, but in some contexts it returns `null` incorrectly even when it should match a child element.

| Firefox (normal) | Firefox (ShadowDOM?) |
|---|---|
|screen shot 2017-12-08 at 1 16 08 pm|screen shot 2017-12-08 at 1 16 16 pm|

/cc @kul3r4

### CODE REVIEW

File: src/dom.js [hunk 1]
```diff
@@ -408,13 +408,17 @@ export function setScopeSelectorSupportedForTesting(val) {
...
+ * Test that the :scope selector is supported and behaves correctly.
  * @param {!Element} parent
  * @return {boolean}
  */
 function isScopeSelectorSupported(parent) {
+  const doc = parent.ownerDocument;
   try {
-    parent.ownerDocument.querySelector(':scope');
-    return true;
+    const testElement = doc.createElement('div');
```
Comment (aghassemi) [inline src/dom.js]: I'd add:

```
NOTE(cvializ, #12383): Firefox's implementation is incomplete, therefore we test actual functionality of `:scope` as well.
```

**Comment by aghassemi** [comment]
Good find!

File: src/dom.js (hunk 1 above)
Comment (cvializ) [reply src/dom.js]: That's a good idea!
