### PR TITLE
✅Enable skipped singlepass tests

### LINKED ISSUE #19499: 🐛withdrawRequest does not work in single pass tests
Travis runs all integration tests with normal build as well as single pass. The two integration test files using `depositRequestUrl` and `withdrawRequest` do not work when built using single pass.  We spent some time debugging this and discovered it to mocha running one version of the code, and the test itself having a different obfuscated version.

This was not obvious earlier because these tests are wrapped with `describe.configure().skipIfPropertiesObfuscated()` so they were not ever being ran with the single pass build.

The actual error occurs when looking for the xhr service which exists on the window but has a mangled name.

### PR DESCRIPTION
**Pull request by calebcordry**
closes #19499

### CODE REVIEW

File: src/service/url-replacements-impl.js [hunk 1]
```diff
@@ -128,17 +128,19 @@ export class GlobalVariableSource extends VariableSource {
...
     // Returns the host of the canonical URL for this AMP document.
-    this.set('CANONICAL_HOST', this.getDocInfoUrl_('canonicalUrl', 'host'));
+    this.set('CANONICAL_HOST', () =>
+      parseUrlDeprecated(this.getDocInfo_().canonicalUrl)['host']);
 
     // Returns the hostname of the canonical URL for this AMP document.
-    this.set('CANONICAL_HOSTNAME', this.getDocInfoUrl_('canonicalUrl',
-        'hostname'));
+    this.set('CANONICAL_HOSTNAME', () =>
+      parseUrlDeprecated(this.getDocInfo_().canonicalUrl)['hostname']);
```
Comment (erwinmombay) [inline src/service/url-replacements-impl.js]: we should be able to do `.hostname` here right? this is the Location object?

File: src/service/url-replacements-impl.js [hunk 2]
```diff
@@ -128,17 +128,19 @@ export class GlobalVariableSource extends VariableSource {
     });
 
     // Returns the canonical URL for this AMP document.
-    this.set('CANONICAL_URL', this.getDocInfoUrl_('canonicalUrl'));
+    this.set('CANONICAL_URL', () => this.getDocInfo_().canonicalUrl);
 
     // Returns the host of the canonical URL for this AMP document.
-    this.set('CANONICAL_HOST', this.getDocInfoUrl_('canonicalUrl', 'host'));
+    this.set('CANONICAL_HOST', () =>
+      parseUrlDeprecated(this.getDocInfo_().canonicalUrl)['host']);
```
Comment (zhouyx) [inline src/service/url-replacements-impl.js]: Can we not use the `parseUrlDeprecated` method, but use the url service instead.

File: src/service/url-replacements-impl.js (hunk 1 above)
Comment (zhouyx) [reply src/service/url-replacements-impl.js]: +1 and all other location object field.

Comment (calebcordry) [reply src/service/url-replacements-impl.js]: Done.

File: src/service/url-replacements-impl.js (hunk 2 above)
Comment (calebcordry) [reply src/service/url-replacements-impl.js]: Done. I assumed it was still in use for a reason, but I guess it was an oversight 🤷‍♂️

Comment (calebcordry) [reply src/service/url-replacements-impl.js]: Looks like this change broke everything. :( Working on fix.

File: test/functional/test-url-replacements.js [hunk 3]
```diff
@@ -166,6 +169,7 @@ describes.sandboxed('UrlReplacements', {}, () => {
         documentElement: {
           nodeType: /* element */ 1,
         },
+        head: document.createElement('head'),
```
Comment (lannka) [inline test/functional/test-url-replacements.js]: is this needed?

Comment (calebcordry) [reply test/functional/test-url-replacements.js]: if we don't include it this will break https://github.com/ampproject/amphtml/pull/19844/files#diff-775f4cb823bb027213fbff02cfb81778R605

File: src/service/url-replacements-impl.js [hunk 4]
```diff
@@ -575,26 +580,30 @@ export class GlobalVariableSource extends VariableSource {
...
+  }
+
+  /**
+   * Return the parsed url for doc.
+   * @param {string} url
+   * @param {boolean=} opt_nocache
+   * @return {!Location}
+   */
+  parseUrl_(url, opt_nocache) {
+    return Services.urlForDoc(this.ampdoc.getHeadNode())
```
Comment (choumx) [inline src/service/url-replacements-impl.js]: Are we sure this will resolve relative URLs in the right context for FIE? `ampdoc.getHeadNode()` will be use the parent window context, whereas `parseUrlDeprecated` uses `self.document`.

Comment (calebcordry) [reply src/service/url-replacements-impl.js]: Interesting, is there a preferred way to get the service now? I saw your change that you now need an element, and we don't have easy access to one here (that I know of).

Comment (calebcordry) [reply src/service/url-replacements-impl.js]: Actually does it even matter as we are passing the url to the `parse()` call, not relying on the service for the url.

Comment (choumx) [reply src/service/url-replacements-impl.js]: Correct, passing the element is the best way. Might require some refactoring if you want to make this change.

Comment (calebcordry) [reply src/service/url-replacements-impl.js]: Oh I see this is for the other cases, not just the new stuff.

**Comment by cramforce** [comment]
Nice one!

**Comment by zhouyx** [comment]
Thanks for the fix. I took a quick look at the variable replacement implementation, and found a very similar issue with viewer integration variables. #19966  cc @erwinmombay 

I'll take another round of look of the file and see if there are other variables that we retrieve with wrong keys in singlepass.

**Comment by calebcordry** [comment]
After chatting with @choumx I decided to go back to `parseUrlDeprecated`. The move to url service will take a bigger refactor and should be done in a separate PR. Also it sounds like FIE may get its own ampdoc at some point.

File: src/service/url-replacements-impl.js (hunk 4 above)
Comment (calebcordry) [reply src/service/url-replacements-impl.js]: changed back to `parseUrlDeprecated`.

File: test/functional/test-url-replacements.js (hunk 3 above)
Comment (calebcordry) [reply test/functional/test-url-replacements.js]: This was removed with change back to `parseUrlDeprecated`
