### PR TITLE
Fix content-type on xhr error check

### LINKED ISSUE #6172: AMP-Form: Support content-type with extra character
I am currently using App Engine's endpoint as a backend service. I would like AMPed my website.

In order for the form to show the success message, it requires `content-type:application/json`. I tried the API call from App Engine, it returns `content-type:application/json; charset=UTF-8` with response status of 200. However the form showed the error message.

Since I can't change the content-type of the App Engine's backend, is it possible that the AMP-Form can ignore the extra characters on the content-type (as long as `application/json` exist and response status of 2XX it treat the form submission as success).

Thanks a lot

### PR DESCRIPTION
**Pull request by mkhatib**
Fixes #6172

### CODE REVIEW

**Comment by mkhatib** [comment]
to/ @erwinmombay

File: src/service/xhr-impl.js [hunk 1]
```diff
@@ -412,7 +412,8 @@ export function assertSuccess(response) {
       if (isRetriable(response.status)) {
         err.retriable = true;
       }
-      if (response.headers.get('Content-Type') == 'application/json') {
+      const contentType = response.headers.get('Content-Type') || '';
+      if (contentType.split(';')[0] == 'application/json') {
```
Comment (jridgewell) [inline src/service/xhr-impl.js]: `/^application\/json($|;)/.test(contentType)`?
