### PR TITLE
🏗 Use locally built validator during `amp validate-html-fixtures`

### LINKED ISSUE #37467: 🐛 Update the `amp validate-html-fixtures` command to be friendly to new extensions
### Description

When creating a new extension it is common to introduce new validation rules with a new `protoascii` file and also add an example in our `examples` folder.  This pattern currently fails our CI pipeline checks.

`amp validate-html-fixtures` is currently run as part of the `checks` stage of our circleCI pipeline. This eventually calls the external `amphtml-validator` package https://github.com/ampproject/amphtml/blob/624997ab9bbbd839daaeb84791ad3702278239e8/build-system/tasks/validate-html-fixtures.js#L91

The problem is that this package does not know about any validation rules that have been changed since the last version of the npm package was built. Any validator rules contained in the PR will not be honored. 

Some ideas for improvement (h/t @rsimha & @alanorozco)
- We could build validator.js as part of the CI run if necessary using validator/build.py
- Maybe it can be done trivially by moving amp validate-html-fixtures from the "checks" CI job to the "validator tests" job and use the (already) built validator instead of the npm package

to/ @ampproject/wg-infra 

### Reproduction Steps

Create a new `amp-foo.protoascii` file as well as an html file in the `examples/` folder that uses this `<amp-foo>` extension. Run `amp validate-html-fixtures` and see failure.

### Relevant Logs

_No response_

### Browser(s) Affected

_No response_

### OS(s) Affected

_No response_

### Device(s) Affected

_No response_

### AMP Version Affected

_No response_

### PR DESCRIPTION
**Pull request by rsimha**
Adding new validation rules while also adding new AMP code could result in a mismatch with the existing rules in the `amphtml-validator` npm pacakge, and lead to developer friction similar to https://github.com/ampproject/amphtml/pull/37414#discussion_r791078244.

This PR updates the `amp validate-html-fixtures` task to attempt to use the locally built wasm / js validator, failing which it will default to the wasm validator from the CDN.

Right now, this will result in CI checks using the locally built js validator. When the wasm validator is added to our CI workflow in future, the task will start using it.

Fixes #37467

### CODE REVIEW

File: build-system/tasks/validate-html-fixtures.js [hunk 1]
```diff
@@ -72,13 +72,35 @@ async function getFileGroups(filesToCheck) {
...
 }
 
+/**
+ * Checks for the existence of a local wasm / js validator binary and returns
+ * its location. Defaults to the wasm binary on the CDN.
+ * @return {Promise<string>}
+ */
+async function getValidatorJs() {
+  const localWasmValidatorPath =
+    'validator/bazel-bin/cpp/engine/wasm/validator_js_bin.js';
```
Comment (rsimha) [inline build-system/tasks/validate-html-fixtures.js:82]: @antiphoton Is this the correct path? If not, do you know what it is?

Comment (antiphoton) [reply build-system/tasks/validate-html-fixtures.js:82]: Yes, this is the correct path.

File: build-system/tasks/validate-html-fixtures.js [hunk 2]
```diff
@@ -72,13 +72,35 @@ async function getFileGroups(filesToCheck) {
...
+  if (await pathExists(localWasmValidatorPath)) {
+    log('Using the', cyan('locally built wasm validator') + '...');
+    return localWasmValidatorPath;
+  }
+  if (await pathExists(localJsValidatorPath)) {
+    log('Using the', cyan('locally built js validator') + '...');
+    return localJsValidatorPath;
+  }
+  log('Using the', cyan('wasm validator from the CDN') + '...');
+  return 'https://cdn.ampproject.org/v0/validator_wasm.js'; // eslint-disable-line local/no-forbidden-terms
```
Comment (calebcordry) [inline build-system/tasks/validate-html-fixtures.js:93]: not sure where would be most appropriate but could we leave a comment about when the other validators would not be available?

Comment (rsimha) [reply build-system/tasks/validate-html-fixtures.js:98]: Added in [`19baddd` (#37569)](https://github.com/ampproject/amphtml/pull/37569/commits/19baddd84cc8579f323aa0b83970575825e35cf3).

**Review by calebcordry — APPROVED** [review]
Thanks for the fix!
