### PR TITLE
🐛Fixes error in document.contains polyfill in IE 10 (#13768)

### LINKED ISSUE #13768: Null reference error in Internet Explorer 10
## What's the issue?

When I open my AMP page in Internet Explorer 10 it doesn't fully load because of:

```
SCRIPT5007: Unable to get property 'prototype' of undefined or null reference 
v0.js, line 477 character 390
```

## How do we reproduce the issue?

1. Use code from the [Hello World](https://ampbyexample.com/playground/#url=https%3A%2F%2Fampbyexample.com%2Fintroduction%2Fhello_world%2Fsource%2F&mode=Responsive) example
2. Put it in hello-world.html
3. Run a web-server (e.g. `php -S 0.0.0.0:9000` from same directory)
4. Open http://localhost:9000/hello-world.html in IE 10

## What browsers are affected?

Internet Explorer 10 and probably 9. It's working fine in IE 11.

## Which AMP version is affected?

1519771395920

### PR DESCRIPTION
**Pull request by sryze**
In IE 10 `window.HTMLDocument` is not available, so accessing its `prototype` property gives an error.  With this patch it will fall back to using `window.Document` instead.

Fixes #13768.

### CODE REVIEW

File: src/polyfills/document-contains.js [hunk 1]
```diff
@@ -36,8 +36,9 @@ function documentContainsPolyfill(node) {
  * @param {!Window} win
  */
 export function install(win) {
-  if (!win.HTMLDocument.prototype.contains) {
-    win.Object.defineProperty(win.HTMLDocument.prototype, 'contains', {
+  const documentClass = win.HTMLDocument || win.Document;
```
Comment (nainar) [inline src/polyfills/document-contains.js]: Could you please add a comment above this indicating for any future readers the context?

**Comment by sryze** [comment]
OK, I added a comment about this.

**Comment by nainar** [comment]
Thank you! I will merge this in once Travis CI stops being flaky and timing out.
