### PR TITLE
🏗 Add specific RTV opt-in to experiments.html

### LINKED ISSUE #25205: I2I: Opt-in to Specific AMP RTV
# Background

When investigating an issue that was reported to us in the wild, once the issue is reproduced, a natural next step is to use the opt-in cookies to RC and Canary to investigate whether the issue reproduces in different versions of the AMP runtime and under various experiment configs. However, this marks the extent to which an individual can investigate in what versions and configs of AMP the issue exists.

# Overview

This I2I proposes the addition of a new version opt-in mode, to allow bisecting reported issues. With the planned future transition to nightly builds, this ability will prove indispensable for release engineers when determining whether to patch or roll back a version when an issue is found.

As Google is responsible for serving the AMP runtime, the implementation details will be mostly up to Google engineers.

# Implementation details

Add a new option to opt-in to a specific RTV number in the [experiments.html](https://cdn.ampproject.org/experiments.html) page. The page should provide a list of possible RTV numbers to prevent someone from mistyping a number. These will provide a full (15 digits) RTV. AMP RTV numbers are composed of a 2-digit number that indicates the environment (00 for canary, 01 for prod, 02 for control, 03 for RC, and 10–12 and 20–25 for various experimental builds and their control versions) and a 13-digit number indicating a specific code version (see [description of the 13-digit version number](https://github.com/ampproject/amphtml/blob/master/build-system/compile/internal-version.js#L25-L39))

image

Selecting an RTV number and clicking the button below it should opt-in the individual to that specific version, with a cookie set to expire after 1 hour. This is because the purpose of this opt-in is to bisect issues, and so the short expiration is meant to avoid a situation where an individual is “stuck” on an old version of AMP for a long period.

# Security considerations

Unless protected against, a malicious actor can perform an XSS attack to arbitrarily set this cookie to a broken AMP version with security/privacy bugs. The opt-in mechanism should be designed with this type of attack in mind.

Alternatively, we can restrict the cookie to only allow opting-in to a very narrow set of versions, e.g., a “Monday through Friday cookie”. This can reduce the incentive for such an attack as the opportunity for specifying a bad version is greatly reduced. The downside of this is that it costs us the freedom in terms of debugging abilities, especially when attempting to locate a long-standing issue that was only recently discovered.

Another alternative is to use an OS level proxy to replace any arbitrary calls to `https://cdn.ampproject.org/*` to chosen RTV-locked equivalents, `https://cdn.ampproject.org/rtv/<rtv-number>/*`. This is only useful for OSes where such a proxy exists and is easily installable, e.g., this could be difficult in mobile devices. Depending on the proxy software, this also does not necessarily come with an auto-expiration policy which could accidentally lock a developer into one RTV number.

/cc @ampproject/wg-infra

### PR DESCRIPTION
**Pull request by danielrozenberg**
Fixes #25205

image

image

Tag-along change:
* Renamed dev/rc to experimental/beta (UI-facing change only, no backend change here)

### CODE REVIEW

File: tools/experiments/experiments.js [hunk 1]
```diff
@@ -138,6 +143,34 @@ function build() {
   } else {
     redirect.setAttribute('hidden', '');
   }
+
+  const rtvInput = document.getElementById('rtv');
+  const rtvButton = document.getElementById('rtv-submit');
+  rtvInput.addEventListener('input', () => {
+    rtvButton.disabled = !(
```
Comment (rcebulko) [inline tools/experiments/experiments.js]: Could you use `<input pattern="^(\\d{15})?$">` here instead of implementing this test in a listener?

File: tools/experiments/experiments.js [hunk 2]
```diff
@@ -138,6 +143,34 @@ function build() {
...
+      rtvInput.value == '' || RTV_PATTERN.test(rtvInput.value)
+    );
+    rtvButton.textContent = rtvInput.value == '' ? 'opt-out' : 'opt-in';
```
Comment (rcebulko) [inline tools/experiments/experiments.js]: Nit: this can just be `rtvInput ? 'opt-in' : 'opt-out'`

File: tools/experiments/experiments.js [hunk 3]
```diff
@@ -138,6 +143,34 @@ function build() {
...
+  });
+  rtvButton.addEventListener('click', () => {
+    if (rtvInput.value == '') {
```
Comment (rcebulko) [inline tools/experiments/experiments.js]: Does the field default to the currently opted-in RTV value? My concern is that if it's initially empty and someone hits enter, would it opt them out unintentionally?

File: tools/experiments/experiments.js [hunk 4]
```diff
@@ -138,6 +143,34 @@ function build() {
...
+      showConfirmation_(
+        'Do you really want to opt OUT of specific RTV',
```
Comment (rcebulko) [inline tools/experiments/experiments.js]: Nit: add a `?` somewhere :stuck_out_tongue:

File: tools/experiments/experiments.js (hunk 3 above)
Comment (rcebulko) [reply tools/experiments/experiments.js]: Also nit: `if (!rtvInput)`

File: tools/experiments/experiments.js [hunk 5]
```diff
@@ -138,6 +143,34 @@ function build() {
...
+        `Do you really want to opt into the specific RTV ${rtvInput.value}?`,
+        setAmpCanaryCookie_.bind(null, rtvInput.value)
+      );
+    }
+  });
+
+  if (isExperimentOn_(RTV_EXPERIMENT_ID)) {
+    rtvInput.value = getCookie(window, 'AMP_CANARY');
+    rtvInput.dispatchEvent(new Event('input'));
+    document.getElementById('rtv-details').open = true;
```
Comment (rcebulko) [inline tools/experiments/experiments.js]: What is this doing?

File: tools/experiments/experiments.js [hunk 6]
```diff
@@ -348,7 +388,7 @@ function getAmpConfig() {
   xhr.send(null);
   return promise
     .then(text => {
-      const match = text.match(/self\.AMP_CONFIG=([^;]+)/);
+      const match = text.match(/self\.AMP_CONFIG=({.+?})/);
```
Comment (rcebulko) [inline tools/experiments/experiments.js]: What is this syntax?

Comment (rsimha) [inline tools/experiments/experiments.js]: For posterity, what was wrong with the previous regex?

File: tools/experiments/experiments.html [hunk 7]
```diff
@@ -218,6 +245,20 @@ <h2>Release channels</h2>
 
   <section class="content">
     <table id="channels-table" border=1></table>
+    <details id="rtv-details">
+      <summary>Advanced</summary>
+      <p>
+        You can also opt-in to any RTV manually using this form.
```
[the remark this answers is not in the document]
Comment (rcebulko) [reply tools/experiments/experiments.html]: Follow-up: `/in to/into/s`

[the remark this answers is not in the document]
Comment (rsimha) [reply tools/experiments/experiments.html]: Re: follow up. The verb phrase here is "opt in", not "opt", and therefore, "in to" is [recommended](https://english.stackexchange.com/questions/422848/opt-into-vs-opt-in-to) over "into".

File: tools/experiments/experiments.html [hunk 8]
```diff
@@ -218,6 +245,20 @@ <h2>Release channels</h2>
...
+      </p>
+      <p>
+        <em>Warning:</em> This is an advanced setting. It should not be used by AMP publishers, rather it is intended
+        for debugging the AMP runtime itself. To opt-out clear the RTV in the input field.
+      </p>
+      <div>
+        <input id="rtv" placeholder="E.g., 011912312359590" maxlength="15" type="text">
+        <button id="rtv-submit" disabled>opt-in</button>
```
Comment (estherkim) [inline tools/experiments/experiments.html]: Style button to be consistent with other buttons

File: tools/experiments/experiments.js [hunk 9]
```diff
@@ -51,6 +55,7 @@ let ExperimentDef;
  */
 const CANARY_EXPERIMENT_ID = 'dev-channel';
 const RC_EXPERIMENT_ID = 'rc-channel';
```
Comment (rsimha) [inline tools/experiments/experiments.js]: These two lines should eventually be changed to:

```js
const EXPERIMENTAL_CHANNEL_ID = 'experimental-channel';
const BETA_CHANNEL_ID = 'beta-channel';
```

If it's not easy here, separate PR is okay.

File: tools/experiments/experiments.js [hunk 10]
```diff
@@ -51,6 +55,7 @@ let ExperimentDef;
...
+const RTV_EXPERIMENT_ID = 'rtv-channel';
```
Comment (rsimha) [inline tools/experiments/experiments.js]: Based on the above comment, change `RTV_EXPERIMENT_ID` to `RTV_CHANNEL_ID`.

File: tools/experiments/experiments.js (hunk 1 above)
Comment (danielrozenberg) [reply tools/experiments/experiments.js]: I believe this only takes effect if the <input> is inside a <form> that is being submitted? In any case, I use the pattern for other decisions so I would still need to define it in the JS

File: tools/experiments/experiments.js (hunk 2 above)
Comment (danielrozenberg) [reply tools/experiments/experiments.js]: No, but I can do `rtvInput.value ? 'opt-in' : 'opt-out';` :)

File: tools/experiments/experiments.js (hunk 3 above)
Comment (danielrozenberg) [reply tools/experiments/experiments.js]: > Does the field default to the currently opted-in RTV value?

Yes

> My concern is that if it's initially empty and someone hits enter, would it opt them out unintentionally?

There is a confirmation popup

File: tools/experiments/experiments.js (hunk 4 above)
Comment (danielrozenberg) [reply tools/experiments/experiments.js]: Done

File: tools/experiments/experiments.js (hunk 5 above)
Comment (danielrozenberg) [reply tools/experiments/experiments.js]: If you are already opted-in to a specific RTV it opens the section (as if you clicked on the right-pointing triangle)

File: tools/experiments/experiments.js (hunk 6 above)
Comment (danielrozenberg) [reply tools/experiments/experiments.js]: It's a mistake 🙃 it should've been `(\{.+?\})` - fixed.

If you're asking what's `.+?` it means any character (`.`) repeated one or more times (`.+`), but as few matches as possible (`.+?`) to continue to match the rest of the expression. Basically:

```javascript
const str = 'abcd_ efgh_';
str.match(/(.+)_/);  // entire match is 'abcd_ efgh_' and group 1 is 'abcd_ efgh'
str.match(/(.+?)_/); // entire match is 'abcd_' and group 1 will be 'abcd'
```

File: tools/experiments/experiments.html [hunk 11]
```diff
@@ -218,6 +245,20 @@ <h2>Release channels</h2>
...
   <section class="content">
     <table id="channels-table" border=1></table>
+    <details id="rtv-details">
+      <summary>Advanced</summary>
+      <p>
+        You can also opt-in to any RTV manually using this form.
+      </p>
+      <p>
+        <em>Warning:</em> This is an advanced setting. It should not be used by AMP publishers, rather it is intended
+        for debugging the AMP runtime itself. To opt-out clear the RTV in the input field.
```
[the remark this answers is not in the document]
Comment (danielrozenberg) [reply tools/experiments/experiments.html]: Done

File: tools/experiments/experiments.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (danielrozenberg) [reply tools/experiments/experiments.js]: Done

File: tools/experiments/experiments.js [hunk 12]
```diff
@@ -138,6 +143,34 @@ function build() {
...
+    rtvButton.disabled = !(
+      rtvInput.value == '' || RTV_PATTERN.test(rtvInput.value)
+    );
+    rtvButton.textContent = rtvInput.value == '' ? 'opt-out' : 'opt-in';
+  });
+  rtvButton.addEventListener('click', () => {
+    if (rtvInput.value == '') {
+      showConfirmation_(
+        'Do you really want to opt OUT of specific RTV',
+        setAmpCanaryCookie_.bind(null, AMP_CANARY_COOKIE.DISABLED)
```
[the remark this answers is not in the document]
Comment (danielrozenberg) [reply tools/experiments/experiments.js]: This is how `showConfirmation_` and `setAmpCanaryCookie_` are called together in other places in the code so I figured consistency wins

File: tools/experiments/experiments.js [hunk 13]
```diff
@@ -138,6 +143,34 @@ function build() {
...
+      );
+    } else if (RTV_PATTERN.test(rtvInput.value)) {
+      showConfirmation_(
+        `Do you really want to opt into the specific RTV ${rtvInput.value}?`,
```
[the remark this answers is not in the document]
Comment (danielrozenberg) [reply tools/experiments/experiments.js]: Done

File: tools/experiments/experiments.js [hunk 14]
```diff
@@ -237,24 +270,31 @@ function updateExperimentRow(experiment) {
...
-    return getCookie(window, 'AMP_CANARY') == AMP_CANARY_COOKIE.RC;
+  switch (id) {
+    case CANARY_EXPERIMENT_ID:
+      return getCookie(window, 'AMP_CANARY') == AMP_CANARY_COOKIE.CANARY;
+    case RC_EXPERIMENT_ID:
+      return getCookie(window, 'AMP_CANARY') == AMP_CANARY_COOKIE.RC;
+    case RTV_EXPERIMENT_ID:
+      return RTV_PATTERN.test(getCookie(window, 'AMP_CANARY'));
+    default:
+      return isExperimentOn(window, /*OK*/ id);
```
[the remark this answers is not in the document]
Comment (danielrozenberg) [reply tools/experiments/experiments.js]: Correct, I'll have a follow-up change here once the google-internal change is done

File: tools/experiments/experiments.js (hunk 6 above)
Comment (rcebulko) [reply tools/experiments/experiments.js]: LOL nope I was asking about the braces haha

Comment (danielrozenberg) [reply tools/experiments/experiments.js]: When we build locally with a `--config`, v0.js starts:
```javascript
self.AMP_CONFIG||(self.AMP_CONFIG={...});/*AMP_CONFIG*/
```

Whereas when we don't add a config, but rather prepend it as part of our release process, it starts:
```javascript
self.AMP_CONFIG={...};
```

The existing regex catches only the 2nd syntax, the new regex catches both. This assuming that none of the configs are objects themselves but are always strings or numbers :)

Comment (rsimha) [reply tools/experiments/experiments.js]: I see. We should eventually eliminate the difference between the two workflows. #24817 was file to track this.

Meanwhile, the regex change works for now.

File: tools/experiments/experiments.html (hunk 8 above)
Comment (danielrozenberg) [reply tools/experiments/experiments.html]: Done

File: tools/experiments/experiments.js (hunk 9 above)
Comment (danielrozenberg) [reply tools/experiments/experiments.js]: Done

File: tools/experiments/experiments.js (hunk 10 above)
Comment (danielrozenberg) [reply tools/experiments/experiments.js]: Done

File: tools/experiments/experiments.html (hunk 7 above)
[the remark this answers is not in the document]
Comment (rsimha) [reply tools/experiments/experiments.html]: I don't see this change. Missing commits?

File: tools/experiments/experiments.js [hunk 15]
```diff
@@ -237,24 +268,31 @@ function updateExperimentRow(experiment) {
...
 function setAmpCanaryCookie_(cookieState) {
-  const validUntil =
-    cookieState != AMP_CANARY_COOKIE.DISABLED
-      ? Date.now() + COOKIE_MAX_AGE_MS
-      : 0;
+  let validUntil = 0;
+  if (RTV_PATTERN.test(cookieState)) {
+    validUntil = Date.now() + RTV_COOKIE_MAX_AGE_MS;
+  } else if (cookieState != AMP_CANARY_COOKIE.DISABLED) {
+    validUntil = Date.now() + COOKIE_MAX_AGE_MS;
```
Comment (rsimha) [inline tools/experiments/experiments.js]: If someone enters an RTV that doesn't match the correct 13 digit format, it will fall through here. Should there be a separate error handling case before this `else` block?

Comment (danielrozenberg) [reply tools/experiments/experiments.js]: This method gets called post-validation, at this point it only receives one of the hard-coded states, or a 15-digit RTV

File: tools/experiments/experiments.html (hunk 7 above)
[the remark this answers is not in the document]
Comment (danielrozenberg) [reply tools/experiments/experiments.html]: I'm confused. What should be the change?

File: tools/experiments/experiments.html [hunk 16]
```diff
@@ -112,6 +127,21 @@
...
+      width: calc(100% - 150px);
+      padding: 10px;
+    }
+
+    button#rtv-submit {
+      background: #aaa;
+      margin: 5px;
+    }
+
+    button#rtv-submit[disabled] {
```
Comment (rcebulko) [inline tools/experiments/experiments.html]: Nit: drop the element selectors, ID is far more selective anyway (and it would still work if buttons were replaced with anchors or something else)

File: tools/experiments/experiments.html [hunk 17]
```diff
@@ -218,6 +248,20 @@ <h2>Release channels</h2>
 
   <section class="content">
     <table id="channels-table" border=1></table>
+    <details id="rtv-details">
+      <summary>Advanced</summary>
+      <p>
+        You can also opt-in to any RTV manually using this form.
```
Comment (rcebulko) [inline tools/experiments/experiments.html]:
```suggestion
        You can manually opt into a previously released RTV using this form.
```

File: tools/experiments/experiments.html (hunk 7 above)
[the remark this answers is not in the document]
Comment (rcebulko) [reply tools/experiments/experiments.html]: See suggestion below

File: tools/experiments/experiments.js [hunk 18]
```diff
@@ -348,7 +386,7 @@ function getAmpConfig() {
   xhr.send(null);
   return promise
     .then(text => {
-      const match = text.match(/self\.AMP_CONFIG=([^;]+)/);
+      const match = text.match(/self\.AMP_CONFIG=(\{.+?\})/);
```
Comment (rcebulko) [inline tools/experiments/experiments.js]: What exactly is this trying to do that it's regex-matching JS? Not that it should be fixed in this PR, but curious

File: tools/experiments/experiments.html (hunk 7 above)
[the remark this answers is not in the document]
Comment (rsimha) [reply tools/experiments/experiments.html]: > I'm confused. What should be the change?

Just this change from my original comment.

> Suggested rephrasing (changed noun "opt-in" to verb "opt in"):
> > You can manually opt in to a previously released RTV using this form.

File: tools/experiments/experiments.js (hunk 18 above)
Comment (danielrozenberg) [reply tools/experiments/experiments.js]: Read the `AMP_CONFIG`, which is a JavaScript object (which happens to be JSON-compatible), so that it can see which experiments you're opted-in to

File: tools/experiments/experiments.html (hunk 16 above)
Comment (danielrozenberg) [reply tools/experiments/experiments.html]: Done

File: tools/experiments/experiments.html (hunk 7 above)
[the remark this answers is not in the document]
Comment (rsimha) [reply tools/experiments/experiments.html]: > See suggestion below

Almost there, but needs another change. See https://github.com/ampproject/amphtml/pull/26434#discussion_r369292390.
