### PR TITLE
Fix getComputedStyle=null issue on Firefox

### LINKED ISSUE #3096: getComputedStyle returns null on firefox inside iframe with display:none
`f is null` error in this code: https://gist.github.com/erwinmombay/889e83a7cdc65605c51b2a0c262a8ac0#file-f-js-L15

caused by firefox bug https://bugzilla.mozilla.org/show_bug.cgi?id=548397

seems to have been introduced in 1460655576651

### PR DESCRIPTION
**Pull request by dvoytenko**
Closes #3096.

### CODE REVIEW

File: test/functional/test-fixed-layer.js [hunk 1]
```diff
@@ -353,6 +353,26 @@ describe('FixedLayer', () => {
       expect(state['F1'].fixed).to.equal(false);
     });
 
+    it('should tollerate getComputedStyle = null', () => {
```
Comment (erwinmombay) [inline test/functional/test-fixed-layer.js]: tolerate

**Comment by erwinmombay** [comment]
@dvoytenko LGTM, minor nit

**Comment by cramforce** [comment]
LGTM

LOL #everythingisbroken
