### PR TITLE
✨ 🏗 Add a script to enable a pre-push hook that tests local changes before `git push`

### LINKED ISSUE #15369: Add support for developers to quickly test their changes locally before pushing them to GitHub
## What's the issue?

Travis is getting congested with builds containing linting errors. This is making it more difficult to get changes published.

Idea: Add an optional (disabled by default) `pre-push` hook that lints only the files change in a commit. If there is a failure, the push doesn't continue until the linting errors are resolved. This would allow frequent contributors to be more confident their changes will not fail during linting on Travis.

### PR DESCRIPTION
**Pull request by rsimha**
This PR does the following:
1. Adds a default pre-push hook for AMP at `build-system/default-pre-push`, which runs:
    - `gulp bundle-size` (if `dist/v0.js` was built) (~2 sec)
    - `gulp lint --local-changes` (~3 sec)
    - `gulp test --local-changes` (~5 sec)
2. Adds a script called `build-system/enable-git-pre-push.sh`, which when run, will install a shortcut to `build-system/default-pre-push` at `.git/hooks/pre-push`
3. Once enabled, whenever a developer runs `git push`, the pre-push hook will first run, and if it fails, the push is canceled
4. Makes minor updates to `gulp test --local-changes` and `gulp bundle-size` so they work well as pre-push hooks

**Usage:**
- To opt in, simply run `./build-system/enable-git-pre-push.sh` from the root directory.
- Every call to `git push` will first run `.git/hooks/pre-push`
- The total time to run all pre-push hooks is ~10 seconds
- To skip the hook, run `git push --no-verify`
- To remove the hook, simply delete `.git/hooks/pre-push`

Note: We use a level of indirection instead of copying `build-system/default-pre-push` to `.git/hooks/pre-push` so that the default behavior can be changed at a later time, and developers who have opted in don't have to reinstall the hook to get the new behavior.

Fixes #15369

### CODE REVIEW

**Comment by kristoferbaxter** [comment]
Might be a good idea to include the directions to enable these push hooks within the contributing guides.

File: build-system/default-pre-push [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+
+echo $(GREEN "Running") $(CYAN "$GULP_LINT_LOCAL")
+eval $GULP_LINT_LOCAL || exit 1
+echo -e "\n"
+
+echo $(GREEN "Running") $(CYAN "$GULP_TEST_LOCAL")
+eval $GULP_TEST_LOCAL || exit 1
+echo -e "\n"
+
+echo $(GREEN "Done with") $(CYAN "pre-push") $(GREEN "hooks. Pushing commits to GitHub...")
```
Comment (kristoferbaxter) [inline build-system/default-pre-push]: I believe this hook will run even when pushing to other locations than Github. Is there something I'm missing?

File: build-system/enable-git-pre-push.sh [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+
+echo $(YELLOW "-----------------------------------------------------------------------------------------------------------------")
+echo $(GREEN "Running") $(CYAN $SCRIPT)
+echo $(GREEN "This script does the following:")
+echo $(GREEN "  1. If already present, makes a backup of") $(CYAN "$PRE_PUSH_DEST") $(GREEN "at") $(CYAN "$PRE_PUSH_BACKUP")
+echo $(GREEN "  2. Creates a new file") $(CYAN "$PRE_PUSH_DEST") $(GREEN "which calls") $(CYAN "$PRE_PUSH_SRC")
+echo $(GREEN "  3. With this,")  $(CYAN "git push") $(GREEN "will first run the checks in") $(CYAN "$PRE_PUSH_SRC")
+echo $(GREEN "  4. You can edit") $(CYAN "$PRE_PUSH_DEST") $(GREEN "to change the pre-push hooks that are run before") $(CYAN "git push")
+echo $(GREEN "  5. To skip the hook, run") $(CYAN "git push --no-verify") $(GREEN "or") $(CYAN "git push -n")
+echo $(GREEN "  6. To remove the hook, delete the file") $(CYAN "$PRE_PUSH_DEST")
```
Comment (kristoferbaxter) [inline build-system/enable-git-pre-push.sh]: Thanks for adding this description to the installation script. This should reduce the number of questions about the hook.

File: build-system/default-pre-push [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+# distributed under the License is distributed on an "AS-IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the license.
+#
+# This script adds a pre-push hook to .git/hooks/, which runs some basic tests
+# before running "git push".
+#
+# Default pre-push hook for AMPHTML. To enable, run:
+#     "./build-system/enable-git-pre-push.sh"
```
Comment (kristoferbaxter) [inline build-system/default-pre-push]: Out of curiosity, what the plan for Windows developers?

File: build-system/default-pre-push (hunk 1 above)
Comment (rsimha) [reply build-system/default-pre-push]: The script gets installed (via a shortcut) to `~src/amphtml/.git/hooks/pre-push`. Doesn't this mean it gets run only when you push to `ampproject/amphtml`?

File: build-system/default-pre-push (hunk 3 above)
Comment (rsimha) [reply build-system/default-pre-push]: I believe Windows users install `git` in order to develop AMP, and therefore, should already be able to run scripts such as this one. I'd be willing to try this if you have a Windows machine. In any case, since this isn't a required part of the development flow, we can always update it at a later time.

File: build-system/default-pre-push (hunk 1 above)
Comment (kristoferbaxter) [reply build-system/default-pre-push]: The `remote` isn't necessarily on Github. I'd call it good enough though unless it's confusing to others.

File: build-system/default-pre-push (hunk 3 above)
Comment (kristoferbaxter) [reply build-system/default-pre-push]: Perhaps leave a comment or something similar about Windows development.

**Comment by kristoferbaxter** [comment]
Waiting to add it to dev docs makes complete sense until we're certain it works as intended. Good idea!

File: build-system/default-pre-push (hunk 3 above)
Comment (rsimha) [reply build-system/default-pre-push]: Will do this when I add it to the Dev docs. Shouldn't be long before we know if this works or not!

**Comment by rsimha** [comment]
@kristoferbaxter This is now merged.

**Step 1:** Run `./build-system/enable-git-pre-push.sh`
**Step 2:** Let me know if this works for you

:)

**Comment by kristoferbaxter** [comment]
./build-system/enable-git-pre-push.sh: line 23: realpath: command not found

screen shot 2018-05-23 at 12 36 29 pm

**Comment by kristoferbaxter** [comment]
Linting error did fail the push.

screen shot 2018-05-23 at 12 39 43 pm

**Comment by rsimha** [comment]
@kristoferbaxter I've sent out #15535 to fix the `realpath` issue.
