### PR TITLE
🏗 Fetch and print sauce labs status before connecting

### LINKED ISSUE #20488: When sauce connect fails on Travis, print the latest status (with a link)
This is how we indicate that the sauce_connect script failed.

https://github.com/ampproject/amphtml/blob/719b0822ddcdbf42c769331c6844ea84ad4da84d/build-system/sauce_connect/start_sauce_connect.sh#L78-L85

Let's print the latest status from here: https://status.saucelabs.com/

### PR DESCRIPTION
**Pull request by rsimha**
We've had trouble with Sauce Labs of late. This PR prints the current service status before connecting, so we have a better idea of why failures occur.

Documentation:
Status URL: [link](https://wiki.saucelabs.com/display/DOCS/Platform+Information+Methods#PlatformInformationMethods-GetSauceLabsStatus)
REST API: [link](https://wiki.saucelabs.com/display/DOCS/Accessing+the+API)

Fixes #20488
Partial fix for #20492

### CODE REVIEW

File: build-system/sauce_connect/start_sauce_connect.sh [hunk 1]
```diff
@@ -31,6 +35,24 @@ READY_FILE="sauce_connect_ready"
 READY_DELAY_SECS=60
 LOG_PREFIX=$(YELLOW "start_sauce_connect.sh")
 
+# Check the status of the Sauce Labs service
+echo "$LOG_PREFIX Fetching current Sauce Labs service status from $(CYAN "$STATUS_URL")..."
+SAUCE_STATUS="$(curl -s "$AUTHENTICATED_STATUS_URL")"
```
Comment (danielrozenberg) [inline build-system/sauce_connect/start_sauce_connect.sh]: What happens if `curl` returns a non-zero exit status? Does the script move on or does it crash?
(I tested, and the returned HTTP code doesn't change the exit code, but there could be other reasons why `curl` could fail - e.g., if the domain name cannot be resolved for whatever reason)

File: build-system/sauce_connect/start_sauce_connect.sh [hunk 2]
```diff
@@ -31,6 +35,24 @@ READY_FILE="sauce_connect_ready"
...
+SERVICE_OPERATIONAL="$(echo "$SAUCE_STATUS" | jq '.service_operational')"
```
Comment (danielrozenberg) [inline build-system/sauce_connect/start_sauce_connect.sh]: `jq` is a missing dependency on my workstation. Add it to `devDependencies`?

Comment (rsimha) [reply build-system/sauce_connect/start_sauce_connect.sh]: It's shipped with the default Travis VM

File: build-system/sauce_connect/start_sauce_connect.sh (hunk 1 above)
Comment (rsimha) [reply build-system/sauce_connect/start_sauce_connect.sh]: Good point. Just checked. The script moves on after printing the error message from curl. This should be sufficient for our purpose.

File: build-system/sauce_connect/start_sauce_connect.sh (hunk 2 above)
Comment (danielrozenberg) [reply build-system/sauce_connect/start_sauce_connect.sh]: It could still break the flow for people running `gulp pr-check` locally who have a sauce_labs key

Comment (rsimha) [reply build-system/sauce_connect/start_sauce_connect.sh]: That workflow isn't supported, since this script is Linux-only.

We could change the local flow to install the platform appropriate binary, at which point `jq` can be added to the deps. (Out of scope here.)

Comment (danielrozenberg) [reply build-system/sauce_connect/start_sauce_connect.sh]: Fair enough

File: build-system/sauce_connect/start_sauce_connect.sh [hunk 3]
```diff
@@ -19,8 +19,12 @@
 
 CYAN() { echo -e "\033[0;36m$1\033[0m"; }
 YELLOW() { echo -e "\033[1;33m$1\033[0m"; }
+GREEN() { echo -e "\033[0;32m$1\033[0m"; }
+RED() { echo -e "\033[0;31m$1\033[0m"; }
 
 SC_VERSION="sc-4.5.3-linux"
+AUTHENTICATED_STATUS_URL="https://$SAUCE_USERNAME:$SAUCE_ACCESS_KEY@saucelabs.com/rest/v1/info/status"
```
Comment (estherkim) [inline build-system/sauce_connect/start_sauce_connect.sh]: Is there any security concern using $SAUCE_USERNAME and $SAUCE_ACCESS_KEY here? If so, it looks like the `STATUS_URL` without any authentication also returns a JSON of the status which could suffice.

Comment (rsimha) [reply build-system/sauce_connect/start_sauce_connect.sh]: The unauthenticated URL is rate limited. The link in the description has more details.

Comment (rsimha) [reply build-system/sauce_connect/start_sauce_connect.sh]: https://wiki.saucelabs.com/display/DOCS/Rate+Limits+for+the+Sauce+Labs+REST+API
