### PR TITLE
Fixing hidden infinite loop in the build pending and attach cycle

### LINKED ISSUE #3354: Build Resource Infinite Loop
We currently have a hidden infinite loop:

When building `<amp-lightbox>`, we [append each child](https://github.com/ampproject/amphtml/blob/master/extensions/amp-lightbox/0.1/amp-lightbox.js#L55-L57) to a new container element. This causes a us to call `attachedCallback` on that child, which [adds](https://github.com/ampproject/amphtml/blob/d90cfc89b48c5aba822f5a2ca099397d7db5fc65/src/custom-element.js#L639) it the list of resources we need to track.

When we add that element to our list of resources, we add it to a list of unbuilt elements (this is our first problem, but we'll come back to it). When we add to the unbuilt elements list, we [try to build](https://github.com/ampproject/amphtml/blob/d90cfc89b48c5aba822f5a2ca099397d7db5fc65/src/service/resources-impl.js#L398) any unbuilt resources.

And here's the infinite loop. Notice that we're _still_ trying to build our `<amp-lightbox>`. Which means the `<amp-lightbox>` is still "unbuilt", and it's still in that list of unbuilt elements we're should try to build. So after adding that child element to the list of unbuilts, we'll loop through all of our unbuilts to build them. And lo and behold, one of them is the `<amp-lightbox>`. So we'll build it again, causing us to append all children to a container, causing the `attachedCallback`, causing the child it to be added to our unbuilts again. And again. And again. And again.

Easy Fix
------------

Splice the current element before trying to build it. This is not a good solution.

Better Fix
-------------

Use a `currentTryingToBuildOurUnbuilts` mutex. When we enter `#buildReadyResources_`, check if it's true. If it is, return early. If not, set it to true, then do the loop. After the loop, set it to false.

Why's this better? We'll avoid a huge call stack. Let it unwind after the `attachedCallback` until we get back to the build loop. Because we're [not caching the unbuilt's length](https://github.com/ampproject/amphtml/blob/d90cfc89b48c5aba822f5a2ca099397d7db5fc65/src/service/resources-impl.js#L410), we'll eventually get to the newly added unbuilt element.

- - -

Remember that first problem I mentioned above? It's that we sometimes wrap our children in a container. But those children may have already been built. But since we fire another `attachedCallback`, we'll add them to the unbuilts again, and try to build again. It's cool to add them to the list again, but we should make sure they're really unbuilt before trying to [`#build`](https://github.com/ampproject/amphtml/blob/d90cfc89b48c5aba822f5a2ca099397d7db5fc65/src/service/resources-impl.js#L1664-L1667) them again.

### PR DESCRIPTION
**Pull request by mkhatib**
Fixes #3354 

Tested the test case added before and after the test and it does catches the problem before the change (by disconnecting karma) and passes afterwards.

cc/ @jridgewell @erwinmombay 

💯 Thanks to @jridgewell for the awesome quick debugging and the solution proposals in #3354!

### CODE REVIEW

File: src/service/resources-impl.js [hunk 1]
```diff
@@ -407,15 +410,22 @@ export class Resources {
...
   buildReadyResources_() {
+    // Avoid cases where elements add more elements inside of them
+    // and cause an infinite loop of building - see #3354 for details.
+    if (this.isCurrentlyBuildingPendingResources_) {
+      return;
+    }
     for (let i = 0; i < this.pendingBuildResources_.length; i++) {
       const resource = this.pendingBuildResources_[i];
       if (this.documentReady_ || hasNextNodeInDocumentOrder(resource.element)) {
+        this.isCurrentlyBuildingPendingResources_ = true;
```
Comment (jridgewell) [inline src/service/resources-impl.js]: Do this outside the loop. 😛

Comment (mkhatib) [inline src/service/resources-impl.js]: 💃 Done

File: src/service/resources-impl.js [hunk 2]
```diff
@@ -407,6 +410,12 @@ export class Resources {
    * @private
    */
   buildReadyResources_() {
+    // Avoid cases where elements add more elements inside of them
+    // and cause an infinite loop of building - see #3354 for details.
+    if (this.isCurrentlyBuildingPendingResources_) {
+      return;
+    }
+    this.isCurrentlyBuildingPendingResources_ = true;
```
Comment (cramforce) [inline src/service/resources-impl.js]: Wrap the following in `try {…} finally {}`. Otherwise an exception can make this stuck forever.

Comment (cramforce) [inline src/service/resources-impl.js]: Also test these states in some of the existing tests and maybe throw one in that throws an exception.

Comment (mkhatib) [inline src/service/resources-impl.js]: That sounds good. Does this mean if one resource keeps failing to build we're going to be stuck and not able to build all other pending resources? 

Should we also catch a failed build and remove resource from pending resources?

Comment (cramforce) [inline src/service/resources-impl.js]: With the try-finally we should not get stuck. Maybe I misunderstand the question.

Comment (mkhatib) [inline src/service/resources-impl.js]: The try-finally you were suggesting was for the the full for-loop right? But if the `resource.build()` step keeps failing we're never taking the resource from the `this.pendingBuildResources_` array. So next time the loop is going to run same thing going to happen, no?

Comment (cramforce) [inline src/service/resources-impl.js]: I see. Make it so that doesn't happen :)

Comment (mkhatib) [inline src/service/resources-impl.js]: Done. Had to break the method into multiple methods to make it a bit more readable.

Let me know what do you think and if I should add some more test cases.

**Comment by mkhatib** [comment]
PTAL

File: src/service/resources-impl.js [hunk 3]
```diff
@@ -407,18 +410,54 @@ export class Resources {
...
+   * Builds a resource if it's ready.
+   * @param {!Resource} resource
+   * @return {boolean} Whether the resource is ready.
+   * @private
+   */
+  buildResourceIfReady_(resource) {
+    if (this.documentReady_ || hasNextNodeInDocumentOrder(resource.element)) {
+      try {
+        resource.build();
+      } finally {
```
Comment (cramforce) [inline src/service/resources-impl.js]: Why the finally? This would still throw.

File: src/service/resources-impl.js [hunk 4]
```diff
@@ -407,18 +410,54 @@ export class Resources {
...
+
+  /** @private */
+  buildReadyResourcesUnsafe_() {
     for (let i = 0; i < this.pendingBuildResources_.length; i++) {
       const resource = this.pendingBuildResources_[i];
-      if (this.documentReady_ || hasNextNodeInDocumentOrder(resource.element)) {
-        resource.build();
-        // Resource is built remove it from the pending list and step back
-        // one in the index to account for the removed item.
+      try {
```
Comment (jridgewell) [inline src/service/resources-impl.js]: We shouldn't need another try catch (or another below it) here. Just splice before calling `#build`.

Comment (mkhatib) [inline src/service/resources-impl.js]: I was thinking we should also protect against the ready if-clause check failing, but this shouldn't fail and if it does I think we'll be masking a problem. Will remove this try-catch.

File: src/service/resources-impl.js (hunk 3 above)
Comment (mkhatib) [inline src/service/resources-impl.js]: Dropped. I seem to have been very sleepy yesterday... Will revert back some of these changes.

**Comment by mkhatib** [comment]
Thanks for the reviews. PTAL

File: src/service/resources-impl.js [hunk 5]
```diff
@@ -407,13 +410,29 @@ export class Resources {
...
     for (let i = 0; i < this.pendingBuildResources_.length; i++) {
       const resource = this.pendingBuildResources_[i];
-      if (this.documentReady_ || hasNextNodeInDocumentOrder(resource.element)) {
-        resource.build();
-        // Resource is built remove it from the pending list and step back
-        // one in the index to account for the removed item.
+      if (this.documentReady_ ||
+          hasNextNodeInDocumentOrder(resource.element)) {
+        // Remove resource before build to remove it from the pending list
+        // in either case the build succeeed or throws an error.
```
Comment (jridgewell) [inline src/service/resources-impl.js]: Thinking about it, is it possible for `#build` to throw? We have a [try-catch](https://github.com/ampproject/amphtml/blob/master/src/service/resources-impl.js#L1668-L1674) already.

Comment (mkhatib) [inline src/service/resources-impl.js]: Yeah you're right. I kinda skipped this `resource.build` method and was looking at the `element.build`.

This might just to be safe not to get stuck in that state of deadlocking. But @cramforce what do you think?

Comment (cramforce) [inline src/service/resources-impl.js]: Slightly confused. I think the CL is fine like it is :)

Comment (dvoytenko) [inline src/service/resources-impl.js]: Yes, we do try/catch already. But if it's critical for this loop - we can add another one.

Comment (jridgewell) [inline src/service/resources-impl.js]: https://github.com/ampproject/amphtml/pull/3355#discussion_r64851246 is unnecessary because the loop can never throw.

File: src/service/resources-impl.js [hunk 6]
```diff
@@ -407,13 +410,29 @@ export class Resources {
    * @private
    */
   buildReadyResources_() {
+    // Avoid cases where elements add more elements inside of them
```
Comment (dvoytenko) [inline src/service/resources-impl.js]: Should we go ahead and modify the code that puts the element into the queue if it has already been built? E.g.

```
this.pendingBuildResources_.push(resource);
this.buildReadyResources_();
```

Becomes 
```
if (resource.isBuilt())  {
  this.pendingBuildResources_.push(resource);
  this.buildReadyResources_();
}
```

I know it's pretty benign to try to build again, but why do more work if we don't have to.

File: src/service/resources-impl.js [hunk 7]
```diff
@@ -407,13 +410,29 @@ export class Resources {
...
+    // and cause an infinite loop of building - see #3354 for details.
+    if (this.isCurrentlyBuildingPendingResources_) {
```
Comment (dvoytenko) [inline src/service/resources-impl.js]: This has a problem. If we shortcircuiting "may be we can build" signal - we need to reschedule it for later. E.g. consider this:

"A" is being build which adds "B". "B" is put in the queue and it's ready to be built, but its cycle ignored due to `this.isCurrentlyBuildingPendingResources_ == true`. Once "A" is finished building, "B" is still in the queue and now there's no signal to build it again, so it stays in the queue unbuilt.

One way we can deal with this is by using increment instead of boolean for `isCurrentlyBuildingPendingResources_ `. E.g.:

```
this.buildingPendingResourcesIndex_ = 0;

buildReadyResources_() {
  this.buildingPendingResourcesIndex_++;
  if (this.buildingPendingResourcesIndex_ > 1) {
   return;
  }
  try {
    this.buildReadyResourcesUnsafe_();
  } finally {
    this.buildingPendingResourcesIndex_--;
  }
  if (this.buildingPendingResourcesIndex_ > 0) {
    this.buildingPendingResourcesIndex_ = 0;
    this.buildReadyResources_();
  }
}
```

Makes sense?

Comment (jridgewell) [inline src/service/resources-impl.js]: That shouldn't be the case since the [for-loop](https://github.com/ampproject/amphtml/pull/3355/files#diff-80b9cea934a00a64f15d14cb656dfad4R428) will not stop until everything that's in the queue (even things added after the for-loop starts, because we're doing `i < .pending.length` not `i < cachedLengthVar`) has been iterated over.

File: test/functional/test-resources.js [hunk 8]
```diff
@@ -2600,11 +2600,52 @@ describe('Resources.add', () => {
...
+        // Simulate parent elements adding children elements to simulate
+        // the infinite loop of building pending resources and make sure
+        // that we're handling it well.
+        child1BuildSpy();
+        resources.pendingBuildResources_.push(newResource);
+        resources.buildReadyResources_();
+      };
+      resources.buildReadyResources_();
+      expect(child1BuildSpy.called).to.be.true;
+      expect(child2.build.called).to.be.false;
```
Comment (jridgewell) [inline test/functional/test-resources.js]: We should verify that `newChild` has been built as well.

File: src/service/resources-impl.js (hunk 6 above)
Comment (mkhatib) [inline src/service/resources-impl.js]: Yeah I am with doing this actually - just not add it at all.

File: src/service/resources-impl.js (hunk 7 above)
Comment (mkhatib) [inline src/service/resources-impl.js]: @dvoytenko what @jridgewell said. Let me know if there still an issue here?

Comment (mkhatib) [inline src/service/resources-impl.js]: I've also tested that the new added resource is being built as suggested by @jridgewell below.

File: test/functional/test-resources.js (hunk 8 above)
Comment (mkhatib) [inline test/functional/test-resources.js]: Done!

File: src/service/resources-impl.js (hunk 6 above)
Comment (mkhatib) [inline src/service/resources-impl.js]: Done.

File: src/service/resources-impl.js (hunk 5 above)
Comment (mkhatib) [inline src/service/resources-impl.js]: I am cool with having another try-catch, but I agree with @jridgewell that might not be necessary. Let me know if you guys feel strongly about adding it back.

**Comment by mkhatib** [comment]
PTAL

File: src/service/resources-impl.js [hunk 9]
```diff
@@ -392,7 +395,7 @@ export class Resources {
         // Build resource immediately, the document has already been parsed.
         resource.build();
         this.schedulePass();
-      } else {
+      } else if (!resource.element.isBuilt()) {
```
Comment (jridgewell) [inline src/service/resources-impl.js]: We already have the `element` variable.

File: src/service/resources-impl.js (hunk 7 above)
Comment (dvoytenko) [inline src/service/resources-impl.js]: Yeah, this will work. But it's rather cryptic and fragile. We already considered once to reverse traversal from the end of the array. At the very least, let's comment above the for-loop to make it super clear that this cannot be cached.

Also, I have some concerns about optimizers. I see this pattern very common in our binaries and assume that this is the minifier work, but I could be wrong, of course:
```
for (var d = 0, e = a.length; d < e; d++)
```

Comment (mkhatib) [inline src/service/resources-impl.js]: hmmm. Not sure about the optimizers but yeah if it gets translated to this then we'd have the problem you mentioned. If we're worried this could actually happen, I can go ahead and use your suggestion of using a counter instead of a boolean?

File: src/service/resources-impl.js (hunk 5 above)
Comment (dvoytenko) [inline src/service/resources-impl.js]: Let's skip try/catch.

File: src/service/resources-impl.js (hunk 7 above)
Comment (dvoytenko) [inline src/service/resources-impl.js]: There might be other options to make sure of this, such as while-loop. Or we can have `buildReadyResourcesUnsafe_` call itself like this:
```
buildReadyResourcesUnsafe_() {
  let count = this.pendingBuildResources_.length;
  for (let i = 0; i < this.pendingBuildResources_.length; i++) {
    ...
    ...
    this.pendingBuildResources_.splice(i--, 1);
    count--;
    resource.build();
  }
  if (this.pendingBuildResources_.length > count) {
    this.buildReadyResourcesUnsafe_();
  }
}
```

Or maybe we can find another way (I don't really like recursion here). But I think it should be explicit since we explicitly ignoring build signal in a mutex.

Comment (jridgewell) [inline src/service/resources-impl.js]: Optimizers shouldn't touch it due to http://mrale.ph/blog/2014/12/24/array-length-caching.html. Confirming with closure's output:

```js
window.a=[1,2,3];window.test=function(){for(var c=window.a,b=0;b<c.length;b++)console.log(c[b])};
```

The test @mkhatib added should save us from our own changes though, like iterating in reverse.

Comment (mkhatib) [inline src/service/resources-impl.js]: Awesome. Thanks @jridgewell. Proceeding with leaving the for-loop as is and added a comment to explain that resources will get a chance to be built.

File: src/service/resources-impl.js (hunk 5 above)
Comment (mkhatib) [inline src/service/resources-impl.js]: Skipped.

File: src/service/resources-impl.js (hunk 9 above)
Comment (mkhatib) [inline src/service/resources-impl.js]: Done.

File: src/service/resources-impl.js (hunk 7 above)
Comment (dvoytenko) [inline src/service/resources-impl.js]: Cool. If we can confirm - let's keep it then. We may want to double-check by building dist binaries for this PR. @mkhatib could you please triple-check?

Comment (mkhatib) [inline src/service/resources-impl.js]: Yes can confirm this is currently the compiled CDN version of amp
```javascribt
P.prototype.buildReadyResources_ = function() {
    for (var a = 0; a < this.pendingBuildResources_.length; a++) {
        var b = this.pendingBuildResources_[a],
            c;
        if (!(c = this.documentReady_)) a: {
            c = b.element;do
                if (c.nextSibling) {
                    c = !0;
                    break a
                }
            while (c = c.parentNode);
            c = !1
        }
        c && (b.build(), this.pendingBuildResources_.splice(a--, 1))
    }
};
```

**Comment by mkhatib** [comment]
PTAL

**Comment by jridgewell** [comment]
LGTM.

**Comment by cramforce** [comment]
LGTM

**Comment by dvoytenko** [comment]
LGTM
