### PR TITLE
Ignore actions on disabled form controls

### LINKED ISSUE #10642: tap-events trigger although button is disabled
I have a `<button>` that is disabled but the `on="tap:..."` is triggered if the button **has a child-component** - not if it is only containing text.

    <button disabled on="tap:AMP.setState({visible: !visible})">
      <p>Toggle text (disabled not working)</p>
    </button>

Made a JSFiddle demoing it: http://jsbin.com/loyexarifo/1/edit?html,output

AMP version: 1500510703681

### PR DESCRIPTION
**Pull request by robinpokorny**
The action on a [disabled](https://www.w3.org/TR/html5/forms.html#concept-fe-disabled) form control is ignored during the action lookup on the tree.

  * When a `button` has action `event1` and is *disabled*, click on this button is blocked by DOM, click on a children element is not. This change prevents `event1` from firing.
  * A `button` inside a disabled `fieldset` has to be considered *disabled*. (This is why `:disabled` pseudo-class was used, since e.g. `el.disabled` does not take this into account.)

Potential problems:
  * Does not fix the problem on IE8 (and maybe others). I went with a permissive approach: rather allow action on a wrong place than cancel it on a correct place. (*enabled* means it does not match `:disabled`, cf. `:enabled` or `:not(:disabled)`)
  * Action propagation is not stopped, the event can fire on an ancestor. This is related to previous, it is difficult to reliably mark an element as *disabled* cross-platform.

cc: @choumx 
Fixes #10642

### CODE REVIEW

File: src/service/action-impl.js [hunk 1]
```diff
@@ -492,7 +496,8 @@ export class ActionService {
     let n = target;
     while (n) {
       const actionInfos = this.matchActionInfos_(n, actionEventType);
-      if (actionInfos) {
+      const isEnabled = !matches(n, DISABLED_PSEUDOCLASS_);
```
Comment (stryju) [inline src/service/action-impl.js]: I bet there's a more "elegant" solution to this ;-)

Comment (robinpokorny) [inline src/service/action-impl.js]: There could be, sure, but I would be very surprised since I tried a few of them. This is a native API that accesses the browser-computed value.

Compare with jQuery code: https://github.com/jquery/jquery/blob/2d4f53416e5f74fa98e0c1d66b6f3c285a12f0ce/external/sizzle/dist/sizzle.js#L463-L517 and https://github.com/jquery/jquery/blob/2d4f53416e5f74fa98e0c1d66b6f3c285a12f0ce/external/sizzle/dist/sizzle.js#L1709-L1771

File: src/service/action-impl.js [hunk 2]
```diff
@@ -492,7 +496,8 @@ export class ActionService {
     let n = target;
     while (n) {
       const actionInfos = this.matchActionInfos_(n, actionEventType);
-      if (actionInfos) {
```
Comment (jridgewell) [inline src/service/action-impl.js]: We can early `continue` if there are not `actionInfos`.

File: src/service/action-impl.js (hunk 1 above)
Comment (jridgewell) [inline src/service/action-impl.js]: This should only be called on Form controls.

Comment (dvoytenko) [inline src/service/action-impl.js]: I think we should just restrict this to `element.disabled` property where it's available. I.e. `element.disabled === true`. Looks like all browsers we support also support this property.

File: src/service/action-impl.js (hunk 2 above)
Comment (robinpokorny) [inline src/service/action-impl.js]: @jridgewell We can. But does it help?

It seems that everybody is a bit scared of `el.matches()`. Is there a reason it should not be reliable and fast? And this specific selector is a simple one, just a pseudo-class the browser has already computed itself (for CSS and JS behaviour).

Also, do we really save much (if anything) if we first test the element is a form control?

File: src/service/action-impl.js (hunk 1 above)
Comment (robinpokorny) [inline src/service/action-impl.js]: @dvoytenko, `el.disabled` is indeed supported but it does not indicate if the element is **actually disabled** (a term from [specs](https://www.w3.org/TR/html5/disabled-elements.html#concept-element-disabled)). For that one can use `:disabled` or compute it themself by traversing the tree up.

File: src/service/action-impl.js (hunk 2 above)
Comment (jridgewell) [inline src/service/action-impl.js]: Not scared of it, but there's no reason to call it if we already know we won't match.

Comment (robinpokorny) [inline src/service/action-impl.js]: That was not to targeted to this comment 😉 I'll add the early exit.

File: src/service/action-impl.js (hunk 1 above)
Comment (dvoytenko) [inline src/service/action-impl.js]: @robinpokorny Hmm, I think I'm missing the point. E.g. in my quick tests:

```
// Start with:
// Markup: <button disabled></button>
button.disabled === true

// Update property:
button.disabled = false
// Now:
// Markup: <button></button> ("disabled" attribute removed)
button.disabled === false

// Add attribute:
button.setAttribute('disabled', '');
// Now:
// Markup: <button disabled></button>
button.disabled === true
```

Isn't this exactly what we want?

Comment (jridgewell) [inline src/service/action-impl.js]: Disabled property doesn't reflect a parent `<fieldset>` being disabled.

```html
<fieldset disabled>
  <button>
</fieldset>
```

Comment (dvoytenko) [inline src/service/action-impl.js]: I see. That's crappy. But would it make more to do `closest(':disabled')` for X where `X.disabled !== undefined`

Comment (robinpokorny) [inline src/service/action-impl.js]: It can be any ancestor fieldset, unfortunately.

Comment (stryju) [inline src/service/action-impl.js]: @dvoytenko is right, `closest(':disabled')` should work, no?
`disabled` is inherited only for elements in the tree of the disabled element

**Comment by robinpokorny** [comment]
What is improved:

  - `isEnabled` was moved to DOM module (with tests)
  - It first checks the (everywhere supported) `el.disabled` and only if it is falsey it performs the `matches`
  - If there are no `actionInfos`, `isEnabled` is not called (as @jridgewell suggested)

Questions:
  - IE8 can have false positives, is that a problem?
  - Now all elements are checked, it could be restricted only to form controls and `fieldset`s. However, I am not sure how effectively identify them and if it would actually improve performance.

File: src/service/action-impl.js (hunk 1 above)
Comment (dvoytenko) [inline src/service/action-impl.js]: WAT!?

File: src/dom.js [hunk 3]
```diff
@@ -827,3 +830,15 @@ export function isFullscreenElement(element) {
...
+/**
+ * Returns true if node is not disabled.
+ *
+ * IE8 can return false positives, see {@link matches}.
+ * @param {!Element} element
+ * @return {boolean}
+ * @see https://www.w3.org/TR/html5/forms.html#concept-fe-disabled
+ */
+export function isEnabled(element) {
+  return !(element.disabled || matches(element, DISABLED_PSEUDOCLASS_));
```
Comment (dvoytenko) [inline src/dom.js]: FWIW, I'm not a big fan of constants that redirect CSS names and identifiers. I'd much rather have `matches(element, ':disabled')` inlined.

**Comment by choumx** [comment]
Nice work @robinpokorny! Thanks for your ongoing contributions.
