### PR TITLE
[amp-story-player] 🐛 Fixes firefox bug

### LINKED ISSUE #27538: [amp-story-player] Stories don't load in Firefox
## What's the issue?

The amp-story-player spinner spins forever and the story doesn't load. The error reported in the console is:

```
Error: failed to call initLogConstructor log.js:845:14
    buildCallback log.js:845
    loadPlayers amp-story-player-manager.js:104
    onload amp-story-player.js:21
```

## How do we reproduce the issue?

Embed a story in a page using the `amp-story-player` and open the page in Firefox. Example: https://story.tappable.dev/embed/stay-cultured-while-at-home

## What browsers are affected?

Firefox v73 and v74

## Which AMP version is affected?

amp-story-player is pretty new, so I'm guessing all of them.

### PR DESCRIPTION
**Pull request by Enriqe**
Fixes  #27538

When calling `applySandbox()`, `devAssert()` was being called since one of the flags in the sandbox of the iframe isn't allowed in firefox. And since `devAssert()` hasn't been initialized, it was throwing an error. Calling `initLogConstructor()` initializes it.

### CODE REVIEW

File: src/amp-story-player-impl.js [hunk 1]
```diff
@@ -133,7 +134,8 @@ export class AmpStoryPlayer {
 
   /** @public */
   buildCallback() {
-    this.stories_ = toArray(this.element_.querySelectorAll('a'));
+    initLogConstructor();
+    this.stories_ = toArray(this.querySelectorAll('a'));
```
Comment (gmajoulet) [inline src/amp-story-player-impl.js:138]: Shouldn't this be `this.element_` since we reverted the custom element PR?

File: src/amp-story-player-impl.js [hunk 2]
```diff
@@ -133,7 +134,8 @@ export class AmpStoryPlayer {
 
   /** @public */
   buildCallback() {
-    this.stories_ = toArray(this.element_.querySelectorAll('a'));
+    initLogConstructor();
```
Comment (gmajoulet) [inline src/amp-story-player-impl.js:137]: Does it need to be executed as many times as we have players? If not, can we move it to another file?

File: src/amp-story-player-impl.js (hunk 1 above)
Comment (Enriqe) [reply src/amp-story-player-impl.js]: Yes, the merge conflict messed it up. Fixed it.

File: src/amp-story-player-impl.js (hunk 2 above)
Comment (Enriqe) [reply src/amp-story-player-impl.js]: Moved it to the manager.

**Comment by Enriqe** [comment]
+ @danielrozenberg for OWNERS approval
