### PR TITLE
🏗🗑 Remove asynchronous amp-video-service experiment

### LINKED ISSUE #13955: Cleanup `video-service` experiment
`video-service` flags the use of a new implementation of the current [`VideoManager`](https://github.com/ampproject/amphtml/blob/a1b7ab690312bf3432e84abc39af4993ae44758b/src/service/video-manager-impl.js). 

Will be ramped up to 100% and then removed.

### LINKED ISSUE #20800: Removed tests are being looked up by Travis
I intentionally removed (#20792) a couple of tests and Travis is looking for them:

```
[17:06:48] INFO: Determining which unit tests to run...
[17:07:23] INFO: Running the following unit tests:
[17:07:23] extensions/amp-video-service/0.1/test/test-amp-video-service.js
[17:07:23] test/unit/test-video-autoplay.js
[17:07:23] Webserver started at http://localhost:8081
[17:07:23] Started test responses server on localhost:8081
[17:07:24] Running tests locally...
[17:07:29] Transforming tests with browserify...
...................................................................................................................................................
[17:07:41] Done. Running tests...
[17:07:42] ERROR: Zero tests detected by Karma. Something went wrong.
```

The tests it's trying to run are the tests I removed.

/to @rsimha @danielrozenberg @erwinmombay 
/cc @ampproject/wg-infra

### PR DESCRIPTION
**Pull request by alanorozco**
Closes #13955. Replacement for #19836.

Also fixes #20800, a test infra issue where removed test files would be looked up.

## Size reduction samples

- `amp-video`: from `12765` to `10672` bytes (16.39% reduction)
- `amp-video-iframe`: from `12267` to `9710` bytes (20.84% reduction)
- `amp-youtube`: from `12557` to `9980` bytes (20.52% reduction)
- `amp-ima-video`: from `14700` to `12914` bytes (12.14% reduction)
- etc.

### CODE REVIEW

File: build-system/tasks/runtime-test/helpers.js [hunk 1]
```diff
@@ -192,10 +192,14 @@ function unitTestsToRun(unitTestPaths) {
   }
 
   filesChanged.forEach(file => {
+    if (!fs.existsSync(file)) {
+      log(yellow('SKIP:'), 'Skipping removed file', file);
```
Comment (rsimha) [inline build-system/tasks/runtime-test/helpers.js]: This change works. For consistency though, change the logging statement to:
```
if (!process.env.TRAVIS) {
  log(green('INFO:'), 'Skipping', cyan(file), 'because it was deleted');
}
```

File: build-system/tasks/runtime-test/helpers.js [hunk 2]
```diff
@@ -192,10 +192,16 @@ function unitTestsToRun(unitTestPaths) {
   }
 
   filesChanged.forEach(file => {
+    if (!fs.existsSync(file)) {
+      if (!process.env.TRAVIS) {
+        log(green('INFO:'), 'Skipping', cyan(file), 'because it was deleted');
+      }
+      return;
```
Comment (danielrozenberg) [inline build-system/tasks/runtime-test/helpers.js]: nit (feel free to ignore if you just want to get this in) - since this is one of those long "if/else" functions, you can remove the "return" statement and change the next conditional to be an "else if" instead

Comment (alanorozco) [reply build-system/tasks/runtime-test/helpers.js]: Personal preference is to always favor guard clauses but I'll keep consistency here ;)
