### PR TITLE
🐛Remove empty file objects from native form data.

### LINKED ISSUE #18022: Submitting amp-form via action-xhr with empty input[type=file] fails in safari 11
## What's the issue?

Submitting amp-form via action-xhr with empty input[type=file] fails in safari 11

Link to corresponding bug in Webkit:
https://bugs.webkit.org/show_bug.cgi?id=184490

## How do we reproduce the issue?

http://jsbin.com/tutevodeha/1/

1. Open http://jsbin.com/tutevodeha/1/ in Safari 11.1
2. Submit form without uploading file
3. Request fails after timeout

## What browsers are affected?

Safari 11, mobile Safari iOS 11

----------------------------------------------

As suggested in https://stackoverflow.com/questions/49614091/safari-11-1-ajax-xhr-form-submission-fails-when-inputtype-file-is-empty, possible workaround could be detecting and removing empty file input values from FormData before sending it to server

### PR DESCRIPTION
**Pull request by cvializ**
Fixes #18022

/to @nainar @aghassemi

### CODE REVIEW

File: test/functional/test-form-data-wrapper.js [hunk 1]
```diff
@@ -24,25 +24,27 @@ describes.realWin('FormDataWrapper', {}, env => {
   describe('entries', () => {
     let nativeEntries;
     let nativeDelete;
+
```
Comment (nainar) [inline test/functional/test-form-data-wrapper.js]: Spurious change

File: test/functional/test-form-data-wrapper.js [hunk 2]
```diff
@@ -24,25 +24,27 @@ describes.realWin('FormDataWrapper', {}, env => {
...
     const scenarios = [{
       description: 'when native `entries` is not available',
 
       beforeEach() {
-        nativeEntries = FormData.prototype.entries;
-        nativeDelete = FormData.prototype.delete;
+        nativeEntries = env.win.FormData.prototype.entries;
```
Comment (nainar) [inline test/functional/test-form-data-wrapper.js]: Is this addition of `env.win` due to you being the first to touch a file in a long time?

Comment (cvializ) [reply test/functional/test-form-data-wrapper.js]: Maybe, I added `env.win` so the test uses the `FormData` reference local to the iframed test code, instead of being referenced across the iframe boundary. This makes the test more realistic to actual usage, and can prevent bugs.

Comment (nainar) [reply test/functional/test-form-data-wrapper.js]: Makes sense to me then. :)

**Comment by cvializ** [comment]
Thanks for the review @nainar!

File: src/form-data-wrapper.js [hunk 3]
```diff
@@ -121,11 +122,23 @@ class NativeFormDataWrapper {
   constructor(opt_form) {
     /** @private @const {!FormData} */
     this.formData_ = new FormData(opt_form);
+
+    if (opt_form) {
+      iterateCursor(opt_form.elements, input => {
+        if (input.type == 'file' && input.files.length == 0) {
+          this.formData_.delete(input.name);
```
Comment (aghassemi) [inline src/form-data-wrapper.js]: I'm worried this might be a breaking change if server expected `name` to be present for optional file input. 

Can we instead of removing it, make it whatever Chrome sends as the value of the name when dealing with empty files?

Comment (cvializ) [reply src/form-data-wrapper.js]: I think that's a better call than what this PR currently does. I found someone else's workaround here and I think this PR should use the same strategy of a `File` with an empty `Blob` backing it.

Comment (aghassemi) [reply src/form-data-wrapper.js]: interesting solution. If issue is very specific to iOS 11 (fixed in 12?) let's also guard it to just iOS and 11 (or at least to just iOS)

Comment (cvializ) [reply src/form-data-wrapper.js]: Sounds good, that should reduce risk

File: src/form-data-wrapper.js [hunk 4]
```diff
@@ -144,6 +161,41 @@ class NativeFormDataWrapper {
   }
 }
 
+/**
+ * iOS 11 has a bug when submitting empty file inputs.
+ * This works around the bug by replacing the empty files with Blob objects.
+ */
+class Ios11NativeFormDataWrapper extends NativeFormDataWrapper {
```
Comment (aghassemi) [inline src/form-data-wrapper.js]: 💯
