### PR TITLE
Hide placeholder when the ad fallback is shown

### LINKED ISSUE #2345: Placeholder and Fallback overlapping
In the `examples/ads` The Doubleclick no ad with placeholder and fallback (screenshot below) fails to hide placeholder after falling back. I understand that the expected behavior is that the placeholder would be hidden after we fallback.

screen shot 2016-02-29 at 12 50 22 pm

### PR DESCRIPTION
**Pull request by mkhatib**
Fixes #2345

### CODE REVIEW

File: test/functional/test-amp-ad.js [hunk 1]
```diff
@@ -291,6 +291,32 @@ function tests(name, installer) {
...
+          ad.appendChild(fallback);
+          return ad;
+        }).then(ad => {
+          const placeholderEl = ad.querySelector('[placeholder]');
+          sandbox.stub(
+              ad.implementation_, 'deferMutate', function(callback) {
+                callback();
+              });
+          ad.implementation_.noContentHandler_();
+          expect(placeholderEl.classList.contains('amp-hidden')).to.be.true;
```
Comment (erwinmombay) [inline test/functional/test-amp-ad.js]: could you add an assert of when it was visible

**Comment by erwinmombay** [comment]
@mkhatib lgtm, after minor ask.

File: test/functional/test-amp-ad.js (hunk 1 above)
Comment (mkhatib) [inline test/functional/test-amp-ad.js]: Done!
