### PR TITLE
Implement fixed transfer layer for shadow embed mode

### LINKED ISSUE #16755: Reimplement viewport implementation as a shadow root
https://medium.com/@dvoytenko/amp-ios-scrolling-redo-2-the-shadow-wrapper-approach-experimental-3362ed3c2fa2

### PR DESCRIPTION
**Pull request by dvoytenko**
Closes #16755.

Refactoring is done to make this implementation possible. The transfer layer is extracted from FixedLayer class into a separate interface and two implementations provided: the current body-based, and the new shadow-based.

### CODE REVIEW

File: src/service/fixed-layer.js [hunk 1]
```diff
@@ -686,116 +856,69 @@ export class FixedLayer {
...
-    }
+  /** @override */
+  setVisible(visible) {
+    setStyle(this.layer_, 'visibility', visible ? 'visible' : 'hidden');
   }
-}
 
+  /** @override */
+  update() {
+    // Nothing to do.
```
Comment (jridgewell) [inline src/service/fixed-layer.js]: Do we not need to do the same non-inherited CSS syncing?

File: src/service/fixed-layer.js [hunk 2]
```diff
@@ -686,116 +856,69 @@ export class FixedLayer {
...
- *   zIndex: string,
- * }}
- */
-let ElementStateDef;
+    dev().fine(TAG, 'transfer to fixed:', fe.id, fe.element);
+    user().warn(TAG, 'In order to improve scrolling performance in Safari,' +
+        ' we now move the element to a fixed positioning layer:', fe.element);
+
+    // If never been transfered before: create and configure the slot.
+    if (!fe.slot) {
```
Comment (jridgewell) [inline src/service/fixed-layer.js]: Is a new slot necessary for every fixed element? Or could we just share a single slot? Chrome, at least, allows multiple elements in the same slot.

File: src/service/viewport/viewport-binding-ios-embed-sd.js [hunk 3]
```diff
@@ -284,7 +284,7 @@ export class ViewportBindingIosEmbedShadowRoot_ {
 
   /** @override */
   requiresFixedLayerTransfer() {
-    return false;
+    return true;
```
Comment (jridgewell) [inline src/service/viewport/viewport-binding-ios-embed-sd.js]: 😢

File: src/service/fixed-layer.js (hunk 2 above)
Comment (dvoytenko) [reply src/service/fixed-layer.js]: OMG! This is amazing! Had no idea. Works very well.

File: src/service/fixed-layer.js (hunk 1 above)
Comment (dvoytenko) [reply src/service/fixed-layer.js]: No, it's now the responsibility of the viewport, not the transfer layer.

File: src/service/fixed-layer.js (hunk 2 above)
Comment (dvoytenko) [reply src/service/fixed-layer.js]: Done

File: src/service/fixed-layer.js [hunk 4]
```diff
@@ -617,19 +613,177 @@ export class FixedLayer {
...
+ * }}
+ */
+let ElementStateDef;
+
+
+/**
+ * The contract for transfer layer.
+ * @interface
+ */
+class TransferLayerDef {
```
[the remark this answers is not in the document]
Comment (dvoytenko) [reply src/service/fixed-layer.js]: No, anything that's not directly referenced in JS syntax has to have "Def". Since this name is only referenced in closure's `@interface {...}`, eslint does not understand those comments and reports the name as unused. That's the only reason we are using "Def" suffix for - they are all whitelisted against eslint.

File: src/service/fixed-layer.js [hunk 5]
```diff
@@ -617,19 +613,177 @@ export class FixedLayer {
...
+ *   top: string,
+ *   zIndex: string,
+ * }}
+ */
+let ElementStateDef;
+
+
+/**
+ * The contract for transfer layer.
+ * @interface
```
[the remark this answers is not in the document]
Comment (dvoytenko) [reply src/service/fixed-layer.js]: I changed this to just return `getRoot()` to avoid this duplication.

**Comment by dvoytenko** [comment]
@jridgewell @choumx changes done: ptal.
