### PR TITLE
🐛Fixed Analytics Visible Trigger with the Intersection Observer Polyfill

### LINKED ISSUE #18972: amp-analytics visible trigger does not function properly on Safari
the visible trigger on Safari is based on an IntersectionObserverPolyfill, which has limitation on detecting non-scroll triggered visibility change. For example, when an element's visibility is toggled via amp-bind.

We could leverage MutationObserver (which is [well supported](https://caniuse.com/#feat=mutationobserver)) to increase the coverage. 

This is a blocker for Fandango to launch their AMP integration, before we can offer a better analytics solution for single page app #18949.

/cc @zhouyx

### PR DESCRIPTION
**Pull request by torch2424**
closes #18972

This does the following:

* Creates an example in `test/manual` to display the bug in safari.
* Fixes a bug with `intersectionRatio()` to check for a divide by zero.
* Adds a mutation observer to trigger events on `class` and `style` attribute changes.

# Example Screenshot

*Look for the `imagevisible` request in the network tab*

screen shot 2018-10-29 at 1 30 54 pm
screen shot 2018-10-29 at 1 31 00 pm

### CODE REVIEW

File: src/intersection-observer-polyfill.js [hunk 1]
```diff
@@ -273,6 +286,19 @@ export class IntersectionObserverPolyfill {
...
 
+
+    // Add a mutation observer to tick ourself
+    if (!this.mutationObserver_) {
+      this.viewport_ = Services.viewportForDoc(element);
+      this.mutationObserver_ = new MutationObserver(
+          this.handleMutationObserverNotification_.bind(this)
+      );
+      this.mutationObserver_.observe(element.ownerDocument, {
+        attributeFilter: ['class', 'style', 'hidden'],
```
Comment (lannka) [inline src/intersection-observer-polyfill.js]: this filter might not cover all the visibility change

File: src/intersection-observer-polyfill.js [hunk 2]
```diff
@@ -384,7 +421,15 @@ export class IntersectionObserverPolyfill {
  * @return {number}
  */
 function intersectionRatio(smaller, larger) {
-  return (smaller.width * smaller.height) / (larger.width * larger.height);
+  const smallerBoxArea = smaller.width * smaller.height;
+  const largerBoxArea = larger.width * larger.height;
+
+  // Check for a divide by zero
+  if (largerBoxArea === 0) {
```
Comment (lannka) [inline src/intersection-observer-polyfill.js]: prefer ternary operator here.

File: src/intersection-observer-polyfill.js [hunk 3]
```diff
@@ -286,6 +312,9 @@ export class IntersectionObserverPolyfill {
     for (let i = 0; i < this.observeEntries_.length; i++) {
       if (this.observeEntries_[i].element === element) {
         this.observeEntries_.splice(i, 1);
+        if (this.observeEntries_.length <= 0) {
+          this.disconnect();
```
Comment (jridgewell) [inline src/intersection-observer-polyfill.js]: `disconnect` isn't entirely correct here, since it's API is defined by `Service`, not the InOb Polyfill.

Please add a `disconnectMutationObserver_` method.

File: src/intersection-observer-polyfill.js [hunk 4]
```diff
@@ -273,6 +286,19 @@ export class IntersectionObserverPolyfill {
...
     }
 
+
+    // Add a mutation observer to tick ourself
+    if (!this.mutationObserver_) {
+      this.viewport_ = Services.viewportForDoc(element);
+      this.mutationObserver_ = new MutationObserver(
+          this.handleMutationObserverNotification_.bind(this)
+      );
+      this.mutationObserver_.observe(element.ownerDocument, {
```
Comment (jridgewell) [inline src/intersection-observer-polyfill.js]: Use the element's ampdoc's document, not the element's `ownerDocument`.

File: src/intersection-observer-polyfill.js [hunk 5]
```diff
@@ -375,16 +404,33 @@ export class IntersectionObserverPolyfill {
     changeEntry.target = element;
     return changeEntry;
   }
+
+  /**
+   * Handle Mutation Oberserver events
+   * @private
+   */
+  handleMutationObserverNotification_() {
+    this.tick(this.viewport_.getRect());
```
Comment (jridgewell) [inline src/intersection-observer-polyfill.js]: This is gonna fire a lot. `FixedLayer` is getting by with [checking](https://github.com/ampproject/amphtml/blob/master/src/service/fixed-layer.js#L208-L215) if a hidden attribute is changed, not _any_ attribute.

File: src/intersection-observer-polyfill.js (hunk 3 above)
Comment (lannka) [reply src/intersection-observer-polyfill.js]: this.disconnect() call seems not needed here

File: src/intersection-observer-polyfill.js (hunk 5 above)
Comment (lannka) [reply src/intersection-observer-polyfill.js]: visibility can be toggled by attributes other than `hidden`, for example an arbitrary attribute that has CSS selector with `display: none` on it.

Comment (torch2424) [reply src/intersection-observer-polyfill.js]: In my testing, this was only called on page load, and after all bind changes had resolved. But I'll go ahead, and add a throttle 😄

File: src/intersection-observer-polyfill.js [hunk 6]
```diff
@@ -273,6 +285,19 @@ export class IntersectionObserverPolyfill {
       }
     }
 
+
+    // Add a mutation observer to tick ourself
+    if (!this.mutationObserver_) {
+      this.viewport_ = Services.viewportForDoc(element);
+      this.mutationObserver_ = new MutationObserver(
```
[the remark this answers is not in the document]
Comment (torch2424) [reply src/intersection-observer-polyfill.js]: Supported by everything 😄 

https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver#Browser_compatibility

File: src/intersection-observer-polyfill.js (hunk 5 above)
Comment (lannka) [reply src/intersection-observer-polyfill.js]: @torch2424 from your experiment we see all mutation events are already batched right?
@jridgewell do you see otherwise?

Comment (jridgewell) [reply src/intersection-observer-polyfill.js]: > for example an arbitrary attribute that has CSS selector with display: none on it.

Yes, but `FixedLayer`, [on-actions](https://www.ampproject.org/docs/interaction_dynamic/amp-actions-and-events#globally-defined-events-and-actions), and [amp-bind](https://www.ampproject.org/docs/reference/components/amp-bind#bindings) are taking the position that the only official way is the `hidden` attribute.

> this was only called on page load, and after all bind changes had resolved

This will be fired after every animation frame that has an attribute mutation. Like very amp-element's `buildCallback` and `layoutCallback`, etc.

> we see all mutation events are already batched right?

Correct, they're batched per animation frame.

File: src/intersection-observer-polyfill.js [hunk 7]
```diff
@@ -273,6 +284,19 @@ export class IntersectionObserverPolyfill {
       }
     }
 
+
+    // Add a mutation observer to tick ourself
+    if (MutationObserver && !this.mutationObserver_) {
```
Comment (jridgewell) [inline src/intersection-observer-polyfill.js]: This will throw an error if `MutationObserver` is not defined. Use `win.MutationObserver`

File: src/intersection-observer-polyfill.js (hunk 5 above)
Comment (lannka) [reply src/intersection-observer-polyfill.js]: > Yes, but FixedLayer, on-actions, and amp-bind are taking the position that the only official way is the hidden attribute.

how about `attempCollapse` or even `attempChangeHeight`?

File: src/intersection-observer-polyfill.js [hunk 8]
```diff
@@ -233,12 +235,21 @@ export class IntersectionObserverPolyfill {
      * @private {Array<!ElementIntersectionStateDef>}
      */
     this.observeEntries_ = [];
+
+    /**
+     * Mutation observer to fire off on visibility changes
+     * @private {?Object}
+     */
+    this.mutationObserver_ = null;
+    /** @private {?./service/viewport/viewport-impl.Viewport} */
```
Comment (jridgewell) [inline src/intersection-observer-polyfill.js]: Nit: newline before this.

File: src/intersection-observer-polyfill.js (hunk 5 above)
Comment (jridgewell) [reply src/intersection-observer-polyfill.js]: `attemptCollapse` toggles `hidden` (so does expanding). `attemptChangeHeight` does not change the hidden visibility of an element.

File: src/intersection-observer-polyfill.js (hunk 4 above)
Comment (lannka) [reply src/intersection-observer-polyfill.js]: ampdoc.getRootNode can give ShadowRoot. is it the right tree to listen for mutation events?

i.e., can a change from a sibling node of this ShadowRoot affect its visibility?

File: src/intersection-observer-polyfill.js (hunk 5 above)
Comment (lannka) [reply src/intersection-observer-polyfill.js]: `attemptChangeHeight` could have changed sibling's height hence moved the target element in/out viewport.

Comment (jridgewell) [reply src/intersection-observer-polyfill.js]: Correct, and there are numerous ways for CSS sibling selectors to change hidden visibility, too. The runtime's position is that only the `hidden` attribute is the proper way.

Comment (lannka) [reply src/intersection-observer-polyfill.js]: not even CSS sibling selector (which might not be so common). amp-bind can dynamically change CSS classes on an element and toggle visibility. That's to say, if Fandango shopping work flow later has moved away from hidden attribute to something else, then the analytics bug would come again.

overall it's a tradeoff between visibility tracking accuracy / coverage VS runtime performance. I will let @cramforce make the call here.

File: src/intersection-observer-polyfill.js (hunk 8 above)
Comment (torch2424) [reply src/intersection-observer-polyfill.js]: Done.

File: src/intersection-observer-polyfill.js [hunk 9]
```diff
@@ -233,12 +236,25 @@ export class IntersectionObserverPolyfill {
      * @private {Array<!ElementIntersectionStateDef>}
      */
     this.observeEntries_ = [];
+
+    /**
+     * Mutation observer to fire off on visibility changes
+     * @private {?Object}
+     */
+    this.mutationObserver_ = null;
```
Comment (erwinmombay) [inline src/intersection-observer-polyfill.js]: why is mutationobserver just an `Object` type?

File: src/intersection-observer-polyfill.js [hunk 10]
```diff
@@ -273,6 +289,25 @@ export class IntersectionObserverPolyfill {
...
+      this.mutationPass_ = new Pass(ampdoc.win, () => {
+        if (this.viewport_) {
+          this.tick(this.viewport_.getRect());
+        }
+      });
+      this.mutationObserver_ = new ampdoc.win.MutationObserver(
+          this.handleMutationObserverNotification_.bind(this)
+      );
+      this.mutationObserver_.observe(ampdoc.getRootNode(), {
+        attributes: true,
```
Comment (erwinmombay) [inline src/intersection-observer-polyfill.js]: do we need these properties preserved (unmangled)?

Comment (torch2424) [reply src/intersection-observer-polyfill.js]: Discussed offline: "it should get preserved if it knows its a mutation observer instance"

File: src/intersection-observer-polyfill.js (hunk 9 above)
Comment (torch2424) [reply src/intersection-observer-polyfill.js]: Done.

**Comment by torch2424** [comment]
@lannka @jridgewell @erwinmombay 

Made all requested changes 😄

File: src/intersection-observer-polyfill.js [hunk 11]
```diff
@@ -375,16 +413,51 @@ export class IntersectionObserverPolyfill {
...
+  /**
+   * Handle Mutation Oberserver events
+   * @private
+   */
+  handleMutationObserverNotification_() {
+    if (this.mutationPass_.isPending()) {
+      return;
+    }
+
+    // Wait one animation frame so that other mutations may arrive.
```
[the remark this answers is not in the document]
Comment (torch2424) [reply src/intersection-observer-polyfill.js]: Sounds good, we can wait for the decision there 😄

File: src/intersection-observer-polyfill.js (hunk 5 above)
Comment (cramforce) [reply src/intersection-observer-polyfill.js]: Is it worth creating a nasty "DisplayObserver polyfill" like this one?
https://output.jsbin.com/texepexaxa/5/quiet

It costs 1 iframe :)

**Comment by lannka** [comment]
@cramforce Interesting trick. But seems this only detects hidden to
visible, not visible to hidden?

**Comment by cramforce** [comment]
@lannka I'm sure @jridgewell has a better hack. I think that otherwise limiting things to `hidden` is the only feasible way. It is incomplete, but at least possible to implement.

**Comment by lannka** [comment]
@cramforce that SGTM if monitoring all DOM change is a big performance concern, we can limit it to "hidden" attribute only at this moment.

File: src/intersection-observer-polyfill.js [hunk 12]
```diff
@@ -375,16 +413,51 @@ export class IntersectionObserverPolyfill {
...
+    this.mutationPass_.schedule(16);
```
Comment (lannka) [inline src/intersection-observer-polyfill.js]: @torch2424 @jridgewell if the MutationObserver API already batch events to animation frames, why do we need this delay here?

Comment (torch2424) [reply src/intersection-observer-polyfill.js]: From my testing, I noticed that Mutation Observer is batched, though I trust @jridgewell 's judgement on the issue that we should use this.

Comment (jridgewell) [reply src/intersection-observer-polyfill.js]: The original design for `FixedLayer` had all "updates" happening behind the pass. This would queue up the request when a sync request came in, or when an async mutation was detected. But, there were a bunch of testing changes that would have been required, so I undid the sync changes.

I can't think of a technical reason to need this anymore.

**Comment by jridgewell** [comment]
> SGTM if monitoring all DOM change is a big performance concern, we can limit it to "hidden" attribute only at this moment.

For `FixedLayer`, it was a requirement: `FixedLayer` causes `style` mutations to do its measurements, which would in turn queue more mutation observer events, which would cause more `style` mutations, on and on and on. `FixedLayer` does not mutate `hidden` (actually it does, but it does it out of the DOM so it won't trigger an attribute mutation), so this was easy to break.

However, there's still a huge perf hit that can happen with an any-attr observer. Attributes change all the time during the element lifecycle, and it's very likely that as a user scrolled we would start laying out elements and queueing mutations. `hidden` also fixes this.

**Comment by torch2424** [comment]
@lannka @jridgewell 

Made changes, added hidden to [Mutation Observer Attribute Filter](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserverInit), and removed the pass 😄

File: src/intersection-observer-polyfill.js [hunk 13]
```diff
@@ -294,16 +291,12 @@ export class IntersectionObserverPolyfill {
...
-        if (this.viewport_) {
-          this.tick(this.viewport_.getRect());
-        }
-      });
       this.mutationObserver_ = new ampdoc.win.MutationObserver(
           this.handleMutationObserverNotification_.bind(this)
       );
       this.mutationObserver_.observe(ampdoc.getRootNode(), {
         attributes: true,
+        attributeList: ['hidden'],
```
Comment (jridgewell) [inline src/intersection-observer-polyfill.js]: Hoo, I didn't know about this. Actually, looking at [MDN](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserverInit), it should be [`attributeFilter`](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserverInit/attributeFilter).

File: src/intersection-observer-polyfill.js [hunk 14]
```diff
@@ -273,6 +285,21 @@ export class IntersectionObserverPolyfill {
...
 
+
+    // Add a mutation observer to tick ourself
+    const ampdoc = Services.ampdoc(element);
+    if (ampdoc.win.MutationObserver && !this.mutationObserver_) {
+      this.viewport_ = Services.viewportForDoc(element);
+      this.mutationObserver_ = new ampdoc.win.MutationObserver(
+          this.handleMutationObserverNotification_.bind(this)
+      );
+      this.mutationObserver_.observe(ampdoc.getRootNode(), {
```
Comment (lannka) [inline src/intersection-observer-polyfill.js]: @jridgewell was recommending using a different doc: https://github.com/ampproject/amphtml/pull/19034#discussion_r229133003

File: src/intersection-observer-polyfill.js [hunk 15]
```diff
@@ -186,7 +187,8 @@ export class IntersectionObserverApi {
  * The IntersectionObserver receives a callback function and an optional option
  * as params. Whenever the element intersection ratio cross a threshold value,
  * IntersectionObserverPolyfill will call the provided callback function with
- * the change entry.
+ * the change entry. Only Works with one document for now.
+ * TODO (@torch2424): Allow this to observe elements from multiple documents.
```
Comment (lannka) [inline src/intersection-observer-polyfill.js]: could you move this comment to the code that's causing this limitation?

File: src/intersection-observer-polyfill.js (hunk 13 above)
Comment (torch2424) [reply src/intersection-observer-polyfill.js]: Oops! Wrote that line at the DMV will fix now

File: src/intersection-observer-polyfill.js (hunk 14 above)
Comment (torch2424) [reply src/intersection-observer-polyfill.js]: Thanks for catching this! 😄

**Comment by torch2424** [comment]
@lannka @jridgewell 

Made requested changes. Let me know what you think 😄

**Comment by torch2424** [comment]
@jridgewell Now I did 😄 

#19054

**Comment by torch2424** [comment]
Did some testing before merging, seems like the mutation observer is called before the repaint (and display of the element). Thus, we need to wait for a vsync before ticking. Will implement before merging.

**Comment by torch2424** [comment]
Discussed offline with @jridgewell and @lannka Agreed to just re-add the pass to fix the above mentioned issue.

Will merge once travis is done running
