### PR TITLE
Fix race condition between amp-bind's scan and amp-form

### LINKED ISSUE #8647: amp-bind: Race condition scanning forms
`amp-bind` will throw an error if it scans a `<form>` element before that element is upgraded and calls `setFormForElement`. Repros 1/5 on `examples/bind/xhr.amp.html`.

```
could not find form implementation
reportError @ error.js:128
assert @ log.js:301
scanNextNode_ @ bind-impl.js:409
chunktion @ bind-impl.js:451
runTask_ @ chunk.js:179
execute_ @ chunk.js:393
(anonymous) @ chunk.js:408
log.js:295 Uncaught (in promise) Error: could not find form implementation
    at Log.assert (log.js:295)
    at scanNextNode_ (bind-impl.js:409)
    at Task.chunktion [as fn_] (bind-impl.js:451)
    at Task.runTask_ (chunk.js:179)
    at Chunks.execute_ (chunk.js:393)
    at chunk.js:408
```

/to @kmh287

### PR DESCRIPTION
**Pull request by kmh287**
Added a `whenFinished` promise to the AmpFormService to prevent a race condition between bind's scan and AmpFormService filling in form elements with an AmpForm implementation.

Fixes #8647 #8653 

/to @choumx @dvoytenko

### CODE REVIEW

File: src/services.js [hunk 1]
```diff
@@ -70,6 +70,15 @@ export function activityForDoc(nodeOrDoc) {
 }
 
 /**
+ * @param {!Node|!./service/ampdoc-impl.AmpDoc} nodeOrDoc
+ * @return {!../extensions/amp-form/0.1/amp-form.AmpFormService}
+ */
+export function ampFormServiceForDoc(nodeOrDoc) {
+  return /** @type {!../extensions/amp-form/0.1/amp-form.AmpFormService} */ (
```
Comment (dvoytenko) [inline src/services.js]: This should be `getElementServiceForDoc`, right? It requires an extension. And thus, the return value should be a promise.

File: extensions/amp-form/0.1/amp-form.js [hunk 2]
```diff
@@ -792,7 +792,17 @@ export class AmpFormService {
...
+    /** @const @private {!Promise} */
+    this.whenFinished_ = this.installStyles_(ampdoc)
+        .then(() => this.installHandlers_(ampdoc));
+  }
+
+  /**
+   * Returns a promise that resolves when all form implementations (if any)
+   * have been upgraded.
+   */
+  whenFinished() {
```
Comment (dvoytenko) [inline extensions/amp-form/0.1/amp-form.js]: Not sure if `whenFinished` is a good name since this part is re-entrant. Maybe something like "whenInitialized"?

File: extensions/amp-bind/0.1/bind-impl.js [hunk 3]
```diff
@@ -399,19 +399,20 @@ export class Bind {
...
       if (typeof element.getDynamicElementContainers === 'function') {
-        dynamicElements = element.getDynamicElementContainers();
+        element.getDynamicElementContainers().forEach(observeElement);
       } else if (element.tagName === 'FORM') {
-        // FORM is not an amp element, so it doesn't have the getter directly.
-        const form = formOrNullForElement(element);
-        dev().assert(form, 'could not find form implementation');
-        dynamicElements = form.getDynamicElementContainers();
+        // Form implementations are not filled in until ampdoc is ready.
+        ampFormServiceForDoc(this.ampdoc).whenFinished().then(() => {
```
Comment (choumx) [inline extensions/amp-bind/0.1/bind-impl.js]: No need to do this per form element. Store as an ivar.

File: extensions/amp-form/0.1/amp-form.js [hunk 4]
```diff
@@ -792,7 +792,17 @@ export class AmpFormService {
...
-    this.installStyles_(ampdoc).then(() => this.installHandlers_(ampdoc));
+    /** @const @private {!Promise} */
+    this.whenFinished_ = this.installStyles_(ampdoc)
+        .then(() => this.installHandlers_(ampdoc));
+  }
+
+  /**
+   * Returns a promise that resolves when all form implementations (if any)
+   * have been upgraded.
+   */
```
Comment (choumx) [inline extensions/amp-form/0.1/amp-form.js]: `@return {!Promise}`

File: extensions/amp-form/0.1/amp-form.js (hunk 2 above)
Comment (choumx) [inline extensions/amp-form/0.1/amp-form.js]: Or `initializePromise`?

File: extensions/amp-bind/0.1/bind-impl.js (hunk 3 above)
Comment (kmh287) [inline extensions/amp-bind/0.1/bind-impl.js]: good idea. done

File: src/services.js (hunk 1 above)
Comment (dvoytenko) [inline src/services.js]: This is not so much about custom element registration as whether or not the service is hosted in the extension. `getElementServiceForDoc` (probably not the best name) handles the case when the service is deployed via extension, which I believe is the case here. Among other things, it denies the service promise if the extension has not been included, which makes sense since the service will never come.

Comment (kmh287) [inline src/services.js]: Done. Thanks for the explanation :+1:

File: src/services.js [hunk 5]
```diff
@@ -69,6 +69,15 @@ export function activityForDoc(nodeOrDoc) {
 }
 
 /**
+ * @param {!Node|!./service/ampdoc-impl.AmpDoc} nodeOrDoc
+ * @return {!Promise<../extensions/amp-form/0.1/amp-form.AmpFormService>}
```
Comment (dvoytenko) [inline src/services.js]: This should be `!Promise<!../...>`, right? I.e. the promise yields a non-null value...

**Comment by kmh287** [comment]
Thanks!
