### PR TITLE
amp-bind: Fix amp-img[src] rewriting on cache

### LINKED ISSUE #10207: amp-bind: Binding to amp-img[src] also requires [srcset] on cache
When using amp-bind for changing the `src` value of `amp-img`, the page does not work on cache, probably because the cache can't change the src file name, this happens also when using absolute URLs.
In order to replicate open: 
[amp version](https://chiara-ampbyexample.appspot.com/amp-bind-url-images.html)
[cached version](https://chiara--ampbyexample-appspot-com.cdn.ampproject.org/c/s/chiara-ampbyexample.appspot.com/amp-bind-url-images.html)

@choumx @ericlindley-g  FYI

### PR DESCRIPTION
**Pull request by choumx**
Fixes #10207.

/to @jridgewell /cc @kul3r4

### CODE REVIEW

File: src/sanitizer.js [hunk 1]
```diff
@@ -384,8 +384,10 @@ export function isValidAttr(tagName, attrName, attrValue) {
  * @return {string}
  */
 export function rewriteAttributeValue(tagName, attrName, attrValue) {
-  if (attrName == 'src' || attrName == 'href' || attrName == 'srcset') {
-    return resolveUrlAttr(tagName, attrName, attrValue, self.location);
+  const tag = tagName.toLowerCase();
```
Comment (jridgewell) [inline src/sanitizer.js]: Why not change it to compare to `AMP-IMG`?

Comment (choumx) [inline src/sanitizer.js]: Looks like Caja returns tags in lowercase while `Element.tagName` is uppercase.
