### PR TITLE
Wait for viewer visible before requesting cid

### LINKED ISSUE #11628: Request cid failed: document is not visible errors
`Request cid failed: document is not visible` have become common since September 18th. 

Possible culprit: https://github.com/ampproject/amphtml/pull/11046/files#diff-cd24a4710c7e4e23016d10a126055108L180

### PR DESCRIPTION
**Pull request by zhouyx**
fix #11628 

Please note I did NOT bounce multiple cid request to one, as it needs a map from `getCidStruct` to each promise, which I think does not worth it. Service who call `Cid.get()` should be responsible to only call `#get()` once with each `getCidStruct`. But I am glad to store cid result if requested : )

One thing to note is that: Do we TIMEOUT if doc does not become visible after a certain amount of time. I feel we should not do in `Cid.get()` function, but whoever is calling that function should handle timeout.

### CODE REVIEW

**Comment by zhouyx** [comment]
Ping : ) 
Want to make to today's canary

File: src/service/viewer-impl.js [hunk 1]
```diff
@@ -603,14 +613,32 @@ export class Viewer {
...
    */
   whenFirstVisible() {
     return this.whenFirstVisiblePromise_;
   }
 
   /**
+   * Returns a Promise that resolve when current doc becomes visible
+   * @return {!Promise}
+   */
+  nextVisiblePromise() {
```
Comment (aghassemi) [inline src/service/viewer-impl.js]: `whenNextVisible` to match `whenFirstVisible`?

File: src/service/viewer-impl.js [hunk 2]
```diff
@@ -603,14 +613,32 @@ export class Viewer {
...
-   * AMP document becomes visible.
+   * AMP document first becomes visible.
    * @return {!Promise}
    */
   whenFirstVisible() {
     return this.whenFirstVisiblePromise_;
   }
 
   /**
+   * Returns a Promise that resolve when current doc becomes visible
```
Comment (aghassemi) [inline src/service/viewer-impl.js]: mention it resolves if already visible

File: src/service/viewer-impl.js [hunk 3]
```diff
@@ -426,6 +432,10 @@ export class Viewer {
       this.lastVisibleTime_ = now;
       this.hasBeenVisible_ = true;
       this.whenFirstVisibleResolve_();
+      if (this.nextVisibleResolve_) {
+        this.nextVisibleResolve_();
+        this.nextVisibleResolve_ = null;
```
Comment (aghassemi) [inline src/service/viewer-impl.js]: uhmm shouldn't `nextVisiblePromise_`  also be nullified?

File: src/service/viewer-impl.js [hunk 4]
```diff
@@ -426,6 +432,10 @@ export class Viewer {
       this.lastVisibleTime_ = now;
       this.hasBeenVisible_ = true;
       this.whenFirstVisibleResolve_();
+      if (this.nextVisibleResolve_) {
```
Comment (aghassemi) [inline src/service/viewer-impl.js]: How about doing this similar to `whenFirstVisible`? ie.

```
...
    this.whenNextVisiblePromise_ = new Promise(resolve => {
      this.whenNextVisibleResolve_ = resolve;
    });
....

...
// no need to check nullity of this. whenNextVisibleResolve_ anymore.
// just call and nullify nextVisiblePromise_
this.whenNextVisibleResolve_();
this.nextVisiblePromise_ = null;
...
```

Comment (zhouyx) [reply src/service/viewer-impl.js]: Hmmmm unlike `whenFirstVisible` `whenNextVisible` return a promise that should be reset everytime doc becomes invisible. 
I am trying to not initiate a promise if no one is requesting `whenNextVisible`. Otherwise it would require use to create a new promise on every visible state change. 

I did add a `whenNextVisibleResolve_()` helper function to make `#onVisiblityChange_` cleaner. I would prefer to not add that though... let me know

File: src/service/viewer-impl.js (hunk 3 above)
Comment (zhouyx) [reply src/service/viewer-impl.js]: ahhh! good catch

File: src/service/viewer-impl.js (hunk 2 above)
Comment (zhouyx) [reply src/service/viewer-impl.js]: done

File: src/service/viewer-impl.js (hunk 1 above)
Comment (zhouyx) [reply src/service/viewer-impl.js]: done
