### PR TITLE
🐛 Create image pixel in onload event handler of iframe

### LINKED ISSUE #23935: Error: null is not an object (evaluating 'new a.Image')
```
Error: null is not an object (evaluating 'new a.Image')
at Image (https://raw.githubusercontent.com/ampproject/amphtml/1908121824440/src/window-interface.js:95)
at iframe (https://raw.githubusercontent.com/ampproject/amphtml/1908121824440/src/pixel.js:61)
at win (https://raw.githubusercontent.com/ampproject/amphtml/1908121824440/extensions/amp-analytics/0.1/transport.js:246)
at (https://raw.githubusercontent.com/ampproject/amphtml/1908121824440/extensions/amp-analytics/0.1/transport.js:132)
at requestUrl (https://raw.githubusercontent.com/ampproject/amphtml/1908121824440/extensions/amp-analytics/0.1/requests.js:260)
```

My guess is the `window` is destroyed by the time `Transport.sendRequest` is called. A null check may fix it.

/cc @ampproject/wg-analytics

### PR DESCRIPTION
**Pull request by rcebulko**
Context: https://github.com/ampproject/amphtml/issues/23935#issuecomment-598350806

Addresses the [fourth](https://pantheon.corp.google.com/errors/CIzCt9nl8ZL4twE?time=P7D&project=amp-error-reporting) and soon-to-be* [third](https://pantheon.corp.google.com/errors/CIzCt9nl8ZL4twE?time=P7D&project=amp-error-reporting) most frequent unexpected error logged to AMP Error Reporting.

The soon-to-be part is because error volume has skyrocketed due to a very large news publisher updating their site in a way that triggers this race condition all the time. It's only been live for a day or so right now and only on Beta/Experimental, but based on that slice of traffic it's set to outpace almost all other reported errors.

I expect this to eliminate approximately 1 million error reports per week, based on the frequency of these two errors in Beta/Experimental

Closes #23935
Closes https://github.com/ampproject/amphtml/issues/27207

### CODE REVIEW

File: src/pixel.js [hunk 1]
```diff
@@ -59,7 +59,9 @@ function createNoReferrerPixel(win, src) {
       })
     );
     win.document.body.appendChild(iframe);
-    createImagePixel(iframe.contentWindow, src);
+    iframe.onload = function() {
```
Comment (zhouyx) [inline src/pixel.js]: please register the onload event before appending iframe to the document in case the onload event fire beforehand. Thanks

Comment (rcebulko) [reply src/pixel.js]: Done!
