### PR TITLE
Stable bundle size by disabling mangle cache

### LINKED ISSUE #37014: Bundle size calculation changes too often
**summary**

I'm currently investigating root cause, but I believe our bundle size calculation is incorrect.
There are PRs displaying bundle size changes in our GH UI that display 0 diff when building locally. A good example is https://github.com/ampproject/amphtml/pull/37007.

When testing locally via the below command I see no diff on that commit and the one before it for any vendor builds.
```
npx amp dist --noconfig --version_override 0000000000000 && npx amp bundle-size --on_local_build
```

### PR DESCRIPTION
**Pull request by jridgewell**
The mangle cache is necessary when generating multiple binaries which need to interact. However, our bundle size workflow doesn't actually run the code, it just needs to estimate the size impact a PR causes.

Hopefully fixes #37014.

### CODE REVIEW

File: build-system/tasks/dist.js [hunk 1]
```diff
@@ -398,6 +398,8 @@ dist.flags = {
     'Output code with whitespace (useful while profiling / debugging production code)',
   fortesting: 'Compile production binaries for local testing',
   noconfig: 'Compile production binaries without applying AMP_CONFIG',
+  nomanglecache:
+    'Do not share the mangle cache between binaries, useful only in estimating size impatcs of code changes.',
```
Comment (samouri) [inline build-system/tasks/dist.js:402]:
```suggestion
    'Do not share the mangle cache between binaries, useful only in estimating size impacts of code changes.',
```

**Comment by samouri** [comment]
best option yet!

**Comment by jridgewell** [comment]
Ok, finally this created stable rebuilds: [A](https://app.circleci.com/pipelines/github/ampproject/amphtml/20025/workflows/ffcba09c-1498-4922-97f3-09a90d68f39e/jobs/383271/parallel-runs/0/steps/0-113) and [B](https://app.circleci.com/pipelines/github/ampproject/amphtml/20025/workflows/bc5faa5d-7b0e-4312-9ef2-877f9ac9cf00/jobs/383201/parallel-runs/0/steps/0-113).

File: build-system/pr-check/bundle-size-module-build.js [hunk 2]
```diff
@@ -18,7 +18,9 @@ const jobName = 'bundle-size-module-build.js';
  * Steps to run during push builds.
  */
 function pushBuildWorkflow() {
-  timedExecOrDie('amp dist --noconfig --esm --version_override 0000000000000');
+  timedExecOrDie(
+    'amp dist --noconfig --esm --version_override 0000000000000 --nomanglecache'
```
Comment (samouri) [inline build-system/pr-check/bundle-size-module-build.js:22]: nit: it could make sense to instead make a new flag `--for_bundle_size` which encapsulates both of these flags

File: build-system/tasks/helpers.js [hunk 3]
```diff
@@ -536,7 +536,7 @@ const nameCache = {};
 const mangleIdentifier = {
   get(num) {
     const charset =
-      '$ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz0123456789';
+      'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ$_0123456789';
```
Comment (samouri) [inline build-system/tasks/helpers.js:539]: Especially if we pursue this PR, then it makes sense to remove our stable id generation algo in favor of tersers default.

**Review by samouri — APPROVED** [review]

File: build-system/tasks/helpers.js [hunk 4]
```diff
@@ -536,7 +536,7 @@ const nameCache = {};
 const mangleIdentifier = {
```
Comment (samouri) [inline build-system/tasks/helpers.js:536]: Later I'd like to verify that we still need this (only b/c I had seen removing it save ~0.5kb)

File: build-system/pr-check/bundle-size-module-build.js (hunk 2 above)
Comment (danielrozenberg) [reply build-system/pr-check/bundle-size-module-build.js:22]: Mixed feelings about this. I think being explicit about what each flag does is better than saying "build this for a specific use-case", but I also don't really know what "mangle cache" is

**Comment by danielrozenberg** [comment]
> /cc @danielrozenberg I want to confirm that CircleCI's "Module Build (Prod)" and "Nomodule Build (Prod)" workflow steps are not used for anything other than running bundle size bot.

Currently they are only used for that (you can see that plainly from the flow graph. We don't store any artifacts from these jobs other than the bundle-size data)

To be on the safe side, maybe we should change the jobs' names to be `[No]module build (Bundle Size)` - it would get cut off with an ellipsis but I think there's enough characters to give devs an idea what these mean (+ the hover text is complete)

image

**Comment by jridgewell** [comment]
I'll rename in a follow up. Thanks, I just wanted to confirm we weren't planning on persisting and reusing these for something else.

**Comment by alanorozco** [comment]
Thanks for doing this!

**Comment by samouri** [comment]
> Thanks for doing this!

+1. This was not easy to track down!
I had tried fixing this last week and failed miserably.

Thank you Justin!
