### PR TITLE
Make dynamic CORS fail without opt-in

### LINKED ISSUE #12498: amp-bind: Require opt-in for URL substitutions
Require per-use opt-in for `amp-bind` mutations of properties that support URL variables: https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#per-use-opt-in 

This is a solution reached with security and privacy teams as a prerequisite for #9074. Note that this is a breaking change so we should determine impact and warn in advance first. 

@ericlindley-g suggests:
- [x] Add a warning with a specific date that it will become an error (maybe 60 days for this one, assuming we do this after the holidays)
- [ ] ~~Send Search Console warnings/emails when the warning comes out~~
- [ ] ~~Check progress in folks fixing this, and do more high-touch outreach to make sure anyone with significant user impact (high-traffic sites) are making the change~~

### PR DESCRIPTION
**Pull request by choumx**
Fixes #12498.

Context: https://github.com/ampproject/amphtml/issues/12498#issuecomment-385969938

### CODE REVIEW

File: src/batched-json.js [hunk 1]
```diff
@@ -60,18 +60,20 @@ export function batchFetchJsonFor(
     // Throw user error if this element is performing URL substitutions
     // without the soon-to-be-required opt-in (#12498).
     if (opt_urlReplacement == UrlReplacementPolicy.OPT_IN) {
-      urlReplacements.collectUnwhitelistedVars(element).then(unwhitelisted => {
-        if (unwhitelisted.length > 0) {
```
Comment (alabiaga) [inline src/batched-json.js]: I noticed this throughout the codebase. the usage of [].length > 0 vs just
```
    if (unwhitelisted.length) {
    ...
    }
```
which should suffice here and below as 0 will coerce to false and a positive number to true, unless the list is expected to have a negative length at any point where the value will then coerce to true. Are we just explicit to be safe?

File: src/batched-json.js [hunk 2]
```diff
@@ -37,8 +37,8 @@ export const UrlReplacementPolicy = {
  * @param {!Element} element
  * @param {string=} opt_expr Dot-syntax reference to subdata of JSON result
  *     to return. If not specified, entire JSON result is returned.
```
Comment (jridgewell) [inline src/batched-json.js]: Whoa, I don't remember this file at all. I think really bad naming, `SERVICEfor` generally just gets the installed service, but this adds in a bunch of element specific code and URL replacements just for fun.

File: src/batched-json.js (hunk 1 above)
Comment (jridgewell) [reply src/batched-json.js]: `length` is generally understood in JS to be zero-or-positive (it commonly signifies array-likes for iteration algorithms, and that's what they expect).

But, I generally like doing explicit numeric comparisons. The minifier will minify it either way.

File: src/batched-json.js [hunk 3]
```diff
@@ -60,18 +60,20 @@ export function batchFetchJsonFor(
     // Throw user error if this element is performing URL substitutions
     // without the soon-to-be-required opt-in (#12498).
     if (opt_urlReplacement == UrlReplacementPolicy.OPT_IN) {
-      urlReplacements.collectUnwhitelistedVars(element).then(unwhitelisted => {
-        if (unwhitelisted.length > 0) {
+      return urlReplacements.collectUnwhitelistedVars(element).then(invalid => {
```
Comment (jridgewell) [inline src/batched-json.js]: Couldn't this be sync?

Also, isn't this really specific for `UrlReplacements`?

File: src/batched-json.js [hunk 4]
```diff
@@ -60,18 +60,20 @@ export function batchFetchJsonFor(
...
-              'triggered by amp-bind will soon require opt-in. Please add ' +
-              `data-amp-replace="${unwhitelisted.join(' ')}" to the ` +
-              `<${TAG}> element. See "bit.ly/amp-var-subs" for details.`);
-          // For tracking in error reporting.
-          dev().expectedError(TAG, 'amp-bind CORS fetch without opt-in!');
+          throw user().createError('URL variable substitutions in CORS ' +
+              'fetches from dynamic URLs (e.g. via amp-bind) require opt-in. ' +
+              `Please add data-amp-replace="${invalid.join(' ')}" to ` +
+              `the <${TAG}> element. See "bit.ly/amp-var-subs" for details.`);
+        } else {
```
Comment (jridgewell) [inline src/batched-json.js]: Else is unnecessary.

File: src/batched-json.js (hunk 2 above)
Comment (choumx) [reply src/batched-json.js]: Yea. :) Originally this code was duplicated in different extensions (anything that fetches JSON with a `src` attribute) and then extracted here. I was thinking about merging it with `batched-xhr-impl` eventually. We can let the callers provide the UrlReplacements service instead.

File: src/batched-json.js (hunk 3 above)
Comment (choumx) [reply src/batched-json.js]: Could be, but I kept it async so it can use `collectVars` internally which is async. I'll try massaging this to make it sync though.

It is, but fetching and URL replacements often have [tightly coupled business logic](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md). `amp-list` and `amp-state` share this logic in particular.

File: src/batched-json.js (hunk 4 above)
Comment (choumx) [reply src/batched-json.js]: Won't the chained promise below `.then(src => ...` fail to receive the `src` value? This would be easier to read if sync. :)

File: src/batched-json.js (hunk 3 above)
Comment (choumx) [reply src/batched-json.js]: Made this sync which is much better, thanks.

File: src/service/url-replacements-impl.js [hunk 5]
```diff
@@ -1113,20 +1113,21 @@ export class UrlReplacements {
...
-      const varNames = Object.keys(vars);
-      if (whitelist) {
-        return varNames.filter(v => !whitelist[v]);
-      } else {
-        // All vars are unwhitelisted if the element has no whitelist.
-        return varNames;
-      }
-    });
+    const vars = Object.create(null);
+    this.expandStringSync(url, /* opt_bindings */ undefined, vars);
```
Comment (jridgewell) [inline src/service/url-replacements-impl.js]: Nit: Probably don't need to do a full expansion, just a regex, right?

Comment (choumx) [reply src/service/url-replacements-impl.js]: I guess we could write a new function that only collects vars and not any of the other stuff. Not sure it's worth it.
