### PR TITLE
Encode output of svgo to fix carousel arrow SVG in IE

### LINKED ISSUE #8401: amp-carousel: IE/Edge + data-image without encoding
Internet Explorer do not show right and left arrow without base64 encoding on background-image 

Tested on Edge 14.

### PR DESCRIPTION
**Pull request by cvializ**
Closes #8401

IE seems to break when the SVG is not urlencoded We can easily encode the full SVG by passing `encode: true` to the [postcss svgo processor](https://www.npmjs.com/package/postcss-svgo#encode).

This lets us write valid, unencoded SVG files into data-uris without having to manually encode them, partially or fully. This should prevent similar bugs from cropping up in the future.

Fiddle for repro in IE: https://jsfiddle.net/h78nyapL/

### CODE REVIEW

File: build-system/tasks/jsify-css.js [hunk 1]
```diff
@@ -45,6 +45,9 @@ cssnano = cssnano({
   mergeIdents: true,
   reduceIdents: false,
   zindex: false,
+  svgo: {
+    encode: true,
```
Comment (aghassemi) [inline build-system/tasks/jsify-css.js]: cool! There are multiple places that have already URL encoded their SVG (either partially or fully) and this will result in double encoding. We need to decode those places. Do a search for `image/svg+xml` but places I found that need attention (plus manual testing) are:

- [ ] amp-app-banner.css
- [ ] amp-lightbox-viewer.css
- [ ] amp-sticky-ad.css in 0.1
- [ ] amp-sticky-ad.css in 1.0

Comment (cvializ) [inline build-system/tasks/jsify-css.js]: Mmm good intuition, but I checked the build directory, and it looks like `postcss-svgo` is smart about double-encoding and only encodes when necessary. Given that, do you think it's best to convert all the encoded SVGs now, or split that out into a smaller task?

Comment (aghassemi) [inline build-system/tasks/jsify-css.js]: huh, kind of surprised  `postcss-svgo` detected that they were already encoded. Regardless I think we should decode all SVGs we have for consistency. Shouldn't be too much work (its like 2 or 3 that are fully encoded. The rest just encoded `#`). You can maybe set `svgo: { encode: false }`, do a run and take the decoded versions from the build.

**Comment by cvializ** [comment]
I'm actually trying to verify that assumption, not sure if I spoke too soon 😛 I will replace the pre-encoded ones in this PR then.

File: build-system/tasks/jsify-css.js (hunk 1 above)
Comment (cvializ) [inline build-system/tasks/jsify-css.js]: I'm actually trying to verify that assumption, not sure if I spoke too soon 😛 I will replace the pre-encoded ones in this PR then.

Comment (cvializ) [inline build-system/tasks/jsify-css.js]: Ah yes, it's here: https://github.com/svg/svgo/blob/master/lib/svgo/coa.js#L288
Looks like they pass the input string into svgo, which outputs an unencoded svg, which is then encoded.

I'll still update our sources, it's just good to know this won't break unexpectedly if someone pastes an svg with URL0encoded characters in it.
