### PR TITLE
Wrap shadow-v0.js in an IIFE to prevent global name collisions

### LINKED ISSUE #10799: AMP Shadow with amp-access
When using amp-access in a PWA (Polymer), authorization and pingback are failing
The AMP content is injected in the PWA via amp shadow

On the browser console the following errors appear:

Authorization failed: : Cannot read property 'trim' of undefined​​​

Uncaught (in promise) TypeError: Pingback failed: : Cannot read property 'trim' of undefined​​​
    at na (mode.js:56)
    at rd (url-parse-query-string.js:31)
    at Yj.f.getCorsUrl (url.js:465)
    at ak (xhr-impl.js:156)
    at Yj.f.sendSignal (xhr-impl.js:288)
    at amp-access-client.js:143
    at <anonymous>

You can reproduce the issue here:
https://pwa-news.appspot.com/article/chrome/trenta-gradi-e-non-e-finita-il-comune-scatta-l-allerta-1.15504847

schermata 2017-08-04 alle 16 57 19

### PR DESCRIPTION
**Pull request by cvializ**
Fixes #10799

Google Analytics would overwrite one of the `shadow-v0.js`'s minified functions with its own function of the same minified name, causing a strange bug. If we wrap `shadow-v0.js` in an IIFE then its variables won't be on the global object and won't be easily overwritten.

### CODE REVIEW

File: gulpfile.js [hunk 1]
```diff
@@ -325,7 +325,6 @@ function compile(watch, shouldMinify, opt_preventRemoveAndMakeDir,
           watch: watch,
           preventRemoveAndMakeDir: opt_preventRemoveAndMakeDir,
           minify: shouldMinify,
-          wrapper: '<%= contents %>'
```
Comment (dvoytenko) [inline gulpfile.js]: What does this do exactly? Do you have a snippet of the resulting binary?

Comment (dvoytenko) [reply gulpfile.js]: Asking because of this: https://github.com/ampproject/amphtml/blob/master/gulpfile.js#L826

Comment (cvializ) [reply gulpfile.js]: The code path for [minified binaries](https://github.com/ampproject/amphtml/blob/master/gulpfile.js#L804) calls [build-system/tasks/compile.js#closureCompile](https://github.com/cvializ/amphtml/blob/master/build-system/tasks/compile.js#L110) which uses an IIFE as the default wrapper.

Comment (cvializ) [reply gulpfile.js]: PTAL

Comment (dvoytenko) [reply gulpfile.js]: Perfect. LGTM from me.
