### PR TITLE
fix getMode for 3p iframe

### LINKED ISSUE #4701: getMode is broken in 3p iframes
The root cause is because `getMode()` relies on `window.context` which is parsed from iframe src URL. Also, `getMode()` will cache result, so the first call determines its state.

But currently the generation of `window.context` happens after the 1st invocation of `getMode()`, so it'll always give the wrong mode. Especially, in the test related to `3p/integration.js`, `getMode().test` always gives `false`.

The fix would be to move the generation of `window.context` to the top of `3p/integration.js`.

### PR DESCRIPTION
**Pull request by zhouyx**
fix #4701 
Moving this two lines seems to work well. I manually checked `getMode()` and it's set correctly. 

However moving `window.context.location = parseUrl(data._context.location.href)` will break things.

### CODE REVIEW

**Comment by jridgewell** [comment]
When is the first `getMode` called?

**Comment by zhouyx** [comment]
@jridgewell  wish I can tell you. 😢  I am still investigating. 
Current state seems weird to me. `getMode()` return correctly if I initiate `window.context` right before `register()`, but fails if I move assignment of `window.context` right after `register()`.

**Comment by zhouyx** [comment]
Ha!!! I see!
`register()` use a `dev().assert()`.  `dev()` will create a new `logConstructor`. And in `Log` constructor, we use `getMode().test`. That's when we first call `getMode()`. 

https://github.com/ampproject/amphtml/blob/master/3p/3p.js#L48
https://github.com/ampproject/amphtml/blob/master/src/log.js#L74

File: 3p/integration.js [hunk 1]
```diff
@@ -117,6 +117,9 @@ const AMP_EMBED_ALLOWED = {
 // used for extracting fakead3p from production code.
 const IS_DEV = true;
 
+const data = parseFragment(location.hash);
```
Comment (jridgewell) [inline 3p/integration.js]: Do we know that `location.hash` will always be valid JSON?

Comment (zhouyx) [inline 3p/integration.js]: https://github.com/ampproject/amphtml/blob/master/src/3p-frame.js#L114
It will always be valid JSON if the iframe is created during runtime. I am not sure about testing

Comment (jridgewell) [inline 3p/integration.js]: 👍

**Comment by jridgewell** [comment]
LGTM.

**Comment by zhouyx** [comment]
found that `window.context.location = parseUrl(data._context.location.href)` needs to be wrapped in try catch block. `window.context` is enough for `getMode()` will leave `window.context.location` unmoved.
