### PR TITLE
Change default user logging level of AMP runtime from `OFF` to `WARN`

### LINKED ISSUE #11662: Do we swallow user().warn
Hey,

I think we have code all over the place that does `user().warn` but in practice it doesn't output anything unless users opt into logging.

Could we as a quick fix either

- always output it
- or output warnings when development mode is on

?

Or am I wrong about this?

### PR DESCRIPTION
**Pull request by rsimha-amp**
With this PR, the default user logging level will be changed from `OFF` to `WARN`. In addition, the `tag` argument to `user.log.*` is only printed when `localDev` is `true`.

**Before:**
- `user.log.error()`: No output
- `user.log.warn()`: No output
- `user.log.info()`: No output
- `user.log.fine()`: No output

**After:**
- `user.log.error()`: Prints message
- `user.log.warn()`: Prints message
- `user.log.info()`: No output
- `user.log.fine()`: No output

**Here is what the logs will look like for local development:**

image

**Here is what the logs will look like in production:**

image

**Notes:**
- Adding `#development=1` to the URL will set the logging level to `FINE`
- Adding `#log=<N>` to the URL will set the logging level to `<N>` 

Fixes #11662

### CODE REVIEW

**Comment by rsimha-amp** [comment]
Tested with a page containing validation errors. Since the validator runs on page load, the errors are the first things seen on the page.

File: src/log.js [hunk 1]
```diff
@@ -159,7 +156,7 @@ export class Log {
       } else if (level == 'WARN') {
         fn = this.win.console.warn || fn;
       }
-      messages.unshift(Date.now() - start, '[' + tag + ']');
+      messages.unshift('[' + tag + ']');
```
Comment (cramforce) [inline src/log.js]: Should we kill the tag? I find them distracting, but others may disagree.

Comment (rsimha-amp) [reply src/log.js]: The tag can be helpful when you're scanning through logs in a console. Not sure if people rely on it for debugging. For example, `gulp test --verbose` could benefit from it. I agree it's superfluous in the dev tools window.

I'm fine removing it, but that will involve changing all the calling sites. Okay if that happens in a separate PR?

Comment (rsimha-amp) [reply src/log.js]: On second thought, I agree that removing the tag is the way to go, since logs will now be visible to publishers, etc. who use the dev tools console.

Comment (cramforce) [reply src/log.js]: You could guard it by `localDev`

Comment (rsimha-amp) [reply src/log.js]: @cramforce Done. PTAL.

**Comment by rsimha-amp** [comment]
@pbakaus @bpaduch This change is now in `master`, and will make it to the next `canary` release. Let me know if there's any documentation that needs to be updated. If there's a periodic update that we publish, targeted at partners, we should include this in the notes.

**Comment by bpaduch** [comment]
@rsimha-amp - I'd like to understand this better so that we can document anything that devs might have questions about. 

For example, I know that in an intro tutorial we say to use "development=1" to turn on the AMP validator so the developer can go through any validation errors.  So I used that same simple sample and I'm getting actual errors that I didn't expect; this might confuse developers.  It confused me.  

Here's the sample code on my github pages site: https://bpaduch.github.io/codelab2/article2.amp.htm

Just opening the URL and checking the validator shows no errors.  If I turn on `development=1`, I get an error.  Which am I to believe?

console-errors

**Comment by rsimha-amp** [comment]
@bpaduch You're correct in saying the scope of this change covers the AMP runtime. Specifically, it covers the `user.log` statements in the AMP runtime code.

Earlier, developers would not see any logging generated by calls to `user.log.error()`, `user.log.warn()`, `user.log.info()`, or `user.log.fine()` unless they explicitly set `#development=1`. With my change, users will start seeing logging generated by `user.log.error()` and `user.log.warn()` by default in the dev console. (Logging from `user.log.info()` and `user.log.fine()` will continue to be suppressed by default, and will only be visible with `#development=1 or #log=<N>`.

If you make the page `https://bpaduch.github.io/codelab2/article2.amp.html` load a version of the AMP runtime that includes my change, you will start seeing error and warning messages without having to use `#development=1`.

This is new behavior, and will affect webpages that have AMP runtime errors or warnings when the dev console is up. Hope this clarifies things sufficiently. If necessary, @cramforce can add more context to why this was necessary.

**Comment by cramforce** [comment]
I'm not 100% sure we need to document anything. This was more of a bug fix.

Basically when developers of AMP docs make errors they should see an error in the Chrome DevTools console. When they do something that might be wrong, they see a warning. 

I think that is just what people expect, but it might still be great to just state something like: If you have a problem, check the Browser DevTools for error messages or warnings.
