### PR TITLE
Fix ads served from non-localhost servers

### LINKED ISSUE #12054: Running local server on non-localhost causes breakages
Steps to reproduce:
```
gulp --host=<insert name of host machine>
```
navigate to hostname:8000/examples/ads.amp.html
Select doubleclick for ad network.
Notice how all the ads 404

The issue is that non-localhost is not being identified as localDev in mode.js, which is instead hardcoding localhost in its check for localdev mode.

### PR DESCRIPTION
**Pull request by rsimha-amp**
When you run...
```
export AMP_TESTING_HOST=<hostname>
gulp --host=<hostname>
```
... and navigate to `http://<hostname>:8000/examples/ads.amp.html`, the ads don't load because the page is trying to fetch them from `http://ads.localhost:8000/dist.3p/current` and not `http://<hostname>:8000/dist.3p/current`.

This PR replaces `ads.localhost` in `src/3p-frame.js` with `<hostname>` when they are being served from a non-localhost server.

See https://github.com/ampproject/amphtml/issues/12054#issuecomment-355443905 for more details. 

Fixes #12054

### CODE REVIEW

**Comment by rsimha-amp** [comment]
/to @bradfrizzell @lannka @erwinmombay 

@bradfrizzell The fix in the first commit doesn't seem to be sufficient. I'll defer this one to you, since you know the desired behavior better than I do. It would help if you can point out where else we need to replace `ads.localhost` with `<hostname>`.

**Comment by bradfrizzell** [comment]
It seems like thirdPartyFrameHost is not actually ever being set on the AMP_MODE object. If that properly got set I think it would fix this issue. I tried hardcoding it in and that fixed the issue for me.

File: src/3p-frame.js [hunk 1]
```diff
@@ -229,8 +229,10 @@ export function getDefaultBootstrapBaseUrl(parentWindow, opt_srcFileBasename) {
 }
 
 function getAdsLocalhost(win) {
-  return 'http://ads.localhost:'
-      + (win.location.port || win.parent.location.port);
+  const hostname = self.AMP_CONFIG['thirdPartyFrameHost'] ?
+    self.AMP_CONFIG['thirdPartyFrameHost'] : 'ads.localhost';
```
Comment (lannka) [inline src/3p-frame.js]: nit: it can be simplified
```
const hostname = self.AMP_CONFIG['thirdPartyFrameHost'] || 'ads.localhost';
```

File: build-system/tasks/prepend-global/index.js [hunk 2]
```diff
@@ -169,6 +169,7 @@ function enableLocalDev(config, target, configJson) {
   const TESTING_HOST = process.env.AMP_TESTING_HOST;
   if (typeof TESTING_HOST == 'string') {
     LOCAL_DEV_AMP_CONFIG = Object.assign(LOCAL_DEV_AMP_CONFIG, {
+      thirdPartyUrl: 'http://' + TESTING_HOST,
```
Comment (lannka) [inline build-system/tasks/prepend-global/index.js]: I didn't find `thirdPartyUrl` in production v0.js. is it something still in use? @erwinmombay

Comment (erwinmombay) [reply build-system/tasks/prepend-global/index.js]: yes. it is a way for OTHER cdn's to override the 3p url not for ours since ours is the default

Comment (lannka) [reply build-system/tasks/prepend-global/index.js]: I see. 

@rsimha-amp I can see why you pointed this value to TESTING_HOST, so that the 3p frame can be loaded from the local server. But one caveat is that the frame will have the same origin as the parent page, which will cause ads behave differently.

File: src/3p-frame.js (hunk 1 above)
Comment (rsimha-amp) [reply src/3p-frame.js]: Done.

File: build-system/tasks/prepend-global/index.js (hunk 2 above)
Comment (rsimha-amp) [reply build-system/tasks/prepend-global/index.js]: I see. That might explain some of the errors I saw earlier.

**Comment by rsimha-amp** [comment]
@bradfrizzell @lannka @erwinmombay With the latest commit, I have `http://<hostname>:8000/examples/ads.amp.html` working with a non-localhost server. PTAL.

File: build-system/tasks/prepend-global/index.js (hunk 2 above)
Comment (rsimha-amp) [reply build-system/tasks/prepend-global/index.js]: I'll let @bradfrizzell comment on whether this caveat is a problem. The good news though, is that we can now see ads on the test page when it's served from a non-localhost server,  so the original issue is fixed.

Comment (lannka) [reply build-system/tasks/prepend-global/index.js]: It's surely better than not showing ads on non-localhost servers.

But please make sure this does not affect localhost server. Crazy ads are trying hard to jail break the iframe. If it's on same origin, they will add scripts to host page and make it non-AMP, which might break the testing page.

Comment (lannka) [reply build-system/tasks/prepend-global/index.js]: Looking at the code, seems the change also applies to localhost case.  can you confirm?

Comment (rsimha-amp) [reply build-system/tasks/prepend-global/index.js]: @lannka I don't think this applies to the case where the server is served from `localhost`. If you don't set `AMP_TESTING_HOST`, we do not set `getMode().thirdPartyUrl`, and therefore, default to the old behavior for `localhost`.

Does this make sense?

Comment (rsimha-amp) [reply build-system/tasks/prepend-global/index.js]: @lannka PTAL at the latest commit. In `getAdsLocalhost()` (called when `localDev` is enabled), we're overriding the value of the default 3p ad frame if the developer has explicitly set `AMP_TESTING_HOST`.

@bradfrizzell has confirmed that this fixes the case where ads on the test page were 404ing for a non-localhost server. This does not affect production, or normal testing with a `localhost` server.

**Comment by rsimha-amp** [comment]
It turns out this wasn't fully working on linux. We're seeing this error message, which might be related to the issues being seen in #12666 

```
log.js:324 Error: Non-whitelisted 3p type for custom iframe: a8​​​
   at Log.assert (log.js:318)
   at validateAllowedTypes (integration.js:822)
   at window.draw3p (integration.js:478)
   at frame.max.html:9
```

**Comment by cathyxz** [comment]
@rsimha this doesn't work for cases when the `TESTING_HOST` is `https`. Example: https://github.com/ampproject/amphtml/issues/13869. Do we have to hard code it to `http`? Can we require that `TESTING_HOST` specifies a full URL including the protocol?

**Comment by rsimha** [comment]
@cathyxz This is because we hard-code `http://` in https://github.com/ampproject/amphtml/blob/master/build-system/tasks/prepend-global/index.js#L173. Based on our chat, let's conditionally add the `http://` prefix only if there isn't a prefix already present.
