### PR TITLE
Fix fetch calls with credentials=null

### LINKED ISSUE #3405: amp list and mustache
There are several examples of `amp-list` that also use `mustache`.

For example:

```
<ul>
  <amp-list width=auto height=100 layout=fixed-height
      src="https://ampbyexample.com/json/examples.json">
    <template type="amp-mustache" id="amp-template-id">
      <li><a href={{url}}>{{title}}</a></li>
    </template>
  </amp-list>
</ul>
```
However, none of these examples work WRT the mustache substitution.

Is the reason that this url [(https://ampbyexample.com/json/examples.json)] is not CORS-enabled?

Using the test CORS site [(http://test-cors.org/)] the XHR staus is 200 and status text is OK. The site appears to be CORS-enabled.

We also have activated amp-live-list on [(https://cdn.ampproject.org/experiments.html)].

What additions or corrections are needed to activate these list-mustache examples?

What are we missing?

### PR DESCRIPTION
**Pull request by dvoytenko**
Closes #3405.

### CODE REVIEW

File: src/service/xhr-impl.js [hunk 1]
```diff
@@ -77,6 +77,13 @@ class Xhr {
    * @private
    */
   fetch_(input, opt_init) {
+    dev.assert(typeof input == 'string', 'Only URL supported: %s', input);
+    if (opt_init && opt_init.credentials !== undefined) {
+      // In particular, Firefox does not tolerate `null` values for
```
Comment (erwinmombay) [inline src/service/xhr-impl.js]: Ty for comment

**Comment by erwinmombay** [comment]
@dvoytenko LGTM
