### PR TITLE
🏗🐛 Fail Karma when zero tests are detected

### LINKED ISSUE #16851: Karma is ignoring uncaught errors in tests (it thinks zero tests are run)
For example: https://travis-ci.org/ampproject/amphtml/jobs/405408909#L1772

This should've been a Karma failure.

Edit: Turns out that Karma detected zero tests in the suite. As @cramforce says below, the fix for this is to fail when zero tests are detected.

### PR DESCRIPTION
**Pull request by rsimha**
In the past, Karma used to fail when zero tests were run (`failOnEmptyTestSuite` was `true`). However, with `gulp test --local-changes`, running zero tests became a valid case (like when all tests in a file were skipped), so `failOnEmptyTestSuite` was set to `false`. This resulted failures like the one in #16851 going undetected.

This PR introduces a new mechanism to flag a failure when the total number of tests in a suite (`browser.lastResult.total`) is detected as zero. Note that this still allows for cases where all tests in a suite are skipped on a particular browser (where `browser.lastResult.total` is non-zero).

Fixes #16851

### CODE REVIEW

**Comment by choumx** [comment]
Maybe instead add a trivial unit test that will always be run? This will scale if you add more test options in the future.

**Comment by choumx** [comment]
Per #11494, `failOnEmptyTestSuite` won't fail when running zero tests due to browser-specific skips?

**Comment by rsimha** [comment]
@choumx You're right! >_<

Let me re-think this.

File: build-system/tasks/runtime-test.js [hunk 1]
```diff
@@ -457,6 +457,7 @@ function runTests() {
         log(cyan(test));
       });
     }
+    c.failOnEmptyTestSuite = false;
```
Comment (cramforce) [inline build-system/tasks/runtime-test.js]: Add comment.

**Comment by rsimha** [comment]
@choumx @cramforce I've re-implemented this PR. Karma returns the count of the total number of tests detected in a suite. In the error case, this is zero. In the case where all tests are skipped, the total is still non-zero.

Here are the logs when I injected a failure:
```
START:
HeadlessChrome 0.0.0 (Mac OS X 10.13.6) ERROR
  {
    "message": "Uncaught ReferenceError: describess is not defined\nat /Users/rsimha/src/amphtml/test/functional/test-log.js:31 <- /var/folders/nv/ycwrjg_j32gdz6s542xlxy0m0037zm/T/732dc15073a1239366832db6040ecb65.browserify:74657:1\n\nReferenceError: describess is not defined\n    at Object.require./Users/rsimha/src/amphtml/test/functional/test-log.js.../../src/log (/Users/rsimha/src/amphtml/test/functional/test-log.js:31 <- /var/folders/nv/ycwrjg_j32gdz6s542xlxy0m0037zm/T/732dc15073a1239366832db6040ecb65.browserify:74657:1)\n    at s (/var/folders/nv/ycwrjg_j32gdz6s542xlxy0m0037zm/T/node_modules/browser-pack/_prelude.js:1 <- /var/folders/nv/ycwrjg_j32gdz6s542xlxy0m0037zm/T/732dc15073a1239366832db6040ecb65.browserify:1:262)\n    at test/functional/test-log.js:1:34",
    "str": "Uncaught ReferenceError: describess is not defined\nat /Users/rsimha/src/amphtml/test/functional/test-log.js:31 <- /var/folders/nv/ycwrjg_j32gdz6s542xlxy0m0037zm/T/732dc15073a1239366832db6040ecb65.browserify:74657:1\n\nReferenceError: describess is not defined\n    at Object.require./Users/rsimha/src/amphtml/test/functional/test-log.js.../../src/log (/Users/rsimha/src/amphtml/test/functional/test-log.js:31 <- /var/folders/nv/ycwrjg_j32gdz6s542xlxy0m0037zm/T/732dc15073a1239366832db6040ecb65.browserify:74657:1)\n    at s (/var/folders/nv/ycwrjg_j32gdz6s542xlxy0m0037zm/T/node_modules/browser-pack/_prelude.js:1 <- /var/folders/nv/ycwrjg_j32gdz6s542xlxy0m0037zm/T/732dc15073a1239366832db6040ecb65.browserify:1:262)\n    at test/functional/test-log.js:1:34"
  }
[17:52:41] ERROR: Something went wrong. Zero tests detected by Karma.
rsimha@rsimha-macbookpro2 (2018-07-18-ZeroTests):~/src/amphtml$ 
```

PTAL.

File: build-system/tasks/runtime-test.js [hunk 2]
```diff
@@ -616,8 +616,13 @@ function runTests() {
       console./* OK*/log('travis_fold:start:console_errors_' + sectionMarker);
     }
   }).on('browser_complete', function(browser) {
+    const result = browser.lastResult;
+    // Prevent cases where Karma detects zero tests and still passes. #16851.
+    if (result.total == 0) {
+      log(red('ERROR: Zero tests detected by Karma. Something went wrong.'));
+      process.exit();
```
Comment (cramforce) [inline build-system/tasks/runtime-test.js]: Better to exit explicitly with a non-zero exit code?
