### PR TITLE
🏗✨🐛 Run tests against minified code during PR checks

### LINKED ISSUE #22198: Make sure bundle size checks are run for all push builds
I've seen the odd instance where a Travis push build fails the first stage, and causes problems for all subsequent PRs based on that SHA.

In this example, a PR appears unrelated to validator, so we skipped validator checks during the PR build. It then failed the validator checks during the push build. See https://travis-ci.org/ampproject/amphtml/builds/529555940. This caused a "couldn't find the size of the baseline" failure in the bundle size PR check for all PRs based on the first PR.

We can do two things here:
1. It costs nothing extra to run validator checks for runtime and build system changes in addition to validator changes. We should do so.
2. For push builds, make the bundle size upload step run in the first stage, soon after Dist. This way, it is guaranteed to be run, even if some other check happens to fail. This might require the use of conditional builds in `.travis.yml`.

### PR DESCRIPTION
**Pull request by rsimha**
This PR does the following:
- Does a full `gulp dist --fortesting` during PR jobs
- Runs the bundle size check with the `Dist` job in the `Build` stage
- Runs the validator tests for runtime and build system changes
- Uses minified code for integration tests on sauce labs
- Adds a helper function to `yarn-checks.js`
- Reorganizes `.travis.yml` and renames a couple of files in `build-system/pr-check`

With this, the only tests that use unminified code are the visual diff tests, end-to-end tests, and local integration tests (which measure code coverage)

Fixes #22198

### CODE REVIEW

**Comment by estherkim** [comment]
This is neat! I'm still taking a look, but at first glance it seems like the viewer and shadow environments for E2E tests are having trouble initializing with the dist package. It could be how we're detecting that the environment is ready, or maybe they have a dependency on the uncompiled bits, not sure yet.

File: build-system/pr-check/dist-bundle-size.js [hunk 1]
```diff
@@ -17,34 +17,62 @@
...
-    printChangeSummary();
-    console.log(`${FILELOGPREFIX} Skipping ` + colors.cyan('Dist ') +
-        'because this is a PR build');
+    printChangeSummary(FILENAME);
+    if (buildTargets.has('RUNTIME') ||
+        buildTargets.has('UNIT_TEST') ||
+        buildTargets.has('INTEGRATION_TEST') ||
+        buildTargets.has('BUILD_SYSTEM') ||
+        buildTargets.has('FLAG_CONFIG') ||
+        buildTargets.has('VISUAL_DIFF')) {
```
Comment (danielrozenberg) [inline build-system/pr-check/dist-bundle-size.js]: Why `VISUAL_DIFF`?

File: build-system/pr-check/dist-bundle-size.js [hunk 2]
```diff
@@ -17,34 +17,62 @@
...
+      timedExecOrDie('gulp update-packages');
+      timedExecOrDie('gulp dist --fortesting');
+      timedExecOrDie('gulp bundle-size --on_pr_build');
+      uploadDistOutput(FILENAME);
+    } else {
+      timedExecOrDie('gulp bundle-size --on_skipped_build');
+      console.log(`${FILELOGPREFIX} Skipping ` +
```
Comment (danielrozenberg) [inline build-system/pr-check/dist-bundle-size.js]: nit: can use commas to create spaces instead of `+`s

File: build-system/pr-check/build-targets.js [hunk 3]
```diff
@@ -202,9 +202,8 @@ function areValidBuildTargets(buildTargets, fileName) {
     console.log(fileLogPrefix, colors.red('ERROR:'),
         'Please move these files to a separate PR:',
         colors.cyan(nonFlagConfigFiles.join(', ')));
-    return false;
+    process.exit(1);
```
Comment (estherkim) [inline build-system/pr-check/build-targets.js]: Is there a reason for this change? Node docs recommend against using `process.exit()` directly [(reasons here)](https://nodejs.org/api/process.html#process_process_exit_code)

Comment (estherkim) [reply build-system/pr-check/build-targets.js]: Also I like keeping methods as simple as possible; killing a Node process in `validateBuildTargets()` makes assumptions about the caller and kind of oversteps what the function is supposed to do per the name, which is validate.
