### PR TITLE
Fix broken test-element-stub when run alone.

### LINKED ISSUE #3480: test-stub-element missing required requires
```
Chrome 51.0.2704 (Linux 0.0.0) test-element-stub insert script for amp-ad when script is not included FAILED
	TypeError: element.build is not a function
	    at /tmp/d604d52773fa921a683cdc7505270bc8.browserify:20430:21 <- /usr/local/google/home/dinghongfei/code/amphtml/testing/iframe.js:212:20
Chrome 51.0.2704 (Linux 0.0.0) test-element-stub insert script for amp-embed when script is not included FAILED
	TypeError: element.build is not a function
	    at /tmp/d604d52773fa921a683cdc7505270bc8.browserify:20430:21 <- /usr/local/google/home/dinghongfei/code/amphtml/testing/iframe.js:212:20
Chrome 51.0.2704 (Linux 0.0.0) test-element-stub not insert script when element is not amp-ad amp-embed FAILED
	TypeError: element.build is not a function
	    at /tmp/d604d52773fa921a683cdc7505270bc8.browserify:20430:21 <- /usr/local/google/home/dinghongfei/code/amphtml/testing/iframe.js:212:20
Chrome 51.0.2704 (Linux 0.0.0): Executed 3 of 3 (3 FAILED) ERROR (0.126 secs / 0.096 secs)
```

### PR DESCRIPTION
**Pull request by mkhatib**
Fixes #3480

### CODE REVIEW

File: test/functional/test-element-stub.js [hunk 1]
```diff
@@ -18,6 +18,8 @@ import {ElementStub} from '../../src/element-stub';
 import {createIframePromise} from '../../testing/iframe';
 import {resetExtensionScriptInsertedOrPresentForTesting,}
     from '../../src/insert-extension';
+require('../../extensions/amp-ad/0.1/amp-ad');
```
Comment (lannka) [inline test/functional/test-element-stub.js]: I tried import works as well.

import '../../extensions/amp-ad/0.1/amp-ad';
import '../../extensions/amp-analytics/0.1/amp-analytics';

Comment (mkhatib) [inline test/functional/test-element-stub.js]: Thanks! Done!

**Comment by lannka** [comment]
LGTM
