### PR TITLE
Confirmation message fixed for deactivated experiments

### LINKED ISSUE #1288: Switching an experiment to "off" asks you if you want to enable the experiment.
To reproduce:
1. Go to https://cdn.ampproject.org/experiments.html.
2. Toggle an experiment to 'on'. Accept the confirmation dialog.
3. Toggle an experiment to 'off'. The dialog should show like it does in this screenshot where it asks if you want to enable the experiment:
screen shot 2016-01-04 at 2 29 58 pm

Expected behavior is to use the term "disable" or use something neutral to the state like "Do you want to toggle the experiment ${experiment name}?"

### PR DESCRIPTION
**Pull request by dvoytenko**
Closes #1288.

### CODE REVIEW

File: tools/experiments/experiments.js [hunk 1]
```diff
@@ -195,20 +196,22 @@ function isExperimentOn_(id) {
  * @param {boolean=} opt_on
  */
 function toggleExperiment_(id, name, opt_on) {
+  const currentlyOn = isExperimentOn_(id);
+  const on = opt_on !== undefined ? opt_on : !currentlyOn;
```
Comment (jridgewell) [inline tools/experiments/experiments.js]: Double negation is a pet-peeve. How about `on = opt_on === undefined ? !currentlyOn : optOn`?

Comment (dvoytenko) [inline tools/experiments/experiments.js]: Done.

**Comment by jridgewell** [comment]
LGTM
