### PR TITLE
Resolve macros before encoding for analytics variables

### LINKED ISSUE #21751: `getNameArgs ` in variables.js doesn't understand nested macros
We have a function export function `getNameArgs` that extracts the name from the arguments in our macros. `encodeVars` relies on this function to not encode the arguments to a macro which will later be resolved by UrlReplacementService. This does not work for nested macros and thus the arguments get encoded and everything breaks.

example: 
`encodeVars(SOME_MACRO(abc,123))  == SOME_MACRO(abc,123)`
`encodeVars(SOME_MACRO(abc, OTHER_MACRO(foo)))  == SOME_MACRO(abc%2C%20OTHER_MACRO(foo))`

This could be fixed by altering the regex here to be smart about nested macros.
https://github.com/ampproject/amphtml/blob/bbabe0a9d266a9421a1b527f37fcbd3e06482e72/extensions/amp-analytics/0.1/variables.js#L31

cc/ @ampproject/wg-analytics

### PR DESCRIPTION
**Pull request by micajuine-ho**
Clean PR copy + merge fixes of #22379. Closes #21751.

In amp-analytics, as we recursively call `expandTemplate()`, we want to resolve macros (through `url-replacement-service`) as we encounter them to avoid premature encoding (eg: `QUERY_PARAM(foo, (QUERY_PARAM(bar, default))` should return `default` instead of encoding the second QUERY_PARAM).

There are caveats to this approach, so documentation will be added in this PR to address it. See test cases in `test-variables.js`.

### CODE REVIEW

**Comment by micajuine-ho** [comment]
> LGTM assuming changes are the same. Still some merge conflicts to resolve 🙃

I caused these conflicts :'-)

**Comment by micajuine-ho** [comment]
cc @estherkim  for `presubmit-checks.js`

**Comment by micajuine-ho** [comment]
cc @jridgewell for `string.js`

File: src/string.js [hunk 1]
```diff
@@ -173,6 +173,37 @@ export function trimStart(str) {
...
+ */
+export function asyncStringReplace(str, regex, replacer) {
+  const stringBuilder = [];
+  let lastIndex = 0;
+  str.replace(regex, function() {
+    // String.prototype.replace will pass 3 to n number of arguments to the
+    // callback function based on how many capture groups the regex may or may
+    // not contain. We know that the match will always be first, and the
+    // index will always be second to last.
+    const match = arguments[0];
```
Comment (jridgewell) [inline src/string.js]: Nit: use the parameter instead of grabbing it from `arguments`

File: src/string.js [hunk 2]
```diff
@@ -173,6 +173,37 @@ export function trimStart(str) {
...
+    const matchIndex = arguments[arguments.length - 2];
+    stringBuilder.push(str.slice(lastIndex, matchIndex));
+    // Store the promise in it's eventual string position.
+    const replacementPromise =
+      typeof replacer === 'function'
+        ? replacer.apply(null, arguments)
+        : replacer;
```
Comment (jridgewell) [inline src/string.js]: The type says this is always a function. How do we get to this else branch?

File: src/string.js [hunk 3]
```diff
@@ -173,6 +173,37 @@ export function trimStart(str) {
...
+    stringBuilder.push(replacementPromise);
+    lastIndex = matchIndex + match.length;
```
Comment (jridgewell) [inline src/string.js]: Nit: Move this directly under the slice.

File: src/string.js (hunk 2 above)
Comment (calebcordry) [reply src/string.js]: I think that this is just a bad type on my part, was trying to keep it consistent with `string.replace` where the replacer can be a `{Function|string}`. e.g. test-string.js L170 in this PR.

Comment (jridgewell) [reply src/string.js]: Then we need to check it earlier. We can't support the `string` replacer here, since we've already passed a function to `string.replace()`. But if you check before calling string replace, you can just `Promise.resolve(string.replace(regex, replacment))`.

Comment (calebcordry) [reply src/string.js]: Sorry I don't think I understand the difference. We are only really using native `string.replace` to get the matches & offset? Can you give an example that breaks it?

Comment (jridgewell) [reply src/string.js]: `'t123'.replace(/t(\d+)/g, '$1')`. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_string_as_a_parameter, the string `replacement` value is much more complicated then most realize. Let's either forbid a string, or support it properly.

Comment (calebcordry) [reply src/string.js]: ah thanks, you are totally right. Moving the check sgtm.

Comment (calebcordry) [reply src/string.js]: also @micajuine-ho can we add a test case or two using these "special replacement patterns" :)

File: src/string.js [hunk 4]
```diff
@@ -173,6 +173,38 @@ export function trimStart(str) {
...
+ * @param {string} str
+ * @param {RegExp} regex
+ * @param {Function|string} replacer
+ * @return {!Promise<string>}
+ */
+export function asyncStringReplace(str, regex, replacer) {
+  const stringBuilder = [];
+  let lastIndex = 0;
+  if (typeof replacer === 'string') {
+    stringBuilder.push(Promise.resolve(str.replace(regex, replacer)));
```
Comment (calebcordry) [inline src/string.js]: nit: no need to use stringBuilder here, I think the idea was just `return Promise.resolve(str.replace(...)))` @jridgewell to confirm.

File: test/unit/test-string.js [hunk 5]
```diff
@@ -159,6 +160,72 @@ describe('trimEnd', () => {
...
+    const result = asyncStringReplace('the quick silver fox', /brown/, 'red');
+    return expect(result).to.eventually.equal('the quick silver fox');
+  });
+
+  it('should replace with string as callback', () => {
+    const result = asyncStringReplace('the quick brown fox', /brown/, 'red');
+    return expect(result).to.eventually.equal('the quick red fox');
+  });
+
+  it('should use replacer with special pattern', async () => {
```
Comment (calebcordry) [inline test/unit/test-string.js]: Thank you!

File: src/string.js (hunk 4 above)
Comment (micajuine-ho) [reply src/string.js]: Yeah, that makes sense 👍

File: src/string.js [hunk 6]
```diff
@@ -173,6 +173,38 @@ export function trimStart(str) {
...
 }
 
+/**
+ * Wrapper around String.replace that handles asynchronous resolution.
+ * @param {string} str
+ * @param {RegExp} regex
+ * @param {Function|string} replacer
+ * @return {!Promise<string>}
+ */
+export function asyncStringReplace(str, regex, replacer) {
```
Comment (jridgewell) [inline src/string.js]: LGTM.
