### PR TITLE
🐛 Possible fix for resizing amp-ad beop

### LINKED ISSUE #25687: content.requestResize from amp-ad doesn't update the container
##  What's the issue?

I work at BeOp and we were reported that our `amp-ad` tag didn't work properly.

On http://www.letribunaldunet.fr/insolite/images-exceptionnelles-eruption-nocturne-volcan-krakatoa-video.html/amp the `<amp-ad type="beopinion" />` adding breakpoints to the `content.requestResize` calls in the beop integration (search for `onHeightChange:` in the devtools) with its correct target height but the container never updates. 

## How do we reproduce the issue?

- Go to: http://www.letribunaldunet.fr/insolite/images-exceptionnelles-eruption-nocturne-volcan-krakatoa-video.html/amp
- Go at the end of the article

## What browsers are affected?

All browsers

## Which AMP version is affected?

The version used on the website is 1911121900560.

Thanks in advance for your help.

### PR DESCRIPTION
**Pull request by bloodyowl**
It would appear that the confusion would come from the inverted
parameters:

- `requestResize` has (width, height)
- `onResizeDenied` callback has (height, width)

Attaching requestResize to onResizeDenied would invert the height &
width, and given it reads the width from the #c container, mistaking
them results in the resized container to be `InitialHeight x RequestedHeight`.

Took the occasion to only register `onResizeDenied` once instead of
multiple times.

Closes #25687

### CODE REVIEW

**Comment by zhouyx** [comment]
to @ampproject/wg-ads to review

File: 3p/beopinion.js [hunk 1]
```diff
@@ -87,6 +87,9 @@ function createContainer(global, data) {
  */
 function getBeOpinionAsyncInit(global, accountId) {
   const {context} = global;
+  context.onResizeDenied(function(requestedHeight, requestedWidth) {
+    context.requestResize(requestedWidth, requestedHeight);
```
Comment (lannka) [inline 3p/beopinion.js]: woops. this is pretty brutal. could you add some timeout?

Comment (lannka) [reply 3p/beopinion.js]: never mind, we should add the protection in API: https://github.com/ampproject/amphtml/issues/25894

**Comment by lannka** [comment]
also created another tracker for the error-prone API: https://github.com/ampproject/amphtml/issues/25895

**Comment by lannka** [comment]
tests are failing. please check

**Comment by bloodyowl** [comment]
@lannka I've checked, the error is `context.onResizeDenied is not a function`. is the function only available after some point in time?
