### PR TITLE
Polyfill classList.toggle on IE

### LINKED ISSUE #6347: layout media attribute does not work in IE 11
The media attribute does not seem to work on IE 11. Since the Browser is out of scope for AMP this might not be a high priority issue, but it might be worth investigation since IE 11 still has some coverage (especially on corporate machines)

## How do we reproduce the issue?

1. open IE 11
2. visit https://jsbin.com/kohagif/
3. notice all three carousels are shown

## What browsers are affected?

<= IE 11

## Which AMP version is affected?

Version 1478801557976

### PR DESCRIPTION
**Pull request by mkhatib**
Fixes #6347

### CODE REVIEW

File: src/polyfills/domtokenlist-toggle.js [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+}
+
+/**
+ * Returns true if browser is IE.
+ * @param {!Window} win
+ * @return {boolean}
+ */
+function isIe(win) {
+  const ua = win.navigator.userAgent;
+  return /MSIE/i.test(ua) || /IEMobile/i.test(ua) || /Trident/i.test(ua);
```
Comment (cramforce) [inline src/polyfills/domtokenlist-toggle.js]: Do you really need them all? Trident should be enough.

File: src/polyfills/domtokenlist-toggle.js [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+  }
+}
+
+
+/**
+ * Polyfills `DOMTokenList.prototype.toggle` API in IE.
+ * @param {!Window} win
+ */
+export function install(win) {
+  if (isIe(win) && win.DOMTokenList && win.DOMTokenList.prototype.toggle) {
```
Comment (jridgewell) [inline src/polyfills/domtokenlist-toggle.js]: This overwrites `#toggle` on IE? Their's a bad implementation?

File: src/polyfills/domtokenlist-toggle.js [hunk 3]
```diff
@@ -0,0 +1,64 @@
...
+ * Polyfill for `DOMTokenList.prototype.toggle(token, opt_force)` method.
+ * This is specially important because IE does not support `opt_force` attribute.
+ * See https://goo.gl/hgKNYY for details.
+ * @param {string} token
+ * @param {boolean=} opt_force
+ * @this {DOMTokenList}
+ * @return {boolean}
+ */
+function domTokenListTogglePolyfill(token, opt_force) {
+  if (opt_force !== undefined) {
```
Comment (jridgewell) [inline src/polyfills/domtokenlist-toggle.js]:
```js
const remove = opt_force === undefined ? this.contains(token) : !opt_force;
if (remove) {
  // ...
} else {
  // ...
}

File: src/service/platform-impl.js [hunk 4]
```diff
@@ -79,7 +79,8 @@ export class Platform {
    */
   isIe() {
     return (/MSIE/i.test(this.navigator_.userAgent) ||
```
Comment (jridgewell) [inline src/service/platform-impl.js]: Hoist this function out, import it in the polyfill. Also, let's join the regexes.

File: src/polyfills/domtokenlist-toggle.js (hunk 2 above)
Comment (jridgewell) [inline src/polyfills/domtokenlist-toggle.js]: I don't understand why we're testing for `&& win.DOMTokenList.prototype.toggle`. If they don't have it, don't we want to polyfill it too?

File: src/polyfills/domtokenlist-toggle.js (hunk 1 above)
Comment (mkhatib) [inline src/polyfills/domtokenlist-toggle.js]: I am not 100% sure `Trident` is always used in IE UAs. I am happy to drop the rest, but better safe than sorry?

File: src/service/platform-impl.js (hunk 4 above)
Comment (mkhatib) [inline src/service/platform-impl.js]: Hoist it out in the same file? And import it in `polyfills/domtokenlist-toggle.js`as in:
```javascript
import {isIe} from '../service/platform-impl'
```

I was worried this might mess up some dependencies but this works for me otherwise.

File: src/polyfills/domtokenlist-toggle.js (hunk 3 above)
Comment (mkhatib) [inline src/polyfills/domtokenlist-toggle.js]: Done

**Comment by mkhatib** [comment]
PTAL 👀

File: src/service/platform-impl.js (hunk 4 above)
Comment (mkhatib) [inline src/service/platform-impl.js]: This is causing a circular-dep because we're importing `polyfills` in `service.js` (or at least this is what I think the following error is)

```
src/service/platform-impl.js:17: ERROR - required "module$src$service" namespace not provided yet
import {fromClass} from '../service';
```

@camelburrito suggested we move it to a `user-agent.js` file and import it into both of them. You're ok with that?

File: src/service/platform-impl.js [hunk 5]
```diff
@@ -18,6 +18,16 @@ import {fromClass} from '../service';
 
 
 /**
+ * Returns true if the userAgent represents an IE browser.
+ * @param {string} userAgent
+ * @return {boolean}
+ */
+export function isIe(userAgent) {
+  return /Trident|MSIE|IEMobile/i.test(userAgent);
```
Comment (jridgewell) [inline src/service/platform-impl.js]: I always thought you had to use parenthesis to use an pipe!

File: src/service/platform-impl.js (hunk 4 above)
Comment (jridgewell) [inline src/service/platform-impl.js]: Fine with me.

File: src/polyfills/domtokenlist-toggle.js [hunk 6]
```diff
@@ -0,0 +1,49 @@
...
+}
+
+
+/**
+ * Polyfills `DOMTokenList.prototype.toggle` API in IE.
+ * @param {!Window} win
+ */
+export function install(win) {
+  const ua = win.navigator.userAgent;
+  if (isIe(ua) && win.DOMTokenList && win.DOMTokenList.prototype.toggle) {
```
Comment (jridgewell) [inline src/polyfills/domtokenlist-toggle.js]: https://github.com/ampproject/amphtml/pull/6400#discussion_r90308940. Shouldn't we always be polyfilling?

File: src/polyfills/domtokenlist-toggle.js (hunk 2 above)
Comment (mkhatib) [inline src/polyfills/domtokenlist-toggle.js]: They have `toggle` but not the full implementation. Their implementation doesn't have the 2nd `force` parameter. I am not trying to polyfill the missing toggle but I guess we can drop that check and polyfill it regardless.

File: src/service/platform-impl.js (hunk 4 above)
Comment (mkhatib) [inline src/service/platform-impl.js]: Went with duping code here to remove dependency from polyfill on our sources.

**Comment by mkhatib** [comment]
@jridgewell PTAL 👀

File: test/functional/test-polyfill-domtokenlist-toggle.js [hunk 7]
```diff
@@ -0,0 +1,103 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+import {install} from '../../src/polyfills/domtokenlist-toggle';
+import {toArray} from '../../src/types';
+import * as sinon from 'sinon';
+
+
+describe('DOMTokenList.toggle', () => {
```
Comment (camelburrito) [inline test/functional/test-polyfill-domtokenlist-toggle.js]: use describes?

**Comment by camelburrito** [comment]
LGTM except for the tests.
