### PR TITLE
🏗🐛 Rename `gulp changelog` flag `--version` to `--tag`, since `--version` is reserved by `gulp-cli`

### LINKED ISSUE #17513: `gulp changelog` is broken because it uses the reserved flag `--version`
`gulp changelog` uses a flag called `--version`. This is bad, because the flag is reserved for use by `gulp-cli`, so the `changelog` task is never executed when `--version` is passed in. 

We must use a different flag, like `--tag`.

### PR DESCRIPTION
**Pull request by rsimha**
Fixes the use of commands like...
```
 gulp changelog --type canary --version xxxxxxxxxxxxxx
```
... which don't run correctly as part of the default AMP developer workflow.

Fixes #17513

### CODE REVIEW

File: build-system/tasks/changelog.js [hunk 1]
```diff
@@ -117,7 +117,7 @@ function changelog() {
  * @return {!Promise}
  */
 function getGitMetadata() {
-  if (!argv.version) {
+  if (!argv.tag) {
```
Comment (erwinmombay) [inline build-system/tasks/changelog.js]: lets maintain both for now

**Comment by erwinmombay** [comment]
LGTM
