### PR TITLE
Fix getAdContainer potential crash when the body element is called <amp-body>

### LINKED ISSUE #12912: Shadow Dom - advertising div is not collapsing
## What's the issue?
When delivered inside a PWA through shadow dom advertising div is not collapsing

schermata 2018-01-19 alle 11 26 55

## How do we reproduce the issue?
It's possible to reproduce the issue here:
https://rep.repubblica.it/pwa/commento/2018/01/10/news/il_galateo_di_serracchiani_per_il_bon_ton_dei_sindaci-186240380/

## What browsers are affected?
FF always anche Chrome sometimes depending on the speed of the scrolling

## Which AMP version is affected?
Version 1516337355291
.

### PR DESCRIPTION
**Pull request by danielrozenberg**
Fixes #12912

The function `getAdContainer` in `ad-helper.js` crashes when the `<body>` tag is renamed to `<amp-body>`, which happens when the AMP document is embedded in a shadow root in Firefox (I'm not sure why this function works in Chrome. Do we not rename the tag to `<amp-body>` in that case?)

In any case, rewriting the while loop that goes up the tree until it finds a "blessed" container element, body, or "ran out of elements" would fix this behaviour.

PATAL at the above function, `isAdPositionAllowed`, which I haven't modified, and let me know if you think this also needs to be fixed to catch that case.

### CODE REVIEW

File: src/ad-helper.js [hunk 1]
```diff
@@ -82,13 +82,13 @@ export function isAdPositionAllowed(element, win) {
  */
 export function getAdContainer(element) {
   if (element[AD_CONTAINER_PROP] === undefined) {
-    let el = element;
-    do {
-      el = el.parentElement;
+    let el = element.parentElement;
+    while (el && el.tagName != 'BODY') {
```
Comment (lannka) [inline src/ad-helper.js]: a safer looping 👍 

shall we remove `el.tagName != 'BODY'` as well to reduce confusion?

Comment (danielrozenberg) [reply src/ad-helper.js]: I wasn't sure how important that might be. My hunch says that if we remove this the loop should at most run one more iteration (for the `<html>` element) but how does this work with shadow roots in all browsers? I feel like it's safer to leave this in unless someone more knowledgeable than me says otherwise :)
