### PR TITLE
amp-bind: Support range, checkbox, and radio inputs 

### LINKED ISSUE #7765: Custom slider w/ amp-bind
Copied from thread:

So we already support the "change" event in AMP actions, we just need a bit extra to pass the slider value to amp-bind.

E.g. <input type="range" on="change:AMP.setState(myValue=event.value)">

`event.value` is the part that doesn't work yet, but should be straightforward to add.

/cc @choumx

### PR DESCRIPTION
**Pull request by kmh287**
This PR adds support for amp-bind (and actions as a whole) to access the details of a value change on a range input, specifically `min`, `max`, and `value`.

In order to pass these values through on 'change' events, I've replaced the browser-generated event passed through to `action#trigger` with the custom event we use elsewhere when generating events. 

@dvoytenko Dima, you're much more familiar with this code than I am. Is there any code that depends on the events passed through for 'change' events to have properties from the browser-generated event?

Fixes #7765 

/to @choumx @dvoytenko 
/cc @ericlindley-g

### CODE REVIEW

File: src/service/action-impl.js [hunk 1]
```diff
@@ -152,11 +158,33 @@ export class ActionService {
...
+    }
+  }
+
+  getChangeDetails_(event) {
+    const details = {};
+    const target = event.target;
+    if (event.target.tagName.toLowerCase() === 'input') {
+      const inputType = target.getAttribute('type');
+      const fieldsToInclude = WHITELISTED_INPUT_DATA_[inputType];
+      // TODO(kmh287): Cast numeric values to numbers?
```
Comment (dvoytenko) [inline src/service/action-impl.js]: Why TODO if it's straightforward and likely necessary?

File: src/service/action-impl.js [hunk 2]
```diff
@@ -152,11 +158,33 @@ export class ActionService {
...
+    } else if (name == 'change') {
+      this.root_.addEventListener(name, event => {
+        const target = event.target;
+        const changeEvent = this.getChangeDetails_(event);
+        this.trigger(dev().assertElement(target), name, changeEvent);
+      });
+    }
+  }
+
+  getChangeDetails_(event) {
```
Comment (dvoytenko) [inline src/service/action-impl.js]: jsdoc

Comment (kmh287) [inline src/service/action-impl.js]: thanks

File: src/service/action-impl.js (hunk 1 above)
Comment (kmh287) [inline src/service/action-impl.js]: I think it's more complicated than it may initially seem. Since we'll likely support more input types in the future, we'll need to keep track of which attributes should and shouldn't be cast. We would also need to make clear to users of bind which values on the events are numbers and which are strings. 

This is definitely solvable with documentation, but I thought it would be worth discussing before implementing it.

Comment (choumx) [inline src/service/action-impl.js]: It may suffice to convert values that look like numbers, i.e. `parseFloat(value) == value`.

File: src/service/action-impl.js [hunk 3]
```diff
@@ -152,11 +158,39 @@ export class ActionService {
...
+  /**
+   * Generate custom event from browser `change` event.
+   * @param {!Event} event A `change` event.
+   * @return {!Event} A custom event with a details property containing the
+   *    relevant information for the change that generated the initial event.
+   */
+  getChangeDetails_(event) {
+    const details = {};
+    const target = event.target;
+    if (event.target.tagName.toLowerCase() === 'input') {
```
Comment (choumx) [inline src/service/action-impl.js]: [Change events](https://developer.mozilla.org/en-US/docs/Web/Events/change) are also fired by `<select>` and `<textarea>` elements, which we may want to support in the future. Recommend expanding the lookup table to include tag name.

File: test/functional/test-action.js [hunk 4]
```diff
@@ -969,6 +966,31 @@ describe('Core events', () => {
     const element = {tagName: 'target2', nodeType: 1};
     const event = {target: element};
     handler(event);
-    expect(action.trigger).to.have.been.calledWith(element, 'change', event);
+    expect(action.trigger).to.have.been.calledWith(
+        element,
+        'change',
+        sinon.match.any);
```
Comment (choumx) [inline test/functional/test-action.js]: Can you match the `target` prop at least?

File: test/functional/test-action.js [hunk 5]
```diff
@@ -969,6 +966,31 @@ describe('Core events', () => {
...
+    element.setAttribute('min', '0');
+    element.setAttribute('max', '10');
+    element.setAttribute('value', '5');
+    const event = {target: element};
+    handler(event);
+    expect(action.trigger).to.have.been.calledWith(
+      element,
+      'change',
+      sinon.match.any);
+    // Doesn't play well with sinon matchers
```
Comment (choumx) [inline test/functional/test-action.js]: What about a property or custom matcher? http://sinonjs.org/releases/v1.17.7/matchers

File: src/service/action-impl.js (hunk 3 above)
Comment (kmh287) [inline src/service/action-impl.js]: I'm not sure that can be done in a clean way. For the `input` tag we need to switch on the input type, but I don't think we'll need to do that for the others. Maybe it would be best to reevaluate when we implement support for `<select>` and `<textarea>`?

File: src/service/action-impl.js (hunk 1 above)
Comment (kmh287) [inline src/service/action-impl.js]: Sure. Do you think we should do the same for amp-selector's options?

File: test/functional/test-action.js (hunk 4 above)
Comment (kmh287) [inline test/functional/test-action.js]: The custom event doesn't have the target on it, but the target is still passed through as the first argument to `trigger`

File: test/functional/test-action.js (hunk 5 above)
Comment (kmh287) [inline test/functional/test-action.js]: custom matcher :+1:

File: src/service/action-impl.js [hunk 6]
```diff
@@ -46,6 +47,11 @@ const ELEMENTS_ACTIONS_MAP_ = {
   'AMP': ['setState'],
 };
 
+/** @const {!Object<string, !Array<string>>} */
+const WHITELISTED_INPUT_DATA_ = {
```
Comment (aghassemi) [inline src/service/action-impl.js]: I was just about to create an FR for something similar to this! Love it when what I need is already done :)

Well, I actually needed `checked` for `radio` and `checkbox` as well. Could we please those in this PR as well? Thanks!

File: src/service/action-impl.js [hunk 7]
```diff
@@ -152,11 +158,40 @@ export class ActionService {
...
       });
-    } else if (name == 'submit' || name == 'change') {
+    } else if (name == 'submit') {
       this.root_.addEventListener(name, event => {
         this.trigger(dev().assertElement(event.target), name, event);
       });
+    } else if (name == 'change') {
+      this.root_.addEventListener(name, event => {
+        const target = event.target;
+        const changeEvent = this.getChangeDetails_(event);
```
Comment (aghassemi) [inline src/service/action-impl.js]: I highly recommend adding a `detail` property to the existing `event` object instead of cloning it into a custom event. Components that register actions may need access to the original event.

File: src/service/action-impl.js (hunk 6 above)
Comment (kmh287) [inline src/service/action-impl.js]: Good idea. Done.

File: test/functional/test-action.js (hunk 4 above)
Comment (kmh287) [inline test/functional/test-action.js]: Reverted after ali's suggestion

File: src/service/action-impl.js [hunk 8]
```diff
@@ -155,14 +162,41 @@ export class ActionService {
...
+    const detail = {};
+    const target = event.target;
+    if (event.target.tagName.toLowerCase() === 'input') {
+      const inputType = target.getAttribute('type');
+      const fieldsToInclude = WHITELISTED_INPUT_DATA_[inputType];
+      if (fieldsToInclude) {
+        fieldsToInclude.forEach(field => {
+          const value = target[field];
+          const valueAsNumber = parseFloat(value);
+          detail[field] = valueAsNumber || value;
```
Comment (dvoytenko) [inline src/service/action-impl.js]: That would overwrite `0` with `'0'`.

Comment (kmh287) [inline src/service/action-impl.js]: thanks for catching this

File: src/service/action-impl.js (hunk 1 above)
Comment (dvoytenko) [inline src/service/action-impl.js]: TBH it was initially a question. I'm not sure what's the right thing to do here. Does anyone have any other opinion? There's a bit of a conflict here before us preferring to operate with the actual types and (looks like) `input/range` values appear to be strings in Chrome? Am I seeing this right? This is actually pretty strange and might be worth confirming. If I read the spec right, they all should be fp numbers already: https://www.w3.org/TR/html5/forms.html#range-state-(type=range)

Might be worth filing a bug against Chrome and proceed with what we'd prefer downstream. One option is to add types in the `WHITELISTED_INPUT_DATA_` config. Alternatively, we can sniff for typed values. E.g. `!isNaN(input.valueAsNumber)` or such.

Comment (kmh287) [inline src/service/action-impl.js]: @dvoytenko 

Just confirmed, `min` and `max` are strings. [Image](https://drive.google.com/a/ampproject.org/file/d/0B2blAKCEOPg-cm0yMEVCMmRVbjA/view?usp=sharing)

File: src/service/action-impl.js [hunk 9]
```diff
@@ -155,14 +162,41 @@ export class ActionService {
...
+    const detail = {};
+    const target = event.target;
+    if (event.target.tagName.toLowerCase() === 'input') {
+      const inputType = target.getAttribute('type');
+      const fieldsToInclude = WHITELISTED_INPUT_DATA_[inputType];
+      if (fieldsToInclude) {
+        fieldsToInclude.forEach(field => {
+          const value = target[field];
+          const valueAsNumber = parseFloat(value);
+          detail[field] = isNaN(valueAsNumber) ? value : valueAsNumber;
```
Comment (aghassemi) [inline src/service/action-impl.js]: can't do this. `parseFloat('3XYZ')`  returns number `3`. (y tho? cauz JS!)

`isNaN` however works nicely with strings and can be used to determine if a string is a number. So do this instead:
`detail[field] = isNaN(value) ? value : parseFloat(value);`

Comment (aghassemi) [inline src/service/action-impl.js]: ugh `isNaN('') == false` so you need to handle the case where value is: `''`, `'   '`, `true`, `false`, `null` separately as both `isNaN` and `Number()` behave weirdly for those values. 

(Also assumption that `value` is always a string is wrong since we are reading property and not necessarily an attribute)

Comment (kmh287) [inline src/service/action-impl.js]: @aghassemi I'm going to put the type on the map and then coerce based on the expected type.

File: src/service/action-impl.js (hunk 1 above)
Comment (choumx) [inline src/service/action-impl.js]: My guess is that they're strings to be able support floating point, integral and date-time values. All other numeric-type attributes are more straightforward: https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement

File: src/service/action-impl.js [hunk 10]
```diff
@@ -49,6 +49,21 @@ const ELEMENTS_ACTIONS_MAP_ = {
...
+    min: 'number',
+    max: 'number',
+    value: 'number',
+  },
+  radio: {
+    checked: 'boolean',
+  },
+  checkbox: {
+    checked: 'boolean',
+  },
```
Comment (choumx) [inline src/service/action-impl.js]: Nit: Use string literals for keys that should be constants. This future-proofs against Closure renaming.

File: src/service/action-impl.js [hunk 11]
```diff
@@ -49,6 +49,21 @@ const ELEMENTS_ACTIONS_MAP_ = {
...
 
+/** @const {!Object<string, !Object<string, string>>} */
+const WHITELISTED_INPUT_DATA_ = {
+  range: {
+    min: 'number',
+    max: 'number',
+    value: 'number',
+  },
+  radio: {
+    checked: 'boolean',
```
Comment (choumx) [inline src/service/action-impl.js]: The `checked` property should always return a boolean so casting in that case may be a waste.

File: src/service/action-impl.js [hunk 12]
```diff
@@ -49,6 +49,21 @@ const ELEMENTS_ACTIONS_MAP_ = {
   'AMP': ['setState'],
 };
 
+/** @const {!Object<string, !Object<string, string>>} */
+const WHITELISTED_INPUT_DATA_ = {
+  range: {
+    min: 'number',
+    max: 'number',
+    value: 'number',
```
Comment (choumx) [inline src/service/action-impl.js]: Nit: You can use an int-based enum to reduce the number of string constants in the min build.

File: examples/bind/forms.amp.html [hunk 13]
```diff
@@ -19,18 +19,26 @@
...
+            <input type="text" name="name" id="name1" required>
+          </label>
+          <label>
+            <span>Your email</span>
+            <input type="email" name="email" id="email1" required>
           </label>
           <label>
-              <span>Your email</span>
-              <input type="email" name="email" id="email1" required>
+            <span>Your Orffer</span>
```
Comment (kmh287) [inline examples/bind/forms.amp.html]: thanks

File: src/service/action-impl.js (hunk 12 above)
Comment (kmh287) [inline src/service/action-impl.js]: done

File: src/service/action-impl.js (hunk 10 above)
Comment (kmh287) [inline src/service/action-impl.js]: done

File: src/service/action-impl.js (hunk 11 above)
Comment (kmh287) [inline src/service/action-impl.js]: I think the guarantee of passing in a boolean is worth the cost of the cast.

**Comment by kmh287** [comment]
@choumx I'm still on the fence about casting strings that look like numbers. I'm concerned that returning different types based on the user's input is counter intuitive. (particularly if we decide to support text inputs with these events as well.

As for documentation, I've created another PR: #8569
