### PR TITLE
🏗 Use in-process `gulp` server during `visual-diff` and `e2e`

### LINKED ISSUE #25613: `gulp visual-diff` fails to start server on macOs
Running `gulp visual-diff` on `master` yields the following error message on MacOS Mojave 10.14.6: 

```
Error: Failed to start a web server: Error: connect ECONNREFUSED 127.0.0.1:8000
    at log (/Users/carolineliu/amp/amphtml/build-system/tasks/visual-diff/helpers.js:73:13)
    at performVisualTests (/Users/carolineliu/amp/amphtml/build-system/tasks/visual-diff/index.js:747:5)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

This appears to be failing at [`launchWebServer`](https://github.com/ampproject/amphtml/blob/3c9075504a45bf263dedb3b387170a9d937ea20f/build-system/tasks/visual-diff/index.js#L148). Directly executing `gulp serve --compiled --host localhost --port 8000` works, so the issue is not suspected to be with the `gulp serve` command itself.

### PR DESCRIPTION
**Pull request by rsimha**
In order to support lazy-building, the `gulp serve` task was recently re-written to be an in-process server (instead of a `nodemon` child process). See #24325. This PR modifies the `visual-diff` and `e2e` tasks to use this new server startup mode.

**Highlights:**
- Rewrites `launchWebServer_()` in `visual-diff` and `e2e` to directly call `startServer()`
- Refactors `gulp serve` code to support non-default startup modes like `--compiled` or `--rtv <15 digits>`, and prevent lazy building during tests
- Fixes a bug in the `--rtv` case, where the mode was being set to `rtv` instead of the actual 15 digits

Fixes #25613

### CODE REVIEW

File: build-system/tasks/serve.js [hunk 1]
```diff
@@ -117,8 +127,11 @@ function resetServerFiles() {
  * Stops the currently running server
  */
 function stopServer() {
-  connect.serverClose();
-  log(green('Stopped server at'), cyan(url));
+  if (url) {
+    connect.serverClose();
```
Comment (danielrozenberg) [inline build-system/tasks/serve.js]: Is this synchronous?

File: build-system/tasks/visual-diff/index.js [hunk 2]
```diff
@@ -137,49 +139,10 @@ async function launchPercyAgent() {
...
-    host: HOST,
-    port: PORT,
-    retries: WEBSERVER_TIMEOUT_RETRIES, // retry timeout defaults to 1 sec
-  })
-    .on('connected', () => {
-      return resolver(webServerProcess_);
-    })
-    .on('timeout', rejecter);
-  return deferred;
+  await startServer({host: HOST, port: PORT}, argv.webserver_debug);
```
Comment (estherkim) [inline build-system/tasks/visual-diff/index.js]: Add `{compiled: true}` serving mode

File: build-system/tasks/e2e/index.js [hunk 3]
```diff
@@ -48,33 +45,12 @@ function buildRuntime_() {
   execOrDie(`gulp dist --fortesting --config ${argv.config}`);
 }
 
-function launchWebServer_() {
-  log('Launching webserver at', cyan(`http://${HOST}:${PORT}`) + '...');
-  webServerProcess_ = execScriptAsync(
-    `gulp serve --compiled --host ${HOST} --port ${PORT}`,
-    {stdio: 'ignore'}
```
Comment (estherkim) [inline build-system/tasks/e2e/index.js]: I believe `{stdio: 'ignore'}` was needed to prevent Travis from hanging due to a node process still running. Same applies to the visual-diff task.

File: build-system/tasks/serve.js [hunk 4]
```diff
@@ -30,29 +30,29 @@ const {
...
+let url = null;
+let {quiet} = argv;
 
 const serverFiles = globby.sync(['build-system/server/**']);
 
 /**
- * Logs the server's mode (based on command line arguments).
+ * Logs the server's mode.
  */
 function logServeMode() {
```
Comment (estherkim) [inline build-system/tasks/serve.js]: What if we move this to `app-utils` so that you don't have to import `isRtvMode` or `getServeMode` just for this method?

File: build-system/tasks/e2e/index.js (hunk 3 above)
Comment (caroqliu) [reply build-system/tasks/e2e/index.js]: If it helps, I tried running `gulp visual-diff` twice and both times it appeared to be hanging after tests completed:

Screen Shot 2019-11-18 at 3 41 10 PM

Comment (rsimha) [reply build-system/tasks/e2e/index.js]: Both useful comments. I'm seeing this too. Lemme see if I can find a fix.

Comment (rsimha) [reply build-system/tasks/e2e/index.js]: Turns out that `visual-diff` and `e2e` were triggering the lazy build workflow, causing the server to not fully shutdown after all tests were run. I've refactored the server code to prevent this, and initial testing suggests the problem is fixed.

**Comment by rsimha** [comment]
PR updated as follows:

- Fixed stalling tasks by refactoring tests to not trigger lazy build workflow
- Reinstated @danielrozenberg's changes to `build-system/common/exec.js` (it was a red herring)

Verified everything passes with these changes:

**Linux (Travis)**
- **E2E:** https://travis-ci.org/ampproject/amphtml/jobs/613791699#L2112

Screen Shot 2019-11-18 at 8 59 56 PM

- **Visual Diff:** https://travis-ci.org/ampproject/amphtml/jobs/613791695#L2428

Screen Shot 2019-11-18 at 8 59 38 PM

**Mac (Local)**

- **E2E:**

Screen Shot 2019-11-18 at 9 02 06 PM

- **Visual Diff:**

Screen Shot 2019-11-18 at 9 01 38 PM

File: build-system/server/app-utils.js [hunk 5]
```diff
@@ -14,31 +14,60 @@
...
  * @return {string}
  */
 function getServeMode() {
-  const argv = minimist(process.argv.slice(2), {string: ['rtv']});
-  if (argv.compiled) {
-    return 'compiled';
-  }
-  if (argv.cdn) {
-    return 'cdn';
+  return serveMode;
```
Comment (estherkim) [inline build-system/server/app-utils.js]: Is this needed anymore?

Comment (rsimha) [reply build-system/server/app-utils.js]: Yes, because there are several [call sites](https://github.com/ampproject/amphtml/search?utf8=%E2%9C%93&q=getServeMode) across all server code.
