### PR TITLE
Ad test failures

### LINKED ISSUE #8965: Ads test failures
```
Chrome 45.0.2454 (Linux 0.0.0) amp-ad-network-adsense-impl   #getAdUrl with multiple slots FAILED
	Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
................................................................................
......
Chrome 45.0.2454 (Linux 0.0.0) amp-ad-3p-impl preconnectCallback should add preconnect and prefech to DOM header FAILED
	Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
..........................
Chrome 45.0.2454 (Linux 0.0.0) amp-ad-xorigin-iframe-handler Initialized iframe should be able to use embed-state API FAILED
	Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
................
Chrome 45.0.2454 (Linux 0.0.0): Executed 3495 of 5047 (3 FAILED) (skipped 55) DISCONNECTED (12 mins 47.278 secs / 1 min 53.179 secs)
```

### PR DESCRIPTION
**Pull request by jridgewell**
3 things:

- Skips A4A's `with multiple slots` test (/cc @tdrl)
- Improves `createIframeWithMessageStub` so that exact matches are not necessary (callback can be provided to check/assert the message is the intended one)
  - This should help us determine if it's not receiving the `embed-size` messages, or if it's not getting the exact right string back
- Fixes the shoddy `amp-ad-3p-impl preconnectCallback` test

Closes #8965 and competes with #8968.

### CODE REVIEW

File: testing/iframe.js [hunk 1]
```diff
@@ -319,25 +320,42 @@ export function createIframeWithMessageStub(win) {
...
-  element.expectMessageFromParent = msg => {
-    return new Promise(resolve => {
-      const listener = event => {
-        let expectMsg = msg;
-        let actualMsg = event.data.receivedMessage;
-        if (typeof expectMsg !== 'string') {
-          expectMsg = JSON.stringify(expectMsg);
-          actualMsg = JSON.stringify(actualMsg);
+  element.expectMessageFromParent = (type, callback) => {
+    if (typeof type === 'function') {
```
Comment (zhouyx) [inline testing/iframe.js]: this is so confusing... 😖  why can't weseparatee them to two functions?

File: test/functional/test-iframe-stub.js [hunk 2]
```diff
@@ -19,11 +19,12 @@ import {
   expectPostMessage,
 } from '../../testing/iframe';
 
-describe('test-iframe-createIframeWithMessageStub', () => {
+describe.only('test-iframe-createIframeWithMessageStub', () => {
```
Comment (zhouyx) [inline test/functional/test-iframe-stub.js]: nit: remove only

File: extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js [hunk 3]
```diff
@@ -216,7 +216,8 @@ describes.sandboxed('amp-ad-network-adsense-impl', {}, () => {
     });
     // Not using arrow function here because otherwise the way closure behaves
     // prevents me from calling this.timeout(5000).
-    it('with multiple slots', function() {
+    // TODO(@tdrl, #8965): Make this pass reliably on Travis.
+    it.skip('with multiple slots', function() {
```
Comment (zhouyx) [inline extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js]: what about we only skip it on old chrome?

File: extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js [hunk 4]
```diff
@@ -179,10 +180,10 @@ describe('amp-ad-3p-impl', () => {
   });
 
   describe('preconnectCallback', () => {
-    it('should add preconnect and prefech to DOM header', done => {
+    it('should add preconnect and prefech to DOM header', () => {
       ad3p.buildCallback();
       ad3p.preconnectCallback();
-      setTimeout(() => {
+      return whenFirstVisible.then(() => {
```
Comment (zhouyx) [inline extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js]: is this the reason why the test is flaky? I can't see why

Comment (jridgewell) [inline extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js]: Could be 1 of two things:

- [Assertion](https://github.com/ampproject/amphtml/blob/28dcf17331237772eceb822797c8a46b96c72f12/extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js#L190-L194) is being [swallowed](https://github.com/ampproject/amphtml/issues/8966) (because this [callback](https://github.com/ampproject/amphtml/blob/28dcf17331237772eceb822797c8a46b96c72f12/src/preconnect.js#L200-L214) has not fired yet)
- `setTimeout` has been throttled

File: extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js (hunk 3 above)
Comment (jridgewell) [inline extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js]: I prefer this to make A4A fix it faster. 😈

File: testing/iframe.js (hunk 1 above)
Comment (jridgewell) [inline testing/iframe.js]: It's argument reordering, so that you could pass a type, callback, or type and callback.

Comment (zhouyx) [inline testing/iframe.js]: Yeah, I think it's not very straightforward for people to use in tests. For example I would have to go through the code to figure out what a callback function should look like.
Maybe update the comment for the function description? At least we should document it clear.

File: extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js (hunk 3 above)
Comment (zhouyx) [inline extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js]: LOL.  so 😈 !

File: extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js (hunk 4 above)
Comment (zhouyx) [inline extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js]: Wow! that's a good catch!!!

File: testing/iframe.js (hunk 1 above)
Comment (jridgewell) [inline testing/iframe.js]: Try this.

File: extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js (hunk 4 above)
Comment (lannka) [inline extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js]: @jridgewell could you further explain what does "setTimeout is throttled" mean?

File: testing/iframe.js [hunk 5]
```diff
@@ -318,26 +319,46 @@ export function createIframeWithMessageStub(win) {
...
-          resolve(msg);
+          reject(e);
         }
-      };
+      }
       win.addEventListener('message', listener);
     });
   };
+
+  function returnTrue() {
```
Comment (lannka) [inline testing/iframe.js]: is this used?

File: testing/iframe.js [hunk 6]
```diff
@@ -318,26 +319,46 @@ export function createIframeWithMessageStub(win) {
...
-          expectMsg = JSON.stringify(expectMsg);
-          actualMsg = JSON.stringify(actualMsg);
+  element.expectMessageFromParent = (callbackOrType) => {
+    let filter;
+    if (typeof callbackOrType === 'string') {
+      filter = (data) => {
+        return 'type' in data && data.type == type;
+      };
+    } else if (!callback) {
+      filter = callbackOrType;
```
Comment (lannka) [inline testing/iframe.js]: when is this get called?

File: testing/iframe.js (hunk 1 above)
Comment (zhouyx) [inline testing/iframe.js]: I like it. Note: I just found one thing, the callback function is only used for testing `expectMessageFromParent` function. Do we really need it?

File: testing/iframe.js [hunk 7]
```diff
@@ -318,26 +319,46 @@ export function createIframeWithMessageStub(win) {
...
-        if (typeof expectMsg !== 'string') {
-          expectMsg = JSON.stringify(expectMsg);
-          actualMsg = JSON.stringify(actualMsg);
+  element.expectMessageFromParent = (callbackOrType) => {
+    let filter;
+    if (typeof callbackOrType === 'string') {
+      filter = (data) => {
+        return 'type' in data && data.type == type;
+      };
+    } else if (!callback) {
```
Comment (lannka) [inline testing/iframe.js]: callback?

File: extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js (hunk 4 above)
Comment (jridgewell) [inline extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js]: Chrome throttles weirdly. 🤷‍♂️

File: testing/iframe.js (hunk 7 above)
Comment (jridgewell) [inline testing/iframe.js]: Whoops.

**Comment by zhouyx** [comment]
LGTM to @lannka
