### PR TITLE
🐛Fix broken args in expander.

### LINKED ISSUE #20816: Nested macro bug
cc @ampproject/wg-analytics 

In the following example, nested macro doesn't work properly

`$REPLACE(CLIENT_ID(navigationStart)test, 'AD_', '')"`
resolves to `client_id`, note that `test` is dropped

`$REPLACE(testCLIENT_ID(navigationStart), 'AD_', '')"`
resolves to `test`, note that client_id is dropped

`$REPLACE(NAV_TIMING(navigationStart, loadEventStart), 'AD_', '')"`
resolves to empty string, note that the nav_timing number is dropped. 

I believe there are two issues here
1. Nested macro doesn't handle number properly
2. Nested macro doesn't handle concat string properly

### PR DESCRIPTION
**Pull request by calebcordry**
The expander works by walking the input string. When it sees a macro it pushes the promise of a value (async) or the immediate resulting value (sync) into an array, that will be joined at the end of string or the next `)`. 

For example in a async call:
`'abcMACROdef' => ['abc', Promise, 'def'] `

This can become a problem in nested context because this array is what is passed to the function that resolves the function through `function.apply`. 
`'OUTER(INNER)' => OUTER.apply([INNER]) // good`
`'OUTER(foo, INNER)' => OUTER.apply(['foo', INNER]) // good`  
`'OUTER(fooINNER, bar)' => OUTER.apply(['foo', INNER, 'bar']) // bad - three args passed to OUTER instead of two`

This fix changes this to use an array of arrays, where we can keep track of each argument in its own array, and therefore pass the correct number of args. The inner array(s) are then flattened before passing to `.apply()`. 

`'OUTER(fooINNER, bar)' => [['foo', INNER], ['bar']] => flatten =>` 
`OUTER.apply(['fooINNER', 'bar'] // good :)` 

An added bonus is that this casts any argument to a string before invoking the function :) This should help us with any changes to preserve types.

Also added a bunch of comments since this code is hairy, and its fresh in my mind for now.
  
Closes #20816

### CODE REVIEW

File: src/service/url-expander/expander.js [hunk 1]
```diff
@@ -168,20 +172,23 @@ export class Expander {
           urlIndex = match.stop + 1;
           match = matches[++matchIndex];
 
+          // Collect any chars that may be prefixing the macro, if we are in
+          // a nested context trim the args.
+          if (builder.trim().length) {
```
Comment (zhouyx) [inline src/service/url-expander/expander.js]: nit: Since we parse the string from left to right could we append the builder to result first before we handle with the matched binding.

File: src/service/url-expander/expander.js [hunk 2]
```diff
@@ -142,14 +142,18 @@ export class Expander {
 
     const evaluateNextLevel = encode => {
       let builder = '';
-      const results = [];
+      let results = [];
+      const args = [];
 
       while (urlIndex < url.length && matchIndex <= matches.length) {
         if (match && urlIndex === match.start) {
```
Comment (zhouyx) [inline src/service/url-expander/expander.js]: Have a question about the usage of backtick. 
What's the expected output with
```
abc`TIMESTAMP`def
```
I couldn't find where we respect the `PARSER_IGNORE_FLAG` when handling with macros. Do you think that's an issue?

File: src/service/url-expander/expander.js (hunk 1 above)
Comment (zhouyx) [reply src/service/url-expander/expander.js]: Also I understand this is used for 
```
CLIENT_ID(   SUBSTR(abc, 1, 2))
```
or 
```
CLIENT_ID(  testSUBSTR(abc, 1, 2))
```
However it also applies to
```
CLIENT_ID (   test  SUBSTR(abc, 1, 2))
```
What do you think should be the different between these cases?

File: src/service/url-expander/expander.js (hunk 2 above)
Comment (calebcordry) [reply src/service/url-expander/expander.js]: You are right this macro is still resolved. The backtick only really works for spaces, parens, and commas. I think this is ok as we note in docs that macro names are reserved, but happy to revisit this. If we were to change it would need to be a separate PR.

File: src/service/url-expander/expander.js (hunk 1 above)
Comment (calebcordry) [reply src/service/url-expander/expander.js]: for the first comment, sure we can move it up before finding the binding. For the second comment you are right these will all behave the same. The hard part is the distinction between `CLIENT_ID (   test  SUBSTR(abc, 1, 2))` and `CLIENT_ID (a,  test  SUBSTR(abc, 1, 2))`. We could only trim the first space instead of trimming the whole thing. What do you think?

File: src/service/url-expander/expander.js (hunk 2 above)
Comment (zhouyx) [reply src/service/url-expander/expander.js]: > I think this is ok as we note in docs that macro names are reserved

As long as we've made that decision, I think it makes sense. could you please remind me when did we add support for backtick (before nested macro support, or after).

Comment (calebcordry) [reply src/service/url-expander/expander.js]: After.

File: src/service/url-expander/expander.js (hunk 1 above)
Comment (zhouyx) [reply src/service/url-expander/expander.js]: Hmmm `CLIENT_ID ( test SUBSTR(abc, 1, 2))` maybe a bad example, because there's a space between `CLIENT_ID` and `(`. I don't think we can handle that. Let me know if that's true and expected. 

`CLIENT_ID(a,  test  SUBSTR(abc, 1, 2))`. So I assume the `  test  ` will be trimmed to `test`. And it equals to `CLIENT_ID(a,testSUBSTR(abc, 1, 2))`. Is that right? 
Do you think we should only remove the trialing space in such case?

Comment (calebcordry) [reply src/service/url-expander/expander.js]: you are correct these would be equivalent. Do you mean the leading space? If so I think that may be a good idea.

Comment (calebcordry) [reply src/service/url-expander/expander.js]: just so we are on the same page, I am thinking something like `trimLeft` instead of trim.

Comment (zhouyx) [reply src/service/url-expander/expander.js]: Ah, you're right. leading space it is : )

Comment (calebcordry) [reply src/service/url-expander/expander.js]: 👍changed to trimStart and moved the builder push before the binding stuff.

Comment (calebcordry) [reply src/service/url-expander/expander.js]: also added test with the space. ```$IF(QUERY_PARAM(test), foo TIMESTAMP, ``)```

File: src/service/url-expander/expander.js (hunk 2 above)
Comment (zhouyx) [reply src/service/url-expander/expander.js]: Cool. I think reserve macros makes sense because I believe we have no plan to support keeping the `${vars}` anyway.
