### PR TITLE
Fix amp-lightbox scheduling bug due to viewport not being updated - @mkhatib

### LINKED ISSUE #3131: amp-youtube loads slowly inside amp-lightbox
## Description
When we embed amp-youtube inside amp-lightbox, it takes too long until the video embed is loaded.

## Steps

The [page] (https://amp-by-example-staging.appspot.com/sample_amps/product_sample/) to reproduce. Here is the code sample

```
    <a on="tap:watch-video-lightbox"
        role="button"
        class="button button-secondary play"
        tabindex="0">
      Show Video
    </a>

    <amp-lightbox id="watch-video-lightbox"
        layout="nodisplay">
      <div class="amp-youtube-container">
        <div class="video">
          <a on="tap:watch-video-lightbox.close"
              role="button"
              tabindex="0">
            Close
          </a>
          <amp-youtube width="480"
              height="270"
              layout=responsive
              data-videoid="4cAHL4LMNlY">
          </amp-youtube>
        </div>
      </div>
    </amp-lightbox>
```
## What browsers are affected?
Chrome and Chrome on Android

### PR DESCRIPTION
**Pull request by mkhatib**
Fixes #3131

### CODE REVIEW

**Comment by mkhatib** [comment]
cc/ @erwinmombay this is the bug we were talking about on https://www.ampproject.org/

File: src/base-element.js [hunk 1]
```diff
@@ -665,7 +665,7 @@ export class BaseElement {
   * @return {!Promise}
   */
   mutateElement(mutator, opt_element) {
-    this.resources_.mutateElement(opt_element || this.element, mutator);
+    return this.resources_.mutateElement(opt_element || this.element, mutator);
```
Comment (dvoytenko) [inline src/base-element.js]: /fyi @erwinmombay

File: extensions/amp-lightbox/0.1/amp-lightbox.js [hunk 2]
```diff
@@ -80,18 +80,20 @@ class AmpLightbox extends AMP.BaseElement {
...
     this.getViewport().resetTouchZoom();
     this.getViewport().hideFixedLayer();
-    this.element.style.display = '';
-    this.element.style.opacity = 0;
 
-    // TODO(dvoytenko): use new animations support instead.
-    this.element.style.transition = 'opacity 0.1s ease-in';
-    requestAnimationFrame(() => {
-      this.element.style.opacity = '';
+    this.mutateElement(() => {
```
Comment (dvoytenko) [inline extensions/amp-lightbox/0.1/amp-lightbox.js]: I described the possible problem in the bug. But reviewing again - it doesn't apply here because the only thing that's animated is opacity. If we animated other properties we might have had an issue. As it stands - this is fine to leave as is.

File: extensions/amp-lightbox/0.1/amp-lightbox.js [hunk 3]
```diff
@@ -80,18 +80,20 @@ class AmpLightbox extends AMP.BaseElement {
...
+      this.element.style.display = '';
+      this.element.style.opacity = 0;
+      // TODO(dvoytenko): use new animations support instead.
+      this.element.style.transition = 'opacity 0.1s ease-in';
+      requestAnimationFrame(() => {
```
Comment (dvoytenko) [inline extensions/amp-lightbox/0.1/amp-lightbox.js]: Please change to use `vsync.mutate`.

**Comment by dvoytenko** [comment]
LGTM with one request. Thanks!

File: extensions/amp-lightbox/0.1/amp-lightbox.js (hunk 3 above)
Comment (mkhatib) [inline extensions/amp-lightbox/0.1/amp-lightbox.js]: Done, mind taking a final look at this to make sure I am using vsync correctly?

**Comment by mkhatib** [comment]
Thanks @dvoytenko PTAL for the vsync part

File: extensions/amp-lightbox/0.1/amp-lightbox.js (hunk 3 above)
Comment (mkhatib) [inline extensions/amp-lightbox/0.1/amp-lightbox.js]: Done.

File: extensions/amp-lightbox/0.1/amp-lightbox.js [hunk 4]
```diff
@@ -80,18 +81,20 @@ class AmpLightbox extends AMP.BaseElement {
...
-    // TODO(dvoytenko): use new animations support instead.
-    this.element.style.transition = 'opacity 0.1s ease-in';
-    requestAnimationFrame(() => {
-      this.element.style.opacity = '';
+    this.mutateElement(() => {
+      this.element.style.display = '';
+      this.element.style.opacity = 0;
+      // TODO(dvoytenko): use new animations support instead.
+      this.element.style.transition = 'opacity 0.1s ease-in';
+      vsyncFor(this.getWin()).mutate(() => {
```
Comment (dvoytenko) [inline extensions/amp-lightbox/0.1/amp-lightbox.js]: Just `this.getVsync()`
