### PR TITLE
Simple version check for minimum node version for our gulp deps.

### LINKED ISSUE #1622: Check for minimum node version in gulp
We require node 4.0 or newer.

A problem might be that gulp might completely fail to start up. Not sure how to best handle that.

### PR DESCRIPTION
**Pull request by cramforce**
Fixes #1622

### CODE REVIEW

File: gulpfile.js [hunk 1]
```diff
@@ -656,6 +658,20 @@ function buildLoginDoneVersion(version, options) {
       });
 }
 
+/**
+ * Exits the process if gulp is running with a node version lower than
+ * the required version. This has to run very early to avoid parse
+ * errors from modules that e.g. use let.
+ */
+function checkMinVersion() {
+  var majorVersion = process.version.replace(/v/, '').split('.')[0];
```
Comment (erwinmombay) [inline gulpfile.js]: can we explicitly cast to Number :smile_cat: 

LGTM

Comment (cramforce) [inline gulpfile.js]: OK :)
