### PR TITLE
Check for win.performance before using it

### LINKED ISSUE #6312: Integration tests failing in Safari 8 after #6227
`ReferenceError: Can't find variable: performance`

`performance` API does not exist in Safari 8. So you probably need to polyfill `time: performance.now(),` in `intersection-observer-polyfill.js` with `Date().now()`

/to @zhouyx 
/cc @jridgewell

### PR DESCRIPTION
**Pull request by zhouyx**
fix #6312 

@jridgewell, @aghassemi and I talked about it, and there are other files that use `win.performance ` function. they basically check the existence of `win.performance`.  With this I don't want to create a `win.performance` polyfill just for `performance.now()` because it will break their checks. 
I decide not to polyfill it here. If we go with polyfilling, I think we should polyfill everything for `win.performance`

### CODE REVIEW

File: src/intersection-observer-polyfill.js [hunk 1]
```diff
@@ -38,6 +38,8 @@ export const DEFAULT_THRESHOLD =
     [0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4,
     0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1];
 
+const INIT_TIME = Date.now();
```
Comment (jridgewell) [inline src/intersection-observer-polyfill.js]: This won't pass presubmit as the `Date.now()` call can't be DCEd.

File: src/intersection-observer-polyfill.js [hunk 2]
```diff
@@ -411,7 +413,9 @@ function calculateChangeEntry(
   }
 
   return /** @type {!IntersectionObserverEntry} */ ({
-    time: performance.now(),
+    time: (typeof performance !== 'undefined' &&
+        typeof performance.now !== 'undefined') ? performance.now()
```
Comment (jridgewell) [inline src/intersection-observer-polyfill.js]: `(performance && performance.now) ? performance.now() : ...`. The `performance.now` check is probably unnecessary anyways.

File: src/intersection-observer-polyfill.js (hunk 1 above)
Comment (zhouyx) [inline src/intersection-observer-polyfill.js]: presubmit is passing locally for me. 
Well if I can't do this where should I get the init time? I can create one in `IntersectionObserverPolyfill`, but what about the export function `#getIntersectionChangeEntry`?

Comment (jridgewell) [inline src/intersection-observer-polyfill.js]: Maybe it's lint? Something will fail.

> but what about the export function #getIntersectionChangeEntry

First call to `calculateChangeEntry` sets?

File: src/intersection-observer-polyfill.js (hunk 2 above)
Comment (zhouyx) [inline src/intersection-observer-polyfill.js]: As @aghassemi  pointed out https://github.com/ampproject/amphtml/issues/6312#issuecomment-262398954

for performance.now check. yes it's probably unnecessary. However I see we are doing this check in other places. I thought it would be safer to include the extra check. I am ok with removing it.

File: src/intersection-observer-polyfill.js (hunk 1 above)
Comment (jridgewell) [inline src/intersection-observer-polyfill.js]: Oh, it's because I'm [only checking](https://github.com/ampproject/amphtml/blob/master/build-system/eslint-rules/no-export-side-effect.js#L19) exports. While this won't be DCEd, it's fine as is.

Comment (zhouyx) [inline src/intersection-observer-polyfill.js]: cool!

File: src/intersection-observer-polyfill.js (hunk 2 above)
Comment (zhouyx) [inline src/intersection-observer-polyfill.js]: fixed

**Comment by zhouyx** [comment]
LOL~ I don't think anyone is relying on that value. However that is what native IntersectionObserver returns. I think as long as we don't return Date.now() here, it's ok to be not accurate.

**Comment by jridgewell** [comment]
I'd vote for the simplified code (and performance win, ironically).
