### PR TITLE
🏗🐛 Add a more robust mechanism for dynamically skipping tests

### LINKED ISSUE #17245: Fix usage of `this.skip()` within tests
Using `this.skip()` within tests can cause `afterEach()` to be skipped. https://github.com/mochajs/mocha/issues/2148

In addition, `this.skip()` doesn't work from within a nested `describe` block. https://github.com/mochajs/mocha/issues/2683#

Figure out how to get past these two issues while still allowing tests to dynamically skip themselves.

### PR DESCRIPTION
**Pull request by rsimha**
There are two issues with mocha's `this.skip()`:
1. Using it within the body of a `beforeEach()` block or `it()` block will cause `afterEach()` to be skipped (https://github.com/mochajs/mocha/issues/2148)
2. It doesn't work when used within a nested `describe` block (https://github.com/mochajs/mocha/issues/2683)

According to https://mochajs.org/#inclusive-tests, the recommended place in which to dynamically skip tests is within a `before()` block.

This PR does the following:
- Introduces `this.skipTest()`, a more robust version of `this.skip()` that...
    - makes sure it is being used within a `before()` block
    - works within nested `describe` blocks
- Forbids the use of `this.skip()` within tests, and recommends the use of `this.skipTest()` instead

With this, dirty global state due to inadvertent skipping of `afterEach()` should no longer be a problem.

Fixes #17245
Partial fix for #14360

### CODE REVIEW

File: test/_init_tests.js [hunk 1]
```diff
@@ -390,17 +386,22 @@ function preventAsyncErrorThrows() {
   stubAsyncErrorThrows();
 }
 
+before(function() {
+  // This is a more robust version of `this.skip()`. See #17245.
+  this.skipTest = function() {
+    if (this._runnable.title != '"before all" hook') {
+      throw new Error('skipTest() can only be called from within before()');
+    }
+    this.test.parent.pending = true;
```
Comment (jridgewell) [inline test/_init_tests.js]: What's this?

File: test/functional/test-fixed-layer.js [hunk 2]
```diff
@@ -1339,83 +1339,82 @@ describes.realWin('FixedLayer: shadow transfer', {}, env => {
...
-    fixedLayer = new FixedLayer(ampdoc, vsyncApi,
-        /* borderTop */ 0, /* paddingTop */ 11, /* transfer */ true);
-    fixedLayer.setup();
-    transferLayer = fixedLayer.getTransferLayer_();
-    root = transferLayer.getRoot();
-    container = doc.createElement('div');
-    doc.body.appendChild(container);
-  });
+  // Can only test when SD is supported.
+  describe.configure().ifChrome('shadow transfer', function() {
```
Comment (jridgewell) [inline test/functional/test-fixed-layer.js]: This is Safari, too. You can use generic `if`:

```js
describe.configure().if(() => Element.prototype.attachShadow)
```

File: test/functional/test-viewport-binding.js [hunk 3]
```diff
@@ -438,293 +438,292 @@ describes.realWin('ViewportBindingIosEmbedWrapper', {ampCss: true}, env => {
   });
 });
 
-describes.realWin('ViewportBindingIosEmbedShadowRoot_', {ampCss: true}, env => {
+describes.realWin('ViewportBindingIos', {ampCss: true}, env => {
```
Comment (jridgewell) [inline test/functional/test-viewport-binding.js]: Please use the old name. We have multiple iOS bindings.

File: test/functional/test-viewport-binding.js [hunk 4]
```diff
@@ -438,293 +438,292 @@ describes.realWin('ViewportBindingIosEmbedWrapper', {ampCss: true}, env => {
...
-    expect(binding.requiresFixedLayerTransfer()).to.be.true;
-  });
-
-  it('should start w/o overscroll and set it on doc ready', () => {
-    const root = binding.getScrollingElement();
-    expect(root).to.not.have.class('i-amphtml-ios-overscroll');
-    return whenDocumentReady(win.document).then(() => {
-      expect(root).to.have.class('i-amphtml-ios-overscroll');
+  // Can only test when SD is supported.
+  describe.configure().ifChrome('EmbedShadowRoot_', function() {
```
Comment (jridgewell) [inline test/functional/test-viewport-binding.js]: Safari also has `attachShadow`. Also, it's a Safari specific test suite. 😉

File: test/_init_tests.js (hunk 1 above)
Comment (rsimha) [reply test/_init_tests.js]: Workaround for https://github.com/mochajs/mocha/issues/2683.

File: test/functional/test-fixed-layer.js (hunk 2 above)
Comment (rsimha) [reply test/functional/test-fixed-layer.js]: Done.

File: test/functional/test-viewport-binding.js (hunk 3 above)
Comment (rsimha) [reply test/functional/test-viewport-binding.js]: Reverted.

File: test/functional/test-viewport-binding.js (hunk 4 above)
Comment (rsimha) [reply test/functional/test-viewport-binding.js]: Done.

**Comment by rsimha** [comment]
@jridgewell PTAL.

File: test/functional/test-viewport-binding.js [hunk 5]
```diff
@@ -445,286 +445,286 @@ describes.realWin('ViewportBindingIosEmbedShadowRoot_', {ampCss: true}, env => {
...
-  });
-
-  it('should start w/o overscroll and set it on doc ready', () => {
-    const root = binding.getScrollingElement();
-    expect(root).to.not.have.class('i-amphtml-ios-overscroll');
-    return whenDocumentReady(win.document).then(() => {
-      expect(root).to.have.class('i-amphtml-ios-overscroll');
+  // Can only test when SD is supported.
+  describe.configure().if(() => Element.prototype.attachShadow).run('Viewport' +
+      'BindingIosEmbedShadowRoot_', function() {
```
Comment (choumx) [inline test/functional/test-viewport-binding.js]: Nit: 'Shadow DOM available'

File: test/functional/test-fixed-layer.js [hunk 6]
```diff
@@ -1339,83 +1339,83 @@ describes.realWin('FixedLayer: shadow transfer', {}, env => {
...
-    fixedLayer = new FixedLayer(ampdoc, vsyncApi,
-        /* borderTop */ 0, /* paddingTop */ 11, /* transfer */ true);
-    fixedLayer.setup();
-    transferLayer = fixedLayer.getTransferLayer_();
-    root = transferLayer.getRoot();
-    container = doc.createElement('div');
-    doc.body.appendChild(container);
-  });
+  // Can only test when SD is supported.
+  describe.configure().if(() => Element.prototype.attachShadow).run('shadow ' +
```
Comment (choumx) [inline test/functional/test-fixed-layer.js]: Note that this now checks whether shadow DOM is supported in the test runner window rather than the "realWin".

File: build-system/tasks/presubmit-checks.js [hunk 7]
```diff
@@ -612,6 +612,14 @@ const forbiddenTerms = {
       'extensions/amp-access/0.1/iframe-api/access-controller.js',
     ],
   },
+  'this\\.skip\\(\\)': {
+    message: 'Use of `this.skip()` is forbidden. Use `this.skipTest()` ' +
+        'from within a `before()` block instead. See #17245.',
+    checkInTestFolder: true,
```
Comment (choumx) [inline build-system/tasks/presubmit-checks.js]: Does this only match tests or also source files?

File: test/functional/test-viewport-binding.js (hunk 5 above)
Comment (rsimha) [reply test/functional/test-viewport-binding.js]: Fixed.

File: test/functional/test-fixed-layer.js (hunk 6 above)
Comment (rsimha) [reply test/functional/test-fixed-layer.js]: Given that this is a nested `describe` within a `describes.realWin`, will it not have the same effect? (From actually running the test, It seemed to me that we do have the desired skipping behavior.)

File: build-system/tasks/presubmit-checks.js (hunk 7 above)
Comment (rsimha) [reply build-system/tasks/presubmit-checks.js]: It matches all files, but there are no instances of `this.skip()` in source files. I've updated the error message to be more clear.

File: test/functional/test-fixed-layer.js (hunk 6 above)
Comment (choumx) [reply test/functional/test-fixed-layer.js]: Most likely fine unless we want to do something weird in `describes` later.
