### PR TITLE
Revert "✨[amp-story-player] Upgrading amp-story-player to CE"

### LINKED ISSUE #27732: amp-story-player failing to load
When opted in in Beta, load a page with the player.

The following error will be thrown:
```
Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
    at new J (amp-story-player-v0.js:15)
    at amp-story-player-v0.js:28
```

Because the code shipped is transpilled from a class to a function syntax, it can't extend the native HTMLElement class, which is something CEv1 does. Since we don't ship a polyfill or expect publishers to install a CEv1 polyfill themselves, the code fails to run.

### PR DESCRIPTION
**Pull request by Enriqe**
closes #27732

Reverts ampproject/amphtml#27320

### CODE REVIEW

File: src/amp-story-player-impl.js [hunk 1]
```diff
@@ -14,19 +14,18 @@
  * limitations under the License.
  */
 
-import {IframePool} from './amp-story-player-iframe-pool';
```
Comment (dvoytenko) [inline src/amp-story-player-impl.js:17]: I'd really rather see all of this in a separate folder. Can we move?

Comment (Enriqe) [reply src/amp-story-player-impl.js:17]: Yes, I'll move all of the player code to a separate directory @dvoytenko
