### PR TITLE
🔥In case cache CID api is not opted in or failed, fallback to local generated CID.

### LINKED ISSUE #15202: getExternalCid_ returns null when opted out of API instead of using localStorage
https://github.com/ampproject/amphtml/blob/55a1285fbcfb96f2723472e88519f5e1babfb69d/src/service/cid-impl.js#L236

This should not return null but should instead get the CID from localStorage

### PR DESCRIPTION
**Pull request by lannka**
Fixes #15202

### CODE REVIEW

File: src/service/cid-impl.js [hunk 1]
```diff
@@ -213,10 +213,16 @@ export class Cid {
...
     const url = parseUrl(this.ampdoc.win.location.href);
+    let api = null;
     if (!isProxyOrigin(url)) {
+      api = this.cidApi_;
+    } else if (this.cacheCidApi_.isSupported()) {
+      api = this.cacheCidApi_;
+    }
+    if (api) {
       const apiKey = this.isScopeOptedIn_(scope);
       if (apiKey) {
```
Comment (ericfs) [inline src/service/cid-impl.js]: If the scope is not opted in the CID API, then it falls back to using a cookie? Is that correct on the AMP Cache?

**Comment by lannka** [comment]
Test the non-proxy case locally. Couldn't really test the proxy case though without server opening a sandbox option for testing. @Gregable 

TODO: the proxy case does not respect CID optout.

File: src/service/cid-impl.js [hunk 2]
```diff
@@ -230,26 +230,33 @@ export class Cid {
...
-          });
+
+      if (this.cacheCidApi_.isSupported() && this.isScopeOptedIn_(scope)) {
+        return this.cacheCidApi_.getScopedCid(scope).then(scopedCid => {
+          if (scopedCid) {
+            return scopedCid;
+          }
+          return this.scopeBaseCid_(persistenceConsent, scope, url);
+        });
+      }
```
Comment (choumx) [inline src/service/cid-impl.js]: Why move `cacheCidApi_` logic here? Native aGSA doesn't have a viewer, right?

Comment (lannka) [reply src/service/cid-impl.js]: yep, so `supported` is `false` in this case.

Moving here is mainly to simplify the async code a bit. It's safe because `this.viewerCidApi_.isSupported()` and `this.cacheCidApi_.isSupported()` are mutually exclusive.

Comment (lannka) [reply src/service/cid-impl.js]: Tried, but seems complicated in this async code style. Any good techniques here ?

Comment (choumx) [reply src/service/cid-impl.js]: Can we just revert this nesting (move this cache CID block back above the viewer CID block)?

As long as cache CID and viewer CID can't both be supported, that should be fine. Or maybe I'm missing something.

Comment (lannka) [reply src/service/cid-impl.js]: you will introduce another nesting:
```
if (this.cacheCidApi_.isSupported()) {
  if (this.isScopeOptedIn_(scope)) {
      return...
  } 
  return ...
}
```

and you will also repeat the `this.scopeBaseCid_` a 3rd time.

File: src/service/cid-impl.js [hunk 3]
```diff
@@ -230,26 +230,33 @@ export class Cid {
...
+      return this.scopeBaseCid_(persistenceConsent, scope, url);
     });
   }
 
+  scopeBaseCid_(persistenceConsent, scope, url) {
```
[the remark this answers is not in the document]
Comment (jridgewell) [reply src/service/cid-impl.js]: Ping @lannka
