### PR TITLE
Fix 3P ad frame for local development

### LINKED ISSUE #12054: Running local server on non-localhost causes breakages
Steps to reproduce:
```
gulp --host=<insert name of host machine>
```
navigate to hostname:8000/examples/ads.amp.html
Select doubleclick for ad network.
Notice how all the ads 404

The issue is that non-localhost is not being identified as localDev in mode.js, which is instead hardcoding localhost in its check for localdev mode.

### LINKED ISSUE #12439: Wrong 3P frame.html loaded when testing local compiled binary
All 3P frames are loading `//ampproject.net/dist.3p/1513120604167/frame.html`.
This might be due to this change  #12152 , which sets config.localDev=true,
hence triggered the following logic in 3p-frame.js:

```
function getAdsLocalhost(win) {
  if (urls.localDev) {
    return `//${urls.thirdPartyFrameHost}`;
  }
  return 'http://ads.localhost:'
      + (win.location.port || win.parent.location.port);
}
```

To reproduce, 
```
gulp dist --fortesting
gulp serve --fortesting --compiled
```

then load page http://localhost:8000/examples/ads.amp.html

### PR DESCRIPTION
**Pull request by rsimha-amp**
Steps: Run 
```
gulp clean
gulp build
gulp serve
```
or
```
gulp clean
gulp dist --fortesting
gulp serve --compiled
```
and navigate to http://localhost:8000/examples/ads.amp.html

Earlier, you'd see several instances of the wrong 3P ad frame.
With this PR, you'll see the ads loading correctly.

Fixes #12439
Partial fix for #12054

### CODE REVIEW

File: src/3p-frame.js [hunk 1]
```diff
@@ -229,9 +229,6 @@ export function getDefaultBootstrapBaseUrl(parentWindow, opt_srcFileBasename) {
 }
 
 function getAdsLocalhost(win) {
-  if (urls.localDev) {
-    return `//${urls.thirdPartyFrameHost}`;
-  }
   return 'http://ads.localhost:'
```
Comment (lannka) [inline src/3p-frame.js]: this might not work on heroku though

Comment (rsimha-amp) [reply src/3p-frame.js]: Is there a separate check for heroku? We can replace `if (urls.localDev)` with that check.

Comment (rsimha-amp) [reply src/3p-frame.js]: @lannka Can you confirm that this doesn't work for heroku? If so, is there a valid check, given that this is runtime code and not infra code?

Comment (lannka) [reply src/3p-frame.js]: I'm not aware of any. Maybe just check the existence of `urls.thirdPartyFrameHost` (which is from AMP_TESING_HOST env var)?

Comment (lannka) [reply src/3p-frame.js]: > Can you confirm that this doesn't work for heroku?

See this: http://amphtml-nightly.herokuapp.com/examples/ads.amp.html

Comment (rsimha-amp) [reply src/3p-frame.js]: I see. The heroku flow, and more generally, 3P ads on a non-localhost server were already broken prior to this PR. @bradfrizzell is working separately on fixing the issue. See Item 2 in https://github.com/ampproject/amphtml/issues/12054#issuecomment-346154439.

This PR should not affect that flow, so I'm going to merge it. The non-localhost issue can be addressed separately.
