### PR TITLE
Fix a test isolation problem caused by the use of Object.defineProperty w/o restore.

### LINKED ISSUE #23689: Test state leakage due to the use of Object.defineProperty w/o restore
```
gulp unit --nobuild --headless --files={test/unit/test-viewport.js,test/unit/test-dom.js}
```

Running the above 2 tests on master branch will fail some tests:

```
FAILED TESTS:
  DOM

      ● isConnectedNode
        HeadlessChrome 76.0.3809 (Mac OS X 10.14.5)
      TypeError: a.attachShadow is not a function
          at Context.<anonymous> (Users/dinghongfei/Development/projects/amphtml/test/unit/test-dom.js:82:22)

      ● isConnectedNode (no Node.p.isConnected)
        HeadlessChrome 76.0.3809 (Mac OS X 10.14.5)
      TypeError: a.attachShadow is not a function
          at Context.<anonymous> (Users/dinghongfei/Development/projects/amphtml/test/unit/test-dom.js:111:24)
```

issue is first found here: https://github.com/ampproject/amphtml/pull/23671#issuecomment-518346305

### PR DESCRIPTION
**Pull request by lannka**
Also introduced a helper method to automatically restore properties in `afterEach`: `sandbox.defineProperty(...)` 

closes #23689

### CODE REVIEW

File: test/unit/test-viewport.js [hunk 1]
```diff
@@ -1570,9 +1570,11 @@ describe('createViewport', () => {
       let win;
       let ampDoc;
       let viewer;
+      let sandbox;
 
       beforeEach(() => {
         win = env.win;
+        sandbox = env.sandbox;
```
Comment (rsimha) [inline test/unit/test-viewport.js]: We already set `window.sandbox` in the global `beforeEach()` in `_init_tests.js`. Would it make sense to use it instead? Or will this code end up using the same instance?

https://github.com/ampproject/amphtml/blob/13c141e5b4ea313f510f297e123a0020eb8673da/test/_init_tests.js#L406

Comment (lannka) [reply test/unit/test-viewport.js]: it's different instance. i think we should use different sandbox instance for each test for better isolation.

we should probably remove `window.sandbox` later. unless it has good use cases.

Comment (rsimha) [reply test/unit/test-viewport.js]: `window.sandbox` was added by @choumx in #18318 because tests were failing without it. IIRC, we set up a global sandbox because not all tests were creating their own sandbox.

Comment (lannka) [reply test/unit/test-viewport.js]: got it. those tests using global sandbox are likely legacy tests that don't have proper isolations. those are the ones we should pay extra attention :-)

Comment (choumx) [reply test/unit/test-viewport.js]: +1 to removing the global sandbox. It already existed before that PR:

> Looks like it's being set in the SandboxFixture in describes.js
