### PR TITLE
🐛  [Story devtools] Toggle devtools on mjs build

### LINKED ISSUE #34364: getMode().development missing from *.mjs
## What's the issue?

Looks like `getMode().development` is missing from `*.mjs` binaries. 

This results in features like AMP story's preview mode being inaccessible on pages that use `*.mjs` binaries.

## How do we reproduce the issue?

Search for "development" in:
- https://cdn.ampproject.org/v0/amp-story-1.0.js
- https://cdn.ampproject.org/v0/amp-story-1.0.mjs

The origin URL (js) triggers AMP story's preview mode, but the CDN (mjs) doesn't:
- https://travel.usnews.com/ampstories/newyorkcity#development=1
- https://travel-usnews-com.cdn.ampproject.org/v/s/travel.usnews.com/ampstories/newyorkcity?amp_js_v=0.1&usqp=mq331AQHKAFQArABIA%3D%3D#development=1

## What browsers are affected?

All browsers.

## Which AMP version is affected?

Not sure if this is a recent regression in MJS build.

### PR DESCRIPTION
**Pull request by mszylkowski**
On the minified JS build, `getMode().development` gets replaced with `false` so the Web Story DevTools don't get triggered.

Exposing a function `isModeDevelopment` can be used by `amp-story.js` to check whether to trigger the tools without relying on `getMode()`

Closes #34364

### CODE REVIEW

**Review by gmajoulet — APPROVED** [review]
Still up to @rcebulko but the implementation from his guidance LGTM

File: src/mode.js [hunk 1]
```diff
@@ -130,6 +122,25 @@ function getRtvVersion(win) {
...
+ */
+export function isModeDevelopment(win) {
+  const hashQuery = parseQueryString_(
+    win.location['originalHash'] || win.location.hash
+  );
+  return !!(
+    ['1', 'actions', 'amp', 'amp4ads', 'amp4email'].indexOf(
+      hashQuery['development']
+    ) >= 0 || win.AMP_DEV_MODE
+  );
```
Comment (rcebulko) [inline src/mode.js:141]:
```suggestion
  return !!(
    ['1', 'actions', 'amp', 'amp4ads', 'amp4email'].includes(
      hashQuery['development']
    ) || win.AMP_DEV_MODE
  );
```
We polyfill this in IE anyway

**Review by rcebulko — APPROVED** [review]

File: extensions/amp-story/1.0/amp-story.js [hunk 2]
```diff
@@ -2940,7 +2940,7 @@ export class AmpStory extends AMP.BaseElement {
    */
   maybeLoadStoryDevTools_() {
     if (
-      !getMode().development ||
+      !isModeDevelopment(this.win) ||
```
Comment (choumx) [inline extensions/amp-story/1.0/amp-story.js:2943]: Are we sure we want to reuse all of this code? `#development=actions|amp|amp4ads|amp4email` will also work, and this will be true when tests are running.

**Comment by choumx** [comment]
Thanks for the quick turnaround!

File: src/mode.js [hunk 3]
```diff
@@ -130,6 +122,25 @@ function getRtvVersion(win) {
   return `01${internalRuntimeVersion()}`;
 }
 
+/**
+ * Triggers validation or enable pub level logging. Validation can be
+ * bypassed via #validate=0.
+ * Note that AMP_DEV_MODE flag is used for testing purposes.
+ * Uses Array.indexOf instead of Array.includes because of #24219
```
Comment (choumx) [inline src/mode.js:129]: Obsolete comment now.

File: src/mode.js [hunk 4]
```diff
@@ -89,15 +89,7 @@ function getMode_(win) {
...
-    // Triggers validation or enable pub level logging. Validation can be
-    // bypassed via #validate=0.
-    // Note that AMP_DEV_MODE flag is used for testing purposes.
-    // Use Array.indexOf instead of Array.includes because of #24219
-    development: !!(
-      ['1', 'actions', 'amp', 'amp4ads', 'amp4email'].indexOf(
-        hashQuery['development']
-      ) >= 0 || win.AMP_DEV_MODE
-    ),
+    development: isModeDevelopment(win),
```
Comment (jridgewell) [inline src/mode.js:92]: I wonder if we can get rid of this entirely? Or move it into the binaries that need it.

**Review by jridgewell — APPROVED** [review]

File: src/mode.js (hunk 4 above)
Comment (rcebulko) [reply src/mode.js:92]: The plan is to turn all the mode properties into DCE-able helpers that can be consumed directly and only included in binaries that use it.

Comment (mszylkowski) [reply src/mode.js:92]: @jridgewell @rcebulko I didn't plan to change all the `getMode().development` calls into `getModeDeveloppment()` throughout the codebase in this PR, is that sth that we'd want to do now?

Comment (rcebulko) [reply src/mode.js:92]: Nope, it's good that most of the codebase accesses via `getMode()`. The dependencies required for that don't exist in `core` yet :)

File: extensions/amp-story/1.0/amp-story.js (hunk 2 above)
Comment (mszylkowski) [reply extensions/amp-story/1.0/amp-story.js:2943]: @choumx From my understanding we want to have a helper that parses the url and returns whether the development mode is active, so we can reuse it easily. What's your suggestion?

**Comment by processprocess** [comment]
(As discussed in stand ups)
`parseQueryString_` is undefined in:
https://github.com/ampproject/amphtml/blob/main/src/mode.js#L133
