### PR TITLE
🚀 Dont autogenerate sizes if the ssr image contains sizes already, or is ssr'd using a transformer

### LINKED ISSUE #32644: amp-img ssr: don't generate sizes attribute
## Problem

Server-side rendering a hero image can cause double download of the same image when using `srcset` but not `sizes`. The problem is: the amp-img extension in that case generates a viewport specific sizes attribute which might cause a re-download of the same image.

## Steps to reproduce

Load https://lava-useful-horesradish.glitch.me/ in DevTools simulating a mobile device, e.g. G4. You can see that the image is downloaded twice:

Screenshot 2021-02-12 at 22 38 04

## Suggested fix

Don't generate a sizes attribute for ssr'd `img`. There's no value in setting this anyway, as the user agent has already decided at this point in time which image to download.

//cc @patrickkettner @jridgewell

### PR DESCRIPTION
**Pull request by kristoferbaxter**
Fixes #32644.

### CODE REVIEW

File: builtins/amp-img.js [hunk 1]
```diff
@@ -200,7 +200,8 @@ export class AmpImg extends BaseElement {
       return;
     }
     // No need to generate sizes if already present.
-    const sizes = this.element.getAttribute('sizes');
+    const sizes =
```
Comment (rcebulko) [inline builtins/amp-img.js:203]: Is getAttribute used here in case the attribute value is empty, in which case hasAttribute would return true but getAttribute would be falsey?

File: builtins/amp-img.js [hunk 2]
```diff
@@ -200,7 +200,8 @@ export class AmpImg extends BaseElement {
...
+      this.element.hasAttribute('sizes') || this.img_.hasAttribute('sizes');
```
Comment (sebastianbenz) [inline builtins/amp-img.js:204]: This still generates the sizes attribute if none is specified. We need to check for the `i-amphtml-ssr` and not generate `sizes` if it is present.

File: builtins/amp-img.js (hunk 1 above)
Comment (kristoferbaxter) [reply builtins/amp-img.js:203]: There was no test for this, but we could add one? 

Right now I am not certain what the values should be in those cases.

File: builtins/amp-img.js (hunk 2 above)
Comment (kristoferbaxter) [reply builtins/amp-img.js:204]: I'll add a different check for this.

Comment (kristoferbaxter) [reply builtins/amp-img.js:204]: Actually, could this be a breaking change? 

There are other sources that server render images, and we don't know if they expect to have auto generated sizes.

File: builtins/amp-img.js [hunk 3]
```diff
@@ -199,8 +199,13 @@ export class AmpImg extends BaseElement {
     if (!this.img_) {
       return;
     }
+    // If the image is server rendered, do not generate sizes.
+    if (this.element.hasAttribute('i-amphtml-ssr')) {
```
Comment (kristoferbaxter) [inline builtins/amp-img.js:203]: This is the change I am nervous about: @lannka do AMP Advertisements need to autogenerate `sizes`?

File: builtins/amp-img.js (hunk 2 above)
Comment (kristoferbaxter) [reply builtins/amp-img.js:208]: I've added the check above, I am still concerned it's a breaking change.

File: test/unit/test-amp-img.js [hunk 4]
```diff
@@ -640,7 +640,44 @@ describes.sandboxed('amp-img', {}, (env) => {
...
+      expect(img.getAttribute('sizes')).to.equal('50vw');
+    });
+
+    it('should not generate sizes for amp-imgs when rendered from the server', async () => {
+      const ampImg = await getImg({
+        src: '/examples/img/sample.jpg',
+        srcset: SRCSET_STRING,
+        width: 300,
+        height: 200,
+        'i-amphtml-ssr': true,
```
Comment (jridgewell) [inline test/unit/test-amp-img.js:671]:
```suggestion
        'i-amphtml-ssr': '',
```

**Review by jridgewell — APPROVED** [review]

File: test/unit/test-amp-img.js (hunk 4 above)
Comment (kristoferbaxter) [reply test/unit/test-amp-img.js:671]: Good call. Committing.

**Review by sebastianbenz — APPROVED** [review]

File: builtins/amp-img.js (hunk 3 above)
Comment (powerivq) [reply builtins/amp-img.js:203]: Can't speak of other advertisers, but Google Ads server side rendering does not generate srcset or sizes attributes on the img tag.

**Review by rcebulko — APPROVED** [review]
bundle size

**Review by erwinmombay — APPROVED** [review]

**Comment by kristoferbaxter** [comment]
From Slack conversation with @lannka and @powerivq:

"Ads never generate these things (srcset/sizes) on ssr'ed img tag."

**Review by lannka — COMMENTED** [review]
sorry being late. the change looks good to me

File: builtins/amp-img.js (hunk 3 above)
Comment (dvoytenko) [reply builtins/amp-img.js:203]: If I'm reading this right, this will mostly disable the sizes-generation for all cached pages? Is that desired?

**Comment by dvoytenko** [comment]
Hi all! Sorry for delay. I was OOO. If I'm reading this right, this will disable sizes generation in cached pages. Not sure if that's what you were going for? If we want to do this, IMHO, we might as well remove the concept sizes-generation entirely from the amp-img.

**Comment by kristoferbaxter** [comment]
>> If I'm reading this right, this will disable sizes generation in cached pages.

This will only disable automatic `sizes` generation.

In general: agree with removing the concept, if we can prove its non-breaking.

**Comment by dvoytenko** [comment]
> In general: agree with removing the concept, if we can prove its non-breaking.

To confirm: this PR does just that - disables automatic sizes generation for cached pages. Is that right?

**Comment by kristoferbaxter** [comment]
It removes the auto-generation for images with the attribute `i-amphtml-ssr`.

I am _quite_ nervous about the backward compatibility, asked here: https://github.com/ampproject/amphtml/pull/32647/files#r575565890.

**Comment by dvoytenko** [comment]
There's pretty much my question as well. The `i-amphtml-ssr`, I think, will be produced for most of `amp-img` tags on cache.

**Comment by sebastianbenz** [comment]
Afaik it'll only be generated for server-side generated `img` elements, which currently only happens for ads and in AMP Optimizer. AMP caches only render the layout, but not the actual `img` element and don't set the `I-amphtml-ssr` flag.
