### PR TITLE
🐛 Fix #38312 toggleChecked

### LINKED ISSUE #38312: action toggleChecked doesn't work without specifying `force`
### Description

The action `toggleChecked` doesn't work when leaving the optional parameter as default - it generates a JS error. However, specifying `force` does make it work.

@anrghg 
@jridgewell 

### Reproduction Steps

```
<!DOCTYPE html>
<html ⚡>
  <head>
    <meta charset="utf-8" />
    <title>My AMP Page</title>
    <link rel="canonical" href="self.html" />
    <meta name="viewport" content="width=device-width" />
    <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
    <script async src="https://cdn.ampproject.org/v0.js"></script>
    <style amp-custom>
      h1 {
        margin: 1rem;
      }
    </style>
  </head>
  <body>
    <h1>Hello AMPHTML World!</h1>
    <button on="tap:checkbox.toggleChecked">
      toggleChecked
    </button>
    <input id=checkbox type=checkbox>
  </body>
</html>
```

Clicking on the button results in an error:

```
Uncaught TypeError: Cannot read properties of null (reading 'force')
    at standard-actions-impl.js:594:16
    at mutate (mutator-impl.js:206:9)
    at Da (vsync-impl.js:456:17)
    at i.xl (vsync-impl.js:413:9)
```

This was added in https://github.com/ampproject/amphtml/pull/35795.

### Relevant Logs

_No response_

### Browser(s) Affected

_No response_

### OS(s) Affected

_No response_

### Device(s) Affected

_No response_

### AMP Version Affected

_No response_

### PR DESCRIPTION
**Pull request by anrghg**
@zhangsu reported that `toggleChecked()` fails when `force` is null.

@jridgewell fixed it in https://github.com/ampproject/amphtml/issues/38312#issuecomment-1168095157

### CODE REVIEW

**Comment by jridgewell** [comment]
Can you add a test case like https://github.com/ampproject/amphtml/pull/35795/files#diff-c40a9cbb33878257be07db9020ce30ed845e54dc3ff389eb6e63eac520d1193aR537? We need to specify one without the `args` specified.

**Comment by anrghg** [comment]
> Can you add a test case like https://github.com/ampproject/amphtml/pull/35795/files#diff-c40a9cbb33878257be07db9020ce30ed845e54dc3ff389eb6e63eac520d1193aR537? We need to specify one without the `args` specified.

I'm trying to figure out the difference with https://github.com/anrghg/amphtml/blob/121f8e27c18c19a187b42e30a7dde8ae0df7b532/test/unit/test-standard-actions.js#L545 and https://github.com/anrghg/amphtml/blob/121f8e27c18c19a187b42e30a7dde8ae0df7b532/test/unit/test-standard-actions.js#L558

**Comment by anrghg** [comment]
> one without the `args` specified.

When we did not specify `args`, the test did not work, so we added `args` as an empty object. But what if `args: {undefined}` or `args: {null}`?

**Comment by jridgewell** [comment]
> When we did not specify `args`, the test did not work, so we added `args` as an empty object. But what if `args: {undefined}` or `args: {null}`?

I think this is the bug you're fixing. We need to do `args: null`, to ensure that we match what happens when you do `on="tap:checkbox.toggleChecked"`

**Comment by anrghg** [comment]
> We need to do `args: null`, to ensure that we match what happens when you do `on="tap:checkbox.toggleChecked"`

Thank you, I've added these tests in https://github.com/anrghg/amphtml/blob/ae2e96016117ef44a928deef2d060537bccd6d0d/test/unit/test-standard-actions.js#L571

Do those with `args: {}` not work and should be deleted?

**Review by jridgewell — APPROVED** [review]

**Comment by jridgewell** [comment]
There's a linting issue, otherwise LGTM.

**Comment by anrghg** [comment]
> There's a linting issue

I'm failing to see it at my end; do you spot the issue?

> otherwise LGTM.

Thanks for approval.

File: test/unit/test-standard-actions.js [hunk 1]
```diff
@@ -560,6 +560,32 @@ describes.sandboxed('StandardActions', {}, (env) => {
       standardActions.handleToggleChecked_(invocation);
       expectCheckboxToHaveCheckedStateTrue(element);
     });
+
```
Comment (jridgewell) [inline test/unit/test-standard-actions.js:563]: The linting issue is here, there's trailing whitespace on this line.

```suggestion

```

Comment (anrghg) [reply test/unit/test-standard-actions.js]: > The linting issue is here, there's trailing whitespace on this line.

Thank you very much! It's now fixed at https://github.com/anrghg/amphtml/blob/2471a18d9bc1b0b12f63bc9f87d76c753693832b/test/unit/test-standard-actions.js#L563

**Review by jridgewell — APPROVED** [review]
All good, I'm restarting the visual diff tests to fix.
