### PR TITLE
[#18671], Fix a11y issue for IE platform

### LINKED ISSUE #18671: Improve accessibility of keyboard focus and skip links in IE11
## What's the issue?

In WordPress themes it is extremely common for there to be a JS file included like this: https://github.com/Automattic/_s/blob/master/js/skip-link-focus-fix.js

The purpose of this JS is to fix an accessibility issue in IE11 for keyboard-only users. In particular, per https://github.com/Automattic/_s/pull/136:

> The problem is that when someone clicks a skip link, the viewport is scrolled to the #content, but pressing tab will bring focus to the site's main navigation. The expected behavior would be to select the first link in the #content, not the site's main navigation. Of course this is the browser's default behavior, and not really a _s bug, but it is an opportunity to make _s-based themes more accessible to users that navigate solely through keyboard input.
>
> I learned about this issue via [an article written by Nicholas C. Zakas](http://www.nczonline.net/blog/2013/01/15/fixing-skip-to-content-links/). He suggests setting focus to the #content using JavaScript. I've adapted his example to use jQuery and to better conform to WordPress coding standards.

In work on the [AMP for WordPress plugin](https://github.com/Automattic/amp-wp), this is a common bit of JS that is encountered which must be suppressed to avoid validation errors. However, in doing so then IE11 users miss out on the a11y fix. 

See also:
* https://github.com/WordPress/twentynineteen/pull/47
* https://github.com/wprig/wprig/pull/139

Should this a11y fix be made part of the AMP runtime?

## What browsers are affected?

IE11

### PR DESCRIPTION
**Pull request by sagarkbhatt**
Fix element focus issue for IE

Fixes #18671

### CODE REVIEW

**Comment by sagarkbhatt** [comment]
I signed it!

File: src/service/viewport/viewport-impl.js [hunk 1]
```diff
@@ -501,6 +501,9 @@ export class Viewport {
    * @param {!Element} parent
    */
   scrollIntoViewInternal_(element, parent) {
+    if (Services.platformFor(this.ampdoc.win).isIe()) {
+      element.focus();
```
Comment (aghassemi) [inline src/service/viewport/viewport-impl.js]: Please use `tryFocus` utility from `dom.js`

**Comment by sagarkbhatt** [comment]
@aghassemi Travis CI is failing because of the following error.
`The command "yarn" failed and exited with 1 during .`

**Comment by aghassemi** [comment]
@sagarkbhatt Thanks, PR is approved. There are currently some issues with our CI. I will rerun and merge your PR when it passes.

**Comment by cvializ** [comment]
This needs to be rebased or merged with master to get the build fix from #19046 before it will get a green build

File: src/service/navigation.js [hunk 2]
```diff
@@ -458,6 +459,19 @@ export class Navigation {
         if (targetAttr != '_top' && targetAttr != '_blank') {
           target.setAttribute('target', '_blank');
         }
+        return; // bail early.
+      }
+
+      // Accessibility fix for IE browser
```
Comment (cramforce) [inline src/service/navigation.js]: Is there a blog post or similar that this could point to? Otherwise please explain what this fixes and how it works.

Comment (aghassemi) [reply src/service/navigation.js]: @cramforce https://github.com/ampproject/amphtml/issues/18671 has some discussion. tl;dr: a common plugin in WP needed since IE does not move the a11y cursor when doing anchor navigation.

**Comment by aghassemi** [comment]
@sagarkbhatt Can you please rebase per @cvializ's comment above.

File: src/service/navigation.js (hunk 2 above)
Comment (cramforce) [reply src/service/navigation.js]: I understand why it is needed. But would be nice to have a reference in the code for future code readers.

Comment (sagarkbhatt) [reply src/service/navigation.js]: Should I add a comment in this branch? ( It is merged )

Comment (aghassemi) [reply src/service/navigation.js]: Would need to be a separate PR. Thank you!

Comment (sagarkbhatt) [reply src/service/navigation.js]: @aghassemi 
PR: https://github.com/ampproject/amphtml/pull/19064
