### PR TITLE
Ignore resize failure when 3p iframe can handle overflow

### LINKED ISSUE #11154: Ignore resize failures for some size updates
See the thread in the #8085.

Some Ad networks, such as "mywidget" have an ability to show their own overflow element and thus resize denials are not a problem. In that case, we do not need to warn a publisher that the embed has insufficient space.

I recommend simply adding `{hasOverflow: true}` in the `embed-size` post message that will proceed as it does now with the only exception that the error is ignored and not reported to the publisher.

/cc @jasti @priver

### PR DESCRIPTION
**Pull request by zhouyx**
Closes #11154 

This only allows 3p ad iframe to handle resize failure. We can easily expand the feature to other 3p iframes. 

Generally I don't like the idea of writing `this.element_.has3pOverflow = true` from a helper function, but using `setAttribute` is more expensive I guess. Happy to switch if there's better way to pass the boolean value to the customElement class

### CODE REVIEW

File: src/custom-element.js [hunk 1]
```diff
@@ -221,6 +221,9 @@ function createBaseCustomElementClass(win) {
       /** @private {!./size-list.SizeList|null|undefined} */
       this.heightsList_ = undefined;
 
+      /** @public {boolean} */
+      this.has3pOverflow = false;
```
Comment (choumx) [inline src/custom-element.js]: How about overriding `getOverflowElement()` in the A4A custom element... (continued below)

File: src/custom-element.js [hunk 2]
```diff
@@ -1665,7 +1668,7 @@ function createBaseCustomElementClass(win) {
     overflowCallback(overflown, requestedHeight, requestedWidth) {
       this.getOverflowElement();
       if (!this.overflowElement_) {
-        if (overflown) {
+        if (overflown && !this.has3pOverflow) {
```
Comment (choumx) [inline src/custom-element.js]: And then here:

```js
const overflow = this.getOverflowElement();
if (!overflow) {
  ...
}
```

Comment (zhouyx) [reply src/custom-element.js]: Still need two variable `this.overflowElement_` and `this.has3pOverflow_`. Since it's the 3p context that handle overflow, I don't want runtime to deal with `this.overflowElement_` in that case. 

If so I feel the only difference between the two approaches is where the `this.has3pOverflow` variable is placed, in customElement class or baseElement class? Since it's only a boolean I don't want to write get/set function for the value. 

Should I store the variable to baseElement class instead?

Comment (choumx) [reply src/custom-element.js]: You could infer if `getOverflowElement() && !this.overflowElement_`, but that's confusing. 😄 

Ok this is fine, but how about we call it `warnOnMissingOverflow` instead?

Comment (zhouyx) [reply src/custom-element.js]: : ) Renamed
