### PR TITLE
Fix url rewritting to new version

### LINKED ISSUE #5575: AMP sometimes fails to load when serving from SW
Repro URL
https://www.google.com/amp/s/amp.cnn.com/cnn/2016/10/12/politics/donald-trump-women-new-york-times-report/index.html

I'm seeing this with the current Android Chrome Dev Channel.

Extensions are failing to load
```
https://cdn.ampproject.org/rtv/001475174282386/amp-twitter-0.1.js Failed to load resource: the server responded with a status of 404 ()
https://cdn.ampproject.org/rtv/001475174282386/amp-analytics-0.1.js Failed to load resource: the server responded with a status of 404 ()
https://cdn.ampproject.org/rtv/001475174282386/amp-iframe-0.1.js Failed to load resource: the server responded with a status of 404 ()
https://cdn.ampproject.org/rtv/001475174282386/amp-ad-0.1.js Failed to load resource: the server responded with a status of 404 ()
runtime.js:183Powered by AMP ⚡ HTML – Version 1475174282386
https://cdn.ampproject.org/rtv/001475174282386/amp-iframe-0.1.js Failed to load resource: the server responded with a status of 404 ()
https://cdn.ampproject.org/rtv/001475174282386/amp-analytics-0.1.js Failed to load resource: the server responded with a status of 404 ()
https://cdn.ampproject.org/rtv/001475174282386/amp-twitter-0.1.js Failed to load resource: the server responded with a status of 404 ()
https://cdn.ampproject.org/rtv/001475174282386/amp-ad-0.1.js Failed to load resource: the server responded 
GET https://cdn.ampproject.org/rtv/021475798648076/v0/amp-iframe-0.1.js 
index.html:31 GET https://cdn.ampproject.org/rtv/021475798648076/v0/amp-analytics-0.1.js 
index.html:31 GET https://cdn.ampproject.org/rtv/021475798648076/v0/amp-twitter-0.1.js 
index.html:31 GET https://cdn.ampproject.org/rtv/021475798648076/v0/amp-ad-0.1.js 
```

- Interestingly `v0.js` appears to succeed.
- This does not repro when "bypass for network" is active in Dev Tools.
- Note, that there are 2 versions in those logs.
- I verified that `https://cdn.ampproject.org/rtv/001475174282386/amp-ad-0.1.js` is actually in the cache storage.

### PR DESCRIPTION
**Pull request by jridgewell**
We were rewriting requests like so:

- `/v0/amp-comp.js` -> `rtv/123/amp-comp.js`
- `rtv/100/v0/amp-comp.js` ->`rtv/123/amp-comp.js`

Notice that the rewrites have dropped the `v0/` directory. Doh!

I've also added tests so that `v1` requests will work (whenever we release one).

Fixes #5575.

### CODE REVIEW

File: test/functional/test-cache-sw-core.js [hunk 1]
```diff
@@ -90,19 +90,59 @@ runner.run('Cache SW', () => {
...
+            'https://cdn.ampproject.org/rtv/123/v1/amp-comp.js')
+      });
     });
 
-    it('only recognizes prefix and timestamp RTVs', () => {
-      const prefixless = url.replace(rtv, version);
-      expect(sw.rtvVersion(prefixless)).to.equal(`01${version}`);
+    describe('with RTV versioned file', () => {
+      const v0 = `https://cdn.ampproject.org/rtv/${rtv}/v0.js`;
+      const v1 = v0.replace('v0', 'v1');
```
Comment (cramforce) [inline test/functional/test-cache-sw-core.js]: Please hardcode the full strings. That is easier to read.

Comment (jridgewell) [inline test/functional/test-cache-sw-core.js]: Great suggestion, done.
