### PR TITLE
🐛 Guard against getBoundingClientRect to prevent unspecified errors in IE.

### LINKED ISSUE #20438: Error: "Unspecified error" on getBoundingClientRect() on disconnected elements [IE]
Error: Unspecified error.
at setupDone_ (https://raw.githubusercontent.com/ampproject/amphtml/1901081935550/src/service/viewport/viewport-binding-ios-embed-sd.js:213)
at size_ (https://raw.githubusercontent.com/ampproject/amphtml/1901081935550/src/service/layers-impl.js:481)
at (https://raw.githubusercontent.com/ampproject/amphtml/1901081935550/extensions/amp-ad/0.1/amp-ad-3p-impl.js:306)
at measureIframeLayoutBox_ (https://raw.githubusercontent.com/ampproject/amphtml/1901081935550/extensions/amp-ad/0.1/amp-ad-3p-impl.js:274)
at (https://raw.githubusercontent.com/ampproject/amphtml/1901081935550/src/service/resource.js:862)
at type (https://raw.githubusercontent.com/ampproject/amphtml/1901081935550/src/service/action-impl.js:1201)
at removeResource_ (https://raw.githubusercontent.com/ampproject/amphtml/1901081935550/src/service/resources-impl.js:660)
at marginChange (https://raw.githubusercontent.com/ampproject/amphtml/1901081935550/src/service/resources-impl.js:1294)
at (https://raw.githubusercontent.com/ampproject/amphtml/1901081935550/src/service/history-impl.js:503)
at rebuildDomWhenReady (https://raw.githubusercontent.com/ampproject/amphtml/1901081935550/src/service/resources-impl.js:276)

go/ampe/CNPXxaLgnI3ILg

### PR DESCRIPTION
**Pull request by delima02**
- Before calling `Element.getBoundingClientRect()`, check if the element has been defined.
- If the element has not been defined replace with a zero. This should only happen in IE.
- Zero is the default return for `Element.getBoundingClientRect()` in other browsers.
- Fixes #20438 

🐛
@choumx @jridgewell

### CODE REVIEW

File: src/service/viewport/viewport-binding-natural.js [hunk 1]
```diff
@@ -222,7 +222,12 @@ export class ViewportBindingNatural_ {
 
   /** @override */
   getLayoutRect(el, opt_scrollLeft, opt_scrollTop) {
-    const b = el./*OK*/getBoundingClientRect();
+    // Default value for when 'el' is has not been added to the page yet.
+    let b = 0;
+    if (el != undefined && el != null) {
```
Comment (choumx) [inline src/service/viewport/viewport-binding-natural.js]: Two problems with this:

1. Our type checking system already asserts that `el` is not null [1].
2. This does not address the cause of the bug. Calling a function on a null/undefined object yields a different runtime error (try it out yourself).

[1] https://github.com/ampproject/amphtml/blob/4cd12f1f5dc814f3df7cd35d5849c545663cab04/src/service/viewport/viewport-binding-def.js#L167-L176

About Closure Compiler annotations: https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler

File: src/service/viewport/viewport-binding-natural.js [hunk 2]
```diff
@@ -222,9 +222,16 @@ export class ViewportBindingNatural_ {
 
   /** @override */
   getLayoutRect(el, opt_scrollLeft, opt_scrollTop) {
+
+    const documentElement = this.win.document.documentElement;
+    const childMatch = childElement(documentElement /* parent */, (child) => {
+      child.equals(el);
+    });
+    const isElementInDoc = (childMatch != null);
```
Comment (choumx) [inline src/service/viewport/viewport-binding-natural.js]: https://developer.mozilla.org/en-US/docs/Web/API/Node/isConnected

File: src/service/viewport/viewport-binding-natural.js [hunk 3]
```diff
@@ -222,7 +222,12 @@ export class ViewportBindingNatural_ {
 
   /** @override */
   getLayoutRect(el, opt_scrollLeft, opt_scrollTop) {
-    const b = el./*OK*/getBoundingClientRect();
+    // Default value for when 'el' is has not been added to the page yet.
+    let b = 0;
+    if (el.isConnected) {
```
Comment (choumx) [inline src/service/viewport/viewport-binding-natural.js]: From chat:

> JP: hey I think that Node.isConnected is not supported by IE

> Will: Correct 🙂 but we should use it if it's available
Another hint: try searching through current codebase to see if there's precedence
Always try to find any historical context in code first

File: src/service/viewport/viewport-binding-natural.js [hunk 4]
```diff
@@ -222,7 +222,12 @@ export class ViewportBindingNatural_ {
 
   /** @override */
   getLayoutRect(el, opt_scrollLeft, opt_scrollTop) {
-    const b = el./*OK*/getBoundingClientRect();
+    // Default value for when 'el' is has not been added to the page yet.
+    let b = 0;
```
Comment (choumx) [inline src/service/viewport/viewport-binding-natural.js]: What happens on lines 231-244 if `b == 0`? E.g. what does `b.top` yield?

File: src/polyfills.js [hunk 5]
```diff
@@ -38,6 +41,7 @@ installObjectValues(self);
 installPromise(self);
 installDocContains(self);
 installArrayIncludes(self);
+installGetBoundingClientRect(self);
```
Comment (jridgewell) [inline src/polyfills.js]: This is probably the wrong file for installing this patch.

File: src/get-bounding-client-rect.js [hunk 6]
```diff
@@ -0,0 +1,64 @@
...
+/**
+ * Polyfill for Node.getBoundingClientRect API.
+ * @param {!Element} el
+ * @return {!LayoutRectDef}
+ */
+function getBoundingClientRect(el) {
+  let result = layoutRectLtwh(0, 0, 0, 0);
+
+  if (isConnectedNode(el)) {
+    result = nativeClientRect.call(el);
```
Comment (jridgewell) [inline src/get-bounding-client-rect.js]:
```suggestion
    return nativeClientRect.call(el);
```

File: src/get-bounding-client-rect.js [hunk 7]
```diff
@@ -0,0 +1,64 @@
...
+  }
+
+  return result;
```
Comment (jridgewell) [inline src/get-bounding-client-rect.js]:
```suggestion
  return layoutRectLtwh(0, 0, 0, 0);
```

File: src/get-bounding-client-rect.js [hunk 8]
```diff
@@ -0,0 +1,64 @@
...
+
+/**
+ * Determines if this polyfill should be installed.
+ * @param {!Window} win
+ * @return {boolean}
+ */
+function shouldInstall(win) {
+  try {
+    const div = win.document.createElement('div');
+    div.getBoundingClientRect();
```
Comment (jridgewell) [inline src/get-bounding-client-rect.js]: This will likely be DCE'd by closure compiler. Instead, we could try something like:

```js
const rect = div.getBoundingClientRect();
return div.top !== 0;
```

File: src/get-bounding-client-rect.js [hunk 9]
```diff
@@ -0,0 +1,65 @@
...
+}
+
+/**
+ * Sets the getBoundingClientRect polyfill if using IE 10 or an
+ * earlier version.
+ * @param {!Window} win
+ */
+export function install(win) {
+  if (shouldInstall(win)) {
+    win.Object.defineProperty(Element.prototype, 'getBoundingClientRect', {
```
Comment (choumx) [inline src/get-bounding-client-rect.js]: `win.Element.prototype`

File: src/get-bounding-client-rect.js [hunk 10]
```diff
@@ -0,0 +1,65 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+import {
+  LayoutRectDef,
+  layoutRectLtwh,
+} from './layout-rect';
+import {isConnectedNode} from './dom';
+
```
Comment (choumx) [inline src/get-bounding-client-rect.js]: Let's explain more clearly why this is needed. Add a file overview comment:

```js
/**
 * @fileoverview
 * IE 10 throws "Unspecified error" when calling getBoundingClientRect() on a disconnected node.
 * @see https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/106812/
 */
```

File: src/get-bounding-client-rect.js (hunk 8 above)
Comment (choumx) [reply src/get-bounding-client-rect.js]: @delima02 What does the compiled output of this look like? 

Hint: use `gulp dist --noextensions` and then try to find this code snippet inside `dist/v0.js`. 

You can open the file in Chrome and use devtools pretty printing to make life easier: https://developers.google.com/web/tools/chrome-devtools/javascript/pretty-print
