### PR TITLE
Increase timeout to fix flakiness of attemptChangeSize request

### LINKED ISSUE #16825: test/integration/test-amp-ad-3p.js is flaky
For example:
https://travis-ci.org/ampproject/amphtml/jobs/405108838#L616
https://travis-ci.org/ampproject/amphtml/jobs/405085066#L616

### PR DESCRIPTION
**Pull request by lannka**
also unmuted an assertion that seems to be working again.
tested locally with complied code.

Closes #16825

### CODE REVIEW

File: test/integration/test-amp-ad-3p.js [hunk 1]
```diff
@@ -162,7 +161,7 @@ describe.configure().skipIfPropertiesObfuscated().run('amp-ad 3P', () => {
     }).then(() => {
       return poll('wait for attemptChangeSize', () => {
         return iframe.contentWindow.ping.resizeSuccess != undefined;
-      });
+      }, null, 5000);
```
Comment (zhouyx) [inline test/integration/test-amp-ad-3p.js]: Hmmm I don't understand. If we don't want to fail the test on this assertion, it's same as we mute it. What's is the difference?

Comment (lannka) [reply test/integration/test-amp-ad-3p.js]: this line change is actually not relevant to the above assertion that I unmute. just found this `poll` is flaky out on Travis.

Comment (lannka) [reply test/integration/test-amp-ad-3p.js]: Updated PR description to better describe the intention of the PR.
