### PR TITLE
Polyfill for shadowRoot.styleSheets in Safari

### LINKED ISSUE #11266: Components in Shadow DOM fail with errors in Desktop and Mobile Safari
screen shot 2017-09-11 at 2 18 18 pm

### PR DESCRIPTION
**Pull request by cvializ**
Fixes #11266

It creates a new list each access, but it will always be up to date if any stylesheets are added. Open to suggestions.

### CODE REVIEW

File: src/shadow-embed.js [hunk 1]
```diff
@@ -61,7 +66,15 @@ export function createShadowRoot(hostElement) {
   // Native support.
   const shadowDomSupported = getShadowDomSupportedVersion();
   if (shadowDomSupported == ShadowDomVersion.V1) {
-    return hostElement.attachShadow({mode: 'open'});
+    const shadowRoot = hostElement.attachShadow({mode: 'open'});
+    if (!shadowRoot.styleSheets) {
+      Object.defineProperty(shadowRoot, 'styleSheets', {
+        get: function() {
+          return new StyleSheetListImpl(shadowRoot);
```
Comment (dvoytenko) [inline src/shadow-embed.js]: Unfortunately, everywhere we use this property is via array access. E.g. `x.styleSheets[0]`. I'm thinking maybe let's use array instead? Or any other idea?

Comment (cvializ) [reply src/shadow-embed.js]: Ah I missed that, I was just reading the spec which only offers an items property.
