### PR TITLE
🏗 Check for unknown dependencies during after compilation

### LINKED ISSUE #24283: Closure complier not failing when expected
I introduced some code in #24044 which included a new dependency where `amp-story-auto-ads` is dependent on the [`assertConfig`](https://github.com/ampproject/amphtml/blob/098b2be2852515f4a3ecf5100f0e72d8cff515df/extensions/amp-ad-exit/0.1/config.js#L117) function from `amp-ad-exit`.

I added the explicit path `extensions/amp-ad-exit/0.1/config.js` to the [`CLOSURE_SRC_GLOBS`](https://github.com/ampproject/amphtml/blob/098b2be2852515f4a3ecf5100f0e72d8cff515df/build-system/sources.js#L68) array.

This function has a transitive dependency of the `extensions/amp-ad-exit/0.1/filters/filter.js` file. When this change hit canary it started throwing the error `FilterType$$module$extensions$amp_ad_exit$0_1$filters$filter is not defined`

It is unclear why this error was not caught at compile time. I also manually tested with `gulp clean && gulp dist --fortesting && gulp serve --compiled` and everything appeared to be working fine.

### PR DESCRIPTION
**Pull request by jridgewell**
Fixes #24283.

Blocked by:
- ~https://github.com/ampproject/amphtml/issues/24297~
- ~https://github.com/ampproject/amphtml/issues/24281~
- ~https://github.com/ampproject/amphtml/issues/24253~

### CODE REVIEW

File: build-system/compile/check-for-unknown-deps.js [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+ */
+'use strict';
+
+const colors = require('ansi-colors');
+const log = require('fancy-log');
+const through = require('through2');
+
+/**
+ * We can replace full-text of standard licenses with a pre-approved shorten
+ * version.
```
Comment (rsimha) [inline build-system/compile/check-for-unknown-deps.js]: Update copy-pasta comment.

File: build-system/compile/compile.js [hunk 2]
```diff
@@ -372,11 +373,17 @@ function compile(entryModuleFilenames, outputDir, outputFilename, options) {
         .pipe(gulpIf(shouldShortenLicense, shortenLicense()))
         .pipe(sourcemaps.init({loadMaps: true}))
         .pipe(gulpClosureCompile(compilerOptionsArray, distNailgunPort))
+        .pipe(rename(outputFilename))
+        .pipe(
+          gulpIf(
+            !argv.pseudo_names && options.shouldCheckUnknownDeps !== false,
```
Comment (rsimha) [inline build-system/compile/compile.js]: This logic looks unwieldy. What if you switch `shouldCheckUnknownDeps` to `skipUnknownDepsCheck` with a default value of `false`, and change the `gulpIf` condition to `!argv.pseudo_names && !options.skipUnknownDepsCheck`?

File: bundles.config.js [hunk 3]
```diff
@@ -134,6 +134,7 @@ exports.jsBundles = {
       incudePolyfills: true,
       extraGlobs: ['extensions/amp-viewer-integration/**/*.js'],
       compilationLevel: 'WHITESPACE_ONLY',
+      shouldCheckUnknownDeps: false,
```
Comment (rsimha) [inline bundles.config.js]: Per my other comment, change this to `skipUnknownDepsCheck: true`.

**Comment by jridgewell** [comment]
Blocked by:
- https://github.com/ampproject/amphtml/issues/24297
- https://github.com/ampproject/amphtml/issues/24281
- https://github.com/ampproject/amphtml/issues/24253

File: build-system/compile/compile.js [hunk 4]
```diff
@@ -372,11 +373,17 @@ function compile(entryModuleFilenames, outputDir, outputFilename, options) {
...
         .pipe(sourcemaps.init({loadMaps: true}))
         .pipe(gulpClosureCompile(compilerOptionsArray, distNailgunPort))
+        .pipe(rename(outputFilename))
+        .pipe(
+          gulpIf(
+            !argv.pseudo_names && !options.skipUnknownDepsCheck,
+            checkForUnknownDeps()
+          )
+        )
         .on('error', err => {
```
Comment (rsimha) [inline build-system/compile/compile.js]: I believe this handler should immediately follow the compile step.

File: build-system/compile/compile.js [hunk 5]
```diff
@@ -377,6 +378,16 @@ function compile(entryModuleFilenames, outputDir, outputFilename, options) {
...
+        .pipe(
+          gulpIf(
+            !argv.pseudo_names && !options.skipUnknownDepsCheck,
+            checkForUnknownDeps()
+          )
+        )
+        .on('error', err => {
+          handleCompilerError(outputFilename);
+          reject(err);
+        })
```
Comment (rsimha) [inline build-system/compile/compile.js]: This one is unnecessary

File: build-system/compile/compile.js [hunk 6]
```diff
@@ -389,6 +390,12 @@ function compile(
           reject(err);
         })
         .pipe(rename(outputFilename))
+        .pipe(
+          gulpIf(
+            !argv.pseudo_names && !options.skipUnknownDepsCheck,
```
Comment (rsimha) [inline build-system/compile/compile.js]: I take it this works for single pass?

File: build-system/compile/compile.js [hunk 7]
```diff
@@ -389,6 +390,12 @@ function compile(
...
+            checkForUnknownDeps()
```
Comment (rsimha) [inline build-system/compile/compile.js]: Can you make `checkForUnknownDeps()` call `reject` if the check fails? Similar to line 390. It's plumbed through the rest of the compilation pipeline.

Comment (jridgewell) [reply build-system/compile/compile.js]: You told me to delete it https://github.com/ampproject/amphtml/pull/24284#discussion_r321505122

Comment (rsimha) [reply build-system/compile/compile.js]: The thing I asked you to delete back then was the call to `handleCompilerError()`, which is only meant to process errors spat out by closure compiler.

What I'm suggesting right now is that you call `reject` with whatever error `checkForUnknownDeps()` spits out (assuming it fails).

Unless I'm missing something?

Comment (rsimha) [reply build-system/compile/compile.js]: I think this will work:
```js
        .pipe(
          gulpIf(
            !argv.pseudo_names && !options.skipUnknownDepsCheck,
            checkForUnknownDeps()
          )
        )
        .on('error', reject)
        .pipe(sourcemaps.write('.'))
```

Comment (jridgewell) [reply build-system/compile/compile.js]: Done.

Comment (rsimha) [reply build-system/compile/compile.js]: And I went in and looked at `handleCompilerError` and noticed that all it does is print a message with the filename, so it's fine to call it here. I retract my entire series of comments!

File: build-system/compile/compile.js (hunk 6 above)
Comment (jridgewell) [reply build-system/compile/compile.js]: Done.

File: build-system/compile/check-for-unknown-deps.js [hunk 8]
```diff
@@ -0,0 +1,55 @@
...
+
+    const match = regex.exec(contents) || [
+      `couldn't parse the dep. Look for "$$module$" in the file`,
+    ];
+
+    log(
+      colors.red(
+        'Unknown dependency found in ' + file.relative + ': ' + match[0]
+      )
+    );
```
Comment (rsimha) [inline build-system/compile/check-for-unknown-deps.js]: This `log` statement may not be necessary, since the compilation pipeline prints out the error you're emitting in lines 48-53.

Comment (rsimha) [reply build-system/compile/check-for-unknown-deps.js]: #25248. WDYT?
