### PR TITLE
Make DocInfo.pageViewId64 async

### LINKED ISSUE #23988: Error: Cannot read property 'obj' of undefined
Started seeing these in [1908150025400](https://github.com/ampproject/amphtml/releases/tag/1908150025400). A top 10 error report in the first day of 1%.

```
Error: Cannot read property 'obj' of undefined
at obj (https://raw.githubusercontent.com/ampproject/amphtml/1908150025400/src/service.js:395)
at getServiceInternal (https://raw.githubusercontent.com/ampproject/amphtml/1908150025400/src/service.js:196)
at (https://raw.githubusercontent.com/ampproject/amphtml/1908150025400/src/services.js:280)
at Services$$module$src$services.extensionsFor (https://raw.githubusercontent.com/ampproject/amphtml/1908150025400/src/service/crypto-impl.js:155)
at loadPolyfill_ (https://raw.githubusercontent.com/ampproject/amphtml/1908150025400/src/service/crypto-impl.js:81)
at sha384 (https://raw.githubusercontent.com/ampproject/amphtml/1908150025400/src/service/crypto-impl.js:123)
at sha384Base64 (https://raw.githubusercontent.com/ampproject/amphtml/1908150025400/src/service/cid-impl.js:655)
at getRandomString64 (https://raw.githubusercontent.com/ampproject/amphtml/1908150025400/src/service/document-info-impl.js:95)
at get (https://raw.githubusercontent.com/ampproject/amphtml/1908150025400/src/services.js:269)
at Services$$module$src$services.documentInfoForDoc (https://raw.githubusercontent.com/ampproject/amphtml/1908150025400/src/service/resources-impl.js:1223)
```

Stack trace implies that `"extensions"` service is not registered on the given window, which is confusing.

UA appears to be always "Miui Browser".

### PR DESCRIPTION
**Pull request by choumx**
Fixes #23988.

Bug introduced in: https://github.com/ampproject/amphtml/pull/23451/files#r314530969

Affects browsers that don't implement `WebCrypto` or `Crypto.getRandomValues`: https://caniuse.com/#search=getRandomValues

### CODE REVIEW

File: src/service/document-info-impl.js [hunk 1]
```diff
@@ -104,7 +105,15 @@ export class DocInfo {
       },
       canonicalUrl,
       pageViewId,
-      pageViewId64,
+      get pageViewId64() {
```
Comment (zhouyx) [inline src/service/document-info-impl.js]: Does this mean we are relying on ` get pageViewId64()` getting called after extensions service is ready?

**Comment by jridgewell** [comment]
Does this even need to be on document info?

**Comment by zhouyx** [comment]
@jridgewell Good point. Maybe not.

I do see one concern here. If this hasn't changed, FIE and the parent doc shares the same ampdoc instance. Maybe we should not store pageViewId within the `DocInfo`, as that shares the same id between FIE and parent doc. 

Do you see this as the case? If so I think that's an issue we need to fix asap

**Comment by choumx** [comment]
> Maybe we should not store pageViewId within the DocInfo, as that shares the same id between FIE and parent doc.

This would also affect `PAGE_VIEW_ID` then, right? `PAGE_VIEW_ID_64` isn't a whitelisted A4A variable but looks like `PAGE_VIEW_ID` is.

https://github.com/ampproject/amphtml/blob/dcaf2ceebe44693d4e377528293ef6ba0385ff68/extensions/amp-a4a/0.1/a4a-variable-source.js#L26-L71

**Comment by zhouyx** [comment]
True, it should only affect PAGE_VEW_ID. cc @lannka Should page_view_id be supported in FIE?

**Comment by zhouyx** [comment]
Talked to @lannka offline, we will be sharing `PAGE_VIEW_ID`, and maybe `PAGE_VIEW_ID_64` in the future upon request. This is good now

File: src/service/document-info-impl.js (hunk 1 above)
Comment (choumx) [reply src/service/document-info-impl.js]: Only after it's registered which happens very soon afterwards in `runtime.adopt()`.
