### PR TITLE
amp-date-picker: restore rrule support

### LINKED ISSUE #24682: amp-date-picker highlighted/blocked attributes do not work
## What's the issue?

amp-date-picker highlighted and blocked attributes have no effect

## How do we reproduce the issue?

See https://amp.dev/documentation/examples/components/amp-date-picker/?format=websites#highlighted-and-blocked-attributes . 

## What browsers are affected?

All browsers? 

## Which AMP version is affected?

AMP version 1909141409590. Not sure if this is a new issue, haven't tried to use the date picker before.

### PR DESCRIPTION
**Pull request by samouri**
**summary**
Reverts #25230, fixes #24682 and https://github.com/ampproject/amphtml/issues/25244. This PR replaces https://github.com/ampproject/amphtml/pull/28842.

We need `rrule` in order to support a couple of [features](https://github.com/ampproject/amphtml/issues/24682) within amp-date-picker. `rrule` imports luxon which has circular deps which breaks Google Closure Compiler. 

Even though `luxon` is marked as an optional dependency of rrule within its package.json, it statically [imports luxon](https://github.com/jakubroztocil/rrule/blob/7790d8cc9f37aaaf45e7e968c0743417bf150cff/src/datewithzone.ts#L2) making it essentially required. If Closure Compiler had the same notion of "externals" that webpack has we could potentially get around it by declaring luxon as external.

short term fix: patch `datewithzone.js` within node_modules.
long term fix: find a better solution: e.g. a timezone-less esm output target for rrule. 

**rrule in action**
Screen Shot 2020-06-15 at 2 32 41 PM

cc @caroqliu

### CODE REVIEW

File: build-system/compile/sources.js [hunk 1]
```diff
@@ -42,6 +42,9 @@ const COMMON_GLOBS = [
   'node_modules/intersection-observer/intersection-observer.install.js',
   'node_modules/promise-pjs/package.json',
   'node_modules/promise-pjs/promise.mjs',
+  'node_modules/rrule-without-luxon/dist/esm/src/**/*.js',
```
Comment (caroqliu) [inline build-system/compile/sources.js:45]: I think you should be able to reference the import with `rrule-without-luxon` if you add the `package.json` here.

**Comment by caroqliu** [comment]
One thing to consider here: I believe the original motivation for putting `rrule` directly in the `node_modules` is so it would get opted into auto version upgrades with renovate bot. If we want to use some modified unchanging version like `rrule-without-luxon` we should be able to place it in `third_party/` instead of forking from your repo. /cc @rsimha

**Comment by samouri** [comment]
After testing, I've learned that the esm version of rrule adds `12.01KB` whereas the es5 version adds `12.68KB`.
I was surprised by how well the es5 version minifies based on usage (from 50kb!). It opens up another possibility for us to upstream a fix and use the built es5 version.

Testing this out now here https://github.com/jakubroztocil/rrule/pull/410

File: .renovaterc.json [hunk 2]
```diff
@@ -77,6 +77,10 @@
         "managerBranchPrefix": "linting-"
       }
     },
+    {
+      "packagePatterns": ["rrule"],
```
Comment (samouri) [inline .renovaterc.json:81]: I don't actually know if this is valid renovate bot config or how to test it out, but the intention is to have rrule opt out of auto-updates since they could be breaking. I'll leave a comment (pretty sure renovate supports json with comments).

**Comment by samouri** [comment]
@rsimha: do you have any preference between using a fork of `rrule` that lives within third_party vs. [patching](https://github.com/ampproject/amphtml/pull/28887/files#diff-75c4fd3240d8b8609fb3755e55636581R98) it within the `update_packages` command?

**Comment by rsimha** [comment]
> @rsimha: do you have any preference between using a fork of `rrule` that lives within third_party vs. [patching](https://github.com/ampproject/amphtml/pull/28887/files#diff-75c4fd3240d8b8609fb3755e55636581R98) it within the `update_packages` command?

Sorry about the late reply. My preference is to patch `node_modules/rrule/` during `gulp update-packages` for two reasons: a) there is precedent for doing so, and b) we'll benefit from regular updates to `rrule` and still retain the benefit of being able to patch the JS file.

**Comment by samouri** [comment]
Oh noes, while this seems to work in uncompiled mode, when its compiled I get errors that I haven't been able to debug: 
Screen Shot 2020-06-29 at 1 56 07 PM

**Comment by rsimha** [comment]
> This is still suboptimal because an `rrule` update may break the patch. I don't see a good answer here without an upstreamed fix or manually periodically updating the src.

Yeah. Hopefully your patch is targeted enough that it will always work. Perhaps you could make the replacement optional and print a non-blocking warning if it's missing, so that if a future version stops importing `luxon`, we'll get to know without breaking compilation.

**Comment by samouri** [comment]
> print a non-blocking warning if it's missing

I'm not sure this makes sense considering we run `update-packages` more often than we reinstall the local node_modules, which is why they use `writeIfModified` (on most runs, the node_modules have already been patched so no work is necessary).

**Comment by samouri** [comment]
@caroqliu / @rsimha: this is ready for a rereview :)

File: build-system/tasks/update-packages.js [hunk 3]
```diff
@@ -95,6 +95,29 @@ function patchIntersectionObserver() {
   writeIfUpdated(patchedName, file);
 }
 
+/**
+ * TODO(samouri): remove this patch when a better fix is upstreamed (https://github.com/jakubroztocil/rrule/pull/410).
+ *
+ * Patches rrule to remove references to luxon. Even though rrule marks luxon as an optional dependency,
+ * it is used as if its a required one (static import). rrule relies on its consumers either
```
Comment (rsimha) [inline build-system/tasks/update-packages.js:102]: super-nit: First `its` on this line should be `it's`.

File: build-system/compile/sources.js [hunk 4]
```diff
@@ -42,6 +42,7 @@ const COMMON_GLOBS = [
   'node_modules/intersection-observer/intersection-observer.install.js',
   'node_modules/promise-pjs/package.json',
   'node_modules/promise-pjs/promise.mjs',
+  'node_modules/rrule/dist/es5/rrule.min.js',
```
Comment (rsimha) [inline build-system/compile/sources.js:45]: OMG, you got this to work!

giphy-downsized

File: build-system/tasks/update-packages.js (hunk 3 above)
Comment (samouri) [reply build-system/tasks/update-packages.js:102]: I appreciate the grammar fix :)

File: extensions/amp-date-picker/0.1/dates-list.js [hunk 5]
```diff
@@ -14,16 +14,20 @@
  * limitations under the License.
  */
 
+import * as rrule from '../../../node_modules/rrule/dist/es5/rrule.min.js';
 import {requireExternal} from '../../../src/module';
 
+const rrulestr = rrule.default.rrulestr || rrule.rrulestr; // CC imports into .default, browserify flattens a layer.
```
Comment (jridgewell) [inline extensions/amp-date-picker/0.1/dates-list.js:20]: Nit: Please move this into `tryParseRrulestr`.

**Comment by samouri** [comment]
sidebar: i realized that `amp-date-picker` currently accepts dates that are not the ISO 8601. We should either change the documentation or make the code more strict.

File: extensions/amp-date-picker/0.1/dates-list.js (hunk 5 above)
Comment (samouri) [reply extensions/amp-date-picker/0.1/dates-list.js:20]: I think it makes more sense where it is, considering ideally it would even be `import {rrulestr} from 'rrule';`
