### PR TITLE
Don't use ES6 syntax in gulp task definitions

### LINKED ISSUE #9106: gulp test fails without running any tests
Test log:

```
/home/taymon/amphtml/build-system/tasks/visual-diff.js:91
  let webpage = '';
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/taymon/amphtml/build-system/tasks/index.js:35:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/taymon/amphtml/gulpfile.js:40:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Liftoff.handleArguments (/home/taymon/.nvm/versions/node/v4.7.2/lib/node_modules/gulp/bin/gulp.js:116:3)
```

### PR DESCRIPTION
**Pull request by rsimha-amp**
This PR fixes all instances of ES6 syntax in visual-diff.js.

FIxes #9106

### CODE REVIEW

**Comment by jridgewell** [comment]
- All the `const`s
- `String#includes` on L58

File: build-system/tasks/visual-diff.js [hunk 1]
```diff
@@ -33,7 +33,7 @@ const percyTokenLength = 64;  // Standard Percy API key length.
  * @param {string} cmd
  */
 function execOrDie(cmd) {
-  const p =
+  var p =
       child_process.spawnSync('/bin/sh', ['-c', cmd], {'stdio': 'inherit'});
   if (p.status != 0) {
     console/*OK*/.log(
```
Comment (taymonbeal) [inline build-system/tasks/visual-diff.js]: No template strings in ES5

File: build-system/tasks/visual-diff.js [hunk 2]
```diff
@@ -130,7 +130,7 @@ function constructCommandLine(percyKeys) {
   commandLine.push('--repo ' + percyKeys.percyProject);
 
   // Percy args.
-  const percyArgs = extractPercyArgs();
+  var percyArgs = extractPercyArgs();
   commandLine.push('--baseurl /' + percyArgs.webpage);
   commandLine.push('--widths ' + percyArgs.widths);
```
Comment (taymonbeal) [inline build-system/tasks/visual-diff.js]: No arrow functions in ES5

**Comment by rsimha-amp** [comment]
I tested my original PR by running "gulp test" before submitting it. Could this be a difference between running gulp test on macOS vs. Linux?

**Comment by taymonbeal** [comment]
What version of Node are you running? (`node -v`)

**Comment by rsimha-amp** [comment]
I'm using node v7.9.0.

**Comment by taymonbeal** [comment]
Ah, that version supports most of ES6. I'm using v4.8.3, which, according to package.json, is the version that AMP officially supports. Should we consider just bumping the required Node version and then use ES6 freely in Node scripts?

File: build-system/tasks/visual-diff.js (hunk 1 above)
Comment (rsimha-amp) [inline build-system/tasks/visual-diff.js]: Done.

File: build-system/tasks/visual-diff.js (hunk 2 above)
Comment (rsimha-amp) [inline build-system/tasks/visual-diff.js]: Done.

**Comment by taymonbeal** [comment]
Also, I observe that Travis is configured to run against the latest stable release.

**Comment by rsimha-amp** [comment]
Yes. I noticed that there is ES6 syntax in other js files in build-system. There certainly is ES6 code in pr-check.js, which runs against every PR. I'll keep this in mind for later. Meanwhile, I still think there's value in checking in the changes in this PR, since others on the team are likely to run into what you just saw.

I've pushed a new commit with (hopefully) all the changes you requested.

**Comment by rsimha-amp** [comment]
@jridgewell or @taymonbeal, could one of you merge this PR? (I don't have permissions yet.)
