### PR TITLE
Bypass isConnected checks when destroying FIE

### LINKED ISSUE #15883: Error: Cannot read property '__AMP_TOP' of undefined
High frequency error reported in most recent canary 1528247370025 with 6k occurrences. 

Stacktrace: 
```
Error: Cannot read property '__AMP_TOP' of undefined
at (https://raw.githubusercontent.com/ampproject/amphtml/1527203409437/build/patched-module/document-register-element/build/document-register-element.node.js:390)
at (https://raw.githubusercontent.com/ampproject/amphtml/1527203409437/build/patched-module/document-register-element/build/document-register-element.node.js:99)
at (https://raw.githubusercontent.com/ampproject/amphtml/1527203409437/build/patched-module/document-register-element/build/document-register-element.node.js:412)
at (https://raw.githubusercontent.com/ampproject/amphtml/1527203409437/build/patched-module/document-register-element/build/document-register-element.node.js:369)
at (https://raw.githubusercontent.com/ampproject/amphtml/1527203409437/build/patched-module/document-register-element/build/document-register-element.node.js:1009)
at (https://raw.githubusercontent.com/ampproject/amphtml/1527203409437/src/service/ampdoc-impl.js:229)
at declaresExtension (https://raw.githubusercontent.com/ampproject/amphtml/1527203409437/src/service/ampdoc-impl.js:242)
at onResize (https://raw.githubusercontent.com/ampproject/amphtml/1527203409437/src/service/viewport/viewport-impl.js:577)
at (https://raw.githubusercontent.com/ampproject/amphtml/1527203409437/src/service/resource.js:660)
at (https://raw.githubusercontent.com/ampproject/amphtml/1527203409437/src/service/resources-impl.js:2148)
```

Sample Metadata
Referrer	
https://amp-20minutos-es.cdn.ampproject.org/v/s/amp.20minutos.es/noticia/3057043/0/que-es-defensor-pueblo/?amp_js_v=a1&amp_gsa=1&usqp=mq331AQCCAE%3D 
User agent	
Mozilla/5.0 (Linux; Android 7.0; SM-G570M Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.68 Mobile Safari/537.36

### LINKED ISSUE #17604: Error: null is not an object (evaluating 'new a.Image')
Appears starting in the current opt-in canary release (1534447274459)

```
Error: null is not an object (evaluating 'new a.Image')
at Image (https://raw.githubusercontent.com/ampproject/amphtml/1534447274459/src/pixel.js:69)
at iframe (https://raw.githubusercontent.com/ampproject/amphtml/1534447274459/src/pixel.js:57)
at win (https://raw.githubusercontent.com/ampproject/amphtml/1534447274459/extensions/amp-analytics/0.1/transport.js:79)
at win (https://raw.githubusercontent.com/ampproject/amphtml/1534447274459/extensions/amp-analytics/0.1/transport.js:61)
at requestUrl (https://raw.githubusercontent.com/ampproject/amphtml/1534447274459/extensions/amp-analytics/0.1/requests.js:247)
```

### LINKED ISSUE #17839: Error: null is not an object (evaluating 'a.getComputedStyle')
Error at: go/ampe/CIflwJ_xzvSrLg
Occurring 3,893 / day, new bug on version 1535579255907

Stacktrace
```
Error: null is not an object (evaluating 'a.getComputedStyle')
at (https://raw.githubusercontent.com/ampproject/amphtml/1535579255907/src/dom.js:50)
at (https://raw.githubusercontent.com/ampproject/amphtml/1535579255907/src/service/fixed-layer.js:767)
at setupElement_ (https://raw.githubusercontent.com/ampproject/amphtml/1535579255907/src/service/fixed-layer.js:476)
at (https://raw.githubusercontent.com/ampproject/amphtml/1535579255907/src/service.js:172)
```

### PR DESCRIPTION
**Pull request by jridgewell**
This may be the cause of all the "window is null" bugs...

Introduced in #13945, we started to ignore `disconnectedCallback`s when the node itself was still connected to a document. But, FIE's destroy themselves and try to clean up `Resource`s even though those resources are still connected to the FIE's document. So, we would end up ignoring the disconnect, leaving all of them in memory and active.

Fixes #17839.
Fixes #15883.
Fixes #17604.
Probably more... Anything that touches FIE.

Fixes (maybe) #9177?
Fixes (maybe) #17840?

Working on tests now.

### CODE REVIEW

File: src/custom-element.js [hunk 1]
```diff
@@ -863,13 +866,34 @@ function createBaseCustomElementClass(win) {
...
+    /** The Custom Elements V0 sibling to `disconnectedCallback`. */
+    detachedCallback() {
+      this.disconnectedCallback();
+    }
+
+    /**
+     * Called when an element is disconnected from DOM, or when an ampDoc is
+     * being disconnected (the element itself may still be connected to ampDoc).
+     *
+     * This does not guard against connected elements.
```
Comment (choumx) [inline src/custom-element.js]: This is confusing since we still check `this.isConnected_`. Maybe rename that variable to `connectedCallbackWasCalled_`?

File: src/custom-element.js [hunk 2]
```diff
@@ -863,13 +866,34 @@ function createBaseCustomElementClass(win) {
...
+     */
+    disconnect() {
```
Comment (choumx) [inline src/custom-element.js]: I think using `opt_force = false` or `opt_checkDom = true` param in `disconnectedCallback` is more readable. Then add a comment to resource.js about why we pass false in that case.

Comment (jridgewell) [reply src/custom-element.js]: Done.

**Comment by cathyxz** [comment]
@jridgewell @choumx is this PR important enough to cherry pick into the current release before promoting to production? All of these referenced issues are present in current canary at relatively high error rates.
