### PR TITLE
Move out ini-load related logic to separate file.

### LINKED ISSUE #24421: "A more real AMPHTML image ad" test flaky in INABOX_LITE experiment
Integration tests in `test-amphtml-ads.js` are flaky on Headless Chrome in experiment B (INABOX_LITE):
```
DESCRIBE => A more real AMPHTML image ad
  DESCRIBE => ATF within friendly frame or safe frame
    DESCRIBE =>  
      IT => should properly render ad in a friendly iframe with viewability pings
        ✗ Error: Timeout of 15000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
●
      IT => should properly render ad in a safe frame with viewability pings
        ✗ Error: Timeout of 15000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
●
  DESCRIBE => No Host Script within friendly frame or safe frame
    DESCRIBE =>  
      IT => should properly render ad in a friendly iframe with viewability pings
        ✗ Error: Timeout of 15000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
●
      IT => should properly render ad in a safe frame with viewability pings
        ✗ Error: Timeout of 15000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

[23:25:01] HeadlessChrome 76.0.3809 (Linux 0.0.0): Executed 266 of 440 (Skipped 174) 4 FAILED
```

Two flakes on master today.

https://travis-ci.org/ampproject/amphtml/builds/582846281
https://travis-ci.org/ampproject/amphtml/builds/582910186

/to @lannka

### PR DESCRIPTION
**Pull request by lannka**
fixes #24421

- moved `whenContentIniLoad` from `friendly-iframe-embed.js` to `ini-load.js`, as it is used by `amp-analytics`, `amp-a4a` & `performance-impl`
- moved `getMeasuredResources` from `resources-impl.js` to `ini-load.js`
- migrated the only usage of `getResourcesInRect` to `whenContentIniLoad`

This change mostly are just rearranging the dependencies. The only one logic change:
Before: performance-impl's `pc` event waits for all resources in viewport to load
After: performance-impl's `pc` event waits for resources other than 
https://github.com/ampproject/amphtml/blob/f292573c6a7419c9a47f10c5ddd69d0d67e42da6/src/friendly-iframe-embed.js#L61-L66

I think the new behavior is what we actually wanted. 

@dvoytenko PTAL if it looks right. will update tests if it looks good in general.

### CODE REVIEW

File: src/service/performance-impl.js [hunk 1]
```diff
@@ -632,13 +633,12 @@ export class Performance {
...
-        .resources_);
-      return resources
-        .getResourcesInRect(this.win, rect, /* isInPrerender */ true)
-        .then(resources => Promise.all(resources.map(r => r.loadedOnce())));
+      return whenContentIniLoad(
+        documentElement,
+        this.win,
+        rect,
+        /* isInPrerender */ true
+      );
```
Comment (lannka) [inline src/service/performance-impl.js]: note that here is a logic diff:

whenContentIniLoad does not wait for elements like `amp-ad`, `amp-analytics` etc, which I think is the right behavior for performance reporting. Let me know what you think.

Comment (lannka) [reply src/service/performance-impl.js]: @dvoytenko

Comment (dvoytenko) [reply src/service/performance-impl.js]: Is there a delta from the old behavior in practice? Is it in a way the performance service worked before or some other service?

Comment (lannka) [reply src/service/performance-impl.js]: yes, as noted above, the diff is that 
Before: performance-impl's `pc` event waits for all resources in viewport to load
After: performance-impl's `pc` event waits for resources other than 
https://github.com/ampproject/amphtml/blob/f292573c6a7419c9a47f10c5ddd69d0d67e42da6/src/friendly-iframe-embed.js#L61-L66

I think the new behavior is what we actually wanted. Let me know if you think otherwise.

Comment (dvoytenko) [reply src/service/performance-impl.js]: Ads and analytics are not pre-render-allowed components. So they were excluded before as well. Are there other deltas?

Comment (lannka) [reply src/service/performance-impl.js]: OK, so it means no delta then.
