### PR TITLE
🐛 [amp-consent] Fix <amp-consent> inside <amp-next-page> firing again for the same consent id

### LINKED ISSUE #29449: <amp-consent> inside <amp-next-page> fires twice when loaded from Google Search viewer
## What's the issue?

I can only reproduce this in AMP documents loaded inside the Google Search results AMP viewer.

If an AMP page uses the following:

- `<amp-consent>` extension
- `<amp-next-page>` to load a second AMP document. This document also contains the `<amp-consent>` extension

The expected behaviour is that since the `<amp-consent>` has already collected user's consent in the host AMP document, the `<amp-consent>` component that belongs to the hosted AMP document loaded inside the `<amp-next-page>` is not asking for consent again.

When the AMP document is loaded from its canonical URL the behaviour is the right one, all works fine. However, when the same AMP document is loaded from the Google Search AMP viewer, the `<amp-consent>` appears twice: first when the user opens the page, and second when the user scrolls down and the AMP document inside the `<amp-next-page>` becomes active 

I understand that not having the `<amp-consent>` component in the hosted AMP document inside the `<amp-next-page>` is not an option, because then other components wouldn't receive the user's consent (`<amp-analytics>` `<amp-ad>` etc.)

## How do we reproduce the issue?
To reproduce this you need to load the URLs from a region where GDPR / CCPA applies (i.e EU or California)

Here you can see an AMP document loaded inside the Google AMP viewer where the issue is reproducible
https://www.google.com/amp/s/ewn.co.za/2020/07/23/economists-express-mixed-views-on-another-interest-rate-cut/amp

The same document loaded from the original URL works correctly
https://ewn.co.za/2020/07/23/economists-express-mixed-views-on-another-interest-rate-cut/amp

### PR DESCRIPTION
**Pull request by dmanek**
Fixes #29449

### CODE REVIEW

**Review by dvoytenko — APPROVED** [review]

File: src/services.js [hunk 1]
```diff
@@ -632,6 +632,26 @@ export class Services {
...
+      : null;
+    // We need to verify that ampdocs are on the same origin, therefore
+    // we compare the windows of both.
+    const ampdoc =
+      topAmpdoc && topAmpdoc.win == thisAmpdoc.win ? topAmpdoc : thisAmpdoc;
+    return /** @type {!Promise<!./service/storage-impl.Storage>} */ (getServicePromiseForDoc(
+      ampdoc,
+      'storage'
+    ));
+  }
```
Comment (micajuine-ho) [inline src/services.js:653]: Can we add a test for this new functionality in `test-storage`?

**Review by micajuine-ho — CHANGES_REQUESTED** [review]

File: src/services.js (hunk 1 above)
Comment (dmanek) [reply src/services.js:653]: `test-service.js` is for `service.js`. Unfortunately, there's are no unit tests for the functions in `serviceS.js` 😞

Comment (micajuine-ho) [reply src/services.js:653]: I see, that's probably because most of the `serviceS.js` is installing element or doc services and not much meat. Up to you if you want to add test somewhere to give us more confidence.

**Review by micajuine-ho — APPROVED** [review]

File: src/services.js (hunk 1 above)
Comment (dmanek) [reply src/services.js:654]: Added todo. Good item for fixit week.

**Review by rsimha — APPROVED** [review]

File: spec/amp-localstorage.md [hunk 2]
```diff
@@ -58,6 +58,7 @@ The following AMP components and service are using the localStorage.
 -   `<amp-user-notification>` : Store the user decision on dismiss notification
 -   `<amp-consent>` : Store the user decision and granular information on consent
 -   Client ID Service : Store the user decision to opt-out CID service.
+-   Consent Instance : Store the user consent decision.
```
Comment (micajuine-ho) [inline spec/amp-localstorage.md:61]: Is this different from the above:
```
<amp-consent> : Store the user decision and granular information on consent
```

**Review by micajuine-ho — COMMENTED** [review]
Do you think it's better to add documentation in `amp-next-page` or `amp-consent`, to say that you should have the same consent config in all the pages?

File: spec/amp-localstorage.md (hunk 2 above)
Comment (dmanek) [reply spec/amp-localstorage.md:61]: Added it because Consent Instance is a service. And defined in `consent-state-manager.js` not in `amp-consent.js`.
