### PR TITLE
🐛 Don't assume window is always available for inabox. It can be already destroyed

### LINKED ISSUE #22961: Cannot read property 'frameElement' of null
## What's the issue?

An unhandled exception is raised: 

TypeError: Cannot read property 'frameElement' of null

## How do we reproduce the issue?

Check details here: https://sentry.io/share/issue/7cfc752c7b4b41109082328ee016644c/

## What browsers are affected?

Chrome

## Which AMP version is affected?

https://raw.githubusercontent.com/ampproject/amphtml/1906111828200/ads/inabox/position-observer.js

### PR DESCRIPTION
**Pull request by lannka**
Fixes #22961

### CODE REVIEW

File: ads/inabox/position-observer.js [hunk 1]
```diff
@@ -136,7 +136,11 @@ export class PositionObserver {
     const parentWin = element.ownerDocument.defaultView;
     for (
       let j = 0, tempWin = parentWin;
-      j < 10 && tempWin != this.win_ && tempWin != this.win_.top;
+      j < 10 &&
+      // win can be null if the ad iframe is already destroyed
+      tempWin != null &&
```
Comment (powerivq) [inline ads/inabox/position-observer.js]: How about
```js
tempWin &&
tempWin != this.win_ &&
tempWin != this.win_.top;
```
?
