### PR TITLE
Inabox: Support layers

### LINKED ISSUE #17825: Inabox ad visibility tracking is broken on Safari in current canary release 1535579255907
Caused by the launch of "layers" experiment.

### PR DESCRIPTION
**Pull request by jridgewell**
Layers returns scroll relative layout boxes.

Fixes #17825

### CODE REVIEW

File: src/inabox/inabox-viewport.js [hunk 1]
```diff
@@ -177,9 +180,14 @@ export class ViewportBindingInabox {
   /** @override */
   getLayoutRect(el) {
     const b = el./*OK*/getBoundingClientRect();
+    let {left, top} = b;
+    if (this.useLayers_) {
+      left -= this.viewportRect_.left;
```
Comment (lannka) [inline src/inabox/inabox-viewport.js]: can you explain why do we offset with viewportRect?

Comment (lannka) [reply src/inabox/inabox-viewport.js]: oh, is layer's coordinate system relative to viewport instead of doc?

Comment (jridgewell) [reply src/inabox/inabox-viewport.js]: Yes, Layer’s rects should exactly match `getBoundingClientRect` (with rounding) in every circumstance.

In this case, we need to factor in that the is relative to a viewport in a parent document.
