### PR TITLE
Fix amp-pixel integration test on Saucelabs.

### LINKED ISSUE #8853: Unskip amp-pixel test
Need to fix the amp-pixel test and unskip integration test.
related to #8597  
Please fix change from #8862, #8859 .
https://travis-ci.org/ampproject/amphtml/builds/223723995
https://travis-ci.org/ampproject/amphtml/builds/224049453

### PR DESCRIPTION
**Pull request by lannka**
The previous failure was due to the fixture iframe that we created for each test does not have an origin (we use `srcdoc`). In such case, some browsers will take the top window origin as `referrer`, but some will use `null` .

The fix is to fully mimic the real production world. Use an iframe to load a valid AMP page from a server.

Closes #8853

### CODE REVIEW

File: test/integration/test-amp-pixel.js [hunk 1]
```diff
@@ -19,41 +19,22 @@ import {
...
-  it.skip('should remove referrer', () => {
-    // TODO(@lannka): unskip this test
-    const pixel = doc.createElement('amp-pixel');
-    pixel.setAttribute('src', depositRequestUrl('no-referrer'));
-    pixel.setAttribute('referrerpolicy', 'no-referrer');
-    doc.body.appendChild(pixel);
-
-    return withdrawRequest(win, 'no-referrer').then(request => {
+describes.integration('amp-pixel integration test', {
+  body: `<amp-pixel src="${depositRequestUrl('no-referrer')}"
```
Comment (zhouyx) [inline test/integration/test-amp-pixel.js]: This looks awesome!

File: testing/describes.js [hunk 2]
```diff
@@ -333,6 +338,42 @@ class SandboxFixture {
   }
 }
 
+/** @implements {Fixture} */
+class IntegrationFixture {
+  /** @param {!{body: string}} spec */
```
Comment (zhouyx) [inline testing/describes.js]: As we discussed, can we add a TODO here to support extension and version later

File: test/integration/test-amp-pixel.js [hunk 3]
```diff
@@ -19,41 +19,22 @@ import {
...
+             referrerpolicy="no-referrer">`,
+}, env => {
+  it('should remove referrer if referrerpolicy=no-referrer', () => {
+    return withdrawRequest(env.win, 'no-referrer').then(request => {
```
Comment (zhouyx) [inline test/integration/test-amp-pixel.js]: Though the new integration test looks good. I really can't tell why it will fix test failure on old Chrome?

File: testing/describes.js (hunk 2 above)
Comment (lannka) [inline testing/describes.js]: i don't think TODO is needed, especially we recently introduced a new "TODO rule" that we need to create a github issue for each TODO.

this works as is right now. if anyone want to add tests using extension, they will add them wisely.

File: test/integration/test-amp-pixel.js (hunk 3 above)
Comment (lannka) [inline test/integration/test-amp-pixel.js]: The previous failure was due to the fixture iframe that we created for each test does not have an origin (we use `srcdoc`). In such case, some browsers will take the top window origin as `referrer`, but some will use `null` .

File: testing/describes.js (hunk 2 above)
Comment (zhouyx) [inline testing/describes.js]: we have such a rule now? OK, I agree they will find it.

File: test/integration/test-amp-pixel.js (hunk 3 above)
Comment (zhouyx) [inline test/integration/test-amp-pixel.js]: Make sense. Let's merge this and see : )

File: testing/describes.js (hunk 2 above)
Comment (lannka) [inline testing/describes.js]: @dvoytenko will tell you about the new rule. :-)
