### PR TITLE
Use window.document instead of window in loadPromise.

### LINKED ISSUE #4925: amp-analytics signal is unreliable/not working at all
## Short description of your issue:

I tried to create a page with an amp-analytics tag and checked how reliable the signals are.
- When there is no config file is included as attribute, the signal is sent out most of the times. 
- When a config file is included as attribute, the signal is NEVER sent out.

### When no config file is provided:
1. Go to [http://jsbin.com/buyiri/edit?html,output](http://jsbin.com/buyiri/edit?html,output)
2. Edit the json for the amp-analytics element and observe the requests in the developer tools
3. Requests to "pageview" are there most of the times, but sometimes they are missing. Note: This seems to only happen in Chrome(i used 53.0.2785.101 m), it worked in Firefox(45.3.0)

### When a config file is provided:
1. Go to [http://jsbin.com/zuxovar/edit?html,output](http://jsbin.com/zuxovar/edit?html,output)
2. Insert correct credentials for a soasta mpulse account or enter a page that returns a config. I fell back to the soasta mpulse config to make sure it is not caused by my config.

Here is what i was using for my tests:
`{"appId":"appid","timestamp":1473679354229}`

Here is what is being returned by soasta mpulse:
`{
"requests": {
"beacon_url": "<key>.mpstat.us/"
},
"vars": {
"h.key": "<apikey>",
"h.d": "<domain>",
"h.cr": "<key>",
"h.t": "1473679354229"
}
}`

3. Edit the json a few times to trigger reloads. If you have a look at the developer tools, amp is making a request to the config and then stops(This happens on chrome and firefox for me)
4. I have tried to debug a little bit, but i got stuck. I can see that amp is actually preparing the url for the request, but the request is never sent.

## What browsers are affected?

As mentioned before: The issue with the config file occurs on Chrome and Firefox(latest versions) and the issue without the config file occurs only in Chrome and only rarely.

## Which AMP version is affected?

AMP Version: Powered by AMP ⚡ HTML – Version 1472695982886

### PR DESCRIPTION
**Pull request by avimehta**
window doesn't seem to have either .complete and .readyState that
loadPromise needs to check if the document has loaded.

Fixes #4925

### CODE REVIEW

File: src/service/performance-impl.js [hunk 1]
```diff
@@ -97,7 +97,7 @@ export class Performance {
         });
 
     // Tick window.onload event.
-    loadPromise(win).then(() => {
+    loadPromise(win.document).then(() => {
```
Comment (dvoytenko) [inline src/service/performance-impl.js]: Why? Is there even a document onload event? Could you please provide a reference?

File: src/service/url-replacements-impl.js [hunk 2]
```diff
@@ -451,7 +451,7 @@ export class UrlReplacements {
       return Promise.resolve();
     } else if (metric < 0) {
       // Metric is not yet available. Retry after a delay.
-      return loadPromise(this.win_).then(() => {
+      return loadPromise(this.win_.document).then(() => {
```
Comment (dvoytenko) [inline src/service/url-replacements-impl.js]: Ditto

**Comment by dvoytenko** [comment]
+ @jridgewell for a second pair of eyes.

**Comment by dvoytenko** [comment]
So, is the issue that we miss `window.load` event?

File: src/service/performance-impl.js (hunk 1 above)
Comment (jridgewell) [inline src/service/performance-impl.js]: It appears to, [according](https://developer.mozilla.org/en-US/docs/Web/API/Document) to MDN, though it just points to the `window.onload` handler.

Comment (dvoytenko) [inline src/service/performance-impl.js]: I'm trying to understand why we are using `window.onload` vs a more predictable `onDocumentReady`?

File: src/service/url-replacements-impl.js (hunk 2 above)
Comment (avimehta) [inline src/service/url-replacements-impl.js]: I can use onDocumentReady if needed. The problem I am trying to solve here is that the promise that is returned by loadPromise(win) is never resolved. As a result, the flow that goes through this path never results in hits being sent from amp-analytics.  

I think performance-impl.js also has the same problem but I am not sure. Can revert that file's changes. 

Also, I can use onDocumentReady if that makes more sense. The main problem occurs [here](https://github.com/ampproject/amphtml/blob/master/src/event-helper.js#L97). Window does not have either of those properties and hence the function never returns true.

**Comment by avimehta** [comment]
@dvoytenko yes, I added more details to another comment but the issue is that https://github.com/ampproject/amphtml/blob/master/src/event-helper.js#L97 never returns true for `window`.

File: src/service/url-replacements-impl.js (hunk 2 above)
Comment (dvoytenko) [inline src/service/url-replacements-impl.js]: That makes sense. We should definitely switch to `onDocumentReady` then. the second use case in `getTimingData` is not super obvious to me though yet. I'm not sure what's the goal there.

Comment (jridgewell) [inline src/service/url-replacements-impl.js]: I think setting up an `onDocumentReady` to add the `win.complete = true` would be a better solution here. Someone else is bound to get tripped up by the same problem.

Comment (dvoytenko) [inline src/service/url-replacements-impl.js]: Alternatively, if we want the proper `window.onload`-like behavior, I believe, we need to listen on doc's `readyState == complete`. This is not what `onDocumentReady` does now, but we can easily add that callback as well. We can put it in the same `document-ready.js` and call it `onDocumentComplete` or something like that. From what I can see this is the closest thing to `window.onload`. So, let's pick the right event and move with that.

Comment (avimehta) [inline src/service/url-replacements-impl.js]: fixed ptal.

File: src/document-ready.js [hunk 3]
```diff
@@ -24,19 +24,37 @@ export function isDocumentReady(doc) {
...
+  onDocumentState(doc, callback, isDocumentReady);
+}
+
+/**
+ * Calls the callback when document's state satisfies the stateFn.
+ * @param {!Document} doc
+ * @param {function(!Document)} callback
+ * @param {function(!Document)} stateFn
+ */
+function onDocumentState(doc, callback, stateFn) {
```
Comment (dvoytenko) [inline src/document-ready.js]: Change `stateFn` and `callback` places.

File: test/functional/test-performance.js [hunk 4]
```diff
@@ -195,9 +195,9 @@ describe('performance', () => {
         expect(perf.events_.length).to.equal(2);
 
         return perf.coreServicesAvailable().then(() => {
-          expect(flushSpy.callCount).to.equal(2);
+          expect(flushSpy.callCount).to.equal(3);
```
Comment (dvoytenko) [inline test/functional/test-performance.js]: Hmm. I don't really understand these. Even worse, I don't see how we can test flush calls from that `whenDocumentComplete` block above since it's a completely separate microtask...

File: test/functional/test-performance.js [hunk 5]
```diff
@@ -456,19 +456,20 @@ describe('performance', () => {
...
           whenReadyToRetrieveResourcesResolve();
           whenViewportLayoutCompleteResolve();
           return perf.whenViewportLayoutComplete_().then(() => {
-            expect(tickSpy.callCount).to.equal(3);
-            expect(tickSpy.getCall(1).args[0]).to.equal('_pc');
-            expect(tickSpy.getCall(2).args[0]).to.equal('pc');
-            expect(tickSpy.getCall(2).args[1]).to.equal('_pc');
-            expect(Number(tickSpy.getCall(1).args[2])).to.equal(perf.initTime_);
-            expect(Number(tickSpy.getCall(2).args[2]))
+            expect(tickSpy.callCount).to.equal(4);
```
Comment (dvoytenko) [inline test/functional/test-performance.js]: Is this right?

File: test/functional/test-performance.js [hunk 6]
```diff
@@ -480,12 +481,13 @@ describe('performance', () => {
...
         whenViewportLayoutCompleteResolve();
         return perf.whenViewportLayoutComplete_().then(() => {
-          expect(tickSpy.callCount).to.equal(2);
-          expect(tickSpy.firstCall.args[0]).to.equal('_pc');
-          expect(tickSpy.secondCall.args[0]).to.equal('pc');
-          expect(tickSpy.secondCall.args[1]).to.equal('_pc');
-          expect(Number(tickSpy.firstCall.args[2])).to.equal(perf.initTime_);
-          expect(Number(tickSpy.secondCall.args[2])).to.equal(
+          expect(tickSpy.callCount).to.equal(3);
+          expect(tickSpy.firstCall.args[0]).to.equal('ol');
```
Comment (dvoytenko) [inline test/functional/test-performance.js]: Still don't understand how `ol` is captured from a separate microtask...

File: test/functional/test-performance.js (hunk 4 above)
Comment (dvoytenko) [inline test/functional/test-performance.js]: Ok, IIUC, this is because that `loadPromise` never ran in tests before?

Comment (avimehta) [inline test/functional/test-performance.js]: I suspect the same. loadPromise never fired before. Since `ol`  is marked in constructor, it happens for all tasks?

File: test/functional/test-performance.js (hunk 5 above)
Comment (avimehta) [inline test/functional/test-performance.js]: the tests seem to pass.

File: test/functional/test-performance.js (hunk 6 above)
Comment (avimehta) [inline test/functional/test-performance.js]: `ol` tick happens from the constructor. Does that answer your question? I don't know much about performance so my answers might be stupid.

File: src/document-ready.js (hunk 3 above)
Comment (avimehta) [inline src/document-ready.js]: Done.

**Comment by avimehta** [comment]
ptal.

File: test/functional/test-performance.js (hunk 6 above)
Comment (dvoytenko) [inline test/functional/test-performance.js]: Ok, I'll ask @erwinmombay to check on this part.

File: src/document-ready.js [hunk 7]
```diff
@@ -24,19 +24,37 @@ export function isDocumentReady(doc) {
...
  */
 export function onDocumentReady(doc, callback) {
-  let ready = isDocumentReady(doc);
+  onDocumentState(doc, isDocumentReady, callback);
+}
+
+/**
+ * Calls the callback when document's state satisfies the stateFn.
+ * @param {!Document} doc
+ * @param {function(!Document)} stateFn
```
Comment (dvoytenko) [inline src/document-ready.js]: `:boolean` for stateFn's return type.

File: src/service/performance-impl.js (hunk 1 above)
Comment (erwinmombay) [inline src/service/performance-impl.js]: going to ping @cramforce on this one as this changes what we're measuring. domready is going to fire much earlier than window.onload

File: src/document-ready.js [hunk 8]
```diff
@@ -24,19 +24,37 @@ export function isDocumentReady(doc) {
   return doc.readyState != 'loading';
 }
 
+/**
+ * Whether the document has loaded all the css and sub-resources.
+ * @param {!Document} doc
+ * @return {boolean}
+ */
+function isDocumentComplete(doc) {
```
Comment (cramforce) [inline src/document-ready.js]: Should this be called `Loaded` instead of `Complete` since that is much clearer?

File: src/document-ready.js [hunk 9]
```diff
@@ -58,3 +76,14 @@ export function whenDocumentReady(doc) {
     onDocumentReady(doc, resolve);
   });
 }
+
+/**
+ * Returns a promise that is resolved when document is complete.
+ * @param {!Document} doc
+ * @return {!Promise<!Document>}
+ */
+export function whenDocumentComplete(doc) {
```
Comment (cramforce) [inline src/document-ready.js]: Same comment re-complete

File: src/service/performance-impl.js (hunk 1 above)
Comment (cramforce) [inline src/service/performance-impl.js]: The code now waits for `complete` state, right? Which should be the same as before.

**Comment by avimehta** [comment]
Actually, changing the metrics was not my plan. I can change his code to
fire at domready if that was the original intention.

File: src/service/performance-impl.js (hunk 1 above)
Comment (erwinmombay) [inline src/service/performance-impl.js]: ah didn't realize it was changed. LGTM then

File: test/functional/test-performance.js (hunk 6 above)
Comment (erwinmombay) [inline test/functional/test-performance.js]: yeah, the original onload event never fired in tests so all counts should have been off by 1

File: src/document-ready.js (hunk 8 above)
Comment (dvoytenko) [inline src/document-ready.js]: I'd rather follow the DOM API directly.

**Comment by dvoytenko** [comment]
@cramforce 

> The code now waits for complete state, right? Which should be the same as before.

Yes. We are keeping the behavior as before, but the goal is to actually make it work. `window.loadPromise` was elusive to get right 100%. `document.complete` which should be functionally equivalent to `window.onload` works all the time.

**Comment by dvoytenko** [comment]
All, I'm ready to LGTM this. Are there any other concerns?

**Comment by dvoytenko** [comment]
LGTM
