### PR TITLE
XHR fetch when view first becomes visible

### LINKED ISSUE #14685: Make XHR service only do requests after first visible by default
We currently have the wrong default in terms of privacy. It'd be better to opt-into the more dangerous behavior than opting out from it.

### PR DESCRIPTION
**Pull request by alabiaga**
Fixes #14685

### CODE REVIEW

File: src/service/xhr-impl.js [hunk 1]
```diff
@@ -170,30 +167,30 @@ export class Xhr {
    * XHRs are intercepted if all of the following are true:
    * - The AMP doc is in single doc mode
    * - The viewer has the `xhrInterceptor` capability
-   * - The Viewer is a trusted viewer or AMP is currently in developement mode
+   * - The Viewer is a trusted viewer or ApMP is currently in developement mode
```
Comment (kristoferbaxter) [inline src/service/xhr-impl.js]: Nit: AMP, looks like a typo!

File: test/functional/test-xhr.js [hunk 2]
```diff
@@ -14,7 +14,7 @@
  * limitations under the License.
  */
 
-import * as sinon from 'sinon';
+import * as sinon from 'sinon';;
```
Comment (kristoferbaxter) [inline test/functional/test-xhr.js]: Nit: Double semi-colon?

File: test/functional/test-xhr.js [hunk 3]
```diff
@@ -73,7 +75,17 @@ describe.configure().skipSafari().run('XHR', function() {
...
-    ampdocServiceForStub.returns({isSingleDoc: () => false});
+    ampdocViewerStub = sandbox.stub(Services, 'viewerForDoc');
+    ampdocViewerStub.returns({
+      whenFirstVisible: () => {
+        return Promise.resolve();
+      },
+    });
+    ampdocServiceForStub.returns({
+      isSingleDoc: () => false,
+      getAmpDoc: () => { return ampdocViewerStub; },
```
Comment (kristoferbaxter) [inline test/functional/test-xhr.js]: Not a huge deal since this is a test file however I believe you could reduce this down a bit.
```
ampdocServiceForStub.returns({
  isSingleDoc: () => false,
  getAmpDoc: () => ampdocViewerStub,
});

File: test/functional/test-xhr.js [hunk 4]
```diff
@@ -73,7 +75,17 @@ describe.configure().skipSafari().run('XHR', function() {
   beforeEach(() => {
     sandbox = sinon.sandbox.create();
     ampdocServiceForStub = sandbox.stub(Services, 'ampdocServiceFor');
-    ampdocServiceForStub.returns({isSingleDoc: () => false});
+    ampdocViewerStub = sandbox.stub(Services, 'viewerForDoc');
+    ampdocViewerStub.returns({
```
Comment (kristoferbaxter) [inline test/functional/test-xhr.js]: Also here:
```
ampdocViewerStub.returns({
  whenFirstVisible: () => Promise.resolve(),
});
```

File: src/service/xhr-impl.js [hunk 5]
```diff
@@ -109,10 +109,7 @@ export class Xhr {
     /** @const {!Window} */
     this.win = win;
 
-    const ampdocService = Services.ampdocServiceFor(win);
-    /** @private {?./ampdoc-impl.AmpDoc} */
-    this.ampdocSingle_ =
-        ampdocService.isSingleDoc() ? ampdocService.getAmpDoc() : null;
+    this.ampdocService = Services.ampdocServiceFor(win);
```
Comment (jridgewell) [inline src/service/xhr-impl.js]: The `isSingleDoc` is still necessary ([context](https://github.com/ampproject/amphtml/pull/9350#discussion_r116625881)).

Also, leave this as a private field, they get minified better.

File: src/service/xhr-impl.js [hunk 6]
```diff
@@ -125,43 +122,43 @@ export class Xhr {
...
-        this.ampdocSingle_ &&
+        ampdocSingle &&
         Math.random() < 0.01 &&
-        parseUrl(input).origin != this.win.location.origin &&
-        !Services.viewerForDoc(this.ampdocSingle_).hasBeenVisible()) {
-      dev().error('XHR', 'attempted to fetch %s before viewer was visible',
+        parseUrl(input).origin != this.win.location.origin) {
+      dev().error('XHR', 'attempted to fetch URL from different origin',
           input);
     }
```
Comment (jridgewell) [inline src/service/xhr-impl.js]: This entire if statement can be removed, since we're now waiting for viewer visible regardless.

File: src/service/xhr-impl.js [hunk 7]
```diff
@@ -125,43 +122,43 @@ export class Xhr {
...
-      // parsing and document construction on the UI thread which would be
-      // expensive.
-      if (init.responseType == 'document') {
-        return fetchPolyfill(input, init);
-      }
-      return (this.win.fetch || fetchPolyfill).apply(null, arguments);
-    });
+    return Services.viewerForDoc(ampdocSingle).whenFirstVisible()
+        .then(() => {
+          return this.maybeIntercept_(input, init, ampdocSingle);
```
Comment (jridgewell) [inline src/service/xhr-impl.js]: @zhangsu: What are the privacy guarantees of the Gmail interceptor? Does it need us to wait for the doc to be shown?

(Basically, should this be the first call, or should `whenFirstVisible` be first)

Comment (zhangsu) [reply src/service/xhr-impl.js]: Thanks for checking with us. Waiting for the email to be shown before firing XHRs sounds good to me since we also want the same level of privacy.

Just curious: what's an example today where XHRs can be fired before the viewer is visible (e.g. in prerender mode)? `amp-list` shouldn't do that because `prerenderAllowed` is false, right?

Comment (jridgewell) [reply src/service/xhr-impl.js]: 👍, that makes it safer on our side as well.

> what's an example today where XHRs can be fired before the viewer is visible (e.g. in prerender mode)?

Generally, these are bugs. There are exceptions for connecting to the CDN itself (or whatever origin is hosting the page), since they've already received the document request.

> amp-list shouldn't do that because prerenderAllowed is false, right?

Correct. The `prerenderAllowed` is one way to catch them, but we're increasingly getting extensions that need to make requests before layout (ads 🙄, and one other). These make requests in `#buildCallback` or other earlier lifecycle callbacks, and they sometimes forget to wait for visible.

File: src/service/xhr-impl.js (hunk 5 above)
Comment (alabiaga) [reply src/service/xhr-impl.js]: hey justin, i know we discussed this a bit yesterday but it might have been under a different context. Do we really need this private field. in my changes you can see that i check if amp is single doc in the fetch call and pass along that info to the methods that need that info. I dont think this private field is needed at all.

**Comment by alabiaga** [comment]
@jridgewell  Hey Justin, pls take another look. I made changes to check for viewer visibility to encapsulate the logic where other viewer related checks are made as well. Thanks

File: src/service/xhr-impl.js [hunk 8]
```diff
@@ -177,40 +172,41 @@ export class Xhr {
...
+  maybeIntercept_(input, init, ampdoc) {
+    if (!this.ampdocService.isSingleDoc()) {
       return Promise.resolve();
     }
-
-    const htmlElement = this.ampdocSingle_.getRootNode().documentElement;
+    const htmlElement = ampdoc.getRootNode().documentElement;
     const docOptedIn = htmlElement.hasAttribute('allow-xhr-interception');
     if (!docOptedIn) {
       return Promise.resolve();
```
[the remark this answers is not in the document]
Comment (alabiaga) [reply src/service/xhr-impl.js]: done.

File: src/service/xhr-impl.js [hunk 9]
```diff
@@ -177,40 +172,41 @@ export class Xhr {
...
+   * @param {?./ampdoc-impl.AmpDoc} ampdoc
    * @return {!Promise<!FetchResponse|!Response|undefined>}
    *     A response returned by the interceptor if XHR is intercepted or
    *     `Promise<undefined>` otherwise.
    * @private
    */
-  maybeIntercept_(input, init) {
-    if (!this.ampdocSingle_) {
+  maybeIntercept_(input, init, ampdoc) {
+    if (!this.ampdocService.isSingleDoc()) {
```
[the remark this answers is not in the document]
Comment (alabiaga) [reply src/service/xhr-impl.js]: fine you win. reverted to a field property :smile:

File: src/service/xhr-impl.js [hunk 10]
```diff
@@ -125,43 +122,41 @@ export class Xhr {
...
-    }
-
+    // The isSingleDoc check is required because if in shadow mode, this will
+    // throw a console error because the shellShadowDoc_ is not set when
+    // fetching the amp doc. So either the test-bind-impl or test pre setup in
+    // shadow mode tests needs to be fixed or there is a bug in ampdoc impl
+    // getAmpDoc.
+    // TODO(alabiaga): This should be investigated and fixed.
+    const ampdoc = this.ampdocService.isSingleDoc() ?
+      this.ampdocService.getAmpDoc(this.win.document) : null;
```
[the remark this answers is not in the document]
Comment (alabiaga) [reply src/service/xhr-impl.js]: Done.  The reason I added it was because I was trying to do away with the isSingleDoc() check..and just make the call getAmpDoc..which was then causing test-bind-impl.js to fail and I was trying to get it to work by passing in the node, though it was not sufficient as the AmpDoc.shellShadowDoc_ was not defined. I wrote a TODO on that line of code as it seems like buggy code to me..or the test is not set up properly. So i believe this is where your initial comment of why this is still required now makes sense...i had to actually debug through the code for it to actually make sense.

File: src/service/xhr-impl.js [hunk 11]
```diff
@@ -125,43 +122,41 @@ export class Xhr {
...
-      // Fallback to xhr polyfill since `fetch` api does not support
-      // responseType = 'document'. We do this so we don't have to do any
-      // parsing and document construction on the UI thread which would be
-      // expensive.
-      if (init.responseType == 'document') {
-        return fetchPolyfill(input, init);
-      }
-      return (this.win.fetch || fetchPolyfill).apply(null, arguments);
-    });
+    return this.maybeIntercept_(input, init, ampdoc)
```
[the remark this answers is not in the document]
Comment (alabiaga) [reply src/service/xhr-impl.js]: fixed to use the assigned property ampdocSingle_ as it was originally.

File: src/service/xhr-impl.js [hunk 12]
```diff
@@ -177,40 +172,41 @@ export class Xhr {
...
-          .then(response =>
-            this.fromStructuredCloneable_(response, init.responseType));
-    });
+    const viewer = Services.viewerForDoc(ampdoc);
+    return viewer.whenFirstVisible()
+        .then(() => {
+          if (!viewer.hasCapability('xhrInterceptor')) {
+            return Promise.resolve();
+          }
+          return viewer.isTrustedViewer().then(viewerTrusted => {
```
[the remark this answers is not in the document]
Comment (alabiaga) [reply src/service/xhr-impl.js]: unnested hasCapability and docOptedIn checked

File: src/service/xhr-impl.js [hunk 13]
```diff
@@ -109,7 +109,15 @@ export class Xhr {
     /** @const {!Window} */
     this.win = win;
 
+    /** @private */
```
Comment (jridgewell) [inline src/service/xhr-impl.js]: This isn't a property, so can't be `@private`.

File: src/service/xhr-impl.js [hunk 14]
```diff
@@ -186,31 +184,28 @@ export class Xhr {
...
+    return viewer.whenFirstVisible()
+        .then(() => {
+          const htmlElement = this.ampdocSingle_.getRootNode().documentElement;
+          const docOptedIn = htmlElement.hasAttribute('allow-xhr-interception');
+          if (!docOptedIn || !viewer.hasCapability('xhrInterceptor')) {
+            return Promise.resolve();
+          }
+          return viewer.isTrustedViewer();
+        }).then(viewerTrusted => {
+          if (!viewerTrusted && !getMode(this.win).development) {
```
Comment (jridgewell) [inline src/service/xhr-impl.js]: Sorry, this lead to confusion when I recommended unnesting. What I meant is that these should be two separate promise chains:

```js
// Shorthand, don't actually write like this
maybeIntercept_(input, init) {
  if (!single) return Promise.resolve();

  const vis = viewer.whenFirstVisible();
  if (!hasCapability) return vis;

  return vis.then(() => {
    if (!optedIn) {
      return false;
    }
    return viewer.isTrusted()
  }).then(trusted => {
    if (!trusted) return;
    return sendMessage(...);
  });
}

Comment (alabiaga) [reply src/service/xhr-impl.js]: @jridgewell  no worries. hopefully i got it right this time. otherwise we can discuss in person. thanks

File: src/service/xhr-impl.js [hunk 15]
```diff
@@ -185,27 +184,29 @@ export class Xhr {
...
-        });
+    const whenFirstVisible = viewer.whenFirstVisible();
+    if (!viewer.hasCapability('xhrInterceptor')) {
+      return whenFirstVisible;
+    }
+    const htmlElement = this.ampdocSingle_.getRootNode().documentElement;
+    const docOptedIn = htmlElement.hasAttribute('allow-xhr-interception');
+    const isDevMode = getMode(this.win).development;
+    if (!docOptedIn) {
+      return Promise.resolve();
```
Comment (jridgewell) [inline src/service/xhr-impl.js]: Return `whenFirstVisible`.

Comment (alabiaga) [reply src/service/xhr-impl.js]: right. Done. Thanks
