### PR TITLE
Fail build on compiler error, after printing a useful message

### LINKED ISSUE #1213: Importing a non-existing import should fail compilation
Or at least a separate check.

I assume this is not failing with babel because of per-file compilation, but possibly we can add an extra check.

CC @erwinmombay

### PR DESCRIPTION
**Pull request by rsimha-amp**
This PR causes the build to fail after a compiler error, after printing a useful message.

**Syntax error:**
```
SyntaxError: amphtml/src/foo.js: Unexpected token (20:6)
  18 | 
  19 | if (foo) {
> 20 |   bar(;
     |       ^
  21 | }
  22 | 
```

**Other errors, like bad imports:**
```
Error: Cannot find module './bar' from 'amphtml/src/foo'
```
Fixes #1213

### CODE REVIEW

File: gulpfile.js [hunk 1]
```diff
@@ -954,11 +954,10 @@ function compileJs(srcDir, srcFilename, destDir, options) {
     const startTime = Date.now();
     return toPromise(bundler.bundle()
       .on('error', function(err) {
-        if (err instanceof SyntaxError) {
-          console.error(red('Syntax error: ' + err.message));
-        } else {
-          console.error(red(err.message));
-        }
+        // Drop the node_modules call stack, which begins with '    at'.
+        const message = err.stack.replace(/    at[^]*/, '').trim();
```
Comment (erwinmombay) [inline gulpfile.js]: why do we want to drop it?

Comment (rsimha-amp) [reply gulpfile.js]: The stack has nothing to do with the actual syntax error, and gets cumbersome to read. For example, here's what I see when I print the entire stack:
```
SyntaxError: /usr/local/google/home/rsimha/src/amphtml/src/service-worker/kill.js: Unexpected token (28:6)
  26 | });
  27 | if (foo)
> 28 |   bar(;
     |       ^
  29 | 
  30 | self.addEventListener('activate', function(event) {
  31 |   // Usually after waiting for a navigation, it has to wait for all other
    at Parser.pp$5.raise (/usr/local/google/home/rsimha/src/amphtml/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/usr/local/google/home/rsimha/src/amphtml/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseExprAtom (/usr/local/google/home/rsimha/src/amphtml/node_modules/babylon/lib/index.js:3750:12)
    at Parser.pp$3.parseExprSubscripts (/usr/local/google/home/rsimha/src/amphtml/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/usr/local/google/home/rsimha/src/amphtml/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/usr/local/google/home/rsimha/src/amphtml/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/usr/local/google/home/rsimha/src/amphtml/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/usr/local/google/home/rsimha/src/amphtml/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseExprListItem (/usr/local/google/home/rsimha/src/amphtml/node_modules/babylon/lib/index.js:4312:16)
    at Parser.pp$3.parseCallExpressionArguments (/usr/local/google/home/rsimha/src/amphtml/node_modules/babylon/lib/index.js:3573:20)
    at Parser.pp$3.parseSubscripts (/usr/local/google/home/rsimha/src/amphtml/node_modules/babylon/lib/index.js:3533:31)
    at Parser.pp$3.parseExprSubscripts (/usr/local/google/home/rsimha/src/amphtml/node_modules/babylon/lib/index.js:3504:15)
    at Parser.pp$3.parseMaybeUnary (/usr/local/google/home/rsimha/src/amphtml/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/usr/local/google/home/rsimha/src/amphtml/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/usr/local/google/home/rsimha/src/amphtml/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/usr/local/google/home/rsimha/src/amphtml/node_modules/babylon/lib/index.js:3344:19)
```

**Comment by calebcordry** [comment]
@rsimha-amp  this error message is awesome. One (unintended?) result is that if I am running `gulp watch` while developing, a syntax error will kill the watch mode and I will have to manually restart. (it does print the nice error message 👍 ). 

Is this the intended behavior?

**Comment by rsimha-amp** [comment]
@calebcordry Good catch, that wasn't intentional. I think we should exit if there's a syntax error during `gulp build` or during the initial build phase of `gulp` or `gulp watch`, but we should not exit when a file is recompiled during the subsequent `watch` phase. Would this work?

I'll send you a PR.

**Comment by calebcordry** [comment]
SGTM. Thanks!
