### PR TITLE
Re-Fix build being called before element is ready to build. 

### LINKED ISSUE #4397: buildCallback invoked when hasNextNodeInDocumentOrder is false
screenshot from 2016-08-05 15 23 27

It's a bit hard to reproduce but as you can see in the screenshot, the `buildCallback` of `<amp-experiment>` is invoked when the `children=[]`. `hasNextNodeInDocumentOrder` also returns `false`. A snapshot of the DOM is printed in the console. We can see at that point, `<amp-experiment>` is not fully ready yet.

To reproduce this locally, please patch the diff: #4399
You can set the same break point as me, and refresh the page a couple times. Normally you see it less than 10 refreshes.

The call stack (on the top right corner of the screenshot) shows the `build` was triggered via 

```
    this.visibilityStateMachine_.setState(
      this.viewer_.getVisibilityState()   // = visible
    );
```

@dvoytenko @mkhatib do you have any idea?

+@rudygalfi  this is what we met in the ABE amp-experiment article.

### PR DESCRIPTION
**Pull request by mkhatib**
This is a resubmit of a reverted PR with a fix to the broken test 

Original PR: #4426 
Revert PR: #4467 

Fixes #4397

### CODE REVIEW

File: test/integration/test-extensions-loading.js [hunk 1]
```diff
@@ -21,8 +21,6 @@ function checkElementUpgrade(element) {
   expect(element).to.have.class('-amp-element');
   expect(element).to.have.class('-amp-layout-responsive');
   expect(element).to.have.class('-amp-layout-size-defined');
-  expect(element).to.not.have.class('-amp-notbuilt');
```
Comment (dvoytenko) [inline test/integration/test-extensions-loading.js]: Please explain.

Comment (mkhatib) [inline test/integration/test-extensions-loading.js]: Yes sorry. So @zhouyx here is testing only if the element was `upgraded` and so checking if it doesn't have `-amp-unresolved` should be enough. Our theory is that the event the test is waiting on is fired maybe too early before the iframe gets built and we weren't able to wait on `amp:load:start` to fire for the `iframe` since it might not be laid out because it probably is out of the viewport during the test.

So we opted for just dropping testing the build part in this test and just test upgrade which what the test is intended for.

Comment (zhouyx) [inline test/integration/test-extensions-loading.js]: so removing this works @mkhatib ?
Yes since after the change we don't build directly  after upgrade, we can't expect element to be built here. if we dispatch event like `amp:built` later, we can introduce integration test that test all element gets built correctly. (If necessary)

**Comment by zhouyx** [comment]
LGTM.  defer to @dvoytenko

File: test/integration/test-extensions-loading.js (hunk 1 above)
Comment (mkhatib) [inline test/integration/test-extensions-loading.js]: Yes it passed when I made this change. 

@dvoytenko pointed out that we might be breaking something here so I am doing few other runs with different setup, the safest path he suggested is to bring back the `build` during `discoverWork_` but protect against unready-builds. Testing few combinations now will report back.

Comment (mkhatib) [inline test/integration/test-extensions-loading.js]: Ok. brought back the build during discover - and changed the tests to wait on multiple events for the elements numbers. This has passed but the test flaked - rerunning the test for this but it should be good to go.

**Comment by dvoytenko** [comment]
LGTM
