### PR TITLE
Try to fix integration tests flakiness

### LINKED ISSUE #20057: Flakes in test-amp-bind.js and test-amp-analytics.js on SL
saw this a couple of times in travis SL:

```
DESCRIBE => amp-bind
  DESCRIBE => + amp-list, amp-mustache:0.2
    DESCRIBE =>  
      IT => evaluate bindings in children
        ✗ Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
Chrome 71.0.3578 (Linux 0.0.0) amp-bind + amp-list, amp-mustache:0.2   evaluate bindings in children FAILED
	Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

e.g.: 
- https://travis-ci.org/ampproject/amphtml/jobs/471150119
- https://travis-ci.org/ampproject/amphtml/jobs/471155956

### PR DESCRIPTION
**Pull request by lannka**
- Retry integration tests on Saucelabs. 
- Add 50ms tolerance to timer trigger
- Set default integration tests timeout to 5s locally 10s on Travis

For #20057

### CODE REVIEW

File: testing/describes.js [hunk 1]
```diff
@@ -441,6 +451,12 @@ class IntegrationFixture {
     /** @const */
     this.spec = spec;
 
+    this.spec.timeout = spec.timeout
+        || window.ampTestRuntimeConfig.mocha.integrationTimeout;
+    if (this.spec.retryOnSaucelabs === undefined) {
+      this.spec.retryOnSaucelabs = 3;
```
Comment (zhouyx) [inline testing/describes.js]: Shall we make it 4 to match the `.retryOnSaucelabs()`

Comment (lannka) [reply testing/describes.js]: SG. done

File: extensions/amp-list/0.1/test/integration/test-amp-list.js [hunk 2]
```diff
@@ -20,8 +20,6 @@ import {poll} from '../../../../../testing/iframe';
 const TIMEOUT = 15000;
 
 describe('amp-list (integration)', function() {
```
Comment (cathyxz) [inline extensions/amp-list/0.1/test/integration/test-amp-list.js]: Did you mean to remove this?

File: test/integration/test-amp-analytics.js [hunk 3]
```diff
@@ -17,9 +17,7 @@
 import {BrowserController, RequestBank} from '../../testing/test-helper';
```
Comment (cathyxz) [inline test/integration/test-amp-analytics.js]: The `should trigger 1s after amp-analytics starts` test in this file is flaky because it tries to assert that 999 > 1000. Probably because the timer for setInterval isn't always accurate.

File: extensions/amp-list/0.1/test/integration/test-amp-list.js (hunk 2 above)
Comment (lannka) [reply extensions/amp-list/0.1/test/integration/test-amp-list.js]: yes. as we right now by default set timeout to 10s on Travis & 5s locally.

File: test/integration/test-amp-analytics.js (hunk 3 above)
Comment (lannka) [reply test/integration/test-amp-analytics.js]: good observation. changed 1000 to 950 to give some tolerance
