### PR TITLE
🐛A4A: Change a few window refs to ampdoc

### LINKED ISSUE #25007: Doubleclick served a4a ads do not work when loaded in a PWA with shadowdom
## What's the issue?

When loading an AMP document into a **shadowdoc** as part of **PWA**, should the document contain an `amp-ad` of type "doubleclick" which loads an **amp4ads** based ad, the ad fails to load due to numerous errors related to `No ampdoc found for [object HTMLHtmlElement]`.

image

## How do we reproduce the issue?

A demo is available here: https://d1kvlucx6m02nr.cloudfront.net/

Upon first ( uncached ) load the ad loads correctly as the document is yet to be loaded within the shell container. 

image

However as soon as navigation occurs & the shell container is used the ad fail to load.

1. Navigate to https://d1kvlucx6m02nr.cloudfront.net/
2. Click on "Article 1"

## What browsers are affected?

All browsers

## Which AMP version is affected?

HTML shadows – Version 1910071803120

Based on previous issues related to PWA, shadowdoc & Doubleclick it looks like there may have a been a regression.

- https://github.com/ampproject/amphtml/issues/9679
- https://github.com/ampproject/amphtml/pull/9999

Additionally the a4a ad example loaded via projects example of a PWA is also broken. http://localhost:8000/pwa/

### PR DESCRIPTION
**Pull request by calebcordry**
Using globals can be risky and may break assumptions in shadow mode. 

Fixes #25007

### CODE REVIEW

File: src/custom-element.js [hunk 1]
```diff
@@ -564,7 +564,7 @@ function createBaseCustomElementClass(win) {
         // If we do early preconnects we delay them a bit. This is kind of
         // an unfortunate trade off, but it seems faster, because the DOM
         // operations themselves are not free and might delay
-        startupChunk(self.document, () => {
+        startupChunk(this.getAmpDoc(), () => {
```
Comment (lannka) [inline src/custom-element.js]: does this work?

Comment (calebcordry) [reply src/custom-element.js]: yes, at least @dvoytenko says so :)
