### PR TITLE
Fix URL variable substitution when links are triggered via right click new tab or new window

### LINKED ISSUE #14768: HTML URL Variable Substitutions not working when user opens link in new window
## What's the issue?

We are trying to use variable substitution in links [as documented here](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#variable-substitution-in-links). 

Here is an example of the HTML we are using: 
`<a href="//example.com/?SRC=QUERY_PARAM(SRC,XXXX)" data-amp-replace="QUERY_PARAM">Go to my site</a>`

This is working fine if you click on the link normally, but we have noticed that if we right-click on one of these links, or press down on a mobile device to open in a new window, the variable substitution does not work correctly. Instead of linking to `//example.com?SRC=XXXX` we get `//example.com?SRC=QUERY_PARAM(SRC,E132)`.

## How do we reproduce the issue?

Here is a link to the test case - http://jsbin.com/daduzekiho/edit?html,output

1. Click on the link normally to observe the variable substitution working correctly
2. Go back to the test case and right-click/press and hold on the link and open in a new tab/window. Observe that the variable has not been substituted.

## What browsers are affected?

We have observed this behaviour in Chrome, Safari and Microsoft Edge. Firefox is the only browser that seems to handle it correctly. 

## Which AMP version is affected?

Version 1524089272632

### PR DESCRIPTION
**Pull request by alabiaga**
Fixes #14768

### CODE REVIEW

**Comment by choumx** [comment]
What does this PR functionally accomplish? There doesn't seem to be any behavior change.

File: src/service/navigation.js [hunk 1]
```diff
@@ -231,14 +235,18 @@ export class Navigation {
 
     const location = this.parseUrl_(target.href);
 
-    // Handle AMP-to-AMP navigation if rel=amphtml.
-    if (this.handleA2AClick_(e, target, location)) {
-      return;
-    }
+    // Ignore handling A2A and custom protocol if it is invoked via a right
+    // click. See github issue #14768.
+    if (!isRightClick) {
```
Comment (choumx) [inline src/service/navigation.js]: Instead, we should probably just early-out after `urlReplacements.maybeExpandLink(...)`. `handleNavClick_()` isn't useful for right-click, right?

Actually it might be more readable to have a separate handler method for left and right click, and move shared logic to a new function that they both can call.

**Comment by alabiaga** [comment]
@choumx addressed your comments. Thanks for the review.

File: src/service/navigation.js [hunk 2]
```diff
@@ -213,21 +217,24 @@ export class Navigation {
     if (e.defaultPrevented) {
       return;
     }
+    const isRightClick = (e.type == EVENT_TYPE_RIGHT_CLICK);
+    if (isRightClick) {
+      this.handleRightClick_(e);
+    }
 
+    this.handleLeftClick_(e);
```
[the remark this answers is not in the document]
Comment (alabiaga) [reply src/service/navigation.js]: right. Explicitly checked for context menu click though as to be defensive in the case that someone adds a different event listener bound to handle which isn't a contextmenu click.

File: src/service/navigation.js [hunk 3]
```diff
@@ -245,6 +252,40 @@ export class Navigation {
...
+      return;
+    }
+
+    this.handleUrlDecorationAndExpansion_(target);
+  }
+
+  /**
+   * @param {!Element} el
+   */
+  handleUrlDecorationAndExpansion_(el) {
```
[the remark this answers is not in the document]
Comment (alabiaga) [reply src/service/navigation.js]: done

File: src/service/navigation.js [hunk 4]
```diff
@@ -39,6 +39,8 @@ import {
 import {toWin} from '../types';
 
 const TAG = 'navigation';
+const EVENT_TYPE_CLICK = 'click';
```
[the remark this answers is not in the document]
Comment (alabiaga) [reply src/service/navigation.js]: i want to keep it named to the event type..as I realized that left or right can be configured differently.
renamed EVENT_TYPE_RIGHT_CLICK to EVENT_TYPE_CONTEXT_MENU

File: src/service/navigation.js [hunk 5]
```diff
@@ -245,6 +253,35 @@ export class Navigation {
...
+   * TODO(alabiaga): investigate fix for handling A2A and custom link
+   * protocols.
+   * @param {!Element} target
+   */
+  handleContextmenuClick(target) {
+    this.expandVarsForAnchor_(target);
+  }
+
+  /**
+   * @param {!Element} el
```
Comment (choumx) [inline src/service/navigation.js]: `@private`

File: src/service/navigation.js [hunk 6]
```diff
@@ -245,6 +253,35 @@ export class Navigation {
...
+   * Handles contextmenu click. Note that currently this only deals
+   * with url variable substitution and expansion, as there is
+   * straightforward way of determining what the user clicked in the
+   * context menu, required for A2A navigation and custom link protocol
+   * handling.
+   * TODO(alabiaga): investigate fix for handling A2A and custom link
+   * protocols.
+   * @param {!Element} target
+   */
+  handleContextmenuClick(target) {
```
Comment (choumx) [inline src/service/navigation.js]: Remove and use `expandVarsForAnchor_` directly. You can put the comment in `handle_`.

File: src/service/navigation.js [hunk 7]
```diff
@@ -213,21 +219,23 @@ export class Navigation {
...
+    } else if (e.type == EVENT_TYPE_CONTEXT_MENU) {
+      this.handleContextmenuClick(target);
     }
+  }
 
-    const urlReplacements = Services.urlReplacementsForDoc(target);
-    urlReplacements.maybeExpandLink(target, defaultExpandParamsUrl);
+  /**
+   * @param {!Element} target
+   * @param {!Event} e
```
Comment (choumx) [inline src/service/navigation.js]: `@private`

File: src/service/navigation.js [hunk 8]
```diff
@@ -213,21 +219,23 @@ export class Navigation {
...
+   */
+  handleClick(target, e) {
```
Comment (choumx) [inline src/service/navigation.js]: `handleClick_`

File: src/service/navigation.js (hunk 5 above)
Comment (alabiaga) [reply src/service/navigation.js]: done

File: src/service/navigation.js (hunk 6 above)
Comment (alabiaga) [reply src/service/navigation.js]: done

File: src/service/navigation.js (hunk 7 above)
Comment (alabiaga) [reply src/service/navigation.js]: done

File: src/service/navigation.js (hunk 8 above)
Comment (alabiaga) [reply src/service/navigation.js]: done

File: src/service/navigation.js [hunk 9]
```diff
@@ -213,21 +219,33 @@ export class Navigation {
...
+    if (e.type == EVENT_TYPE_CLICK) {
+      this.handleClick_(target, e);
+    } else if (e.type == EVENT_TYPE_CONTEXT_MENU) {
+      /**
+        Handles contextmenu click. Note that currently this only deals
+        with url variable substitution and expansion, as there is
+        straightforward way of determining what the user clicked in the
+        context menu, required for A2A navigation and custom link protocol
+        handling.
+      */
```
Comment (choumx) [inline src/service/navigation.js]: Nit: Use single-line comments `//`.

Comment (alabiaga) [reply src/service/navigation.js]: never. kidding, done!
