### PR TITLE
Defer Layout Assertions till Upgrade

### LINKED ISSUE #5980: Clean up CustomElement#connectedCallback
Re: https://github.com/ampproject/amphtml/pull/5976#discussion_r86209297

`#connectedCallback` attempts to verify the layout type of the element. However, now that we can delay the upgrade, this seems wrong. Additionally, the upgrade itself verifies the layout type. So:

- Upgrade is sync
  - upgrade verified layout type, so `#connectedCallback` is duplication
- Upgrade is async
  - `#connectedCallback` can't verify the layout to begin with (because it depends on the upgraded implementation).

### PR DESCRIPTION
**Pull request by jridgewell**
Ooo man, there was a tangle of crap between the `#upgradeComplete` and `#connectedCallback`.

First some info.

- `#connectedCallback` is always called first.
- It calls `#tryUpgrade`
  - if it can upgrade sync, it calls `#upgradeComplete` 
  - Else, it defers calling `#upgradeComplete` until the upgrade is complete (shocking)
- `#connectedCallback` has a ton of code that's written specifically for the sync upgrade case
- `#upgradeComplete` has a ton of code that's written specifically for the async upgrade case

Basically, `#connectedCallback` did `#upgradeComplete`'s job half the time. And that's screwed up. Especially because `#upgradeComplete` is called sync if upgrade is sync, or async or upgrade is async. So we can just move all that code from `#connectedCallback` and still have exactly the same behavior.

Oh, then we remove the layout assertions from the sync case. That fixes #5980.

And we remove a bogus call to `#firstAttachedCallback`. It'll always be called by `#upgradeCallback`, regardless of whether the upgrade is sync or async. Worse, it'll be called twice if the upgrade is sync. Even more worse, we call it on un-upgraded elements if the element is still a StubElement or it's async upgraded.

### CODE REVIEW

File: src/custom-element.js [hunk 1]
```diff
@@ -934,32 +934,23 @@ function createBaseCustomElementClass(win) {
...
+        } catch (e) {
+          reportError(e, this);
+        }
         if (!isStub(this.implementation_)) {
           this.tryUpgrade_();
         }
         if (!this.isUpgraded()) {
           this.classList.add('amp-unresolved');
           this.classList.add('i-amphtml-unresolved');
+          // amp:attached is dispatched from the ElementStub class when it
```
Comment (dvoytenko) [inline src/custom-element.js]: You mean from `completeUpgrade_`?

File: src/service/resources-impl.js [hunk 2]
```diff
@@ -481,7 +481,6 @@ export class Resources {
     } else {
       // Create and add a new resource.
       resource = new Resource((++this.resourceIdCounter_), element, this);
-      this.buildOrScheduleBuildForResource_(resource);
```
Comment (jridgewell) [inline src/service/resources-impl.js]: This is specifically because `CustomElement#completeUpgrade` will now always call `Resources#upgraded`, which does this. This call does nothing if the element hasn't been upgraded (either `StubElement` or deferred upgrade) and was called by `#completeUpgrade` after upgrade completion, or it was called sync by `CustomElement#connectedCallback` (and not called by `#completeUpgrade`).

But now that `#completeUpgrade` always calls it, we can remove. `#completeUpgrade` will be called async if upgrade isn't complete (the first case above), or sync if upgrade is sync (the second case).

File: src/custom-element.js [hunk 3]
```diff
@@ -637,13 +641,9 @@ function createBaseCustomElementClass(win) {
       this.assertLayout_();
       this.implementation_.layout_ = this.layout_;
       this.implementation_.layoutWidth_ = this.layoutWidth_;
-      if (this.everAttached) {
-        this.implementation_.firstAttachedCallback();
```
Comment (jridgewell) [inline src/custom-element.js]: These two lines were duplicated in `#connectedCallback` [here](https://github.com/ampproject/amphtml/pull/8229/files#diff-8e1cdba946c07a7e631ef74645a5d6f0L948). But they're only called if upgrade happens sync, and these two lines are only called if upgrade happens async.

Because `#completeUpgrade` is already called sync or async appropriately, we can just move the lines here and always call them.

File: src/custom-element.js [hunk 4]
```diff
@@ -637,13 +641,9 @@ function createBaseCustomElementClass(win) {
...
-        this.dispatchCustomEventForTesting('amp:attached');
-        // For a never-added resource, the build will be done automatically
-        // via `resources.add` on the first attach.
-        this.getResources().upgraded(this);
-      }
+      this.implementation_.firstAttachedCallback();
+      this.dispatchCustomEventForTesting('amp:attached');
+      this.getResources().upgraded(this);
```
Comment (jridgewell) [inline src/custom-element.js]: Explained at the `buildOrScheduleBuildForResource_` removal below.

File: src/custom-element.js [hunk 5]
```diff
@@ -934,32 +934,23 @@ function createBaseCustomElementClass(win) {
         this.resources_ = resourcesForDoc(this.ampdoc_);
       }
       if (!this.everAttached) {
+        this.everAttached = true;
```
Comment (dvoytenko) [inline src/custom-element.js]: Indeed a maze here. However, from what I can tell, moving `everAttached = true` here (though definitely the right thing to do, imo), creates a risk condition where `resources.upgraded(this)` can be called before `resources.add(this)`. Is that ok?

File: src/custom-element.js (hunk 1 above)
Comment (jridgewell) [inline src/custom-element.js]: I'm copying the exact comment from https://github.com/ampproject/amphtml/pull/8229/files/d4690520ef30a0b5810fa207f85d27bcd48e3ec3#diff-8e1cdba946c07a7e631ef74645a5d6f0L950.

File: src/service/resources-impl.js (hunk 2 above)
Comment (dvoytenko) [inline src/service/resources-impl.js]: Why is this removed?

File: src/custom-element.js (hunk 5 above)
Comment (jridgewell) [inline src/custom-element.js]: Damn, missed that. Let me investigate.

File: src/service/resources-impl.js (hunk 2 above)
Comment (jridgewell) [inline src/service/resources-impl.js]: https://github.com/ampproject/amphtml/pull/8229#discussion_r106743409

File: src/custom-element.js (hunk 3 above)
Comment (dvoytenko) [inline src/custom-element.js]: I don't see that `completeUpgrade` is called on a node reinsertion. I.e. when `everAttached = true`

File: src/custom-element.js (hunk 5 above)
Comment (jridgewell) [inline src/custom-element.js]: [Fixed](https://github.com/ampproject/amphtml/pull/8229/commits/5d67e7bd1d6aa4f1671fa565b5068773960b7cb0).

File: src/custom-element.js (hunk 4 above)
Comment (dvoytenko) [inline src/custom-element.js]: If we call `upgrade` now in all cases (i.e. `everAttached = true`) we need to make sure that downstream we are not trying to build element twice.

File: src/custom-element.js (hunk 3 above)
Comment (jridgewell) [inline src/custom-element.js]: Hmmm. So we need `amp:attached` and `Resources#upgraded` called in that case?

File: src/custom-element.js (hunk 4 above)
Comment (jridgewell) [inline src/custom-element.js]: > If we call upgrade now in all cases (i.e. everAttached = true)

Moving this to https://github.com/ampproject/amphtml/pull/8229#discussion_r106744785

File: src/custom-element.js (hunk 3 above)
Comment (jridgewell) [inline src/custom-element.js]: Fixed.

File: src/custom-element.js [hunk 6]
```diff
@@ -933,37 +933,33 @@ function createBaseCustomElementClass(win) {
         // Resources can now be initialized since the ampdoc is now available.
         this.resources_ = resourcesForDoc(this.ampdoc_);
       }
-      if (!this.everAttached) {
+      this.getResources().add(this);
+
+      if (this.everAttached) {
+        if (this.reconstructWhenReparented()) {
+          this.reset_();
+          this.getResources().upgraded(this);
```
Comment (dvoytenko) [inline src/custom-element.js]: But how do we know here it was already upgraded?

**Comment by dvoytenko** [comment]
@jridgewell Ok, I think we're mostly clear. Just one question left.

File: src/custom-element.js (hunk 6 above)
Comment (jridgewell) [inline src/custom-element.js]: Fixed.
