### PR TITLE
Ensure that fixed transitions do not conflict and fix auto calc with padding

### LINKED ISSUE #5807: Header transition may conflict with the custom transition styles

### PR DESCRIPTION
**Pull request by dvoytenko**
Closes #5807, #5808.

### CODE REVIEW

File: src/service/fixed-layer.js [hunk 1]
```diff
@@ -135,6 +135,7 @@ export class FixedLayer {
       // Apply transform style to all fixed elements
       this.fixedElements_.forEach(e => {
         if (e.fixedNow && e.top) {
+          setStyle(e.element, 'transition', 'none');
```
Comment (muxin) [inline src/service/fixed-layer.js]: Shall we rename this method to something like `transitMutate`? Don't forget to update the doc.

Comment (dvoytenko) [inline src/service/fixed-layer.js]: I updated the docs. But the name, I think, is fine: it's natural to disable a custom transition for a fine-control transform.
