### PR TITLE
Do not use AMP Version as RTV Versions

### LINKED ISSUE #5471: Serving incorrect <amp-ad> script
Go to https://cdn.ampproject.org/c/amp.usatoday.com/story/91751472/

Notice that the current prod AMP version is `1475796420615`, and we load that version for `v0.js`.

The `<amp-ad>` script that is automatically injected is `1475174282386`. That's last week's prod version.

### PR DESCRIPTION
**Pull request by jridgewell**
Closes #5471. #5471 is invalid:

The core issue is that the Cache SW will serve stale-while-revalidate serve last week's (let's call it `v1`) AMP version, but that request will still look like it's requesting the newest AMP version (`v2`). The runtime will then dynamically inject the `<amp-ad>`'s script url using its AMP version (`v1`, not `v2`), so it'll look like we've been served `v2` scripts but then requested the `v1` `<amp-ad>`.

### CODE REVIEW

File: ads/alp/handler.js [hunk 1]
```diff
@@ -177,8 +177,7 @@ export function warmupStatic(win) {
   const linkRel = /*OK*/document.createElement('link');
   linkRel.rel = 'preload';
   linkRel.setAttribute('as', 'script');
-  linkRel.href =
-      `${urls.cdn}/rtv/01$internalRuntimeVersion$/v0.js`;
+  linkRel.href = `${urls.cdn}/v0.js`;
```
Comment (cramforce) [inline ads/alp/handler.js]: @erwinmombay Do we inject the config yet? In any way we should.

Comment (cramforce) [inline ads/alp/handler.js]: Great!
