### PR TITLE
🏗🐛 Build the polyfill and non-polyfill versions of the runtime into separate files

### LINKED ISSUE #16768: `gulp` fails with "Found 2 AMP_CONFIG(s) before write. Aborting"
Occurs when `--extensions` is set.

### PR DESCRIPTION
**Pull request by rsimha**
With #16452, we started building two versions of the runtime: one with polyfills and one without. However, in minified mode, the PR ended up writing both the polyfill and non-polyfill version of `amp.js` to the same destination file in parallel. This race resulted in the error...
```
"Error: Found 2 AMP_CONFIG(s) before write. Aborting!"
```

This PR introduces the following fixes:
1. Writes the non-polyfill version of `amp.js` to a new file called `amp-esm.js`
2. In local development mode, makes sure the AMP config is correctly written to both the polyfill and non-polyfill versions (of minified and non-minfied builds)
3. Updates the build progress output to print out the destination filename (instead of the source filename) during a compilation / minification step

Follow up to #16452
Fixes #16768

### CODE REVIEW

**Comment by rsimha** [comment]
Tested locally as follows:

```
gulp build

[16:52:02] Compiled amp.js (32.201 s)
[16:52:02] Compiled amp-esm.js (32.255 s)
[16:52:02] No configs found in dist/amp.js
[16:52:02] No configs found in dist/amp-esm.js
[16:52:02] Enabled local development mode in dist/amp.js
[16:52:03] Wrote prod AMP config to dist/amp.js
[16:52:03] Enabled local development mode in dist/amp-esm.js
[16:52:03] Wrote prod AMP config to dist/amp-esm.js
```

```
gulp dist --fortesting

[17:12:20] Minified v0.js (29.233 s)
[17:12:38] Minified v0-esm.js (47.296 s)
[17:13:18] No configs found in dist/v0.js
[17:13:18] Enabled local development mode in dist/v0.js
[17:13:18] Wrote prod AMP config to dist/v0.js
[17:13:18] No configs found in dist/v0-esm.js
[17:13:18] Enabled local development mode in dist/v0-esm.js
[17:13:18] Wrote prod AMP config to dist/v0-esm.js
```

File: gulpfile.js [hunk 1]
```diff
@@ -805,7 +809,9 @@ function dist() {
         copyAliasExtensions();
       }).then(() => {
         if (argv.fortesting) {
-          return enableLocalTesting(minifiedRuntimeTarget);
+          return enableLocalTesting(minifiedRuntimeTarget).then(() => {
```
Comment (kristoferbaxter) [inline gulpfile.js]: In person clarification: These are almost instantaneous, so no need to parallelize with `Promise.all`.

Perfect!
