### PR TITLE
🏗  Add `exports` for stylesheets to `package.json`

### LINKED ISSUE #35870: Bento: Can't import CSS file with webpack v5
### Description

In #35446, CSS files were added to the Bento components distributed via npm.

This worked great for my setup using webpack v4, where I was able to simply import the CSS file like this:

```js
import '@ampproject/amp-base-carousel/dist/styles.css';
```

The reason for this seems to be that webpack v5 supports the `exports` field in `package.json`, which v4 did not. And `styles.css` is not present there. So webpack complains.

To fix this, the following export would need to be added to `exports`:

```json
{
	  "./styles.css": "./dist/styles.css"
}
```

Then the following import works:

```js
import '@ampproject/amp-base-carousel/styles.css';
```

### Reproduction Steps

Try to import `styles.css` from `@ampproject/amp-base-carousel` in a webpack v5 environment.

The easiest way is through something like `@wordpress/scripts` v18, which is what I was using.

Then, import the CSS file in the source script and run `npx wp-scripts build <entry>` to try to build the script.

### Relevant Logs

```shell
Module not found: Error: Package path ./dist/styles.css is not exported from package /path/to/node_modules/@ampproject/amp-base-carousel (see exports field in /path/to/node_modules/@ampproject/amp-base-carousel/package.json)
```

### Browser(s) Affected

_No response_

### OS(s) Affected

_No response_

### Device(s) Affected

_No response_

### AMP Version Affected

2108280007000

### PR DESCRIPTION
**Pull request by swissspidy**
This addresses #35870 by adding a new export directive for stylesheets to the generated `package.json` files. For each existing stylesheet, an export as follows is added:

```json
{
	  "./<path_to_file>.css": "./dist/<path_to_file>.css",
}
```

Example:

```json
{
	  "./styles.css": "./dist/styles.css",
}
```

This allows using imports as follows in modern bundlers like webpack v5:

```js
import '@ampproject/amp-base-carousel/styles.css';
```

No export directive is added if there are no stylesheets.

**See also:**

* [Node.js documentation about package entry points](https://nodejs.org/api/packages.html#packages_package_entry_points)

Fixes #35870

### CODE REVIEW

File: build-system/npm-publish/write-package-files.js [hunk 1]
```diff
@@ -60,6 +60,7 @@ async function writePackageJson() {
         import: './dist/component-react.module.js',
         require: './dist/component-react.js',
       },
+      './styles.css': './dist/styles.css',
```
[the remark this answers is not in the document]
Comment (swissspidy) [reply build-system/npm-publish/write-package-files.js:63]: I was wondering about that too but didn't see a way to easily get that information. It would be nice to only add this if there is a stylesheet. Not sure of the implications if the file doesn't exist. Perhaps worst case your IDE just shows you an incorrect autocompletion?

[the remark this answers is not in the document]
Comment (danielrozenberg) [reply build-system/npm-publish/write-package-files.js:63]: This sounds like something that should be figured out before we merge this PR. How about manually generating test packages with/without a style file and seeing what they do?

[the remark this answers is not in the document]
Comment (samouri) [reply build-system/npm-publish/write-package-files.js:63]: When does this step occur? If it is after the `dist` folder was already created, then you could literally do a check for the file's existence via `fs.existsSync` (or ideally a promise-based API if you can find a suitable one)

File: build-system/npm-publish/write-package-files.js [hunk 2]
```diff
@@ -23,6 +23,17 @@ async function shouldSkip() {
...
 
+/**
+ * Determines whether a given directory path contains CSS files
+ *
+ * @param {string} path Path to a directory.
+ * @return {Promise<boolean>}
+ */
+async function hasStylesheets(path) {
+  const files = await readdir(path);
+  return files.some((file) => file.endsWith('.css'));
```
Comment (samouri) [inline build-system/npm-publish/write-package-files.js:34]: We could also use `fast-glob` which we use elsewhere for similar things:
```js
const fastGlob = require('fast-glob');

....

// Returns true if an extension exports CSS files.
function hasStylesheets(extension, version) {
  return fastGlob.sync(`extensions/${extension}/${version}/dist/**/*.css`).length > 0
}


```

**Review by samouri — COMMENTED** [review]
This direction looks great! One nit, but otherwise LGTM

File: build-system/npm-publish/write-package-files.js (hunk 2 above)
Comment (swissspidy) [reply build-system/npm-publish/write-package-files.js:34]: Cool, I didn't know that package was being used already. Makes sense to me 👍 

Is the preference to use the sync or the Promise-based API though?

Comment (kristoferbaxter) [reply build-system/npm-publish/write-package-files.js:34]: I'd likely use the `async` version here since it would be a smaller change from where you currently are.

Comment (samouri) [reply build-system/npm-publish/write-package-files.js:34]: Ah, I should have used `async` in my example...I got lazy

File: build-system/npm-publish/write-package-files.js [hunk 3]
```diff
@@ -42,6 +58,22 @@ async function writePackageJson() {
...
+      import: './dist/component-preact.module.js',
+      require: './dist/component-preact.js',
+    },
+    './react': {
+      import: './dist/component-react.module.js',
+      require: './dist/component-react.js',
+    },
+  };
+
+  if (await hasStylesheets()) {
```
Comment (samouri) [inline build-system/npm-publish/write-package-files.js:73]: Doesn't this need `ext, version` as params?

Comment (swissspidy) [reply build-system/npm-publish/write-package-files.js:73]: `extension` and `extensVersion` are globals in this script, see `const [extension, ampVersion, extensionVersion] = process.argv.slice(2);` at the top.

**Review by samouri — APPROVED** [review]

File: build-system/npm-publish/write-package-files.js (hunk 3 above)
Comment (samouri) [reply build-system/npm-publish/write-package-files.js:73]: Thank you for the explanation! I missed that context

File: build-system/npm-publish/write-package-files.js [hunk 4]
```diff
@@ -42,6 +58,22 @@ async function writePackageJson() {
...
+    exports['./css/*'] = './dist/*';
```
Comment (jridgewell) [inline build-system/npm-publish/write-package-files.js:74]: Why not add an individual export for each css file? We're already doing the glob, so we've already paid for the filesystem access.

Comment (swissspidy) [reply build-system/npm-publish/write-package-files.js:74]: Great question!

Functionality-wise both would be equal—at least I couldn't find any difference in my testing. So it's more a matter of preference I suppose.

[The docs](https://nodejs.org/api/packages.html#packages_subpath_patterns) say this though:

> For packages with a small number of exports or imports, we recommend explicitly listing each exports subpath entry. But for packages that have large numbers of subpaths, this might cause `package.json` bloat and maintenance issues.

Comment (jridgewell) [reply build-system/npm-publish/write-package-files.js:74]: My only issue is that this exposes everything in the `dist` directory, eg `"css/component-react.module.js"` is now valid.

Comment (swissspidy) [reply build-system/npm-publish/write-package-files.js:74]: That's a good point.

I originally had this as `exports['./css/*'] = './dist/*.css';`, but that would require imports like `import '@ampproject/amp-base-carousel/css/styles';`, which is confusing due to the lack of file extension not making it 100% clear one is actually importing a CSS file.

So yeah, individual exports would avoid this.

**Review by jridgewell — APPROVED** [review]

File: build-system/npm-publish/write-package-files.js [hunk 5]
```diff
@@ -25,17 +25,17 @@ async function shouldSkip() {
...
-        `extensions/${extension}/${extensionVersion}/dist/**/*.css`
-      )
-    ).length > 0
+async function getStylesheets() {
+  const files = await fastGlob(
+    `extensions/${extension}/${extensionVersion}/dist/**/*.css`
+  );
+
+  return files.map((path) =>
+    path.replace(`extensions/${extension}/${extensionVersion}/dist/`, '')
```
Comment (samouri) [inline build-system/npm-publish/write-package-files.js:38]: I'm unsure if this will work on Windows

**Review by samouri — APPROVED** [review]

File: build-system/npm-publish/write-package-files.js [hunk 6]
```diff
@@ -27,16 +28,14 @@ async function shouldSkip() {
...
-  );
-
-  return files.map((path) =>
-    path.replace(`extensions/${extension}/${extensionVersion}/dist/`, '')
-  );
+  const extDir = `extensions/${extension}/${extensionVersion}/dist`
+    .split('/')
+    .join(path.sep);
+  const files = await fastGlob(path.join(extDir, '**', '*.css'));
+  return files.map((file) => path.relative(extDir, file));
```
Comment (swissspidy) [inline build-system/npm-publish/write-package-files.js:38]: @samouri neat, thanks!
