### PR TITLE
Implement transfer of fixed children in amp-lightbox

### LINKED ISSUE #20964: Support transfer of fixed elements in lightboxes
Strategy: Transfer fixed descendants of lightbox when "open lightbox" animation completes, and return when "close lightbox" animation begins.

### PR DESCRIPTION
**Pull request by choumx**
Fixes #20964.

- Add CSS rules to specially treat lightbox descendants such that they're visible when lightboxes are open and hidden when lightboxes are closed (opposite of normal fixed layer behavior).
- Refactor FixedLayer's `setVisible()` to `enterLightbox()` and `exitLightbox()`.

### CODE REVIEW

File: src/service/fixed-layer.js [hunk 1]
```diff
@@ -100,27 +104,89 @@ export class FixedLayer {
...
+   * @private
+   */
+  setLightboxMode_(on, opt_isLightboxExperiment) {
+    if (!this.transferLayer_) {
+      return;
+    }
+    this.vsync_.mutate(() => {
+      const root = this.transferLayer_.getRoot();
+      if (opt_isLightboxExperiment) {
+        if (on) {
```
Comment (jridgewell) [inline src/service/fixed-layer.js]: This should be delegated to the transfer layer itself.

File: src/service/fixed-layer.js [hunk 2]
```diff
@@ -134,23 +200,29 @@ export class FixedLayer {
...
+      this.discoverSelectors_(cssRules, fixedSelectors, stickySelectors);
+    }
+    this.fixedSelectors_ = fixedSelectors;
+    this.stickySelectors_ = stickySelectors;
+
+    // Optimistically create the transfer layer. Otherwise, setVisible() may be
+    // called before the transfer layer is created, resulting in an incorrect
+    // initial visibility state. Alternatively, we could force creation of
+    // the transfer layer in setVisible().
+    if (this.fixedSelectors_.length > 0) {
```
Comment (jridgewell) [inline src/service/fixed-layer.js]: Delete, once enter/exit are delegated to the transfer layer.

File: src/service/fixed-layer.js [hunk 3]
```diff
@@ -162,6 +234,19 @@ export class FixedLayer {
...
     }
+  }
+
+  /**
+   * @param {!Node} node
+   * @param {boolean=} opt_lightboxMode
+   * @private
+   */
+  scanNode_(node, opt_lightboxMode) {
+    this.trySetupSelectorsNoInline(node, devAssert(this.fixedSelectors_),
```
Comment (jridgewell) [inline src/service/fixed-layer.js]: We could just instantiate `this.fixedSelectors_` in the constructor.

File: src/service/fixed-layer.js [hunk 4]
```diff
@@ -162,6 +234,19 @@ export class FixedLayer {
...
+        devAssert(this.stickySelectors_), opt_lightboxMode);
```
Comment (jridgewell) [inline src/service/fixed-layer.js]: Also, there's no need to pass around parameters if they're just instance properties.

File: src/service/fixed-layer.js [hunk 5]
```diff
@@ -162,6 +234,19 @@ export class FixedLayer {
...
+
+    // Sort tracked elements in document order.
+    this.sortInDomOrder_();
```
Comment (jridgewell) [inline src/service/fixed-layer.js]: I never understood why this was necessary...

File: src/service/fixed-layer.js [hunk 6]
```diff
@@ -100,27 +104,89 @@ export class FixedLayer {
...
+  leaveLightbox() {
+    const isLightboxExperimentOn =
+        isExperimentOn(this.ampdoc.win, 'fixed-elements-in-lightbox');
+
+    this.setLightboxMode_(false, isLightboxExperimentOn);
+
+    if (isLightboxExperimentOn) {
+      const fes = remove(this.elements_, fe => !!fe.lightboxed);
+      this.returnFixedElements_(fes);
+      if (!this.elements_.length) {
```
Comment (jridgewell) [inline src/service/fixed-layer.js]: Why move this out of `returnFixedElements_`?

File: src/service/fixed-layer.js [hunk 7]
```diff
@@ -586,16 +687,25 @@ export class FixedLayer {
...
-   *    to be forcefully transferred to the transfer layer.
+   * @param {boolean=} opt_forceTransfer If true, then the element will
+   *    be forcibly transferred to the transfer layer.
+   * @param {boolean=} opt_lightboxMode If true, then descendants of lightboxes
+   *    are allowed to be set up. Default is false.
    * @private
    */
-  setupElement_(element, selector, position, opt_forceTransfer) {
+  setupElement_(
+    element, selector, position, opt_forceTransfer, opt_lightboxMode
```
Comment (jridgewell) [inline src/service/fixed-layer.js]: I think we should just setup everything, even descendants of lightbox.

File: src/service/fixed-layer.js [hunk 8]
```diff
@@ -901,7 +1021,8 @@ class TransferLayerBody {
     }
     for (let i = 0; i < layerAttrs.length; i++) {
       const {name} = layerAttrs[i];
-      if (name === 'style' || body.hasAttribute(name)) {
+      if (name === 'style' || startsWith(name, 'i-amphtml-')
```
Comment (jridgewell) [inline src/service/fixed-layer.js]: Why was this added?

File: src/service/fixed-layer.js [hunk 9]
```diff
@@ -100,27 +104,89 @@ export class FixedLayer {
...
-            this.transferLayer_.getRoot(),
-            'visibility',
-            visible ? 'visible' : 'hidden');
+  enterLightbox(opt_lightbox, opt_onComplete) {
+    const isLightboxExperimentOn =
+        isExperimentOn(this.ampdoc.win, 'fixed-elements-in-lightbox');
+
+    this.setLightboxMode_(true, isLightboxExperimentOn);
+
+    if (isLightboxExperimentOn && opt_lightbox && opt_onComplete) {
```
Comment (jridgewell) [inline src/service/fixed-layer.js]: Shouldn't we be sync scanning the node if there's no `opt_onComplete`?

File: extensions/amp-lightbox/0.1/amp-lightbox.js [hunk 10]
```diff
@@ -266,8 +259,9 @@ class AmpLightbox extends AMP.BaseElement {
     this.win.document.documentElement.addEventListener(
         'keydown', this.boundCloseOnEscape_);
 
-    this.getViewport().enterLightboxMode(this.element)
-        .then(() => this.finalizeOpen_());
+    const {promise, resolve} = new Deferred();
+    this.getViewport().enterLightboxMode(this.element, promise)
```
Comment (jridgewell) [inline extensions/amp-lightbox/0.1/amp-lightbox.js]: This makes my head hurt.

File: src/service/fixed-layer.js (hunk 6 above)
Comment (choumx) [reply src/service/fixed-layer.js]: Didn't feel like it belongs in a function called `returnFixedElements_`, which I renamed because I cringed after looking at `removeElement` and `removeElement_`. 

Also did you notice "element" refers to both `Element` and `ElementDef` everywhere?

File: src/service/fixed-layer.js (hunk 1 above)
Comment (choumx) [reply src/service/fixed-layer.js]: Done.

File: src/service/fixed-layer.js (hunk 2 above)
Comment (choumx) [reply src/service/fixed-layer.js]: Done. Note this removes the optimization that avoids instantiating the transfer layer in some cases.

File: src/service/fixed-layer.js (hunk 3 above)
Comment (choumx) [reply src/service/fixed-layer.js]: Done.

File: src/service/fixed-layer.js (hunk 4 above)
Comment (choumx) [reply src/service/fixed-layer.js]: Tried to preserve the functional style but sure.

File: src/service/fixed-layer.js (hunk 5 above)
Comment (choumx) [reply src/service/fixed-layer.js]: Avoid order change for overlapping fixed elements due to z-index change?

File: src/service/fixed-layer.js (hunk 7 above)
Comment (choumx) [reply src/service/fixed-layer.js]: This avoids prematurely transferring lightbox descendants before the open animation completes.

File: src/service/fixed-layer.js (hunk 8 above)
Comment (choumx) [reply src/service/fixed-layer.js]: Need to preserve the `i-amphtml-lightbox` attribute set when a lightbox is open.

File: src/utils/array.js [hunk 11]
```diff
@@ -41,23 +41,27 @@ export function areEqualOrdered(arr1, arr2) {
  *
  * @param {!Array<T>} array
  * @param {function(T, number, !Array<T>):boolean} shouldRemove
+ * @return {!Array<T>}
  * @template T
  */
 export function remove(array, shouldRemove) {
+  const removed = [];
```
Comment (jridgewell) [inline src/utils/array.js]: Funnily enough, I actually removed this because no one was using the return value...

File: src/service/fixed-layer.js [hunk 12]
```diff
@@ -100,57 +104,93 @@ export class FixedLayer {
...
    */
-  setVisible(visible) {
-    if (this.transferLayer_) {
-      this.vsync_.mutate(() => {
-        setStyle(
-            this.transferLayer_.getRoot(),
-            'visibility',
-            visible ? 'visible' : 'hidden');
+  enterLightbox(opt_lightbox, opt_onComplete) {
+    const transferLayer = this.getTransferLayer_();
```
Comment (jridgewell) [inline src/service/fixed-layer.js]: Let's not create it if it's not created already.

File: src/service/fixed-layer.js [hunk 13]
```diff
@@ -100,57 +104,93 @@ export class FixedLayer {
...
+            /* lightboxMode */ true);
       });
     }
   }
 
+  /**
+   * Reverses the actions performed by `enterLightbox()`.
+   */
+  leaveLightbox() {
+    const transferLayer = this.getTransferLayer_();
```
Comment (jridgewell) [inline src/service/fixed-layer.js]: Ditto.

File: src/service/fixed-layer.js (hunk 6 above)
Comment (jridgewell) [reply src/service/fixed-layer.js]: Move this to a specific method, then.

Yah, blame Dima. 😛

File: src/service/fixed-layer.js [hunk 14]
```diff
@@ -879,6 +972,24 @@ class TransferLayerBody {
     return this.layer_;
   }
 
+  /** @override */
+  setLightboxMode(on) {
+    this.vsync_.mutate(() => {
+      const root = this.getRoot();
+      if (this.isLightboxExperimentOn_) {
+        if (on) {
+          root.setAttribute('i-amphtml-lightbox', '');
```
Comment (jridgewell) [inline src/service/fixed-layer.js]: It seems we could just always use this attribute to do the hiding/unhidding, and only add `.i-amphtml-lightbox-element` when the experiment is enabled? I would rename the attr to something more generic.

File: src/service/fixed-layer.js (hunk 8 above)
Comment (jridgewell) [reply src/service/fixed-layer.js]: Make it explicit? As it is, any `i-amphtml-x` will never be removed once it's synced.
