### PR TITLE
Fix ensureLoaded-vs-build race condition in HEAD

### LINKED ISSUE #32978: Latest release Breaks amp-youtube,amp-img on an amp-list inside an lightbox
**Please only file reports about bugs in AMP here.**

## What's the issue?
Previously working functionality broken
Latest release Breaks amp-youtube,amp-img on an amp-list inside an lightbox

Briefly describe the bug.

Images and videos inside an amp-list in a lightbox dont load anymore. 

## How do we reproduce the issue?
1. go to https://storywall-staging.firebaseapp.com/storywall
2. click on any thumbnail , it makes a successful network call and  but the lightbox fails to load the image. 
## What browsers are affected?
All

## Which AMP version is affected?
This is brand new this week. Version: 2102130314001

### PR DESCRIPTION
**Pull request by dvoytenko**
Closes #32978

This is the #32980 for the current HEAD

### CODE REVIEW

**Review by kristoferbaxter — APPROVED** [review]

File: test/unit/test-custom-element.js [hunk 1]
```diff
@@ -1584,7 +1584,8 @@ describes.realWin('CustomElement', {amp: true}, (env) => {
             .once();
 
           const promise = element.ensureLoaded(parentPriority);
-          await element.buildInternal();
+          await resource.build();
+          await resource.whenBuilt();
```
Comment (samouri) [inline test/unit/test-custom-element.js:1588]: is whenBuilt different from `resource.build()`?

File: src/custom-element.js [hunk 2]
```diff
@@ -602,26 +602,31 @@ function createBaseCustomElementClass(win) {
           return this.whenLoaded();
         }
 
+        // Very ugly! The "built" signal must be resolved from the Resource
+        // and not the element itself because the Resource has not correctly
+        // set its state for the downstream to process it correctly.
```
Comment (samouri) [inline src/custom-element.js:607]: what is downstream? would it be cleanest for custom-element to force `built` signal on Resource?

File: test/unit/test-custom-element.js (hunk 1 above)
Comment (dvoytenko) [reply test/unit/test-custom-element.js:1588]: Yes. Unfortunately it is. This is in a nutshell exactly why the bug happened. This is just a quick fix. Our big-fix options:

1. Reimplement `Resource.whenBuild` and state.
2. Transition some elements to V1 faster. V1 do not have that problem by definition.

File: src/custom-element.js (hunk 2 above)
Comment (dvoytenko) [reply src/custom-element.js:607]: Unfortunately, no. The problem is not only a built signal, but also all this code: https://github.com/ampproject/amphtml/blob/c3e45ef8633190ac1fc6a6f8cc6b84512eaad2f0/src/service/resource.js#L346-L362

What we could do is to refactor that code to be called by the `CustomElement` itself in the same microtask as its own [build completion code](https://github.com/ampproject/amphtml/blob/c3e45ef8633190ac1fc6a6f8cc6b84512eaad2f0/src/custom-element.js#L509-L513).

Comment (dvoytenko) [reply src/custom-element.js:607]: This would actually be quite easy to achieve. But I still wonder if doing this would take away time from maybe porting a few more elements to V1 to address most of the issues. Let me know what you think.

Comment (samouri) [reply src/custom-element.js:607]: Is it that both Resource and CustomElement both have their own `isBuilt` state and we need to dedupe them or are there other issues? I'm in favor of deduping as much as possible between Resource and CustomElement (sizes, states, etc)

Comment (dvoytenko) [reply src/custom-element.js:607]: Yes. Big area of concern. V1 elements so far simply do not use `Resource` interface at all (i.e. they are already deduped). We can definitely dedupe V0 elements as well area-by-area.
